unit unewpolymain;

{*******************************************************************************

     Main form for the newPoly demo: least-squares polynomial fitting with
     TPolynomial.Fit (newPolymath.pas) over newVM row vectors, shown on two
     TVMPlot2D components (Graphs/uVMPlot2D.pas) stacked one above the
     other.

     WHAT IT DOES

     Pick a degree, 1, 2 or 3. A fixed "true" polynomial of that degree
     (TruePoly - the same three every run, so the plots are recognisable)
     is sampled at NumPoints = 50 evenly spaced x in [XMin, XMax], and
     Gaussian noise of standard deviation Sigma (the spin edit) is added
     to every y. A polynomial of the SAME degree is then fitted back to
     the noisy points with Fit(X, Y, Degree, Residuals, StdError) - the
     overload that also returns the residuals and the standard error of
     the regression, so nothing here is computed twice.

     The upper plot shows the noisy points (circles, no line), the true
     polynomial (dashed blue) and the fitted one (solid red), all on the
     same 50-point x grid - a cubic is smooth enough at that spacing that
     no finer curve grid is needed, which is what lets one SetData call
     carry all three series. The lower plot shows the residuals y - P(x)
     as circles against a dotted zero line. The memo lists the true and
     fitted coefficients side by side and the standard error s against
     the sigma that generated the noise: with the right degree s should
     land close to sigma, since the residuals are then mostly the noise.

     NOISE

     Math.RandG (Box-Muller over the RTL's Random) rather than
     TVMobj.fillRandom: fillRandom reseeds VSL to a fixed 777 on every
     call, deliberately (see newVM.pas and the test suite's reliance on
     it), so it would hand back the identical noise vector each time -
     and a "New data" button that changes nothing is worse than no
     button. Randomize runs once in FormCreate.

     LAYOUT

     The two TVMPlot2D controls are created and parented in code, as the
     Plot2D demo does, inside a client-aligned panel: the fit plot alTop
     at three fifths of the panel's height (kept there by the panel's
     OnResize), the residual plot alClient below it.

*******************************************************************************}

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils, Math, Forms, Controls, Graphics, Dialogs, ExtCtrls,
  StdCtrls, Spin,
  newVM, newPolymath, uVMPlot2D;

type

  { TForm1 }

  TForm1 = class(TForm)
    btnNewData: TButton;
    lblSigma: TLabel;
    memResults: TMemo;
    pnlControls: TPanel;
    pnlPlots: TPanel;
    rgDegree: TRadioGroup;
    seSigma: TFloatSpinEdit;
    procedure btnNewDataClick(Sender: TObject);
    procedure FormCreate(Sender: TObject);
    procedure pnlPlotsResize(Sender: TObject);
    procedure rgDegreeSelectionChanged(Sender: TObject);
    procedure seSigmaChange(Sender: TObject);
  private
    FPlotFit: TVMPlot2D;
    FPlotRes: TVMPlot2D;
    FX: TVMobj;          // the 50-point x grid, built once
    FNoise: TVMobj;      // N(0,1) noise, regenerated by "New data"
    function TruePoly(Degree: Integer): TPolynomial;
    function FormatPoly(const P: TPolynomial): string;
    procedure NewNoise;
    procedure Refit;
  end;

var
  Form1: TForm1;

const
  NumPoints = 50;
  XMin = -3.0;
  XMax = 3.0;

implementation

{$R *.lfm}

{ TForm1 }

procedure TForm1.FormCreate(Sender: TObject);
begin
  Randomize;

  FX := TVMobj.Create(1, NumPoints);
  FX.linspace(XMin, (XMax - XMin) / (NumPoints - 1));
  FNoise := TVMobj.Create(1, NumPoints);

  FPlotFit := TVMPlot2D.Create(Self);
  FPlotFit.Parent := pnlPlots;
  FPlotFit.Align := alTop;
  FPlotFit.Height := pnlPlots.Height * 3 div 5;
  FPlotFit.XAxisTitle := 'x';
  FPlotFit.YAxisTitle := 'y';
  FPlotFit.SetSeriesStyle(0, clBlack, 1.0, plsNone, 'data', pmsCircle, 6.0);
  FPlotFit.SetSeriesStyle(1, clBlue, 1.5, plsDash, 'true polynomial');
  FPlotFit.SetSeriesStyle(2, clRed, 2.0, plsSolid, 'least-squares fit');

  FPlotRes := TVMPlot2D.Create(Self);
  FPlotRes.Parent := pnlPlots;
  FPlotRes.Align := alClient;
  FPlotRes.XAxisTitle := 'x';
  FPlotRes.YAxisTitle := 'y - P(x)';
  FPlotRes.SetSeriesStyle(0, clRed, 1.0, plsNone, 'residual', pmsCircle, 5.0);
  FPlotRes.SetSeriesStyle(1, clGray, 1.0, plsDot, 'zero');

  NewNoise;
  Refit;
end;

procedure TForm1.pnlPlotsResize(Sender: TObject);
begin
  if Assigned(FPlotFit) then
    FPlotFit.Height := pnlPlots.Height * 3 div 5;
end;

procedure TForm1.btnNewDataClick(Sender: TObject);
begin
  NewNoise;
  Refit;
end;

procedure TForm1.rgDegreeSelectionChanged(Sender: TObject);
begin
  Refit;
end;

procedure TForm1.seSigmaChange(Sender: TObject);
begin
  Refit;
end;

{ The three "true" polynomials, one per degree - each extends the one
  below it by a term, so the plots stay recognisable from run to run.
  TPolynomial.Create takes coefficients in ascending powers. }
function TForm1.TruePoly(Degree: Integer): TPolynomial;
begin
  case Degree of
    1: Result := TPolynomial.Create([1.0, 2.0]);              // 1 + 2x
    2: Result := TPolynomial.Create([1.0, 2.0, -1.5]);        // 1 + 2x - 1.5x^2
  else
       Result := TPolynomial.Create([1.0, 2.0, -1.5, 0.8]);   // 1 + 2x - 1.5x^2 + 0.8x^3
  end;
end;

{ ToString prints the full 15 digits; three decimals read better here. }
function TForm1.FormatPoly(const P: TPolynomial): string;
var
  i: Integer;
  c: Double;
  term: string;
begin
  Result := '';
  for i := 0 to P.Degree do
  begin
    c := P[i];
    case i of
      0: term := Format('%.3f', [Abs(c)]);
      1: term := Format('%.3f x', [Abs(c)]);
    else term := Format('%.3f x^%d', [Abs(c), i]);
    end;
    if i = 0 then
    begin
      if c < 0 then Result := '-' + term else Result := term;
    end
    else if c < 0 then
      Result := Result + ' - ' + term
    else
      Result := Result + ' + ' + term;
  end;
end;

procedure TForm1.NewNoise;
var
  i: Integer;
begin
  for i := 0 to NumPoints - 1 do
    FNoise[0, i] := RandG(0.0, 1.0);
end;

procedure TForm1.Refit;
var
  Degree: Integer;
  Sigma, StdErr: Double;
  PTrue, PFit: TPolynomial;
  YTrue, Y, YFit, R, Zero: TVMobj;
begin
  Degree := rgDegree.ItemIndex + 1;
  Sigma := seSigma.Value;

  PTrue := TruePoly(Degree);
  YTrue := PTrue.Evaluate(FX);
  Y := YTrue + Sigma * FNoise;

  PFit := TPolynomial.Fit(FX, Y, Degree, R, StdErr);
  YFit := PFit.Evaluate(FX);

  FPlotFit.Title := Format('Degree %d polynomial fitted to %d points with N(0, %.2f) noise',
                           [Degree, NumPoints, Sigma]);
  FPlotFit.SetData(FX, [Y, YTrue, YFit]);

  Zero := TVMobj.Create(1, NumPoints);   // zero-filled by Create
  FPlotRes.Title := Format('Residuals  (standard error s = %.3f)', [StdErr]);
  FPlotRes.SetData(FX, [R, Zero]);

  memResults.Lines.BeginUpdate;
  try
    memResults.Clear;
    memResults.Lines.Add('True:    P(x) = ' + FormatPoly(PTrue));
    memResults.Lines.Add('Fitted:  P(x) = ' + FormatPoly(PFit));
    memResults.Lines.Add(Format('Standard error of the regression s = %.4f   (noise sigma = %.2f, %d points, %d degrees of freedom)',
                                [StdErr, Sigma, NumPoints, NumPoints - (Degree + 1)]));
  finally
    memResults.Lines.EndUpdate;
  end;
end;

end.
