unit newPolymath;

{
  PolyMath.pas

  Modern Delphi Polynomial Mathematics Library

  Features:
    - Advanced record implementation
    - Dynamic array coefficients
    - Operator overloading
    - Polynomial arithmetic
    - Calculus operations
    - Division and GCD support

  Representation:

      P(x) = a0 + a1*x + a2*x^2 + ... + an*x^n

      FCoeff[0] = a0
      FCoeff[1] = a1
      ...
      FCoeff[n] = an

  FPC NOTE (newVM): a function result of a record type is NOT a fresh,
  zeroed temporary in Free Pascal the way these routines originally
  assumed - Result is the caller's destination variable (or a reused
  temporary) passed by hidden reference, so SetLength(Result.FCoeff, N)
  keeps whatever coefficients were already there. Every routine that
  accumulates into, or only partly fills, its result (Add, Subtract,
  Multiply, Shift, Reverse) therefore builds the coefficients in a local
  array C and assigns Result.FCoeff := C at the end - which also makes
  P := P * Q and P := P.Reverse safe when Result aliases an operand.
  Found via a probe program: P*Q came back with stale low-order terms
  and DivideBy looped forever on a Shift result with garbage in it.

}

{$mode delphi}{$H+}
{$POINTERMATH ON}

{$I newVMConfig.inc}
// newVMConfig.inc (generated by newvmconfigure - see that program) supplies
// HAVE_LAPACKE, which picks TPolynomial.Fit's backend - see Fit.

interface

uses
  SysUtils,
  Math,
  Generics.Collections,
  newVM;

const

    DefaultTolerance = 1E-12;



 {
    Main polynomial type.

    Stored internally as a dynamic array of Double coefficients.
  }

 type
  TPolynomialEnumerator = class
  private
    FCoefficients: TArray<Double>;
    FIndex: Integer;
  public
    constructor Create(
      const Values: TArray<Double>);

    function MoveNext: Boolean;

    function GetCurrent: Double;

    property Current: Double read GetCurrent;
  end;

Type
  TPolynomial = record

  private

    FCoeff: TArray<Double>;

    procedure Normalize;

    function GetDegree: Integer;

    function GetCoefficient(
      Index: Integer): Double;

    procedure SetCoefficient(
      Index: Integer;
      const Value: Double);

    function GetCount: Integer;

    function GetEnumerator: TPolynomialEnumerator;


  public

    { Construction }

    constructor Create(
      const Values: array of Double);

    class function Zero: TPolynomial; static;

    class function One: TPolynomial; static;


    { Least-squares fit - see the implementation for the two backends }

    class function Fit(
      const X, Y: TVMobj;
      Degree: Integer): TPolynomial; static;


    { Basic properties }

    property Degree: Integer
      read GetDegree;

    property Count: Integer
      read GetCount;


    property Coefficient[Index: Integer]: Double
      read GetCoefficient
      write SetCoefficient; default;


    { Inspection }

    function IsZero: Boolean;

    function IsConstant: Boolean;

    function LeadingCoefficient: Double;


    { Copying }

    function Clone: TPolynomial;


    { Arithmetic operators }

    class operator Add(
      const A,
            B: TPolynomial): TPolynomial;


    class operator Subtract(
      const A,
            B: TPolynomial): TPolynomial;


    class operator Negative(
      const A: TPolynomial): TPolynomial;


    class operator Multiply(
      const A,
            B: TPolynomial): TPolynomial;


    class operator Multiply(
      const A: TPolynomial;
      const B: Double): TPolynomial;


    class operator Multiply(
      const A: Double;
      const B: TPolynomial): TPolynomial;


    class operator Divide(
      const A: TPolynomial;
      const B: Double): TPolynomial;


    class operator Divide(
      const A,
            B: TPolynomial): TPolynomial;


    class operator Equal(
      const A,
            B: TPolynomial): Boolean;


    class operator NotEqual(
      const A,
            B: TPolynomial): Boolean;

    class operator Implicit(
      Value: Double): TPolynomial;


    { Algebra }



    class function GCD(
      A,
      B: TPolynomial): TPolynomial; static;


    function Power(
      Exponent: Integer): TPolynomial;

    function Modulus(
        const Divisor: TPolynomial): TPolynomial;


    { Calculus }

    function Evaluate(
      X: Double): Double;


    function Derivative: TPolynomial;


    function Integral(
      Constant: Double = 0): TPolynomial;


    { Transformations }

    function Shift(
      Amount: Integer): TPolynomial;


    function Reverse: TPolynomial;


    { Numerical information }

    function Norm: Double;


    function Equals(
      const Other: TPolynomial;
      Tolerance: Double =
        DefaultTolerance): Boolean;


    { Text conversion }

    function ToString: string;

{to do    class function Parse(
      const Text: string): TPolynomial; static; }


  end;

    {
    Result of polynomial division:

       Dividend = Quotient * Divisor + Remainder

  }
 type

 TPolynomialDivision = record
    Quotient  : TPolynomial;
    Remainder : TPolynomial;
  end;


 TPolyNomialHelper = Record Helper for TPolyNomial
        function DivideBy(
      const Divisor: TPolynomial)
      : TPolynomialDivision;

  End;






implementation

{$IFDEF HAVE_LAPACKE}
uses
  cblas,    // CBlasRowMajor
  OneAPI;   // lapacke_dgels
{$ENDIF}

{******************************************************************************
  Construction
******************************************************************************}

constructor TPolynomial.Create(
  const Values: array of Double);
var
  I: Integer;
begin
  SetLength(FCoeff, Length(Values));

  for I := Low(Values) to High(Values) do
    FCoeff[I] := Values[I];

  Normalize;
end;


class function TPolynomial.Zero: TPolynomial;
begin
  SetLength(Result.FCoeff, 0);
end;


class function TPolynomial.One: TPolynomial;
begin
  SetLength(Result.FCoeff, 1);
  Result.FCoeff[0] := 1.0;
end;


{******************************************************************************
  Internal storage handling
******************************************************************************}

procedure TPolynomial.Normalize;
var
  Last: Integer;
begin
  Last := High(FCoeff);

  while (Last >= 0) and
        (Abs(FCoeff[Last]) <= DefaultTolerance) do
    Dec(Last);

  SetLength(FCoeff, Last + 1);
end;


function TPolynomial.GetDegree: Integer;
begin
  Result := High(FCoeff);
end;


function TPolynomial.GetCount: Integer;
begin
  Result := Length(FCoeff);
end;


function TPolynomial.GetCoefficient(
  Index: Integer): Double;
begin
  if (Index < 0) or
     (Index >= Length(FCoeff)) then
    Exit(0.0);

  Result := FCoeff[Index];
end;


procedure TPolynomial.SetCoefficient(
  Index: Integer;
  const Value: Double);
begin
  if Index < 0 then
    raise EArgumentOutOfRangeException.Create(
      'Coefficient index cannot be negative.');

  if Index >= Length(FCoeff) then
    SetLength(FCoeff, Index + 1);

  FCoeff[Index] := Value;

  Normalize;
end;


{******************************************************************************
  Inspection
******************************************************************************}

function TPolynomial.IsZero: Boolean;
begin
  Result := Length(FCoeff) = 0;
end;


function TPolynomial.IsConstant: Boolean;
begin
  Result := Degree <= 0;
end;


function TPolynomial.LeadingCoefficient: Double;
begin
  if IsZero then
    Exit(0.0);

  Result := FCoeff[High(FCoeff)];
end;


{******************************************************************************
  Copying
******************************************************************************}

function TPolynomial.Clone: TPolynomial;
begin
  Result.FCoeff := Copy(FCoeff);
end;


{******************************************************************************
  Equality support
******************************************************************************}

function TPolynomial.Equals(
  const Other: TPolynomial;
  Tolerance: Double): Boolean;
var
  I,
  MaxLength: Integer;
begin
  MaxLength :=
    Max(Length(FCoeff),
        Length(Other.FCoeff));


  for I := 0 to MaxLength - 1 do
  begin
    if Abs(Self[I] - Other[I]) > Tolerance then
      Exit(False);
  end;

  Result := True;
end;

{******************************************************************************
  Addition
******************************************************************************}

class operator TPolynomial.Add(
  const A,
        B: TPolynomial): TPolynomial;
var
  C: TArray<Double>;
  I,
  N: Integer;
begin
  N := Max(Length(A.FCoeff),
           Length(B.FCoeff));

  SetLength(C, N);

  for I := 0 to N - 1 do
  begin
    if I < Length(A.FCoeff) then
      C[I] :=
        C[I] + A.FCoeff[I];

    if I < Length(B.FCoeff) then
      C[I] :=
        C[I] + B.FCoeff[I];
  end;

  Result.FCoeff := C;
  Result.Normalize;
end;


{******************************************************************************
  Subtraction
******************************************************************************}

class operator TPolynomial.Subtract(
  const A,
        B: TPolynomial): TPolynomial;
var
  C: TArray<Double>;
  I,
  N: Integer;
begin
  N := Max(Length(A.FCoeff),
           Length(B.FCoeff));

  SetLength(C, N);

  for I := 0 to N - 1 do
  begin
    if I < Length(A.FCoeff) then
      C[I] :=
        C[I] + A.FCoeff[I];

    if I < Length(B.FCoeff) then
      C[I] :=
        C[I] - B.FCoeff[I];
  end;

  Result.FCoeff := C;
  Result.Normalize;
end;


{******************************************************************************
  Unary negative
******************************************************************************}

class operator TPolynomial.Negative(
  const A: TPolynomial): TPolynomial;
var
  I: Integer;
begin
  SetLength(Result.FCoeff,
            Length(A.FCoeff));

  for I := 0 to High(A.FCoeff) do
    Result.FCoeff[I] := -A.FCoeff[I];
end;


{******************************************************************************
  Polynomial multiplication

      (a0+a1x+...) * (b0+b1x+...)

******************************************************************************}

class operator TPolynomial.Multiply(
  const A,
        B: TPolynomial): TPolynomial;
var
  C: TArray<Double>;
  I,
  J: Integer;
begin
  if A.IsZero or B.IsZero then
    Exit(TPolynomial.Zero);


  SetLength(C,
            A.Degree +
            B.Degree + 1);


  for I := 0 to A.Degree do
  begin
    for J := 0 to B.Degree do
    begin
      C[I+J] :=
        C[I+J] +
        A.FCoeff[I] *
        B.FCoeff[J];
    end;
  end;


  Result.FCoeff := C;
  Result.Normalize;
end;


{******************************************************************************
  Polynomial times scalar
******************************************************************************}

class operator TPolynomial.Multiply(
  const A: TPolynomial;
  const B: Double): TPolynomial;
var
  I: Integer;
begin
  if (A.IsZero) or
     (Abs(B) <= DefaultTolerance) then
    Exit(TPolynomial.Zero);


  SetLength(Result.FCoeff,
            Length(A.FCoeff));


  for I := 0 to High(A.FCoeff) do
    Result.FCoeff[I] :=
      A.FCoeff[I] * B;


  Result.Normalize;
end;


{******************************************************************************
  Scalar times polynomial
******************************************************************************}

class operator TPolynomial.Multiply(
  const A: Double;
  const B: TPolynomial): TPolynomial;
begin
  Result := B * A;
end;


{******************************************************************************
  Polynomial divided by scalar
******************************************************************************}

class operator TPolynomial.Divide(
  const A: TPolynomial;
  const B: Double): TPolynomial;
var
  I: Integer;
begin
  if Abs(B) <= DefaultTolerance then
    raise EZeroDivide.Create(
      'Polynomial division by zero scalar.');


  SetLength(Result.FCoeff,
            Length(A.FCoeff));


  for I := 0 to High(A.FCoeff) do
    Result.FCoeff[I] :=
      A.FCoeff[I] / B;


  Result.Normalize;
end;


{******************************************************************************
  Equality operators
******************************************************************************}

class operator TPolynomial.Equal(
  const A,
        B: TPolynomial): Boolean;
begin
  Result := A.Equals(B);
end;


class operator TPolynomial.NotEqual(
  const A,
        B: TPolynomial): Boolean;
begin
  Result := not A.Equals(B);
end;

{******************************************************************************
  Polynomial Division

      Dividend = Quotient * Divisor + Remainder

******************************************************************************}

function TPolynomialHelper.DivideBy(
  const Divisor: TPolynomial): TPolynomialDivision;
var
  Working: TPolynomial;
  Shift: Integer;
  Scale: Double;
begin
  if Divisor.IsZero then
    raise EZeroDivide.Create(
      'Cannot divide by zero polynomial.');

  Result.Quotient := TPolynomial.Zero;
  Result.Remainder := TPolynomial.Zero;

  Working := Self.Clone;


  { Dividend degree smaller than divisor }

  if Working.Degree < Divisor.Degree then
  begin
    Result.Remainder := Working;
    Exit;
  end;


  SetLength(Result.Quotient.FCoeff,
            Working.Degree -
            Divisor.Degree + 1);


  while (not Working.IsZero) and
        (Working.Degree >= Divisor.Degree) do
  begin

    Shift :=
      Working.Degree -
      Divisor.Degree;


    Scale :=
      Working.LeadingCoefficient /
      Divisor.LeadingCoefficient;


    Result.Quotient.FCoeff[Shift] :=
      Scale;


    Working :=
      Working -
      (Divisor.Shift(Shift) * Scale);

  end;


  Result.Quotient.Normalize;
  Working.Normalize;

  Result.Remainder := Working;
end;



{******************************************************************************
  Polynomial division operator

  Returns quotient only.

  Example:

       Q := A / B;

******************************************************************************}

class operator TPolynomial.Divide(
  const A,
        B: TPolynomial): TPolynomial;
var
  D: TPolynomialDivision;
begin
  D := A.DivideBy(B);

  Result := D.Quotient;
end;



{******************************************************************************
  Polynomial modulus

  Returns remainder.

******************************************************************************}

function TPolynomial.Modulus(
  const Divisor: TPolynomial): TPolynomial;
begin
  Result :=
    Self.DivideBy(Divisor).Remainder;
end;



{******************************************************************************
  Greatest Common Divisor

  Euclidean algorithm:

       gcd(a,b)

       = gcd(b, a mod b)

******************************************************************************}

class function TPolynomial.GCD(
  A,
  B: TPolynomial): TPolynomial;
var
  R: TPolynomial;
  Lead: Double;
begin

  A.Normalize;
  B.Normalize;


  while not B.IsZero do
  begin
    R := A.Modulus(B);

    A := B;
    B := R;
  end;


  if A.IsZero then
    Exit(TPolynomial.Zero);


  { Make monic polynomial }

  Lead := A.LeadingCoefficient;

  if Abs(Lead) > DefaultTolerance then
    A := A / Lead;


  Result := A;
end;



{******************************************************************************
  Polynomial exponentiation

  Uses exponentiation by squaring.

******************************************************************************}

function TPolynomial.Power(
  Exponent: Integer): TPolynomial;
var
  Base: TPolynomial;
begin

  if Exponent < 0 then
    raise EArgumentOutOfRangeException.Create(
      'Polynomial exponent cannot be negative.');


  if Exponent = 0 then
    Exit(TPolynomial.One);


  Base := Self;
  Result := TPolynomial.One;


  while Exponent > 0 do
  begin

    if Odd(Exponent) then
      Result := Result * Base;


    Exponent :=
      Exponent div 2;


    if Exponent > 0 then
      Base := Base * Base;

  end;

end;

{******************************************************************************
  Polynomial evaluation

  Uses Horner's method:

      (((an*x + an-1)*x + an-2)...)

******************************************************************************}

function TPolynomial.Evaluate(
  X: Double): Double;
var
  I: Integer;
begin
  if IsZero then
    Exit(0.0);


  Result := FCoeff[High(FCoeff)];


  for I := High(FCoeff)-1 downto 0 do
    Result :=
      Result * X +
      FCoeff[I];
end;



{******************************************************************************
  Derivative

       d/dx (a0+a1x+a2x²...)

       = a1+2a2x+3a3x²...

******************************************************************************}

function TPolynomial.Derivative: TPolynomial;
var
  I: Integer;
begin

  if Degree <= 0 then
    Exit(TPolynomial.Zero);


  SetLength(Result.FCoeff,
            Degree);


  for I := 1 to Degree do
    Result.FCoeff[I-1] :=
      FCoeff[I] * I;


  Result.Normalize;
end;



{******************************************************************************
  Integral

       ∫P(x)dx

  Constant term is supplied by caller.

******************************************************************************}

function TPolynomial.Integral(
  Constant: Double): TPolynomial;
var
  I: Integer;
begin

  SetLength(Result.FCoeff,
            Degree + 2);


  Result.FCoeff[0] :=
    Constant;


  for I := 0 to Degree do
    Result.FCoeff[I+1] :=
      FCoeff[I] / (I + 1);


  Result.Normalize;
end;



{******************************************************************************
  Shift polynomial

  Multiplies by x^Amount.

  Example:

       1 + 2x + 3x²

  Shift(2)

       x² + 2x³ + 3x⁴

******************************************************************************}

function TPolynomial.Shift(
  Amount: Integer): TPolynomial;
var
  C: TArray<Double>;
  I: Integer;
begin

  if Amount < 0 then
    raise EArgumentOutOfRangeException.Create(
      'Shift amount cannot be negative.');


  if IsZero then
    Exit(TPolynomial.Zero);


  SetLength(C,
            Degree + Amount + 1);


  for I := 0 to Degree do
    C[I + Amount] :=
      FCoeff[I];


  Result.FCoeff := C;
  Result.Normalize;
end;



{******************************************************************************
  Reverse polynomial

  Example:

       1 + 2x + 3x²

  becomes

       3 + 2x + x²

******************************************************************************}

function TPolynomial.Reverse: TPolynomial;
var
  C: TArray<Double>;
  I: Integer;
begin

  if IsZero then
    Exit(TPolynomial.Zero);


  SetLength(C,
            Length(FCoeff));


  for I := 0 to Degree do
    C[I] :=
      FCoeff[Degree-I];


  Result.FCoeff := C;
  Result.Normalize;
end;



{******************************************************************************
  Euclidean norm

       sqrt(a0²+a1²+...)

******************************************************************************}

function TPolynomial.Norm: Double;
var
  I: Integer;
begin

  Result := 0.0;


  for I := 0 to High(FCoeff) do
    Result :=
      Result +
      Sqr(FCoeff[I]);


  Result := Sqrt(Result);
end;

{******************************************************************************
  Polynomial Enumerator
******************************************************************************}

constructor TPolynomialEnumerator.Create(
  const Values: TArray<Double>);
begin
  inherited Create;

  FCoefficients := Copy(Values);

  FIndex := -1;
end;


function TPolynomialEnumerator.MoveNext: Boolean;
begin
  Inc(FIndex);

  Result :=
    FIndex < Length(FCoefficients);
end;


function TPolynomialEnumerator.GetCurrent: Double;
begin
  Result := FCoefficients[FIndex];
end;



function TPolynomial.GetEnumerator:
  TPolynomialEnumerator;
begin
  Result :=
    TPolynomialEnumerator.Create(FCoeff);
end;



{******************************************************************************
  Implicit numeric conversion

  Allows:

       P := 5;

  which creates:

       5

******************************************************************************}


class operator TPolynomial.Implicit(
  Value: Double): TPolynomial;
begin
  Result := TPolynomial.Create([Value]);
end;



{******************************************************************************
  String formatting

  Examples:

       3x^2 + 2x + 1

       -x^3 + 4

******************************************************************************}

function TPolynomial.ToString: string;
var
  I: Integer;
  C: Double;
  Term: string;
  First: Boolean;
begin

  if IsZero then
    Exit('0');


  Result := '';

  First := True;


  for I := Degree downto 0 do
  begin

    C := FCoeff[I];


    if Abs(C) <= DefaultTolerance then
      Continue;


    Term := '';


    if I = 0 then
    begin
      Term :=
        FloatToStr(Abs(C));
    end

    else

    begin

      if Abs(Abs(C)-1.0) >
         DefaultTolerance then
        Term :=
          FloatToStr(Abs(C));


      if I = 1 then
        Term := Term + 'x'
      else
        Term :=
          Term +
          'x^' +
          IntToStr(I);

    end;



    if First then
    begin

      if C < 0 then
        Result := '-';


      Result :=
        Result +
        Term;

      First := False;

    end

    else

    begin

      if C < 0 then
        Result :=
          Result +
          ' - ' +
          Term

      else

        Result :=
          Result +
          ' + ' +
          Term;

    end;

  end;
end;


{******************************************************************************
  Least-squares polynomial fit

  Fits  P(x) = a0 + a1*x + ... + ad*x^d  (d = Degree) to the N points
  (X[i], Y[i]) in the least-squares sense, minimising the sum of
  (P(X[i]) - Y[i])^2. X and Y are newVM vectors - row (1,N) or column
  (N,1), either way - of the same length, and 0 <= Degree <= N-1: at
  Degree = N-1 the fit is exact interpolation through every point (for
  distinct X). Degree 0 is the mean of Y. Neither input is modified.

  Library-backed (HAVE_LAPACKE): LAPACKE_dgels on the N x (d+1) Vandermonde
  design matrix [1, x, x^2, ..., x^d] - a QR factorisation of the design
  matrix itself, which is far better conditioned than forming the normal
  equations (the condition number of V rather than of V'V). dgels wants the
  right-hand side sized max(N, d+1) = N and returns the d+1 coefficients in
  its first d+1 entries. It needs full column rank: info > 0 means a
  diagonal entry of R came out exactly zero (e.g. every X identical with
  Degree >= 1), raised here as EMathError.

  Fallback (no HAVE_LAPACKE): the normal equations, ported from LMath's
  PolFit (LMath/uRegression/upolfit.pas). The (d+1)x(d+1) matrix of power
  sums V[i,j] = sum x^(i+j) is a Hankel matrix, so only its first row
  (x^0 .. x^d) and last column (x^(d+1) .. x^(2d)) need accumulating and
  the rest is copied along the anti-diagonals, exactly as LMath does; the
  right-hand side is B[i] = sum x^i * y. Solved via newVM's own LinearSolve
  in place of LMath's LinEq, which routes to whichever LU newVM has on
  this machine (Accelerate's dgetrf_, or PurePascalLU) - so this unit
  carries no linear-algebra code of its own.

  Coefficients go through TPolynomial.Create, so trailing coefficients
  within DefaultTolerance of zero are trimmed like any other polynomial
  here - a fit that comes back of lower degree than asked for simply had
  a negligible leading coefficient.
******************************************************************************}

class function TPolynomial.Fit(
  const X, Y: TVMobj;
  Degree: Integer): TPolynomial;
var
  N, M, I, J, Info: Integer;
  XP, YP: PDouble;
  XI: Double;
  Coef: TArray<Double>;
{$IFDEF HAVE_LAPACKE}
  A: TArray<Double>;
{$ELSE}
  K: Integer;
  V, B: TVMobj;
{$ENDIF}
begin
  if (X.Rows <> 1) and (X.Cols <> 1) then
    raise EArgumentException.Create(
      'TPolynomial.Fit: X must be a vector (one row or one column).');

  if (Y.Rows <> 1) and (Y.Cols <> 1) then
    raise EArgumentException.Create(
      'TPolynomial.Fit: Y must be a vector (one row or one column).');

  N := X.Rows * X.Cols;

  if Y.Rows * Y.Cols <> N then
    raise EArgumentException.Create(
      'TPolynomial.Fit: X and Y must have the same number of points.');

  if (Degree < 0) or (Degree > N - 1) then
    raise EArgumentOutOfRangeException.CreateFmt(
      'TPolynomial.Fit: Degree must be between 0 and N-1 ' +
      '(%d points given, degree %d asked for).', [N, Degree]);

  M := Degree + 1;
  XP := X.DataPtr;
  YP := Y.DataPtr;

{$IFDEF HAVE_LAPACKE}

  { Row-major N x M Vandermonde matrix: row i is 1, x_i, x_i^2, ..., x_i^d.
    Coef doubles as dgels's right-hand side, so it starts as a copy of Y
    (length N) and is cut down to the M coefficients afterwards. }

  SetLength(A, N * M);
  SetLength(Coef, N);

  for I := 0 to N - 1 do
  begin
    XI := 1.0;

    for J := 0 to M - 1 do
    begin
      A[I * M + J] := XI;
      XI := XI * XP[I];
    end;

    Coef[I] := YP[I];
  end;

  Info := lapacke_dgels(CBlasRowMajor, 'N', N, M, 1, @A[0], M, @Coef[0], 1);

  if Info < 0 then
    raise EMathError.CreateFmt(
      'TPolynomial.Fit: LAPACKE_dgels rejected argument %d.', [-Info]);

  if Info > 0 then
    raise EMathError.Create(
      'TPolynomial.Fit: the design matrix is rank deficient - ' +
      'are the X values distinct?');

  SetLength(Coef, M);

{$ELSE}

  V := TVMobj.Create(M, M);
  B := TVMobj.Create(M, 1);

  for K := 0 to N - 1 do
  begin
    { first row of V: x^0 .. x^d; right-hand side: x^i * y }
    XI := 1.0;

    for I := 0 to M - 1 do
    begin
      V[0, I] := V[0, I] + XI;
      B[I, 0] := B[I, 0] + XI * YP[K];
      XI := XI * XP[K];
    end;

    { last column of V: x^(d+1) .. x^(2d) - XI is x^(d+1) here }
    for I := 1 to M - 1 do
    begin
      V[I, M - 1] := V[I, M - 1] + XI;
      XI := XI * XP[K];
    end;
  end;

  { Hankel: every other entry is a copy along its anti-diagonal }
  for I := 1 to M - 1 do
    for J := 0 to M - 2 do
      V[I, J] := V[I - 1, J + 1];

  Info := LinearSolve(V, B);

  if Info <> 0 then
    raise EMathError.CreateFmt(
      'TPolynomial.Fit: the normal equations could not be solved (info %d).',
      [Info]);

  SetLength(Coef, M);

  for I := 0 to M - 1 do
    Coef[I] := B[I, 0];

{$ENDIF}

  Result := TPolynomial.Create(Coef);
end;


end.


