unit newVMComplexSingle;

{*******************************************************************************

     Vector / Matrix objects leveraging intel mkl libraries (COMPLEX SINGLE)

     Derived from newVMComplex.pas (double-precision complex). Adapted for
     single-precision complex data using the MKL "C" (single-precision
     complex) BLAS/LAPACK routines - the complex analogue of MKL_Complex8 /
     C's float _Complex. Sibling of newVMSingle.pas (real single) the same
     way newVMComplex.pas is a sibling of newVM.pas (real double).

     Inspired by Dew MtxVec Library for fpc but does not distinguish
     between matrix and vector objects. Vectors are column dimension (*,1)
     or row dimension (1,*).

     TComplex8 (re/im: Single) and the lapacke_cgesv / lapacke_claset /
     lapacke_clacpy bindings live in OneAPI.pas, alongside their TComplex16
     / "z" counterparts - added there for exactly this unit.

     Notes carried over from newVMComplex.pas, equally true here:

     1) cblas_cgemm expects alpha/beta as pointers to a complex scalar
        (CBLAS C convention `const void *alpha`), so alpha/beta are passed
        as @alpha/@beta - unlike the real gemm routines, which take them
        by value.

     2) lapacke_claset takes its alpha/beta (off-diagonal/diagonal fill
        values) by value as complex scalars, matching the LAPACKE C
        signature - passed directly (not by pointer) here.

     3) MKL's VSL has no complex Gaussian generator. fillRandom instead
        reinterprets the complex data buffer as a Single array of twice
        the length (valid because TComplex8 is exactly two contiguous
        singles) and calls vsRngGaussian once, filling both the real and
        imaginary parts with independent N(0,1) samples.

     OPERATOR OVERLOADS (algebraic expressions on TVMobjC) - the single-
     precision analogue of the ones added to newVMComplex.pas:
       - '+'/'-' element-wise via cblas_caxpy; unary '-' via cblas_csscal
         (MKL's "scale a complex vector by a real scalar" routine).
       - '*' between two same-type TVMobjC is ELEMENT-WISE multiplication,
         delegating to MulObjC (MKL VML's vcMul) - NOT matrix
         multiplication; use MatMultC (cblas_cgemm) explicitly for a real
         matrix product (same distinction as newVMComplex.pas's TVMobjZ -
         see its header comment).
       - '*'/'/' accept either a TComplex8 scalar (cblas_cscal) or a plain
         Single scalar (cblas_csscal); division computes the scalar
         reciprocal in Pascal first.
       - mixed-type '+' and '-' against a real TVMobjS promote the real
         operand to complex via RealToComplexS, then delegate to the
         TVMobjC operators above. Mixed-type '*' does not: TVMobjC*TVMobjS
         and TVMobjS*TVMobjC both call MatMultC (real matrix
         multiplication) directly, not MulObjC - the same same-type-
         element-wise-vs-mixed-type-matrix split as newVMComplex.pas.

*******************************************************************************}

{$mode Delphi}{$H+}
{$Align 8}

{$I newVMConfig.inc}
// newVMConfig.inc (generated by ./newvmconfigure - see newVM.pas's own
// header comment for the full rationale) defines HAVE_MKL/HAVE_IPP/
// HAVE_OPENBLAS/HAVE_FFTW and, derived from those, PUREPASCAL - set
// whenever any of OpenBLAS/MKL/IPP is missing on the machine that ran the
// configure tool. When PUREPASCAL is set, every routine below that would
// otherwise call into cblas/OneAPI instead uses a plain-Pascal
// implementation of its own, individually guarded - the complex-single
// analogue of newVMComplex.pas's own PUREPASCAL bodies (see that unit and
// newVM.pas for the algorithms this mirrors). EigDecomposeS
// (LAPACKE_sgeev) and the FFTW-backed FFT_R2C/FFT_C2R/FFT/IFFT have no
// such fallback - out of scope, same as newVMComplex.pas's EigDecompose;
// they already assert clearly when the library they need isn't loaded.
// (NOTE: '//' line comments throughout this block deliberately, not a
// '{ ... }' block - see newVM.pas's own copy of this note for why.)

{$IFDEF UNIX}
  {$IFDEF HAVE_MKL}
{$Linklib 'mkl_rt.so'}
{$Linklib 'pthread'}
{$Linklib 'm'}
{$Linklib 'dl'}
//mkl_rt.so dlopen's libmkl_core.so (and friends) at runtime, which
//expects libm/pthread/dl to already be loaded into the process's
//global symbol table - without this you get errors like:
//  symbol lookup error: .../libmkl_core.so: undefined symbol: log10
//Unix/ELF dynamic-linker quirk only - not needed for mkl_rt.dll on Windows.
  {$ENDIF}
{$ENDIF}

interface

uses
  Classes, SysUtils, cblas, math, TestRegistry, OneAPI, Types, newVMSingle, fftw3;

Const
  // See newVM.pas's own MaxDim comment - an arbitrary development-time
  // value, not a real limit, raised in step with it across every
  // parallel real/complex x double/single unit. This is the one that
  // most directly matters for SDR_Radio's FFT epoch size, since TVMobjC
  // is what its spectrum pipeline's raw IQ epoch (and the CPU-fallback
  // FFT path) is built from.
  MaxDimC = 2097152;    //maximum dimensions of any array

Type
  TDimC = 0..MaxDimC-1;
  TDataSizeC = 1..MaxDimC*MaxDimC;

  TVectorC = Array of TComplex8;   //maximum dimensions of any array; TComplex8 declared in OneAPI


type

  { TVMobjC }

  TVMobjC = record
    private
      fData : TVectorC;  //Holds data for object
      frows, fcols : TDimC;
      fIpiv : array of Integer;  //cached LU pivot indices from LinearSolveC, valid iff fLUFactored
      fLUFactored : Boolean;     //True once LinearSolveC has LU-factorised this object in place (see LinearSolveC)
      function getelement(r,c: TDimC): TComplex8;
      procedure setelement(r,c: TDimC; AValue: TComplex8);
    public
      constructor create(r,c :TDimC);Overload;
      Constructor create(r,c: TDimC; const Values : TVectorC); overload;
      function writeMatrix: TStringList;
      property Element[r,c:TDimC]:TComplex8 read getelement write setelement; default;
      procedure fillRandom;
      procedure Id;
      procedure linspace(Start, increment: TComplex8);
      function Transpose: TVMObjC;
      property Rows: TDimC read frows;              //read-only dimension accessors
      property Cols: TDimC read fcols;
      property LU: Boolean read fLUFactored;  //True once LinearSolveC has cached an LU factorisation of this object

      { Operator overloads - see OPERATOR OVERLOADS note in the header above.
        Mode Delphi only supports operator overloading as "class operator"
        members of the record. The mixed real/complex forms are declared
        here (rather than on TVMobjS in newVMSingle.pas) because TVMobjC is
        the common operand in all of them, and only this unit sees both
        types. }
      class operator +(const A, B: TVMobjC): TVMobjC;
      class operator -(const A, B: TVMobjC): TVMobjC;
      class operator -(const A: TVMobjC): TVMobjC;
      class operator *(const A, B: TVMobjC): TVMobjC;
      class operator *(const A: TVMobjC; const k: TComplex8): TVMobjC;
      class operator *(const k: TComplex8; const A: TVMobjC): TVMobjC;
      class operator *(const A: TVMobjC; const k: Single): TVMobjC;
      class operator *(const k: Single; const A: TVMobjC): TVMobjC;
      class operator /(const A: TVMobjC; const k: TComplex8): TVMobjC;
      class operator /(const A: TVMobjC; const k: Single): TVMobjC;
      class operator +(const A: TVMobjC; const B: TVMobjS): TVMobjC;
      class operator +(const A: TVMobjS; const B: TVMobjC): TVMobjC;
      class operator -(const A: TVMobjC; const B: TVMobjS): TVMobjC;
      class operator -(const A: TVMobjS; const B: TVMobjC): TVMobjC;
      class operator *(const A: TVMobjC; const B: TVMobjS): TVMobjC;
      class operator *(const A: TVMobjS; const B: TVMobjC): TVMobjC;
      class operator =(const A, B: TVMobjC): Boolean;
  end;

function calcoffsetC(r,c,cols :TDimC):integer;inline;
function MatMultC( const A, B: TVMObjC): TVMobjC;
function LinearSolveC(var A, B: TVMObjC):integer;
function CopyObjC(Const A : TVMObjC):TVMobjC;
function InvertC(const A: TVMobjC): TVMobjC;  //matrix inverse, via LAPACKE_cgetrf+cgetri; leaves A untouched
function KronC(const A, B: TVMobjC): TVMobjC;  //Kronecker product - see Kron in newVM.pas
function DiagC(const A: TVMobjC): TVMobjC;  //column vector (n,1) -> (n,n) diagonal matrix - see Diag in newVM.pas
function NormC(const A: TVMobjC): Single;  //Euclidean norm (real-valued), via cblas_scnrm2 - see Norm in newVM.pas
function TraceC(const A: TVMobjC): TComplex8;  //sum of A's leading-diagonal elements - see Trace in newVM.pas
function DetC(const A: TVMobjC): TComplex8;  //determinant, via LAPACKE_cgetrf - see Det in newVM.pas
function FlipUDC(const A: TVMobjC): TVMobjC;  //reverses row order - see FlipUD in newVM.pas
function FlipLRC(const A: TVMobjC): TVMobjC;  //reverses each row's element order, via ippsFlip_32fc - see FlipLR in newVM.pas
function MergeUDC(const A, B: TVMobjC): TVMobjC;  //stacks A above B - see MergeUD in newVM.pas
function MergeLRC(const A, B: TVMobjC): TVMobjC;  //places A left of B - see MergeLR in newVM.pas
function ReshapeC(const A: TVMobjC; NewRows, NewCols: TDimC): TVMobjC;  //reinterprets A's elements with new dims - see Reshape in newVM.pas
function RepmatC(const A: TVMobjC; RowReps, ColReps: Integer): TVMobjC;  //tiles A RowReps x ColReps - see Repmat in newVM.pas
{ AddScalarC - adds K to every element, via ippsAddC_32fc_I - see AddScalarZ
  in newVMComplex.pas (same two-overload convention: a native TComplex8
  constant, or a plain Single treated as a real scalar added to the real
  part only). }
function AddScalarC(const A: TVMobjC; K: TComplex8): TVMobjC; overload;
function AddScalarC(const A: TVMobjC; K: Single): TVMobjC; overload;
function SubMatrixC(const A: TVMobjC; R0, C0, RCount, CCount: TDimC): TVMobjC;  //extracts a submatrix, via LAPACKE_clacpy - see SubMatrix in newVM.pas
function Cplx8(re,im : Single): TComplex8;inline;
function RealToComplexS(const A : TVMobjS): TVMobjC;    //promotes a real single TVMobjS to a complex TVMobjC, im = 0
function GetRealPartS(const A : TVMobjC): TVMobjS;      //extracts the real component of A into a real single TVMobjS
function GetImagPartS(const A : TVMobjC): TVMobjS;      //extracts the imaginary component of A into a real single TVMobjS
procedure SplitComplexS(const A : TVMobjC; out RealPart, ImagPart: TVMobjS); //convenience: both parts in one call
procedure EigDecomposeS(const A : TVMobjS; out EigenValues, EigenVectors: TVMobjC); //eigenvalues/(right) eigenvectors of a real square matrix, via LAPACKE_sgeev

{ Elementwise transcendental/algebraic functions, via MKL VML (vc* routines
  in OneAPI.pas - complex-valued, principal-branch results). Each returns a
  new TVMobjC of the same dimensions as A, with the function applied to
  every element. Marked "overload" since Sin/Cos/Sqr/Sqrt/Exp/Ln also exist
  in System/Math for plain numeric types - without "overload" the TVMobjC
  versions here would hide those entirely within this unit. }
function Sin(const A: TVMobjC): TVMobjC; overload;
function Cos(const A: TVMobjC): TVMobjC; overload;
function Tan(const A: TVMobjC): TVMobjC; overload;
function Sinh(const A: TVMobjC): TVMobjC; overload;
function Sqr(const A: TVMobjC): TVMobjC; overload;
function Sqrt(const A: TVMobjC): TVMobjC; overload;
function Exp(const A: TVMobjC): TVMobjC; overload;
function Ln(const A: TVMobjC): TVMobjC; overload;
function MulObjC(const A, B: TVMObjC): TVMobjC;
function DivObjC(const A, B: TVMObjC): TVMobjC;

{ Real<->complex and complex<->complex 1D FFTs, via FFTW3 (fftw3.pas) on
  the single-precision library - see the matching FFT_R2C..IFFT comment in
  newVMComplex.pas for the shape/mutation/normalization rules, which apply
  here identically. Marked "overload" because newVMComplex.pas declares
  the TVMobj/TVMobjZ (double) analogues of these same names. }
function FFT_R2C(const A: TVMobjS): TVMobjC; overload;         //real -> packed half-spectrum
function FFT_C2R(const A: TVMobjC; N: Integer): TVMobjS; overload; //packed half-spectrum -> real, normalized
function FFT(const A: TVMobjC): TVMobjC; overload;             //complex -> complex, forward
function IFFT(const A: TVMobjC): TVMobjC; overload;            //complex -> complex, inverse, normalized

{ PowerSpectrum(A): one-call Hamming-windowed LINEAR power spectrum - see
  the matching PowerSpectrum comment in newVMComplex.pas for the full
  rationale (built for repeated use on fixed-size ADC-derived buffers),
  which applies here identically. Real input (A: TVMobjS) returns half
  A's length; complex input (A: TVMobjC) returns the same length as A.
  Both always return a real TVMobjS of LINEAR power (re^2+im^2), not dB.
  Marked "overload" because newVMComplex.pas declares the TVMobj/TVMobjZ
  (double) analogues of these same two names. }
function PowerSpectrum(const A: TVMobjS): TVMobjS; overload;  //real signal -> half-length linear power spectrum
function PowerSpectrum(const A: TVMobjC): TVMobjS; overload;  //complex signal -> full-length linear power spectrum

implementation

function Cplx8(re,im: Single): TComplex8;
begin
  result.re := re;
  result.im := im;
end;

function calcoffsetC(r, c, cols: TDimC): integer;
begin
  result := r*cols+c;
end;

{$IFDEF PUREPASCAL}
{ Complex-arithmetic helpers used only by the PUREPASCAL routines below -
  single-precision analogues of newVMComplex.pas's CAddZ/CSubZ/CMulZ/
  CDivZ/CAbsSqZ/CExpZ/CLnZ/CSinZ/CCosZ/CSinhZ/CSqrtZ and
  PurePascalLUZ/PurePascalLUSolveZ - see that unit for the full rationale
  (self-contained rather than calling the later ReciprocalC, since these
  are needed before LinearSolveC/InvertC/DetC, well before ReciprocalC's
  own position further down this file). }
function CAddC(const a, b: TComplex8): TComplex8;
begin
  result.re := a.re + b.re;
  result.im := a.im + b.im;
end;

function CSubC(const a, b: TComplex8): TComplex8;
begin
  result.re := a.re - b.re;
  result.im := a.im - b.im;
end;

function CMulC(const a, b: TComplex8): TComplex8;
begin
  result.re := a.re*b.re - a.im*b.im;
  result.im := a.re*b.im + a.im*b.re;
end;

function CDivC(const a, b: TComplex8): TComplex8;
var
  d : Single;
begin
  d := b.re*b.re + b.im*b.im;
  result.re := (a.re*b.re + a.im*b.im) / d;
  result.im := (a.im*b.re - a.re*b.im) / d;
end;

function CAbsSqC(const a: TComplex8): Single;
begin
  result := a.re*a.re + a.im*a.im;
end;

function CExpC(const a: TComplex8): TComplex8;
var
  ea : Single;
begin
  ea := Exp(a.re);
  result.re := ea*Cos(a.im);
  result.im := ea*Sin(a.im);
end;

function CLnC(const a: TComplex8): TComplex8;
begin
  result.re := Ln(Sqrt(CAbsSqC(a)));
  result.im := ArcTan2(a.im, a.re);
end;

function CSinC(const a: TComplex8): TComplex8;
begin
  result.re := Sin(a.re)*Cosh(a.im);
  result.im := Cos(a.re)*Sinh(a.im);
end;

function CCosC(const a: TComplex8): TComplex8;
begin
  result.re := Cos(a.re)*Cosh(a.im);
  result.im := -Sin(a.re)*Sinh(a.im);
end;

function CSinhC(const a: TComplex8): TComplex8;
begin
  result.re := Sinh(a.re)*Cos(a.im);
  result.im := Cosh(a.re)*Sin(a.im);
end;

function CSqrtC(const a: TComplex8): TComplex8;
var
  r : Single;
begin
  r := Sqrt(CAbsSqC(a));
  result.re := Sqrt((r+a.re)/2);
  if a.im >= 0 then
    result.im := Sqrt((r-a.re)/2)
  else
    result.im := -Sqrt((r-a.re)/2);
end;

function PurePascalLUC(Data: PComplex8; N: Integer; var ipiv: array of Integer): Integer;
var
  i, j, k, p: Integer;
  maxval, absval: Single;
  tmp, factor: TComplex8;
begin
  result := 0;
  for k := 0 to N-1 do begin
    p := k;
    maxval := CAbsSqC(Data[k*N+k]);
    for i := k+1 to N-1 do begin
      absval := CAbsSqC(Data[i*N+k]);
      if absval > maxval then begin
        maxval := absval;
        p := i;
      end;
    end;
    ipiv[k] := p+1;
    if p <> k then
      for j := 0 to N-1 do begin
        tmp := Data[k*N+j];
        Data[k*N+j] := Data[p*N+j];
        Data[p*N+j] := tmp;
      end;
    if (Data[k*N+k].re = 0) and (Data[k*N+k].im = 0) then begin
      if result = 0 then result := k+1;
      Continue;
    end;
    for i := k+1 to N-1 do begin
      factor := CDivC(Data[i*N+k], Data[k*N+k]);
      Data[i*N+k] := factor;
      for j := k+1 to N-1 do
        Data[i*N+j] := CSubC(Data[i*N+j], CMulC(factor, Data[k*N+j]));
    end;
  end;
end;

procedure PurePascalLUSolveC(LU: PComplex8; N: Integer; const ipiv: array of Integer; B: PComplex8; nrhs: Integer);
var
  i, j, r, p: Integer;
  sum, tmp: TComplex8;
begin
  for i := 0 to N-1 do begin
    p := ipiv[i]-1;
    if p <> i then
      for j := 0 to nrhs-1 do begin
        tmp := B[i*nrhs+j];
        B[i*nrhs+j] := B[p*nrhs+j];
        B[p*nrhs+j] := tmp;
      end;
  end;
  for r := 0 to nrhs-1 do
    for i := 1 to N-1 do begin
      sum := Cplx8(0,0);
      for j := 0 to i-1 do
        sum := CAddC(sum, CMulC(LU[i*N+j], B[j*nrhs+r]));
      B[i*nrhs+r] := CSubC(B[i*nrhs+r], sum);
    end;
  for r := 0 to nrhs-1 do
    for i := N-1 downto 0 do begin
      sum := Cplx8(0,0);
      for j := i+1 to N-1 do
        sum := CAddC(sum, CMulC(LU[i*N+j], B[j*nrhs+r]));
      B[i*nrhs+r] := CDivC(CSubC(B[i*nrhs+r], sum), LU[i*N+i]);
    end;
end;
{$ENDIF}

{ TVMobjC }

function TVMobjC.getelement(r,c: TDimC): TComplex8;
var
   Ix : Integer;
begin
   assert((r<rows) and (c<cols),'Dimensions don''t match in getelement');
   Ix := calcoffsetC(r,c,cols);
   assert(Ix<= high(fdata),'Index out of range in get element');
   result := fdata[Ix];
end;

procedure TVMobjC.setelement(r,c:TDimC; AValue: TComplex8);
var
 Ix : Integer;
begin
   assert((r<rows) and (c<cols),'Dimensions don''t match in setelement');
   Ix := calcoffsetC(r,c,cols);
   assert(Ix <= high(fdata),'Index out of range in set element');
   fdata[Ix] := Avalue;
end;

constructor TVMobjC.create(r,c :TDimC);
var
  i,N : integer;
begin
  assert((r>0) and (c>0),'rows and columns must be > 0');
  frows := r;
  fcols := c;
  N := r*c;
  setLength(fData,N);
  for i := low(fdata) to high(fdata) do fdata[i] := Cplx8(0,0);
  fLUFactored := False;
end;

constructor TVMobjC.create(r,c : TDimC; const Values: TVectorC);
begin
  assert((r>0) and (c>0),'rows and columns must be > 0');
  assert( (r*c) = high(values)+1,'Incompatible dimensions ');
  frows := r;
  fcols := c;
  fdata := copy(Values,0,high(values)+1);
  fLUFactored := False;
end;

function TVMobjC.writeMatrix: TStringList;
const
  fieldwidth = 22;
var
   i,j,k,l: integer;
   s,t : String;
   v : TComplex8;
begin
  result:= TStringList.create;
  for i:=0 to rows-1 do begin // row by row
    s := '    ['+chr(9);
    for j:=0 to cols-1 do begin
      v := FData[i*cols+j];
      t := floatToStrf(v.re,fffixed,10,3);
      if v.im >= 0 then
        t := t + '+' + floatToStrf(v.im,fffixed,10,3) + 'i'
      else
        t := t + '-' + floatToStrf(abs(v.im),fffixed,10,3) + 'i';
      s := s + t;
      l := length(t);    // pad t to get constant length
     if l < fieldwidth then
      for k := 1 to fieldwidth-l do s := s +' ';
    end;
    s := s+']';
    result.add(s);
  end;
end;

procedure TVMobjC.fillRandom;
//
// MKL's VSL RNG functions only generate real-valued distributions -
// there is no complex Gaussian generator. Because TComplex8 is laid
// out as two contiguous singles (re, im), we reinterpret the complex
// buffer as a plain Single array of twice the length and fill it with
// vsRngGaussian in a single call - this fills both the real and
// imaginary parts with independent N(0,1) samples.
//
{$IFDEF PUREPASCAL}
{ PUREPASCAL: see newVM.pas's fillRandom for the fixed-seed Box-Muller
  rationale - identical here, just writing straight into re/im pairs. }
var
  i : Integer;
  u1, u2 : Single;
begin
  RandSeed := 777;
  for i := 0 to high(fdata) do begin
    repeat
      u1 := Random;
    until u1 > 0;
    u2 := Random;
    fdata[i].re := Sqrt(-2*Ln(u1))*Cos(2*Pi*u2);
    fdata[i].im := Sqrt(-2*Ln(u1))*Sin(2*Pi*u2);
  end;
end;
{$ELSE}
const
  vslConst = 8388608;
  VSL_RNG_METHOD_GAUSSIAN_ICDF = 2;
var
  vsSTream : pointer;
  n : integer;
begin
  n := (high(fdata)+1)*2; //2 singles per complex element
  vslNewStream(@vsStream,vslConst,777);
  vsRngGaussian(VSL_RNG_METHOD_GAUSSIAN_ICDF,vsStream,n,PSingle(@Fdata[0]),0,1);
  vsldeleteStream(@vsStream);
end;
{$ENDIF}

procedure TVMobjC.Id;
const
  s : string = 'Routine Id :';
{$IFNDEF HAVE_LAPACKE}
var
  i, j : TDimC;
begin
  assert(cols=rows,s +'Matrix A must be square');
  for i := 0 to rows-1 do
    for j := 0 to cols-1 do
      if i = j then fdata[calcoffsetC(i,j,cols)] := Cplx8(1,0)
      else fdata[calcoffsetC(i,j,cols)] := Cplx8(0,0);
end;
{$ELSE}
var
  zero, one : TComplex8;
begin
  //Check dimensions of matrices are compatible. A must be square
  assert(cols=rows,s +'Matrix A must be square');
  zero := Cplx8(0,0);
  one  := Cplx8(1,0);
  lapacke_claset(CBlasRowMajor,'A',rows,cols,zero,one,@Fdata[0],rows);
end;
{$ENDIF}

procedure TVMobjC.linspace(Start, increment: TComplex8);
const
  s : String ='routine linspace';
var
  i : integer;
begin
  assert(fdata <>nil,s+  ': MVObj Not Initialized');
  //IPP has no complex VectorSlope (ippsVectorSlope_32fc isn't exported by
  //libipps - only the real forms are), so build the arithmetic sequence
  //directly: FData[i] = Start + i*increment.
  for i := 0 to high(fdata) do
    FData[i] := Cplx8(start.re + i*increment.re, start.im + i*increment.im);
end;

function TVMobjC.Transpose:TVMObjC;
var
  temp : TDimC;
{$IFDEF PUREPASCAL}
var
  i, j : TDimC;
begin
  result := TVMObjC.Create(cols, rows);
  for i := 0 to rows-1 do
    for j := 0 to cols-1 do
      result.fdata[calcoffsetC(j,i,result.fcols)] := fdata[calcoffsetC(i,j,cols)];
end;
{$ELSE}
begin
  result := copyobjC(self);
  MKL_Cimatcopy('R','T',rows,cols,Cplx8(1,0),@result.FData[0],cols,rows);
//swap row and column numbers
  temp := self.rows;
  result.frows := self.cols;
  result.fcols := temp;
end;
{$ENDIF}

function MatMultC(const A, B: TVMObjC): TVMobjC;
const
  s : String = 'Routine MatMultC :';
var
  m,n,k : integer;
  C : TVMObjC;
  alpha, beta : TComplex8;
{$IFDEF PUREPASCAL_BLAS}
var
  ii, jj, kk : integer;
  sum : TComplex8;
begin
  m := A.Rows;
  n := B.Cols;
  k := A.Cols;
  assert(A.cols = B.rows,s+'columns of first matrix must equal rows of second');
  c := TVMObjC.Create(m,n);
  for ii := 0 to m-1 do
    for jj := 0 to n-1 do begin
      sum := Cplx8(0,0);
      for kk := 0 to k-1 do
        sum := CAddC(sum, CMulC(A.fdata[calcoffsetC(ii,kk,k)], B.fdata[calcoffsetC(kk,jj,n)]));
      C.fdata[calcoffsetC(ii,jj,n)] := sum;
    end;
  result := C;
end;
{$ELSE}
begin
  m := A.Rows;
  n := B.Cols;
  k := A.Cols;
  //Check for compatibility of matrices
  assert(A.cols = B.rows,s+'columns of first matrix must equal rows of second');
  c := TVMObjC.Create(m,n);
  alpha := Cplx8(1,0);
  beta  := Cplx8(1,0);
  cblas_cgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans,
              m,n,k, { m, n, k }
              @alpha,  { alpha - by pointer, per CBLAS complex convention }
                @A.FData[0], k,
                @B.Fdata[0], n,
              @beta, {beta}
                @C.Fdata[0],n
             );
    result := C;
end;
{$ENDIF}

function LinearSolveC(var A, B: TVMObjC):integer;
const
  s : String = 'Function LinearSolveC : ';
{ Direct linear solve for matrix A and Vectors B. On the first call for a
  given A, this LU-factorises A in place and solves for B via the combined
  LAPACKE_cgesv, caching the pivot indices on A and setting A.LU := True.
  A subsequent call against the same (already-factorised) A skips
  re-factorisation and reuses the cached LU factors/pivots via the cheaper
  LAPACKE_cgetrs (solve only) - much less work when the same A is solved
  against several different B's in turn. On return, A holds its LU-factored
  form (not the original matrix) and the solution is in B. Returns info
  from the underlying LAPACKE call.

  Deliberately has NO HAVE_ACCELERATE branch, unlike InvertC/DetC below -
  see cblas.pas's comment next to accel_cgetrf_/accel_cgetri_ for why:
  Accelerate's cgetrs_ (the solve step this would need) crashes with an
  access violation whenever the factored matrix has an exactly-zero-
  imaginary-part pivot, confirmed via a standalone reproduction outside
  this codebase (same bug as newVMComplex.pas's LinearSolveZ hits with
  zgetrs_). This stays on PurePascalLUC/PurePascalLUSolveC unconditionally
  until that's resolved. }
{$IFNDEF HAVE_LAPACKE}
begin
  assert(A.Cols = A.Rows,s+'Matrix A must be square');
  assert(A.Rows = B.Rows, s+'Matrix A and B have incompatible dimensions');
  if not A.LU then begin
    setlength(A.fIpiv,A.rows);
    PurePascalLUC(@A.FData[0], A.rows, A.fIpiv);
    A.fLUFactored := True;
  end;
  PurePascalLUSolveC(@A.FData[0], A.rows, A.fIpiv, @B.FData[0], B.cols);
  result := 0;
end;
{$ELSE}
begin
  assert(A.Cols = A.Rows,s+'Matrix A must be square');
  assert(A.Rows = B.Rows, s+'Matrix A and B have incompatible dimensions');
  if A.LU then
    result := lapacke_cgetrs(CBlasRowMajor,'N',A.rows,B.cols,@A.Fdata[0],A.cols,@A.fIpiv[0],@B.FData[0],B.cols)
  else begin
    setlength(A.fIpiv,A.rows);
    result := lapacke_cgesv(CBlasRowMajor,A.rows,B.cols,@A.Fdata[0],A.cols,@A.fIpiv[0],@B.FData[0],B.cols);
    if result = 0 then A.fLUFactored := True;
  end;
end;
{$ENDIF}

function CopyObjC(const A: TVMObjC): TVMobjC;
begin
  result := TVMObjC.Create(A.rows,A.cols);
{ See newVM.pas's CopyObj - a whole-buffer copy needs no strides, so a
  flat cblas_ccopy suffices; gated on PUREPASCAL_BLAS rather than
  PUREPASCAL since it never genuinely needed real LAPACK. }
{$IFDEF PUREPASCAL_BLAS}
  Move(A.fdata[0], result.fdata[0], A.rows*A.cols*SizeOf(TComplex8));
{$ELSE}
  cblas_ccopy(A.rows*A.cols, @A.FData[0], 1, @result.FData[0], 1);
{$ENDIF}
end;

function InvertC(const A: TVMobjC): TVMobjC;
const
  s : String = 'Function InvertC : ';
var
  ipiv : array of integer;
  info : integer;
{ Matrix inverse via LAPACKE_cgetrf (LU factorisation) followed by
  LAPACKE_cgetri (inverse from the LU factors), on a CopyObjC scratch
  buffer - both LAPACKE calls overwrite their input matrix in place,
  so A itself is left untouched. }
{$IFNDEF HAVE_LAPACKE}
  {$IFDEF HAVE_ACCELERATE}
{ Accelerate-backed: raw Fortran cgetrf_/cgetri_ (see cblas.pas) - no
  LAPACKE row-major wrapper available. Same transpose-symmetry rationale
  as newVM.pas's Invert / newVMComplex.pas's InvertZ (regular transpose,
  not conjugate) - reinterpreting A's row-major buffer as column-major
  and factoring/inverting it directly, with no transposing needed, leaves
  the buffer holding, when read back as row-major, exactly inv(A).
  Confirmed against known values (including a deliberately non-Hermitian
  matrix) before wiring this in - cgetrf_/cgetri_ were also verified safe
  even at exactly-zero-imaginary-part entries, unlike cgetrs_. }
var
  n, lwork : integer;
  work : array of TComplex8;
  workquery : array[0..0] of TComplex8;
begin
  assert(A.Cols = A.Rows, s+'Matrix A must be square');
  result := CopyObjC(A);
  setlength(ipiv, A.rows);
  n := A.rows;
  accel_cgetrf_(@n, @n, @result.FData[0], @n, @ipiv[0], @info);
  assert(info = 0, s+'cgetrf_ failed (singular matrix?), info='+IntToStr(info));
  lwork := -1;
  accel_cgetri_(@n, @result.FData[0], @n, @ipiv[0], @workquery[0], @lwork, @info);
  lwork := Trunc(workquery[0].re);
  if lwork < 1 then lwork := 1;
  setlength(work, lwork);
  accel_cgetri_(@n, @result.FData[0], @n, @ipiv[0], @work[0], @lwork, @info);
  assert(info = 0, s+'cgetri_ failed (singular matrix?), info='+IntToStr(info));
end;
  {$ELSE}
var
  identity : TVMobjC;
  kk : Integer;
begin
  assert(A.Cols = A.Rows, s+'Matrix A must be square');
  result := CopyObjC(A);
  setlength(ipiv, A.rows);
  info := PurePascalLUC(@result.FData[0], A.rows, ipiv);
  assert(info = 0, s+'matrix is singular, first zero pivot at row='+IntToStr(info));
  identity := TVMobjC.Create(A.rows, A.rows);
  for kk := 0 to A.rows-1 do identity[kk,kk] := Cplx8(1,0);
  PurePascalLUSolveC(@result.FData[0], A.rows, ipiv, @identity.FData[0], A.rows);
  result := identity;
end;
  {$ENDIF}
{$ELSE}
begin
  assert(A.Cols = A.Rows, s+'Matrix A must be square');
  result := CopyObjC(A);
  setlength(ipiv, A.rows);
  info := lapacke_cgetrf(CBlasRowMajor, A.rows, A.cols, @result.Fdata[0], A.cols, @ipiv[0]);
  assert(info = 0, s+'LAPACKE_cgetrf failed (singular matrix?), info='+IntToStr(info));
  info := lapacke_cgetri(CBlasRowMajor, A.rows, @result.Fdata[0], A.cols, @ipiv[0]);
  assert(info = 0, s+'LAPACKE_cgetri failed (singular matrix?), info='+IntToStr(info));
end;
{$ENDIF}

function KronC(const A, B: TVMobjC): TVMobjC;
var
  i, j, k, rowdest, coldest : integer;
  aval : TComplex8;
{$IFDEF PUREPASCAL_BLAS}
var
  l : integer;
begin
  result := TVMobjC.Create(A.Rows*B.Rows, A.Cols*B.Cols);
  for i := 0 to A.Rows-1 do
    for j := 0 to A.Cols-1 do begin
      aval := A[i,j];
      for k := 0 to B.Rows-1 do begin
        rowdest := i*B.Rows + k;
        coldest := j*B.Cols;
        for l := 0 to B.Cols-1 do
          result.fdata[calcoffsetC(rowdest,coldest+l,result.Cols)] := CMulC(aval, B.fdata[calcoffsetC(k,l,B.Cols)]);
      end;
    end;
end;
{$ELSE}
begin
  result := TVMobjC.Create(A.Rows*B.Rows, A.Cols*B.Cols);
  for i := 0 to A.Rows-1 do
    for j := 0 to A.Cols-1 do begin
      aval := A[i,j];
      for k := 0 to B.Rows-1 do begin
        rowdest := i*B.Rows + k;
        coldest := j*B.Cols;
        cblas_caxpy(B.Cols, @aval, @B.FData[k*B.Cols], 1, @result.FData[rowdest*result.Cols + coldest], 1);
      end;
    end;
end;
{$ENDIF}

function DiagC(const A: TVMobjC): TVMobjC;
const
  s : String = 'Function DiagC : ';
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
begin
  assert(A.Cols = 1, s+'A must be a column vector (n,1)');
  result := TVMobjC.Create(A.Rows, A.Rows);
  for i := 0 to A.Rows-1 do
    result.fdata[calcoffsetC(i,i,A.Rows)] := A.fdata[i];
end;
{$ELSE}
begin
  assert(A.Cols = 1, s+'A must be a column vector (n,1)');
  result := TVMobjC.Create(A.Rows, A.Rows);
  cblas_ccopy(A.Rows, @A.FData[0], 1, @result.FData[0], A.Rows+1);
end;
{$ENDIF}

function NormC(const A: TVMobjC): Single;
const
  s : String = 'Function NormC : ';
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
  sumsq : Single;
begin
  assert((A.Rows=1) or (A.Cols=1), s+'A must be a vector (Rows=1 or Cols=1)');
  sumsq := 0;
  for i := 0 to A.Rows*A.Cols-1 do
    sumsq := sumsq + CAbsSqC(A.fdata[i]);
  result := Sqrt(sumsq);
end;
{$ELSE}
begin
  assert((A.Rows=1) or (A.Cols=1), s+'A must be a vector (Rows=1 or Cols=1)');
  result := cblas_scnrm2(A.Rows*A.Cols, @A.FData[0], 1);
end;
{$ENDIF}

function TraceC(const A: TVMobjC): TComplex8;
const
  s : String = 'Function TraceC : ';
var
  i : integer;
begin
  assert(A.Rows = A.Cols, s+'Matrix A must be square');
  result.re := 0;
  result.im := 0;
  for i := 0 to A.Rows-1 do begin
    result.re := result.re + A[i,i].re;
    result.im := result.im + A[i,i].im;
  end;
end;

function DetC(const A: TVMobjC): TComplex8;
const
  s : String = 'Function DetC : ';
var
  ipiv : array of integer;
  info, i, sign : integer;
  scratch : TVMobjC;
  d : TComplex8;
{$IFNDEF HAVE_LAPACKE}
  {$IFDEF HAVE_ACCELERATE}
var
  n : integer;
  {$ENDIF}
{$ENDIF}
begin
  assert(A.Cols = A.Rows, s+'Matrix A must be square');
  scratch := CopyObjC(A);
  setlength(ipiv, A.rows);
{$IFNDEF HAVE_LAPACKE}
  {$IFDEF HAVE_ACCELERATE}
  { See newVM.pas's Det / InvertC above for the transpose-invariance
    rationale (det(A)=det(A^T), regular transpose) - identical here,
    just single-precision complex/cgetrf_-typed. }
  n := A.rows;
  accel_cgetrf_(@n, @n, @scratch.FData[0], @n, @ipiv[0], @info);
  {$ELSE}
  info := PurePascalLUC(@scratch.FData[0], A.rows, ipiv);
  {$ENDIF}
{$ELSE}
  info := lapacke_cgetrf(CBlasRowMajor, A.rows, A.cols, @scratch.Fdata[0], A.cols, @ipiv[0]);
  assert(info >= 0, s+'LAPACKE_cgetrf reported an illegal argument, info='+IntToStr(info));
{$ENDIF}
  sign := 1;
  for i := 0 to A.rows-1 do
    if ipiv[i] <> i+1 then sign := -sign;
  result := Cplx8(sign, 0);
  for i := 0 to A.rows-1 do begin
    d := scratch[i,i];
    result := Cplx8(result.re*d.re - result.im*d.im, result.re*d.im + result.im*d.re);
  end;
end;

function FlipUDC(const A: TVMobjC): TVMobjC;
var
  i : integer;
begin
  result := TVMobjC.Create(A.Rows, A.Cols);
{$IFDEF PUREPASCAL_BLAS}
  for i := 0 to A.Rows-1 do
    Move(A.FData[i*A.Cols], result.FData[(A.Rows-1-i)*A.Cols], A.Cols*SizeOf(TComplex8));
{$ELSE}
  for i := 0 to A.Rows-1 do
    cblas_ccopy(A.Cols, @A.FData[i*A.Cols], 1, @result.FData[(A.Rows-1-i)*A.Cols], 1);
{$ENDIF}
end;

function FlipLRC(const A: TVMobjC): TVMobjC;
var
  i : integer;
{$IFDEF PUREPASCAL}
var
  j : integer;
begin
  result := TVMobjC.Create(A.Rows, A.Cols);
  for i := 0 to A.Rows-1 do
    for j := 0 to A.Cols-1 do
      result.FData[i*A.Cols+j] := A.FData[i*A.Cols + (A.Cols-1-j)];
end;
{$ELSE}
begin
  result := TVMobjC.Create(A.Rows, A.Cols);
  for i := 0 to A.Rows-1 do
    ippsFlip_32fc(@A.FData[i*A.Cols], @result.FData[i*A.Cols], A.Cols);
end;
{$ENDIF}

function MergeUDC(const A, B: TVMobjC): TVMobjC;
const
  s : String = 'Function MergeUDC : ';
begin
  assert(A.Cols = B.Cols, s+'A and B must have the same number of columns');
  result := TVMobjC.Create(A.Rows+B.Rows, A.Cols);
{$IFDEF PUREPASCAL_BLAS}
  Move(A.FData[0], result.FData[0], A.Rows*A.Cols*SizeOf(TComplex8));
  Move(B.FData[0], result.FData[A.Rows*A.Cols], B.Rows*B.Cols*SizeOf(TComplex8));
{$ELSE}
  cblas_ccopy(A.Rows*A.Cols, @A.FData[0], 1, @result.FData[0], 1);
  cblas_ccopy(B.Rows*B.Cols, @B.FData[0], 1, @result.FData[A.Rows*A.Cols], 1);
{$ENDIF}
end;

function MergeLRC(const A, B: TVMobjC): TVMobjC;
const
  s : String = 'Function MergeLRC : ';
var
  i : integer;
begin
  assert(A.Rows = B.Rows, s+'A and B must have the same number of rows');
  result := TVMobjC.Create(A.Rows, A.Cols+B.Cols);
  for i := 0 to A.Rows-1 do begin
{$IFDEF PUREPASCAL_BLAS}
    Move(A.FData[i*A.Cols], result.FData[i*result.Cols], A.Cols*SizeOf(TComplex8));
    Move(B.FData[i*B.Cols], result.FData[i*result.Cols + A.Cols], B.Cols*SizeOf(TComplex8));
{$ELSE}
    cblas_ccopy(A.Cols, @A.FData[i*A.Cols], 1, @result.FData[i*result.Cols], 1);
    cblas_ccopy(B.Cols, @B.FData[i*B.Cols], 1, @result.FData[i*result.Cols + A.Cols], 1);
{$ENDIF}
  end;
end;

function ReshapeC(const A: TVMobjC; NewRows, NewCols: TDimC): TVMobjC;
const
  s : String = 'Function ReshapeC : ';
begin
  assert(NewRows*NewCols = A.Rows*A.Cols, s+'NewRows*NewCols must equal A.Rows*A.Cols');
  result := TVMobjC.Create(NewRows, NewCols);
{$IFDEF PUREPASCAL_BLAS}
  Move(A.FData[0], result.FData[0], A.Rows*A.Cols*SizeOf(TComplex8));
{$ELSE}
  cblas_ccopy(A.Rows*A.Cols, @A.FData[0], 1, @result.FData[0], 1);
{$ENDIF}
end;

function RepmatC(const A: TVMobjC; RowReps, ColReps: Integer): TVMobjC;
const
  s : String = 'Function RepmatC : ';
var
  i, j, r, destRow : integer;
begin
  assert((RowReps > 0) and (ColReps > 0), s+'RowReps and ColReps must be > 0');
  result := TVMobjC.Create(A.Rows*RowReps, A.Cols*ColReps);
  for i := 0 to RowReps-1 do
    for r := 0 to A.Rows-1 do begin
      destRow := i*A.Rows + r;
      for j := 0 to ColReps-1 do
{$IFDEF PUREPASCAL_BLAS}
        Move(A.FData[r*A.Cols], result.FData[destRow*result.Cols + j*A.Cols], A.Cols*SizeOf(TComplex8));
{$ELSE}
        cblas_ccopy(A.Cols, @A.FData[r*A.Cols], 1, @result.FData[destRow*result.Cols + j*A.Cols], 1);
{$ENDIF}
    end;
end;

function AddScalarC(const A: TVMobjC; K: TComplex8): TVMobjC;
{$IFDEF PUREPASCAL}
var
  i : Integer;
begin
  result := CopyObjC(A);
  for i := 0 to A.Rows*A.Cols-1 do
    result.fdata[i] := CAddC(result.fdata[i], K);
end;
{$ELSE}
begin
  result := CopyObjC(A);
  ippsAddC_32fc_I(K, @result.FData[0], A.Rows*A.Cols);
end;
{$ENDIF}

function AddScalarC(const A: TVMobjC; K: Single): TVMobjC;
begin
  result := AddScalarC(A, Cplx8(K, 0));
end;

function SubMatrixC(const A: TVMobjC; R0, C0, RCount, CCount: TDimC): TVMobjC;
const
  s : String = 'Function SubMatrixC : ';
var
  i : Integer;
{ See newVM.pas's SubMatrix - a strided sub-rectangle copy only ever
  needed a per-row cblas_ccopy loop, not LAPACKE_clacpy specifically, so
  this is gated on PUREPASCAL_BLAS too. }
begin
  assert((R0+RCount <= A.Rows) and (C0+CCount <= A.Cols), s+'submatrix (R0,C0,RCount,CCount) extends beyond A''s bounds');
  result := TVMobjC.Create(RCount, CCount);
{$IFDEF PUREPASCAL_BLAS}
  for i := 0 to RCount-1 do
    Move(A.FData[(R0+i)*A.Cols+C0], result.FData[i*CCount], CCount*SizeOf(TComplex8));
{$ELSE}
  for i := 0 to RCount-1 do
    cblas_ccopy(CCount, @A.FData[(R0+i)*A.Cols+C0], 1, @result.FData[i*CCount], 1);
{$ENDIF}
end;

function RealToComplexS(const A: TVMobjS): TVMobjC;
var
  n : integer;
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
begin
  n := A.Rows * A.Cols;
  result := TVMObjC.Create(A.Rows, A.Cols);  //zero-fills both re and im
  for i := 0 to n-1 do
    result.fdata[i].re := A.DataPtr[i];
end;
{$ELSE}
begin
  //A is a real single TVMobjS (from newVMSingle.pas); result is the same
  //dimensions as a complex TVMobjC with imaginary parts all zero.
  n := A.Rows * A.Cols;
  result := TVMObjC.Create(A.Rows, A.Cols);  //zero-fills both re and im
  //TComplex8 = {re,im: Single} packed as two contiguous singles per
  //element, so result.FData viewed as a flat Single array has real
  //parts at even offsets (0,2,4,...) and imaginary parts at odd offsets.
  //cblas_scopy with a destination stride of 2 writes only into the real
  //slots; the imaginary slots are left at the zero the constructor set.
  //A.DataPtr (public accessor on TVMobjS) supplies the source buffer
  //without needing friend access to newVMSingle's private fields.
  cblas_scopy(n, A.DataPtr, 1, PSingle(@result.FData[0]), 2);
end;
{$ENDIF}

function GetRealPartS(const A: TVMobjC): TVMobjS;
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
begin
  result := TVMobjS.Create(A.rows, A.cols);
  for i := 0 to A.rows*A.cols-1 do
    result.DataPtr[i] := A.fdata[i].re;
end;
{$ELSE}
begin
  //A.FData, viewed as a flat Single array, has real parts at even
  //offsets (0,2,4,...). cblas_scopy with a source stride of 2, starting
  //at offset 0, pulls out every real component into a contiguous,
  //ordinary TVMobjS buffer (destination stride 1) - no per-element loop.
  result := TVMobjS.Create(A.rows, A.cols);
  cblas_scopy(A.rows*A.cols, PSingle(@A.FData[0]), 2, result.DataPtr, 1);
end;
{$ENDIF}

function GetImagPartS(const A: TVMobjC): TVMobjS;
var
  pIm : PSingle;
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
begin
  result := TVMobjS.Create(A.rows, A.cols);
  for i := 0 to A.rows*A.cols-1 do
    result.DataPtr[i] := A.fdata[i].im;
end;
{$ELSE}
begin
  //Same trick as GetRealPartS, but starting one single further in, so
  //the stride-2 walk lands on the imaginary slots (offsets 1,3,5,...)
  //instead of the real ones.
  result := TVMobjS.Create(A.rows, A.cols);
  pIm := PSingle(@A.FData[0]);
  inc(pIm);                              //step over the first real slot
  cblas_scopy(A.rows*A.cols, pIm, 2, result.DataPtr, 1);
end;
{$ENDIF}

procedure SplitComplexS(const A: TVMobjC; out RealPart, ImagPart: TVMobjS);
begin
  //Convenience wrapper: two independent MKL scopy calls, one per part.
  RealPart := GetRealPartS(A);
  ImagPart := GetImagPartS(A);
end;

{$IFDEF PUREPASCAL}
{ ============================================================================
  PurePascal general eigenvalue decomposition (single precision) - the
  single-precision counterpart to newVMComplex.pas's own PurePascalEigHqr2
  port; see that unit's header comment for the full rationale (ported from
  LMath's ubalance.pas, uelmhes.pas, ueltran.pas, uhqr2.pas, ubalbak.pas,
  itself a translation of the classic EISPACK Balance/Elmhes/Eltran/Hqr2/
  Balbak pipeline). Identical algorithm, Single throughout instead of
  Double, and TComplex8 (.re/.im) in place of TComplex16 for Lambda.
  ============================================================================ }

type
  TPPVectorS    = array of Single;
  TPPIntVectorS = array of Integer;
  TPPMatrixS    = array of TPPVectorS;
  TPPComplexS   = array of TComplex8;

function PPDSgnS(A, B: Single): Single; inline;
begin
  if B < 0 then result := -Abs(A) else result := Abs(A);
end;

function PPMinIS(A, B: Integer): Integer; inline;
begin
  if A <= B then result := A else result := B;
end;

function PPMaxDS(A, B: Single): Single; inline;
begin
  if A >= B then result := A else result := B;
end;

procedure PPBalanceS(A: TPPMatrixS; Lb, Ub: Integer; out I_low, I_igh: Integer; Scale: TPPVectorS);
const
  RADIX = 2;
var
  I, J, M           : Integer;
  C, F, G, R, S, B2 : Single;
  Flag, Found, Conv : Boolean;

  procedure Exchange;
  var
    I : Integer;
  begin
    Scale[M] := J;
    if J = M then Exit;
    for I := Lb to I_igh do begin
      F := A[I,J]; A[I,J] := A[I,M]; A[I,M] := F;
    end;
    for I := I_low to Ub do begin
      F := A[J,I]; A[J,I] := A[M,I]; A[M,I] := F;
    end;
  end;

begin
  B2 := RADIX * RADIX;
  I_low := Lb;
  I_igh := Ub;

  repeat
    J := I_igh;
    repeat
      I := Lb;
      repeat
        Flag := (I <> J) and (A[J,I] <> 0.0);
        I := I + 1;
      until Flag or (I > I_igh);
      Found := not Flag;
      if Found then begin
        M := I_igh;
        Exchange;
        I_igh := I_igh - 1;
      end;
      J := J - 1;
    until Found or (J < Lb);
  until (not Found) or (I_igh < Lb);

  if I_igh < Lb then I_igh := Lb;
  if I_igh = Lb then Exit;

  repeat
    J := I_low;
    repeat
      I := I_low;
      repeat
        Flag := (I <> J) and (A[I,J] <> 0.0);
        I := I + 1;
      until Flag or (I > I_igh);
      Found := not Flag;
      if Found then begin
        M := I_low;
        Exchange;
        I_low := I_low + 1;
      end;
      J := J + 1;
    until Found or (J > I_igh);
  until (not Found);

  for I := I_low to I_igh do Scale[I] := 1.0;

  repeat
    Conv := True;
    for I := I_low to I_igh do begin
      C := 0.0; R := 0.0;
      for J := I_low to I_igh do
        if J <> I then begin
          C := C + Abs(A[J,I]);
          R := R + Abs(A[I,J]);
        end;
      if (C <> 0.0) and (R <> 0.0) then begin
        G := R / RADIX;
        F := 1.0;
        S := C + R;
        while C < G do begin F := F * RADIX; C := C * B2; end;
        G := R * RADIX;
        while C >= G do begin F := F / RADIX; C := C / B2; end;
        if (C + R) / F < 0.95 * S then begin
          G := 1.0 / F;
          Scale[I] := Scale[I] * F;
          Conv := False;
          for J := I_low to Ub do A[I,J] := A[I,J] * G;
          for J := Lb to I_igh do A[J,I] := A[J,I] * F;
        end;
      end;
    end;
  until Conv;
end;

procedure PPElmHesS(A: TPPMatrixS; Lb, Ub, I_low, I_igh: Integer; I_int: TPPIntVectorS);
var
  I, J, M, La, Kp1, Mm1, Mp1 : Integer;
  X, Y                       : Single;
begin
  La := I_igh - 1;
  Kp1 := I_low + 1;
  if La < Kp1 then Exit;

  for M := Kp1 to La do begin
    Mm1 := M - 1;
    X := 0.0;
    I := M;
    for J := M to I_igh do
      if Abs(A[J,Mm1]) > Abs(X) then begin
        X := A[J,Mm1];
        I := J;
      end;
    I_int[M] := I;
    if I <> M then begin
      for J := Mm1 to Ub do begin
        Y := A[I,J]; A[I,J] := A[M,J]; A[M,J] := Y;
      end;
      for J := Lb to I_igh do begin
        Y := A[J,I]; A[J,I] := A[J,M]; A[J,M] := Y;
      end;
    end;
    if X <> 0.0 then begin
      Mp1 := M + 1;
      for I := Mp1 to I_igh do begin
        Y := A[I,Mm1];
        if Y <> 0.0 then begin
          Y := Y / X;
          A[I,Mm1] := Y;
          for J := M to Ub do A[I,J] := A[I,J] - Y * A[M,J];
          for J := Lb to I_igh do A[J,M] := A[J,M] + Y * A[J,I];
        end;
      end;
    end;
  end;
end;

procedure PPEltranS(A: TPPMatrixS; Lb, Ub, I_low, I_igh: Integer; I_int: TPPIntVectorS; Z: TPPMatrixS);
var
  I, J, Mp, Mp1 : Integer;
begin
  for I := Lb to Ub do
    for J := Lb to Ub do
      if I = J then Z[I,J] := 1.0 else Z[I,J] := 0.0;

  if I_igh < I_low then Exit;

  for Mp := I_igh - 1 downto I_low + 1 do begin
    Mp1 := Mp + 1;
    for I := Mp1 to I_igh do Z[I,Mp] := A[I,Mp - 1];
    I := I_int[Mp];
    if I <> Mp then begin
      for J := Mp to I_igh do begin
        Z[Mp,J] := Z[I,J];
        Z[I,J] := 0.0;
      end;
      Z[I,Mp] := 1.0;
    end;
  end;
end;

function PPHqr2S(H: TPPMatrixS; Lb, Ub, I_low, I_igh: Integer; Lambda: TPPComplexS; Z: TPPMatrixS): Integer;

  procedure Cdiv(Ar, Ai, Br, Bi : Single; var Cr, Ci : Single);
  var
    S, Ars, Ais, Brs, Bis : Single;
  begin
    S := Abs(Br) + Abs(Bi);
    Ars := Ar / S;
    Ais := Ai / S;
    Brs := Br / S;
    Bis := Bi / S;
    S := Sqr(Brs) + Sqr(Bis);
    Cr := (Ars * Brs + Ais * Bis) / S;
    Ci := (Ais * Brs - Ars * Bis) / S;
  end;

var
  I, J, K, L, M, N, En, Na, Itn, Its, Mp2, Enm2                : Integer;
  P, Q, R, S, T, W, X, Y, Ra, Sa, Vi, Vr, Zz, Norm, Tst1, Tst2 : Single;
  NotLas                                                       : Boolean;

label
  60, 70, 100, 130, 150, 170, 225, 260, 270, 280, 320, 330, 340,
  600, 630, 635, 640, 680, 700, 710, 770, 780, 790, 795, 800;

begin
  result := 0;

  K := Lb;
  Norm := 0.0;
  for I := Lb to Ub do begin
    for J := K to Ub do Norm := Norm + Abs(H[I,J]);
    K := I;
    if (I < I_low) or (I > I_igh) then begin
      Lambda[I].re := H[I,I];
      Lambda[I].im := 0.0;
    end;
  end;

  N := Ub - Lb + 1;
  Itn := 30 * N;
  En := I_igh;
  T := 0.0;

60:
  if En < I_low then goto 340;
  Its := 0;
  Na := En - 1;
  Enm2 := Na - 1;

70:
  for L := En downto I_low do begin
    if L = I_low then goto 100;
    S := Abs(H[L - 1,L - 1]) + Abs(H[L,L]);
    if S = 0.0 then S := Norm;
    Tst1 := S;
    Tst2 := Tst1 + Abs(H[L,L - 1]);
    if Tst2 = Tst1 then goto 100;
  end;

100:
  X := H[En,En];
  if L = En then goto 270;
  Y := H[Na,Na];
  W := H[En,Na] * H[Na,En];
  if L = Na then goto 280;

  if Itn = 0 then begin
    result := -En;
    Exit;
  end;

  if (Its <> 10) and (Its <> 20) then goto 130;

  T := T + X;
  for I := I_low to En do H[I,I] := H[I,I] - X;
  S := Abs(H[En,Na]) + Abs(H[Na,Enm2]);
  X := 0.75 * S;
  Y := X;
  W := - 0.4375 * S * S;

130:
  Its := Its + 1;
  Itn := Itn - 1;

  for M := Enm2 downto L do begin
    Zz := H[M,M];
    R := X - Zz;
    S := Y - Zz;
    P := (R * S - W) / H[M + 1,M] + H[M,M + 1];
    Q := H[M + 1,M + 1] - Zz - R - S;
    R := H[M + 2,M + 1];
    S := Abs(P) + Abs(Q) + Abs(R);
    P := P / S;
    Q := Q / S;
    R := R / S;
    if M = L then goto 150;
    Tst1 := Abs(P) * (Abs(H[M - 1,M - 1]) + Abs(Zz) + Abs(H[M + 1,M + 1]));
    Tst2 := Tst1 + Abs(H[M,M - 1]) * (Abs(Q) + Abs(R));
    if Tst2 = Tst1 then goto 150;
  end;

150:
  Mp2 := M + 2;
  for I := Mp2 to En do begin
    H[I,I - 2] := 0.0;
    if I <> Mp2 then H[I,I - 3] := 0.0;
  end;

  for K := M to Na do begin
    NotLas := (K <> Na);
    if (K = M) then goto 170;
    P := H[K,K - 1];
    Q := H[K + 1,K - 1];
    R := 0.0;
    if NotLas then R := H[K + 2,K - 1];
    X := Abs(P) + Abs(Q) + Abs(R);
    if X = 0.0 then goto 260;
    P := P / X;
    Q := Q / X;
    R := R / X;
170:S := PPDSgnS(Sqrt(P * P + Q * Q + R * R), P);
    if K <> M then
      H[K,K - 1] := - S * X
    else if L <> M then
      H[K,K - 1] := - H[K,K - 1];
    P := P + S;
    X := P / S;
    Y := Q / S;
    Zz := R / S;
    Q := Q / P;
    R := R / P;
    if NotLas then goto 225;

    for J := K to Ub do begin
      P := H[K,J] + Q * H[K + 1,J];
      H[K,J] := H[K,J] - P * X;
      H[K + 1,J] := H[K + 1,J] - P * Y;
    end;

    J := PPMinIS(En, K + 3);

    for I := Lb to J do begin
      P := X * H[I,K] + Y * H[I,K + 1];
      H[I,K] := H[I,K] - P;
      H[I,K + 1] := H[I,K + 1] - P * Q;
    end;

    for I := I_low to I_igh do begin
      P := X * Z[I,K] + Y * Z[I,K + 1];
      Z[I,K] := Z[I,K] - P;
      Z[I,K + 1] := Z[I,K + 1] - P * Q;
    end;
    goto 260;

225:
    for J := K to Ub do begin
      P := H[K,J] + Q * H[K + 1,J] + R * H[K + 2,J];
      H[K,J] := H[K,J] - P * X;
      H[K + 1,J] := H[K + 1,J] - P * Y;
      H[K + 2,J] := H[K + 2,J] - P * Zz;
    end;

    J := PPMinIS(En, K + 3);

    for I := Lb to J do begin
      P := X * H[I,K] + Y * H[I,K + 1] + Zz * H[I,K + 2];
      H[I,K] := H[I,K] - P;
      H[I,K + 1] := H[I,K + 1] - P * Q;
      H[I,K + 2] := H[I,K + 2] - P * R;
    end;

    for I := I_low to I_igh do begin
      P := X * Z[I,K] + Y * Z[I,K + 1] + Zz * Z[I,K + 2];
      Z[I,K] := Z[I,K] - P;
      Z[I,K + 1] := Z[I,K + 1] - P * Q;
      Z[I,K + 2] := Z[I,K + 2] - P * R;
    end;

260: end;

  goto 70;

270:
  H[En,En] := X + T;
  Lambda[En].re := H[En,En];
  Lambda[En].im := 0.0;
  En := Na;
  goto 60;

280:
  P := 0.5 * (Y - X);
  Q := P * P + W;
  Zz := Sqrt(Abs(Q));
  H[En,En] := X + T;
  X := H[En,En];
  H[Na,Na] := Y + T;
  if Q < 0.0 then goto 320;

  Zz := P + PPDSgnS(Zz, P);
  Lambda[Na].re := X + Zz;
  Lambda[En].re := Lambda[Na].re;
  if Zz <> 0.0 then Lambda[En].re := X - W / Zz;
  Lambda[Na].im := 0.0;
  Lambda[En].im := 0.0;
  X := H[En,Na];
  S := Abs(X) + Abs(Zz);
  P := X / S;
  Q := Zz / S;
  R := Sqrt(P * P + Q * Q);
  P := P / R;
  Q := Q / R;

  for J := Na to Ub do begin
    Zz := H[Na,J];
    H[Na,J] := Q * Zz + P * H[En,J];
    H[En,J] := Q * H[En,J] - P * Zz;
  end;

  for I := Lb to En do begin
    Zz := H[I,Na];
    H[I,Na] := Q * Zz + P * H[I,En];
    H[I,En] := Q * H[I,En] - P * Zz;
  end;

  for I := I_low to I_igh do begin
    Zz := Z[I,Na];
    Z[I,Na] := Q * Zz + P * Z[I,En];
    Z[I,En] := Q * Z[I,En] - P * Zz;
  end;

  goto 330;

320:
  Lambda[Na].re := X + P;
  Lambda[En].re := Lambda[Na].re;
  Lambda[Na].im := Zz;
  Lambda[En].im := - Zz;

330:
  En := Enm2;
  goto 60;

340:
  if Norm = 0.0 then Exit;

  for En := Ub downto Lb do begin
    P := Lambda[En].re;
    Q := Lambda[En].im;
    Na := En - 1;
    if Q < 0.0 then
      goto 710
    else if Q = 0.0 then
      goto 600
    else
      goto 800;

600:
    M := En;
    H[En,En] := 1.0;
    if Na < Lb then goto 800;

    for I := Na downto Lb do begin
      W := H[I,I] - P;
      R := 0.0;
      for J := M to En do R := R + H[I,J] * H[J,En];
      if Lambda[I].im >= 0.0 then goto 630;
      Zz := W;
      S := R;
      goto 700;
630:  M := I;
      if Lambda[I].im <> 0.0 then goto 640;
      T := W;
      if T <> 0.0 then goto 635;
      Tst1 := Norm;
      T := Tst1;
      repeat
        T := 0.01 * T;
        Tst2 := Norm + T;
      until Tst2 <= Tst1;
635:  H[I,En] := - R / T;
      goto 680;

640:
      X := H[I,I + 1];
      Y := H[I + 1,I];
      Q := Sqr(Lambda[I].re - P) + Sqr(Lambda[I].im);
      T := (X * S - Zz * R) / Q;
      H[I,En] := T;
      if Abs(X) > Abs(Zz) then
        H[I + 1,En] := (- R - W * T) / X
      else
        H[I + 1,En] := (- S - Y * T) / Zz;

680:
      T := Abs(H[I,En]);
      if T = 0.0 then goto 700;
      Tst1 := T;
      Tst2 := Tst1 + 1.0 / Tst1;
      if Tst2 > Tst1 then goto 700;
      for J := I to En do H[J,En] := H[J,En] / T;
700: end;
    goto 800;

710:
    M := Na;
    if Abs(H[En,Na]) > Abs(H[Na,En]) then begin
      H[Na,Na] := Q / H[En,Na];
      H[Na,En] := - (H[En,En] - P) / H[En,Na];
    end else
      Cdiv(0.0, - H[Na,En], H[Na,Na] - P, Q, H[Na,Na], H[Na,En]);

    H[En,Na] := 0.0;
    H[En,En] := 1.0;
    Enm2 := Na - 1;
    if Enm2 < Lb then goto 800;

    for I := Enm2 downto Lb do begin
      W := H[I,I] - P;
      Ra := 0.0;
      Sa := 0.0;
      for J := M to En do begin
        Ra := Ra + H[I,J] * H[J,Na];
        Sa := Sa + H[I,J] * H[J,En];
      end;
      if Lambda[I].im >= 0.0 then goto 770;
      Zz := W;
      R := Ra;
      S := Sa;
      goto 795;
770:  M := I;
      if Lambda[I].im <> 0.0 then goto 780;
      Cdiv(- Ra, - Sa, W, Q, H[I,Na], H[I,En]);
      goto 790;

780:
      X := H[I,I + 1];
      Y := H[I + 1,I];
      Vr := Sqr(Lambda[I].re - P) + Sqr(Lambda[I].im) - Sqr(Q);
      Vi := (Lambda[I].re - P) * 2.0 * Q;
      if (Vr = 0.0) and (Vi = 0.0) then begin
        Tst1 := Norm * (Abs(W) + Abs(Q) + Abs(X) + Abs(Y) + Abs(Zz));
        Vr := Tst1;
        repeat
          Vr := 0.01 * Vr;
          Tst2 := Tst1 + Vr;
        until Tst2 <= Tst1;
      end;
      Cdiv(X * R - Zz * Ra + Q * Sa, X * S - Zz * Sa - Q * Ra, Vr, Vi, H[I,Na], H[I,En]);
      if Abs(X) > Abs(Zz) + Abs(Q) then begin
        H[I + 1,Na] := (- Ra - W * H[I,Na] + Q * H[I,En]) / X;
        H[I + 1,En] := (- Sa - W * H[I,En] - Q * H[I,Na]) / X;
      end else
        Cdiv(- R - Y * H[I,Na], - S - Y * H[I,En], Zz, Q, H[I + 1,Na], H[I + 1,En]);

790:
      T := PPMaxDS(Abs(H[I,Na]), Abs(H[I,En]));
      if T = 0.0 then goto 795;
      Tst1 := T;
      Tst2 := Tst1 + 1.0 / Tst1;
      if Tst2 > Tst1 then goto 795;
      for J := I to En do begin
        H[J,Na] := H[J,Na] / T;
        H[J,En] := H[J,En] / T;
      end;

795: end;
800: end;

  for I := Lb to Ub do
    if (I < I_low) or (I > I_igh) then
      for J := I to Ub do Z[I,J] := H[I,J];

  for J := Ub downto I_low do begin
    M := PPMinIS(J, I_igh);
    for I := I_low to I_igh do begin
      Zz := 0.0;
      for K := I_low to M do Zz := Zz + Z[I,K] * H[K,J];
      Z[I,J] := Zz;
    end;
  end;

  result := 0;
end;

procedure PPBalBakS(Z: TPPMatrixS; Lb, Ub, I_low, I_igh: Integer; Scale: TPPVectorS; M: Integer);
var
  I, J, K : Integer;
  S       : Single;
begin
  if M < Lb then Exit;

  if I_igh <> I_low then
    for I := I_low to I_igh do begin
      S := Scale[I];
      for J := Lb to M do Z[I,J] := Z[I,J] * S;
    end;

  for I := (I_low - 1) downto Lb do begin
    K := Round(Scale[I]);
    if K <> I then
      for J := Lb to M do begin
        S := Z[I,J]; Z[I,J] := Z[K,J]; Z[K,J] := S;
      end;
  end;

  for I := (I_igh + 1) to Ub do begin
    K := Round(Scale[I]);
    if K <> I then
      for J := Lb to M do begin
        S := Z[I,J]; Z[I,J] := Z[K,J]; Z[K,J] := S;
      end;
  end;
end;

function PurePascalEigHqr2S(N: Integer; AData: PSingle; var Wr, Wi: TVectorS; var V: TVectorS): Integer;
var
  H, Z    : TPPMatrixS;
  Scale   : TPPVectorS;
  I_int   : TPPIntVectorS;
  Lambda  : TPPComplexS;
  I_low, I_igh, I, J, ErrCode : Integer;
  NormSq, Nrm : Single;
begin
  SetLength(H, N+1, N+1);
  SetLength(Z, N+1, N+1);
  SetLength(Scale, N+1);
  SetLength(I_int, N+1);
  SetLength(Lambda, N+1);

  for I := 0 to N-1 do
    for J := 0 to N-1 do
      H[I+1,J+1] := AData[I*N+J];

  PPBalanceS(H, 1, N, I_low, I_igh, Scale);
  PPElmHesS(H, 1, N, I_low, I_igh, I_int);
  PPEltranS(H, 1, N, I_low, I_igh, I_int, Z);
  ErrCode := PPHqr2S(H, 1, N, I_low, I_igh, Lambda, Z);

  if ErrCode <> 0 then begin
    result := ErrCode;
    Exit;
  end;

  PPBalBakS(Z, 1, N, I_low, I_igh, Scale, N);

  for I := 0 to N-1 do begin
    Wr[I] := Lambda[I+1].re;
    Wi[I] := Lambda[I+1].im;
  end;
  for I := 0 to N-1 do
    for J := 0 to N-1 do
      V[I*N+J] := Z[I+1,J+1];

  J := 0;
  while J <= N-1 do begin
    if Wi[J] = 0 then begin
      NormSq := 0;
      for I := 0 to N-1 do NormSq := NormSq + Sqr(V[I*N+J]);
      Nrm := Sqrt(NormSq);
      if Nrm > 0 then
        for I := 0 to N-1 do V[I*N+J] := V[I*N+J] / Nrm;
      inc(J);
    end else begin
      NormSq := 0;
      for I := 0 to N-1 do NormSq := NormSq + Sqr(V[I*N+J]) + Sqr(V[I*N+J+1]);
      Nrm := Sqrt(NormSq);
      if Nrm > 0 then
        for I := 0 to N-1 do begin
          V[I*N+J]   := V[I*N+J]   / Nrm;
          V[I*N+J+1] := V[I*N+J+1] / Nrm;
        end;
      inc(J,2);
    end;
  end;

  result := 0;
end;
{$ENDIF}

procedure EigDecomposeS(const A: TVMobjS; out EigenValues, EigenVectors: TVMobjC);
const
  s : String = 'Routine EigDecomposeS : ';
//
// General real nonsymmetric eigenvalue problem, via LAPACKE_sgeev - the
// single-precision counterpart to EigDecompose (newVMComplex.pas), which
// uses LAPACKE_dgeev. See that routine's comments for the full rationale;
// the unpacking logic is identical, just at single precision throughout.
//
var
  n, i, j, info : integer;
  Acopy : TVMobjS;
  wr, wi, vr : TVectorS;   //TVectorS = array of Single, exported by newVMSingle
begin
  assert(A.Rows = A.Cols, s+'Matrix A must be square');
  n := A.Rows;

  //LAPACKE_sgeev overwrites its input matrix in place, so run it on a
  //scratch copy and leave the caller's A untouched.
  Acopy := CopyObjS(A);

  SetLength(wr, n);
  SetLength(wi, n);
  SetLength(vr, n*n);

  //jobvl = 'N' : left eigenvectors not requested (vl unused -> nil, ldvl=n is a harmless placeholder)
  //jobvr = 'V' : right eigenvectors requested, returned in packed real form in vr
{$IFNDEF HAVE_LAPACKE}
  //PurePascalEigHqr2S - see its own header comment above - fills wr/wi/vr in
  //exactly the same packed real/imaginary-column-pair convention LAPACKE_sgeev
  //uses below, so the unpacking loop after this IFDEF is unchanged either way.
  info := PurePascalEigHqr2S(n, Acopy.DataPtr, wr, wi, vr);
  assert(info = 0, s+'PurePascal QR iteration failed to converge, info='+IntToStr(info));
{$ELSE}
  info := LAPACKE_sgeev(CBlasRowMajor, 'N', 'V', n,
                          Acopy.DataPtr, n,
                          @wr[0], @wi[0],
                          nil, n,
                          @vr[0], n);
  assert(info = 0, s+'LAPACKE_sgeev failed, info='+IntToStr(info));
{$ENDIF}

  //--- eigenvalues: one complex value per row, straight from wr/wi ---
  EigenValues := TVMobjC.Create(n,1);
  for i := 0 to n-1 do
    EigenValues.FData[i] := Cplx8(wr[i], wi[i]);

  //--- eigenvectors: unpack LAPACK's real/imaginary column pairing ---
  EigenVectors := TVMobjC.Create(n,n);
  j := 0;
  while j <= n-1 do begin
    if wi[j] = 0 then begin
      //real eigenvalue -> column j of vr IS the eigenvector, im = 0
      for i := 0 to n-1 do
        EigenVectors.FData[i*n+j] := Cplx8(vr[i*n+j], 0);
      inc(j);
    end else begin
      //complex-conjugate pair sharing columns j (real part) and j+1 (imag part)
      for i := 0 to n-1 do begin
        EigenVectors.FData[i*n+j]   := Cplx8(vr[i*n+j],  vr[i*n+j+1]);
        EigenVectors.FData[i*n+j+1] := Cplx8(vr[i*n+j], -vr[i*n+j+1]);
      end;
      inc(j,2);
    end;
  end;
end;

function ReciprocalC(const k: TComplex8): TComplex8;
const
  s : String = 'Operator / (TVMobjC) : ';
var
  d : Single;
begin
  d := k.re*k.re + k.im*k.im;
  assert(d<>0, s+'division by zero complex scalar');
  result.re :=  k.re/d;
  result.im := -k.im/d;
end;

class operator TVMobjC.+(const A, B: TVMobjC): TVMobjC;
const
  s : String = 'Operator + (TVMobjC) : ';
var
  one : TComplex8;
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
begin
  assert((A.rows=B.rows) and (A.cols=B.cols), s+'matrix dimensions must match');
  result := CopyObjC(B);
  for i := 0 to A.rows*A.cols-1 do
    result.fdata[i] := CAddC(result.fdata[i], A.fdata[i]);
end;
{$ELSE}
begin
  assert((A.rows=B.rows) and (A.cols=B.cols), s+'matrix dimensions must match');
  one := Cplx8(1,0);
  result := CopyObjC(B);
  cblas_caxpy(A.rows*A.cols, @one, @A.FData[0], 1, @result.FData[0], 1);
end;
{$ENDIF}

class operator TVMobjC.-(const A, B: TVMobjC): TVMobjC;
const
  s : String = 'Operator - (TVMobjC) : ';
var
  negOne : TComplex8;
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
begin
  assert((A.rows=B.rows) and (A.cols=B.cols), s+'matrix dimensions must match');
  result := CopyObjC(A);
  for i := 0 to A.rows*A.cols-1 do
    result.fdata[i] := CSubC(result.fdata[i], B.fdata[i]);
end;
{$ELSE}
begin
  assert((A.rows=B.rows) and (A.cols=B.cols), s+'matrix dimensions must match');
  negOne := Cplx8(-1,0);
  result := CopyObjC(A);
  cblas_caxpy(A.rows*A.cols, @negOne, @B.FData[0], 1, @result.FData[0], 1);
end;
{$ENDIF}

class operator TVMobjC.-(const A: TVMobjC): TVMobjC;
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
begin
  result := CopyObjC(A);
  for i := 0 to A.rows*A.cols-1 do
    result.fdata[i] := Cplx8(-result.fdata[i].re, -result.fdata[i].im);
end;
{$ELSE}
begin
  result := CopyObjC(A);
  cblas_csscal(A.rows*A.cols, -1, @result.FData[0], 1);
end;
{$ENDIF}

class operator TVMobjC.*(const A, B: TVMobjC): TVMobjC;
begin
  result := MulObjC(A, B);
end;

class operator TVMobjC.*(const A: TVMobjC; const k: TComplex8): TVMobjC;
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
begin
  result := CopyObjC(A);
  for i := 0 to A.rows*A.cols-1 do
    result.fdata[i] := CMulC(result.fdata[i], k);
end;
{$ELSE}
begin
  result := CopyObjC(A);
  cblas_cscal(A.rows*A.cols, @k, @result.FData[0], 1);
end;
{$ENDIF}

class operator TVMobjC.*(const k: TComplex8; const A: TVMobjC): TVMobjC;
begin
  result := A * k;
end;

class operator TVMobjC.*(const A: TVMobjC; const k: Single): TVMobjC;
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
begin
  result := CopyObjC(A);
  for i := 0 to A.rows*A.cols-1 do
    result.fdata[i] := Cplx8(result.fdata[i].re*k, result.fdata[i].im*k);
end;
{$ELSE}
begin
  result := CopyObjC(A);
  cblas_csscal(A.rows*A.cols, k, @result.FData[0], 1);
end;
{$ENDIF}

class operator TVMobjC.*(const k: Single; const A: TVMobjC): TVMobjC;
begin
  result := A * k;
end;

class operator TVMobjC./(const A: TVMobjC; const k: TComplex8): TVMobjC;
var
  r : TComplex8;
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
begin
  result := CopyObjC(A);
  for i := 0 to A.rows*A.cols-1 do
    result.fdata[i] := CDivC(result.fdata[i], k);
end;
{$ELSE}
begin
  r := ReciprocalC(k);
  result := CopyObjC(A);
  cblas_cscal(A.rows*A.cols, @r, @result.FData[0], 1);
end;
{$ENDIF}

class operator TVMobjC./(const A: TVMobjC; const k: Single): TVMobjC;
const
  s : String = 'Operator / (TVMobjC) : ';
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
begin
  assert(k<>0, s+'division by zero');
  result := CopyObjC(A);
  for i := 0 to A.rows*A.cols-1 do
    result.fdata[i] := Cplx8(result.fdata[i].re/k, result.fdata[i].im/k);
end;
{$ELSE}
begin
  assert(k<>0, s+'division by zero');
  result := CopyObjC(A);
  cblas_csscal(A.rows*A.cols, 1/k, @result.FData[0], 1);
end;
{$ENDIF}

class operator TVMobjC.+(const A: TVMobjC; const B: TVMobjS): TVMobjC;
begin
  result := A + RealToComplexS(B);
end;

class operator TVMobjC.+(const A: TVMobjS; const B: TVMobjC): TVMobjC;
begin
  result := RealToComplexS(A) + B;
end;

class operator TVMobjC.-(const A: TVMobjC; const B: TVMobjS): TVMobjC;
begin
  result := A - RealToComplexS(B);
end;

class operator TVMobjC.-(const A: TVMobjS; const B: TVMobjC): TVMobjC;
begin
  result := RealToComplexS(A) - B;
end;

class operator TVMobjC.*(const A: TVMobjC; const B: TVMobjS): TVMobjC;
begin
  result := MatMultC(A, RealToComplexS(B));
end;

class operator TVMobjC.*(const A: TVMobjS; const B: TVMobjC): TVMobjC;
begin
  result := MatMultC(RealToComplexS(A), B);
end;

class operator TVMobjC.=(const A, B: TVMobjC): Boolean;
begin
  Result := (A.rows = B.rows) and (A.cols = B.cols) and
            CompareMem(@A.FData[0], @B.FData[0], A.rows*A.cols*SizeOf(TComplex8));
end;

function Sin(const A: TVMobjC): TVMobjC;
{$IFDEF PUREPASCAL}
var
  i : Integer;
begin
  result := TVMobjC.Create(A.rows, A.cols);
  for i := 0 to A.rows*A.cols-1 do result.fdata[i] := CSinC(A.fdata[i]);
end;
{$ELSE}
begin
  result := TVMobjC.Create(A.rows, A.cols);
  vcSin(A.rows*A.cols, @A.FData[0], @result.FData[0]);
end;
{$ENDIF}

function Cos(const A: TVMobjC): TVMobjC;
{$IFDEF PUREPASCAL}
var
  i : Integer;
begin
  result := TVMobjC.Create(A.rows, A.cols);
  for i := 0 to A.rows*A.cols-1 do result.fdata[i] := CCosC(A.fdata[i]);
end;
{$ELSE}
begin
  result := TVMobjC.Create(A.rows, A.cols);
  vcCos(A.rows*A.cols, @A.FData[0], @result.FData[0]);
end;
{$ENDIF}

function Tan(const A: TVMobjC): TVMobjC;
{$IFDEF PUREPASCAL}
var
  i : Integer;
begin
  result := TVMobjC.Create(A.rows, A.cols);
  for i := 0 to A.rows*A.cols-1 do result.fdata[i] := CDivC(CSinC(A.fdata[i]), CCosC(A.fdata[i]));
end;
{$ELSE}
begin
  result := TVMobjC.Create(A.rows, A.cols);
  vcTan(A.rows*A.cols, @A.FData[0], @result.FData[0]);
end;
{$ENDIF}

function Sinh(const A: TVMobjC): TVMobjC;
{$IFDEF PUREPASCAL}
var
  i : Integer;
begin
  result := TVMobjC.Create(A.rows, A.cols);
  for i := 0 to A.rows*A.cols-1 do result.fdata[i] := CSinhC(A.fdata[i]);
end;
{$ELSE}
begin
  result := TVMobjC.Create(A.rows, A.cols);
  vcSinh(A.rows*A.cols, @A.FData[0], @result.FData[0]);
end;
{$ENDIF}

function Sqr(const A: TVMobjC): TVMobjC;
{$IFDEF PUREPASCAL}
var
  i : Integer;
begin
  result := TVMobjC.Create(A.rows, A.cols);
  for i := 0 to A.rows*A.cols-1 do result.fdata[i] := CMulC(A.fdata[i], A.fdata[i]);
end;
{$ELSE}
begin
  //MKL VM has no vcSqr (complex Sqr isn't part of the VM function set,
  //unlike real vsSqr) - so square elementwise via vcMul(A, A) instead.
  result := TVMobjC.Create(A.rows, A.cols);
  vcMul(A.rows*A.cols, @A.FData[0], @A.FData[0], @result.FData[0]);
end;
{$ENDIF}

function Sqrt(const A: TVMobjC): TVMobjC;
{$IFDEF PUREPASCAL}
var
  i : Integer;
begin
  result := TVMobjC.Create(A.rows, A.cols);
  for i := 0 to A.rows*A.cols-1 do result.fdata[i] := CSqrtC(A.fdata[i]);
end;
{$ELSE}
begin
  result := TVMobjC.Create(A.rows, A.cols);
  vcSqrt(A.rows*A.cols, @A.FData[0], @result.FData[0]);
end;
{$ENDIF}

function Exp(const A: TVMobjC): TVMobjC;
{$IFDEF PUREPASCAL}
var
  i : Integer;
begin
  result := TVMobjC.Create(A.rows, A.cols);
  for i := 0 to A.rows*A.cols-1 do result.fdata[i] := CExpC(A.fdata[i]);
end;
{$ELSE}
begin
  result := TVMobjC.Create(A.rows, A.cols);
  vcExp(A.rows*A.cols, @A.FData[0], @result.FData[0]);
end;
{$ENDIF}

function Ln(const A: TVMobjC): TVMobjC;
{$IFDEF PUREPASCAL}
var
  i : Integer;
begin
  result := TVMobjC.Create(A.rows, A.cols);
  for i := 0 to A.rows*A.cols-1 do result.fdata[i] := CLnC(A.fdata[i]);
end;
{$ELSE}
begin
  result := TVMobjC.Create(A.rows, A.cols);
  vcLn(A.rows*A.cols, @A.FData[0], @result.FData[0]);
end;
{$ENDIF}

function MulObjC(const A, B: TVMObjC): TVMobjC;
const
  s: string ='Routine MulObjC : ';
{$IFDEF PUREPASCAL}
var
  i : Integer;
begin
  assert((a.rows=b.rows)and(a.cols=b.cols),s+'Dimensions of A and B must be the same');
  result := CopyObjC(A);
  for i := 0 to A.rows*A.cols-1 do
    result.fdata[i] := CMulC(result.fdata[i], B.fdata[i]);
end;
{$ELSE}
begin
  assert((a.rows=b.rows)and(a.cols=b.cols),s+'Dimensions of A and B must be the same');
  result := CopyObjC(A);
  vcMul(A.rows*A.cols, @A.FData[0], @B.FData[0], @result.FData[0]);
end;
{$ENDIF}

function DivObjC(const A, B: TVMObjC): TVMobjC;
const
  s: string ='Routine DivObjC : ';
{ Element-wise complex division, the divObj/DivObjS/DivObjZ counterpart
  for single-precision complex data. PUREPASCAL branch uses CDivC (the
  same complex-divide helper PurePascalLUC/PurePascalLUSolveC already
  use), library-backed branch calls MKL VML's vcDiv - see DivObjZ's
  comment for why this is the plain "vc*" entry point, not a vmc*-mode
  one. }
{$IFDEF PUREPASCAL}
var
  i : Integer;
begin
  assert((a.rows=b.rows)and(a.cols=b.cols),s+'Dimensions of A and B must be the same');
  result := CopyObjC(A);
  for i := 0 to A.rows*A.cols-1 do
    result.fdata[i] := CDivC(result.fdata[i], B.fdata[i]);
end;
{$ELSE}
begin
  assert((a.rows=b.rows)and(a.cols=b.cols),s+'Dimensions of A and B must be the same');
  result := CopyObjC(A);
  vcDiv(A.rows*A.cols, @A.FData[0], @B.FData[0], @result.FData[0]);
end;
{$ENDIF}

{$IFNDEF HAVE_FFTW}
// Direct O(N^2) DFT - single-precision counterpart to newVMComplex.pas's own
// PPDirectDFT; see that unit's header comment for the full rationale (works
// for any N, unlike a power-of-two-only radix-2 fast FFT).
procedure PPDirectDFTS(N: Integer; InData, OutData: PComplex8; Forward: Boolean);
var
  k, m : Integer;
  sgn, angle, c, sn, accre, accim : Single;
begin
  if Forward then sgn := -1 else sgn := 1;
  for k := 0 to N-1 do begin
    accre := 0; accim := 0;
    for m := 0 to N-1 do begin
      angle := sgn * 2 * Pi * k * m / N;
      c := cos(angle); sn := sin(angle);
      accre := accre + InData[m].re*c - InData[m].im*sn;
      accim := accim + InData[m].re*sn + InData[m].im*c;
    end;
    OutData[k].re := accre;
    OutData[k].im := accim;
  end;
end;
{$ENDIF}

function FFT_R2C(const A: TVMobjS): TVMobjC;
const
  s : String = 'Routine FFT_R2C : ';
var
  n, nc : integer;
{$IFDEF HAVE_FFTW}
  plan : fftw_plan;
{$ELSE}
  k, m : Integer;
  angle, c, sn, accre, accim : Single;
{$ENDIF}
begin
  assert((A.Rows=1) or (A.Cols=1), s+'A must be a vector (Rows=1 or Cols=1)');
  n := A.Rows*A.Cols;
  nc := n div 2 + 1;
  if A.Cols = 1 then result := TVMobjC.Create(nc, 1) else result := TVMobjC.Create(1, nc);
{$IFDEF HAVE_FFTW}
  assert(Assigned(fftwf_plan_dft_r2c_1d), s+'FFTW3 (single) library not loaded');
  plan := fftwf_plan_dft_r2c_1d(n, A.DataPtr, PComplex8(@result.FData[0]), FFTW_ESTIMATE or FFTW_PRESERVE_INPUT);
  assert(plan<>nil, s+'fftwf_plan_dft_r2c_1d failed');
  fftwf_execute_dft_r2c(plan, A.DataPtr, PComplex8(@result.FData[0]));
  fftwf_destroy_plan(plan);
{$ELSE}
  for k := 0 to nc-1 do begin
    accre := 0; accim := 0;
    for m := 0 to n-1 do begin
      angle := -2 * Pi * k * m / n;
      c := cos(angle); sn := sin(angle);
      accre := accre + A.DataPtr[m]*c;
      accim := accim + A.DataPtr[m]*sn;
    end;
    result.FData[k] := Cplx8(accre, accim);
  end;
{$ENDIF}
end;

function FFT_C2R(const A: TVMobjC; N: Integer): TVMobjS;
const
  s : String = 'Routine FFT_C2R : ';
var
  nc : integer;
{$IFDEF HAVE_FFTW}
  plan : fftw_plan;
  Nd : Double;
{$ELSE}
  full, outc : array of TComplex8;
  k : Integer;
{$ENDIF}
begin
  assert((A.Rows=1) or (A.Cols=1), s+'A must be a vector (Rows=1 or Cols=1)');
  assert(N>0, s+'N must be > 0');
  nc := A.Rows*A.Cols;
  assert(nc = (N div 2 + 1), s+'A''s length must be N div 2 + 1');
  if A.Cols = 1 then result := TVMobjS.Create(N, 1) else result := TVMobjS.Create(1, N);
{$IFDEF HAVE_FFTW}
  assert(Assigned(fftwf_plan_dft_c2r_1d), s+'FFTW3 (single) library not loaded');
  plan := fftwf_plan_dft_c2r_1d(N, PComplex8(@A.FData[0]), result.DataPtr, FFTW_ESTIMATE or FFTW_PRESERVE_INPUT);
  assert(plan<>nil, s+'fftwf_plan_dft_c2r_1d failed');
  fftwf_execute_dft_c2r(plan, PComplex8(@A.FData[0]), result.DataPtr);
  fftwf_destroy_plan(plan);
  assert(Assigned(cblas_sscal), s+'OpenBLAS not available on this machine - FFT_C2R normalization has no PUREPASCAL fallback');
  //Divide via an explicit Double intermediate (Nd), not "1.0/N" directly -
  //see newVMComplex.pas's FFT_C2R for the full rationale (a confirmed
  //FPC/AArch64 codegen bug: "1.0/IntegerExpr" silently loses precision to
  //~single, even though "1.0/Nd" with Nd already Double is fully precise).
  Nd := N;
  cblas_sscal(N, 1.0/Nd, result.DataPtr, 1);   //normalize, matching FFT_C2R(FFT_R2C(x), N) = x
{$ELSE}
  //See newVMComplex.pas's FFT_C2R for the conjugate-symmetry rationale.
  SetLength(full, N);
  SetLength(outc, N);
  for k := 0 to nc-1 do full[k] := A.FData[k];
  for k := nc to N-1 do full[k] := Cplx8(A.FData[N-k].re, -A.FData[N-k].im);
  PPDirectDFTS(N, @full[0], @outc[0], False);
  for k := 0 to N-1 do result.DataPtr[k] := outc[k].re / N;
{$ENDIF}
end;

function FFT(const A: TVMobjC): TVMobjC;
const
  s : String = 'Routine FFT : ';
var
  n : integer;
{$IFDEF HAVE_FFTW}
  plan : fftw_plan;
{$ENDIF}
begin
  assert((A.Rows=1) or (A.Cols=1), s+'A must be a vector (Rows=1 or Cols=1)');
  n := A.Rows*A.Cols;
  result := TVMobjC.Create(A.Rows, A.Cols);
{$IFDEF HAVE_FFTW}
  assert(Assigned(fftwf_plan_dft_1d), s+'FFTW3 (single) library not loaded');
  plan := fftwf_plan_dft_1d(n, PComplex8(@A.FData[0]), PComplex8(@result.FData[0]), FFTW_FORWARD, FFTW_ESTIMATE or FFTW_PRESERVE_INPUT);
  assert(plan<>nil, s+'fftwf_plan_dft_1d failed');
  fftwf_execute_dft(plan, PComplex8(@A.FData[0]), PComplex8(@result.FData[0]));
  fftwf_destroy_plan(plan);
{$ELSE}
  PPDirectDFTS(n, PComplex8(@A.FData[0]), PComplex8(@result.FData[0]), True);
{$ENDIF}
end;

function IFFT(const A: TVMobjC): TVMobjC;
const
  s : String = 'Routine IFFT : ';
var
  n, i : integer;
{$IFDEF HAVE_FFTW}
  plan : fftw_plan;
  Nd : Double;
{$ENDIF}
begin
  assert((A.Rows=1) or (A.Cols=1), s+'A must be a vector (Rows=1 or Cols=1)');
  n := A.Rows*A.Cols;
  result := TVMobjC.Create(A.Rows, A.Cols);
{$IFDEF HAVE_FFTW}
  assert(Assigned(fftwf_plan_dft_1d), s+'FFTW3 (single) library not loaded');
  plan := fftwf_plan_dft_1d(n, PComplex8(@A.FData[0]), PComplex8(@result.FData[0]), FFTW_BACKWARD, FFTW_ESTIMATE or FFTW_PRESERVE_INPUT);
  assert(plan<>nil, s+'fftwf_plan_dft_1d failed');
  fftwf_execute_dft(plan, PComplex8(@A.FData[0]), PComplex8(@result.FData[0]));
  fftwf_destroy_plan(plan);
  assert(Assigned(cblas_csscal), s+'OpenBLAS not available on this machine - IFFT normalization has no PUREPASCAL fallback');
  Nd := n;  //see newVMComplex.pas's FFT_C2R for why "1.0/n" (Integer) is unsafe here
  cblas_csscal(n, 1.0/Nd, @result.FData[0], 1);  //normalize, matching IFFT(FFT(x)) = x
{$ELSE}
  PPDirectDFTS(n, PComplex8(@A.FData[0]), PComplex8(@result.FData[0]), False);
  for i := 0 to n-1 do begin
    result.FData[i].re := result.FData[i].re / n;
    result.FData[i].im := result.FData[i].im / n;
  end;
{$ENDIF}
end;

// Single-precision analogue of newVMComplex.pas's PowerSpectrum(A:
// TVMobj) - see that function's own header comment for the full
// rationale, which applies here identically (just Single/TVMobjS/
// TVMobjC throughout instead of Double/TVMobj/TVMobjZ).
function PowerSpectrum(const A: TVMobjS): TVMobjS;
const
  s : String = 'Routine PowerSpectrum : ';
var
  N, HalfN, i : Integer;
  RowA, W, Windowed, RowResult : TVMobjS;
  Spectrum : TVMobjC;
  bin : TComplex8;
begin
  assert((A.Rows=1) or (A.Cols=1), s+'A must be a vector (Rows=1 or Cols=1)');
  N := A.Rows*A.Cols;
  HalfN := N div 2;
  assert(HalfN > 0, s+'A must have at least 2 elements');

  RowA := ReshapeS(A, 1, N);

  W := TVMobjS.Create(1, N);
  for i := 0 to N-1 do
    W[0,i] := 0.54 - 0.46*cos(2*Pi*i/(N-1));

  Windowed := RowA * W;
  Spectrum := FFT_R2C(Windowed);

  RowResult := TVMobjS.Create(1, HalfN);
  for i := 0 to HalfN-1 do begin
    bin := Spectrum[0,i];
    RowResult[0,i] := bin.re*bin.re + bin.im*bin.im;
  end;

  if A.Cols = 1 then result := ReshapeS(RowResult, HalfN, 1) else result := RowResult;
end;

// Single-precision analogue of newVMComplex.pas's PowerSpectrum(A:
// TVMobjZ) - see that function's own header comment for the full
// rationale, which applies here identically.
function PowerSpectrum(const A: TVMobjC): TVMobjS;
const
  s : String = 'Routine PowerSpectrum : ';
var
  N, i : Integer;
  RowA, Windowed, Spectrum : TVMobjC;
  W, RowResult : TVMobjS;
  bin : TComplex8;
begin
  assert((A.Rows=1) or (A.Cols=1), s+'A must be a vector (Rows=1 or Cols=1)');
  N := A.Rows*A.Cols;
  assert(N > 0, s+'A must have at least 1 element');

  RowA := ReshapeC(A, 1, N);

  W := TVMobjS.Create(1, N);
  for i := 0 to N-1 do
    W[0,i] := 0.54 - 0.46*cos(2*Pi*i/(N-1));

  Windowed := TVMobjC.Create(1, N);
  for i := 0 to N-1 do begin
    bin := RowA[0,i];
    Windowed[0,i] := Cplx8(bin.re*W[0,i], bin.im*W[0,i]);
  end;

  Spectrum := FFT(Windowed);

  RowResult := TVMobjS.Create(1, N);
  for i := 0 to N-1 do begin
    bin := Spectrum[0,i];
    RowResult[0,i] := bin.re*bin.re + bin.im*bin.im;
  end;

  if A.Cols = 1 then result := ReshapeS(RowResult, N, 1) else result := RowResult;
end;

end.
