unit newVM;

{*******************************************************************************

     Vector / Matrix objects leveraging intel mkl libraries

     Dr H. Dent uk. email howard@hgrd.co.uk             29 July 2026

     Inspired by Dew MtxVec Library for fpc but does not  distinguish
     between matrix and vector objects. Vectors are column dimension (*,1)
     or row dimension (1.*).

     ADDITIONS (for interop with newVMComplex.pas):
       - public DataPtr function: raw pointer to the underlying double
         buffer, so other units can pass it straight into MKL calls
         without needing full friend access to the record internals.
       - public Rows / Cols read-only properties, so other units can
         query dimensions to size a matching object (e.g. for a real ->
         complex copy of the "same dimensions").
       These do not change any existing behaviour.

     OPERATOR OVERLOADS (algebraic expressions on TVMobj):
       - '+' and '-' are element-wise, via cblas_daxpy (Y := alpha*X + Y).
       - unary '-' negates via cblas_dscal.
       - '*' between two TVMobj is ELEMENT-WISE multiplication (the
         Hadamard product), via mulObj (MKL VML's vdMul) - NOT matrix
         multiplication. Use the separate MatMult function (cblas_dgemm)
         for a real matrix product. newVMTests.pas's own
         "AssertTrue(A * B = mulObj(A, B))" is the operator's actual,
         tested contract - a prior version of this comment claimed '*'
         was matrix multiplication, which it is not and, per that test,
         never was; getting this backwards produces a matrix that
         silently compiles and runs, just on the wrong values (see
         demos/Chebyshev/NormalIntegration/uCheb.pas's TCheb.Create for a
         real bug this caused: FD2 := FD * FD instead of
         MatMult(FD, FD)).
       - '*' and '/' against a plain Double scalar scale every element,
         via cblas_dscal and IPP's ippsDivC_64f_I respectively.
       These let expressions like  C := A*B + D;  (element-wise) or
       C := 2*A - B/3;  be written directly instead of via named
       routines; use MatMult(A,B) explicitly wherever a real matrix
       product is what's actually wanted.

*******************************************************************************}

{$mode delphi}{$H+}
{$Align 8}

{$I newVMConfig.inc}
// newVMConfig.inc (generated by ./newvmconfigure - see that program's own
// header comment) defines HAVE_MKL/HAVE_IPP/HAVE_OPENBLAS/HAVE_FFTW and,
// derived from those, PUREPASCAL - set whenever any of the three libraries
// this unit's "core" linear algebra actually needs (OpenBLAS, MKL, IPP) is
// missing on the machine that ran the configure tool. When PUREPASCAL is
// set, every routine below that would otherwise call into cblas/OneAPI
// instead uses a plain-Pascal implementation of its own, individually
// guarded - see each routine's own comment for the algorithm used (LU
// decomposition with partial pivoting backs LinearSolve/Invert/Det;
// everything else is a direct loop). FFTW-backed DCT/DST/FFT
// (r2rTransform) have no such fallback - out of scope, since a correct
// pure-Pascal FFT is a much larger undertaking than the rest of this list;
// they already degrade to a clear runtime assert on their own when FFTW
// isn't loaded (see r2rTransform), independent of PUREPASCAL.
// (NOTE: this comment block deliberately uses '//' line comments, not a
// '{ ... }' block - Pascal block comments don't nest, so mentioning a
// real {$IFDEF ...} directive by name inside one would truncate the
// comment at its first '}' and feed the rest of this paragraph to the
// compiler as code; see newvmconfigure.lpr's own comment-writing code
// for the same gotcha hit and fixed while generating newVMConfig.inc.)

{$IFDEF UNIX}
  {$IFDEF HAVE_MKL}
{$Linklib 'mkl_rt.so'}
{$Linklib 'pthread'}
{$Linklib 'm'}
{$Linklib 'dl'}
//The three libs above aren't used directly by this unit, but mkl_rt.so
//dlopen's libmkl_core.so (and friends) at runtime, which expects libm/
//pthread/dl to already be loaded into the process's global symbol table.
//Without this, you get errors like:
//  symbol lookup error: .../libmkl_core.so: undefined symbol: log10
//This is a Unix/ELF dynamic-linker quirk - Windows DLLs resolve their own
//imports independently, so mkl_rt.dll needs no such preload on Windows.
  {$ENDIF}
{$ENDIF}

interface

uses
  Classes, SysUtils,cblas,math,TestRegistry,OneAPI,Types,fftw3,newVMI;

Const
  MaxDim = 65536;    //maximum dimensions of any array

Type
  TDim = 0..MaxDim-1;
  TDataSize = 1..MaxDim*MaxDim;
  TVector = Array of Double;   //maximum dimensions of any array


type
  
  { TVMobj }

  TVMobj = record
    private
      fData : tVector;  //Holds data for object
      frows, fcols : TDim;
      fIpiv : array of Integer;  //cached LU pivot indices from LinearSolve, valid iff fLUFactored
      fLUFactored : Boolean;     //True once LinearSolve has LU-factorised this object in place (see LinearSolve)
      function getelement(r,c: TDim): Double;
      procedure setelement(r,c: TDim; AValue: Double);
    public
      constructor create(r,c :tDim);Overload;
      Constructor create(r,c: TDim; const Values : TVector); overload;
      function writeMatrix: TStringList;
      property Element[r,c:TDim]:Double read getelement write setelement; default;
      procedure fillRandom;
      procedure Id;
      procedure linspace(Start, increment: Double);
      function Transpose: TVMObj;
      function DataPtr: PDouble;   //raw buffer, for MKL interop from other units
      property Rows: TDim read frows;              //read-only dimension accessors
      property Cols: TDim read fcols;
      property LU: Boolean read fLUFactored;  //True once LinearSolve has cached an LU factorisation of this object
      class operator +(const A, B: TVMobj): TVMobj;
      class operator -(const A, B: TVMobj): TVMobj;
      class operator -(const A: TVMobj): TVMobj;
      class operator *(const A, B: TVMobj): TVMobj;
      class operator *(const A: TVMobj; const k: Double): TVMobj;
      class operator *(const k: Double; const A: TVMobj): TVMobj;
      class operator /(const A: TVMobj; const k: Double): TVMobj;
      class operator =(const A, B: TVMobj): Boolean;
    end;

function calcoffset(r,c,cols :TDim):integer;inline;
function MatMult( const A, B: TVMObj): TVMobj;
function LinearSolve(var A, B: TVMObj):integer;
function CopyObj(Const A : TVMObj):TVMobj;
function Invert(const A: TVMobj): TVMobj;  //matrix inverse, via LAPACKE_dgetrf+dgetri; leaves A untouched
{ Find - element-wise comparison of A against Value using Op (see
  TVMCompareOp in newVMI.pas: cmpEQ/cmpLT/cmpLE/cmpGT/cmpGE). Returns a
  same-shape TVMobjI with 1 where the criteria matches and 0 elsewhere.
  No MKL/IPP primitive produces a comparison mask, so this is a plain
  loop; marked "overload" since newVMSingle.pas declares the TVMobjS
  analogue of the same name. }
function Find(const A: TVMobj; Op: TVMCompareOp; Value: Double): TVMobjI; overload;
{ Kron - Kronecker matrix product of A (m,n) and B (p,q): an (m*p, n*q)
  result whose (i,j) block (each p x q) is A[i,j]*B. No BLAS/LAPACK
  routine computes a Kronecker product directly, so this places each
  block via cblas_daxpy (alpha=A[i,j]) row-by-row into the zero-filled
  result - the same "scale via axpy onto a fresh buffer" idiom the '+'/'-'
  operators use, just applied per source row instead of over the whole
  buffer at once, since a block's rows aren't contiguous in the result's
  row-major layout. }
function Kron(const A, B: TVMobj): TVMobj;
{ Diag - turns a column vector A (n,1) into an (n,n) diagonal matrix with
  A's elements on the leading diagonal. Diagonal element i sits at flat
  row-major offset i*n+i = i*(n+1), so this is a single cblas_dcopy from
  A (stride 1) into the zero-filled result buffer at stride (n+1) - no
  loop needed. }
function Diag(const A: TVMobj): TVMobj;
function Norm(const A: TVMobj): Double;  //Euclidean (L2) norm of vector A (Rows=1 or Cols=1), via cblas_dnrm2
{ Trace - sum of A's leading-diagonal elements (A must be square). No
  BLAS/LAPACK/IPP routine computes a trace directly (IPP's ippsSum only
  sums a contiguous buffer, and the diagonal isn't contiguous - extracting
  it first via cblas_?copy, as Diag does, would cost an allocation for no
  benefit over just summing in the loop), so this is a plain loop, same
  rationale as newVMI.pas's Id/Transpose or this unit's own Find/Gather. }
function Trace(const A: TVMobj): Double;
{ Det - determinant of A (must be square), via LAPACKE_dgetrf (LU
  factorisation with partial pivoting, A = P*L*U, run on a CopyObj scratch
  buffer so A itself is left untouched, same convention as Invert). det(A)
  = det(P)*det(L)*det(U): det(L) = 1 (unit lower triangular, not stored),
  det(U) is the product of the diagonal entries getrf leaves in the
  scratch buffer, and det(P) = -1 per row actually interchanged (ipiv[i]
  <> i+1, using getrf's 1-based Fortran pivot convention). No info=0
  assert like Invert's - a singular A (info>0) naturally yields a zero
  diagonal entry, so the product comes out to exactly 0, the correct
  determinant, without special-casing. }
function Det(const A: TVMobj): Double;
{ FlipUD - reverses the order of A's rows (row 0 <-> row Rows-1, etc), same
  shape as A. No BLAS/LAPACK/IPP primitive reverses whole rows as a block
  (IPP's ippsFlip reverses individual elements, not row-sized chunks), so
  this copies each source row to its mirrored destination row via
  cblas_dcopy - one call per row, same "no block primitive -> loop of
  per-row BLAS calls" idiom Kron uses. }
function FlipUD(const A: TVMobj): TVMobj;
{ FlipLR - reverses the order of elements within each row of A, same shape
  as A. Unlike FlipUD, IPP has an exact primitive for this: ippsFlip_64f
  reverses a vector's element order into a (possibly different) destination
  buffer, so this calls it once per row with len=Cols. }
function FlipLR(const A: TVMobj): TVMobj;
{ MergeUD - stacks A above B into an (A.Rows+B.Rows, Cols) result (A and B
  must have the same Cols). Row-major storage makes this trivial: A's rows
  and B's rows are each already contiguous blocks, so this is just two
  whole-buffer cblas_dcopy calls, A's buffer straight into the start of the
  result and B's straight after - no per-row loop needed, unlike MergeLR. }
function MergeUD(const A, B: TVMobj): TVMobj;
{ MergeLR - places A to the left of B into an (Rows, A.Cols+B.Cols) result
  (A and B must have the same Rows). Unlike MergeUD, a source row's data
  isn't contiguous with the next row's in the merged result (each result
  row is A's row immediately followed by B's row), so this copies both
  halves of each row separately via cblas_dcopy - two calls per row, same
  "no block primitive -> loop of per-row BLAS calls" idiom Kron/FlipUD use. }
function MergeLR(const A, B: TVMobj): TVMobj;
{ Reshape - reinterprets A's Rows*Cols elements as a (NewRows,NewCols)
  matrix (asserts NewRows*NewCols = A.Rows*A.Cols). Row-major storage means
  the flat element order never changes, only how it's carved into rows, so
  this is a single whole-buffer cblas_dcopy into a differently-shaped
  result - the same "reinterpret the contiguous buffer" trick MergeUD's
  half of the copy uses. }
function Reshape(const A: TVMobj; NewRows, NewCols: TDim): TVMobj;
{ Repmat - tiles A into a (A.Rows*RowReps, A.Cols*ColReps) result, RowReps
  copies down and ColReps copies across (asserts RowReps>0, ColReps>0). No
  BLAS/LAPACK/IPP primitive tiles a block, and unlike Reshape a tile's rows
  aren't contiguous with the next tile's, so this copies each source row
  into every (row-tile, col-tile) destination slot via cblas_dcopy - same
  "no block primitive -> loop of per-row BLAS calls" idiom Kron/MergeLR use. }
function Repmat(const A: TVMobj; RowReps, ColReps: Integer): TVMobj;
{ AddScalar - adds the constant K to every element of A, returning a new
  TVMobj of the same dimensions. No dimension assert needed - valid for any
  shape. Via IPP's ippsAddC_64f_I (in-place add-constant) on a CopyObj
  scratch buffer, the same idiom the '*'/k and '/'/k scalar operators use
  (ippsDivC_64f_I) - there is no '+'/scalar operator overload for this
  (only '*'/'/' accept a plain scalar; see the OPERATOR OVERLOADS note at
  the top of this file), so this is the named-function equivalent. }
function AddScalar(const A: TVMobj; K: Double): TVMobj;
{ SubMatrix - extracts the (RCount x CCount) submatrix of A starting at
  (R0,C0) (asserts the requested block stays within A's bounds; RCount/
  CCount > 0 is enforced by TVMobj.Create itself). Via LAPACKE_dlacpy,
  pointed at A's data offset by R0*A.Cols+C0 with lda=A.Cols (A's own row
  stride) rather than RCount/CCount - LAPACKE_dlacpy's separate lda/ldb
  parameters mean this single call copies the strided block directly, no
  per-row loop needed despite the submatrix's rows not being contiguous in
  A's buffer (the same "differing leading dimensions do the strided work"
  trick CopyObj's own whole-matrix copy is a degenerate case of). }
function SubMatrix(const A: TVMobj; R0, C0, RCount, CCount: TDim): TVMobj;

{ Elementwise transcendental/algebraic functions, via MKL VML (vd* routines
  in OneAPI.pas). Each returns a new TVMobj of the same dimensions as A,
  with the function applied to every element. Marked "overload" since
  Sin/Cos/Sqr/Sqrt/Exp/Ln also exist in System/Math for plain numeric
  types - without "overload" the TVMobj versions here would hide those
  entirely within this unit, breaking any plain Sqrt(x: Double) call. }
function Sin(const A: TVMobj): TVMobj; overload;
function Cos(const A: TVMobj): TVMobj; overload;
function Tan(const A: TVMobj): TVMobj; overload;
function Sinh(const A: TVMobj): TVMobj; overload;
function Sqr(const A: TVMobj): TVMobj; overload;
function Sqrt(const A: TVMobj): TVMobj; overload;
function Exp(const A: TVMobj): TVMobj; overload;
function Ln(const A: TVMobj): TVMobj; overload;
function mulObj(const A, B: TVMObj): TVMObj;

{ Real-to-real DCT/DST types I-IV, via FFTW3 (fftw3.pas) r2r transforms on
  the double-precision library. A must be a vector (Rows=1 or Cols=1); the
  result has the same shape. Input is never mutated (FFTW_PRESERVE_INPUT).
  These are UNNORMALIZED, matching FFTW's own convention: e.g. DCT1 applied
  twice returns the original scaled by 2*(N-1) - see FFTW's "1D Real-even/
  odd DFTs" documentation for the exact scale factor per kind. Marked
  "overload" for the same reason as Sin/Cos/etc above - newVMSingle.pas
  declares the TVMobjS analogues of these same names. }
function DCT1(const A: TVMobj): TVMobj; overload;  //FFTW_REDFT00
function DCT2(const A: TVMobj): TVMobj; overload;  //FFTW_REDFT10
function DCT3(const A: TVMobj): TVMobj; overload;  //FFTW_REDFT01 (inverse of DCT2, up to scale)
function DCT4(const A: TVMobj): TVMobj; overload;  //FFTW_REDFT11 (self-inverse, up to scale)
function DST1(const A: TVMobj): TVMobj; overload;  //FFTW_RODFT00
function DST2(const A: TVMobj): TVMobj; overload;  //FFTW_RODFT10
function DST3(const A: TVMobj): TVMobj; overload;  //FFTW_RODFT01 (inverse of DST2, up to scale)
function DST4(const A: TVMobj): TVMobj; overload;  //FFTW_RODFT11 (self-inverse, up to scale)

implementation

function calcoffset(r, c, cols: TDim): integer;
begin
  result := r*cols+c;
end;

{$IFDEF PUREPASCAL}
{ PurePascalLU - in-place LU decomposition of an NxN row-major buffer with
  partial pivoting, matching LAPACK's dgetrf storage convention (unit
  lower-triangular L below the diagonal, U on/above it, both packed into
  the same buffer) and its 1-based ipiv convention (ipiv[i] = the row,
  1-based, row i was swapped with) - the shared basis the PUREPASCAL
  LinearSolve/Invert/Det bodies below build on, same relationship those
  have to LAPACKE_dgetrf in the library-backed build. Returns 0 if A was
  non-singular throughout, or the 1-based row index of the first
  exactly-zero pivot otherwise (matching LAPACKE_dgetrf's "info"
  convention) - the decomposition still runs to completion either way,
  since a singular matrix has a perfectly well-defined LU form and Det's
  fallback relies on that to land on exactly 0 with no special-casing,
  same as its LAPACKE-backed counterpart. }
function PurePascalLU(Data: PDouble; N: Integer; var ipiv: array of Integer): Integer;
var
  i, j, k, p: Integer;
  maxval, absval, tmp: Double;
begin
  result := 0;
  for k := 0 to N-1 do begin
    p := k;
    maxval := Abs(Data[k*N+k]);
    for i := k+1 to N-1 do begin
      absval := Abs(Data[i*N+k]);
      if absval > maxval then begin
        maxval := absval;
        p := i;
      end;
    end;
    ipiv[k] := p+1;
    if p <> k then
      for j := 0 to N-1 do begin
        tmp := Data[k*N+j];
        Data[k*N+j] := Data[p*N+j];
        Data[p*N+j] := tmp;
      end;
    if Data[k*N+k] = 0 then begin
      if result = 0 then result := k+1;
      Continue;
    end;
    for i := k+1 to N-1 do begin
      Data[i*N+k] := Data[i*N+k] / Data[k*N+k];
      for j := k+1 to N-1 do
        Data[i*N+j] := Data[i*N+j] - Data[i*N+k]*Data[k*N+j];
    end;
  end;
end;

{ PurePascalLUSolve - solves A*X=B for X given the LU-packed buffer and
  1-based ipiv PurePascalLU produced, overwriting B with the result - same
  in-place convention as LAPACKE_dgetrs, whose role this fills in the
  PUREPASCAL build. B is (N, nrhs), row-major, ldb=nrhs. }
procedure PurePascalLUSolve(LU: PDouble; N: Integer; const ipiv: array of Integer; B: PDouble; nrhs: Integer);
var
  i, j, r, p: Integer;
  sum, tmp: Double;
begin
  for i := 0 to N-1 do begin
    p := ipiv[i]-1;
    if p <> i then
      for j := 0 to nrhs-1 do begin
        tmp := B[i*nrhs+j];
        B[i*nrhs+j] := B[p*nrhs+j];
        B[p*nrhs+j] := tmp;
      end;
  end;
  for r := 0 to nrhs-1 do
    for i := 1 to N-1 do begin
      sum := 0;
      for j := 0 to i-1 do
        sum := sum + LU[i*N+j]*B[j*nrhs+r];
      B[i*nrhs+r] := B[i*nrhs+r] - sum;
    end;
  for r := 0 to nrhs-1 do
    for i := N-1 downto 0 do begin
      sum := 0;
      for j := i+1 to N-1 do
        sum := sum + LU[i*N+j]*B[j*nrhs+r];
      B[i*nrhs+r] := (B[i*nrhs+r] - sum) / LU[i*N+i];
    end;
end;
{$ENDIF}

{ TVMobj }

function TVMobj.getelement(r,c: TDim): Double;
var
   Ix : Integer;
begin
   assert((r<rows) and (c<cols),'Dimensions don''t match in getelement');
   Ix := calcoffset(r,c,cols);
   assert(Ix<= high(fdata),'Index out of range in get element');
   result := fdata[Ix];
end;

procedure TVMobj.setelement(r,c:TDim; AValue: Double);
var
 Ix : Integer;
begin
   assert((r<rows) and (c<cols),'Dimensions don''t match in setelement');
   Ix := calcoffset(r,c,cols);
   assert(Ix <= high(fdata),'Index out of range in set element');
   fdata[Ix] := Avalue;
end;

constructor TVMobj.create(r,c :tDim);
var
  i,N : integer;
begin
  assert((r>0) and (c>0),'rows and columns must be > 0');
  frows := r;
  fcols := c;
  N := r*c;
  setLength(fData,N);
  for i := low(fdata) to high(fdata) do fdata[i] := 0;
  fLUFactored := False;
end;

constructor TVMobj.create(r,c : TDim; const Values: TVector);
begin
  assert((r>0) and (c>0),'rows and columns must be > 0');
  assert( (r*c) = high(values)+1,'Incompatible dimensions ');
  frows := r;
  fcols := c;
  fdata := copy(Values,0,high(values)+1);
  fLUFactored := False;
end;

function TVMobj.writeMatrix: TStringList;
const
  fieldwidth = 10;
var
   i,j,k,l: integer;
   s,t : String;
begin
  result:= TStringList.create;
  for i:=0 to rows-1 do begin // row by row
    s := '    ['+chr(9);//+chr(9);
    for j:=0 to cols-1 do begin
      t :=floatToStrf(FData[i*cols+j],fffixed,10,3);
      s := s + t;
      l := length(t);    // pad t to get constant length
     if l < fieldwidth then
      for k := 1 to fieldwidth-l do s := s +' ';
    end;
    s := s {+chr(9)}+']';
    result.add(s);
  end;
end;

procedure TVMobj.fillRandom;
//
// from c program at
//https://www.smcm.iqfr.csic.es/docs/intel/mkl/mkl_manual/sf/sf_vslusage.htm
// Timed for 1000x1000 loop 100ms intel mkl 2ms!
//
{$IFDEF PUREPASCAL}
{ PUREPASCAL: no VSL, so this generates via a fixed-seed Box-Muller
  transform over FPC's own Random() instead of vdRngGaussian - reseeding
  RandSeed to the same constant (777) on every call preserves the
  MKL-backed version's actual tested contract (two same-sized fillRandom
  calls produce bit-identical data, exploited via '=' by
  TestFillRandomDeterministic and friends - see newVMTests.pas), even
  though the specific values differ from vdRngGaussian's own output. }
var
  i, n : Integer;
  u1, u2 : Double;
begin
  RandSeed := 777;
  n := high(fdata)+1;
  i := 0;
  while i < n do begin
    repeat
      u1 := Random;
    until u1 > 0;  //avoid Ln(0)
    u2 := Random;
    fdata[i] := Sqrt(-2*Ln(u1))*Cos(2*Pi*u2);
    Inc(i);
    if i < n then begin
      fdata[i] := Sqrt(-2*Ln(u1))*Sin(2*Pi*u2);
      Inc(i);
    end;
  end;
end;
{$ELSE}
const
  vslConst = 8388608;
  VSL_RNG_METHOD_GAUSSIAN_ICDF = 2;
var
  vsSTream : pointer;
begin
  vslNewStream(@vsStream,vslConst,777);
  vdRngGaussian(VSL_RNG_METHOD_GAUSSIAN_ICDF,vsStream,high(fdata)+1,@Fdata[0],0,1);
  vsldeleteStream(@vsStream);
end;
{$ENDIF}

procedure TVMobj.Id;
const
  s : string = 'Routine Id :';
{$IFDEF PUREPASCAL}
var
  i, j : TDim;
begin
  assert(cols=rows,s +'Matrix A must be square');
  for i := 0 to rows-1 do
    for j := 0 to cols-1 do
      if i = j then fdata[calcoffset(i,j,cols)] := 1
      else fdata[calcoffset(i,j,cols)] := 0;
end;
{$ELSE}
begin
    //Check dimensions of matrices are compatible. A must be square and A.cols =
  // B.rows
  assert(cols=rows,s +'Matrix A must be square');
  lapacke_dlaset(CBlasRowMajor,'A',rows,cols,0,1,@Fdata[0],rows);
end;
{$ENDIF}

function TVMobj.DataPtr: PDouble;
begin
  result := @fdata[0];
end;

procedure TVMObj.linspace(Start, increment: Double);
const
  s : String ='routine linspace';
{$IFDEF PUREPASCAL}
  {$IFDEF HAVE_ACCELERATE}
begin
  assert(fdata <>nil,s+  ': MVObj Not Initialized');
  accel_vDSP_vrampD(@Start, @increment, @FData[0], 1, high(fdata)+1);
end;
  {$ELSE}
var
  i : Integer;
begin
  assert(fdata <>nil,s+  ': MVObj Not Initialized');
  for i := 0 to high(fdata) do
    fdata[i] := start + i*increment;
end;
  {$ENDIF}
{$ELSE}
begin
  assert(fdata <>nil,s+  ': MVObj Not Initialized');
  ippsVectorSlope_64f(@FData[0],high(fdata)+1,start,increment);
end;
{$ENDIF}

function TVMObj.Transpose:TVMObj;
var
  temp : TDim;
{$IFDEF PUREPASCAL}
var
  i, j : TDim;
begin
  result := TVMObj.Create(cols, rows);
  for i := 0 to rows-1 do
    for j := 0 to cols-1 do
      result.fdata[calcoffset(j,i,result.fcols)] := fdata[calcoffset(i,j,cols)];
end;
{$ELSE}
begin
  result := copyobj(self);
  MKL_Dimatcopy('R','T',rows,cols,1,result.DataPtr,cols,rows);
//swap row and column numbers
  temp := self.rows;
  result.frows := self.cols;
  result.fcols := temp;
end;
{$ENDIF}


function MatMult(const A, B: TVMObj): TVMobj;
const
  s : String = 'Routine MatMult :';
var
  m,n,k,I : integer;
  C : TVMObj;
{$IFDEF PUREPASCAL_BLAS}
var
  ii, jj, kk : integer;
  sum : Double;
begin
  m := A.Rows;
  n := B.Cols;
  k := A.Cols;
  assert(A.cols = B.rows,s+'columns of first matrix must equal rows of second');
  c := TVMObj.Create(m,n);
  for ii := 0 to m-1 do
    for jj := 0 to n-1 do begin
      sum := 0;
      for kk := 0 to k-1 do
        sum := sum + A.fdata[calcoffset(ii,kk,k)]*B.fdata[calcoffset(kk,jj,n)];
      C.fdata[calcoffset(ii,jj,n)] := sum;
    end;
  result := C;
end;
{$ELSE}
begin
  m := A.Rows;
  n := B.Cols;
  k := A.Cols;
  //Check for compatibilty of matrices
  assert(A.cols = B.rows,s+'columns of first matrix must equal rows of second');
  c := TVMObj.Create(m,n);
  //check library initialized
  cblas_dgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans,
              m,n,k, { m, n, k }
              1,     { alpha   }
                @A.FData[0], k,
                @B.Fdata[0], n,
              1, {beta}
                @C.Fdata[0],n
             );
    result := C;
end;
{$ENDIF}

function LinearSolve(var A, B: TVMObj):integer;
const
  s : String = 'Function linear Solve : ';
{ Direct linear solve for matrix A and Vectors B. On the first call for a
  given A, this LU-factorises A in place and solves for B via the combined
  LAPACKE_dgesv, caching the pivot indices on A and setting A.LU := True.
  A subsequent call against the same (already-factorised) A skips
  re-factorisation and reuses the cached LU factors/pivots via the cheaper
  LAPACKE_dgetrs (solve only) - much less work when the same A is solved
  against several different B's in turn. On return, A holds its LU-factored
  form (not the original matrix) and the solution is in B. Returns info
  from the underlying LAPACKE call. }
{$IFDEF PUREPASCAL}
  {$IFDEF HAVE_ACCELERATE}
{ Accelerate-backed: raw Fortran dgetrf_ (factorise) / dgetrs_ (solve, both
  fresh and cached-factorisation reuse) - no LAPACKE row-major wrapper
  exists (see cblas.pas). Two adaptations, both verified against known
  values (including a multi-RHS case) before wiring in:
    1. dgetrf_ factorises A's row-major buffer AS-IS, reinterpreted
       column-major - i.e. it factorises A^T, not A. A.fIpiv/A's buffer
       end up holding the LU of A^T, opaque to any caller outside this
       routine (LinearSolve is the only reader of either field).
    2. Solving A*x=b given the LU of A^T uses dgetrs_'s trans='T' mode
       (solves (A^T)^T*x = A*x = b). dgetrs_ needs B/X in column-major
       layout, so B is transposed into a scratch buffer before the call
       and the solution transposed back into B afterward - cheap even
       when unnecessary (NRHS=1, the overwhelmingly common case, where
       transposing a column vector is a no-op copy); NRHS>1 needs the
       copy for correctness, not just style, since a row-major NxNRHS
       buffer is genuinely not its own column-major reinterpretation
       once NRHS<>1. Mirrors LAPACKE_dgesv's own contract: if
       factorisation fails, B is left untouched and the failing info is
       returned without attempting to solve. }
var
  n, nrhs : integer;
  trans : char;
  bcol : array of double;
  r, c : integer;
begin
  assert(A.Cols = A.Rows,s+'Matrix A must be square');
  assert(A.Rows = B.Rows, s+'Matrix A and B have incompatible dimensions');
  n := A.rows;
  nrhs := B.cols;
  result := 0;
  if not A.LU then begin
    setlength(A.fIpiv,A.rows);
    accel_dgetrf_(@n, @n, A.DataPtr, @n, @A.fIpiv[0], @result);
    if result = 0 then A.fLUFactored := True;
  end;
  if result = 0 then begin
    setlength(bcol, n*nrhs);
    for r := 0 to n-1 do
      for c := 0 to nrhs-1 do
        bcol[c*n+r] := B.FData[r*nrhs+c];
    trans := 'T';
    accel_dgetrs_(@trans, @n, @nrhs, A.DataPtr, @n, @A.fIpiv[0], @bcol[0], @n, @result);
    if result = 0 then
      for r := 0 to n-1 do
        for c := 0 to nrhs-1 do
          B.FData[r*nrhs+c] := bcol[c*n+r];
  end;
end;
  {$ELSE}
{ PUREPASCAL: PurePascalLU/PurePascalLUSolve (see above) fill the same two
  roles as LAPACKE_dgesv (factorise+solve) and LAPACKE_dgetrs (solve only,
  reusing a cached factorisation) respectively - same caching contract via
  A.fIpiv/A.fLUFactored. Always returns 0 (this fallback has no illegal-
  argument path LAPACKE could report; a singular A instead surfaces as a
  division by zero on the affected element during back-substitution). }
begin
  assert(A.Cols = A.Rows,s+'Matrix A must be square');
  assert(A.Rows = B.Rows, s+'Matrix A and B have incompatible dimensions');
  if not A.LU then begin
    setlength(A.fIpiv,A.rows);
    PurePascalLU(A.DataPtr, A.rows, A.fIpiv);
    A.fLUFactored := True;
  end;
  PurePascalLUSolve(A.DataPtr, A.rows, A.fIpiv, B.DataPtr, B.cols);
  result := 0;
end;
  {$ENDIF}
{$ELSE}
begin
  //Check dimensions of matrices are compatible. A must be square and A.cols =
  // B.rows
  assert(A.Cols = A.Rows,s+'Matrix A must be square');
  assert(A.Rows = B.Rows, s+'Matrix A and B have incompatible dimensions');
  if A.LU then
    result := lapacke_dgetrs(CBlasRowMajor,'N',A.rows,B.cols,@A.Fdata[0],A.cols,@A.fIpiv[0],@B.FData[0],B.cols)
  else begin
    setlength(A.fIpiv,A.rows);
    result := lapacke_dgesv(CBlasRowMajor,A.rows,B.cols,@A.Fdata[0],A.cols,@A.fIpiv[0],@B.FData[0],B.cols);
    if result = 0 then A.fLUFactored := True;
  end;
end;
{$ENDIF}

function CopyObj(const A: TVMObj): TVMobj;
begin
  result := TVMObj.Create(A.rows,A.cols);
{ A whole-buffer copy needs no strides at all (source and dest share the
  same shape), so - unlike SubMatrix below - this never genuinely needed
  LAPACKE_dlacpy's row-major-aware strided copy; a flat cblas_dcopy
  produces an identical result and only needs a BLAS backend, not real
  LAPACK, so this is gated on PUREPASCAL_BLAS rather than PUREPASCAL. }
{$IFDEF PUREPASCAL_BLAS}
  Move(A.fdata[0], result.fdata[0], A.rows*A.cols*SizeOf(Double));
{$ELSE}
  cblas_dcopy(A.rows*A.cols, A.DataPtr, 1, result.DataPtr, 1);
{$ENDIF}
end;

function Invert(const A: TVMobj): TVMobj;
const
  s : String = 'Function Invert : ';
var
  ipiv : array of integer;
  info : integer;
{ Matrix inverse via LAPACKE_dgetrf (LU factorisation) followed by
  LAPACKE_dgetri (inverse from the LU factors). Runs on a CopyObj scratch
  buffer, like EigDecompose, since both LAPACKE calls overwrite their
  input matrix in place - A itself is left untouched. }
{$IFDEF PUREPASCAL}
  {$IFDEF HAVE_ACCELERATE}
{ Accelerate-backed: raw Fortran dgetrf_/dgetri_ (see cblas.pas), since no
  LAPACKE row-major wrapper is available. Matrix inversion is
  transpose-symmetric ((A^T)^-1 = (A^-1)^T), so reinterpreting A's
  row-major buffer as column-major (=A^T) and running the column-major
  factor+invert directly on it - no transposing needed at all - leaves
  the buffer holding, when read back as row-major, exactly inv(A).
  Confirmed against known values before wiring this in. dgetri_ needs an
  explicit work buffer (LAPACKE handled this internally) - queried via
  the standard LWORK=-1 workspace-size probe, then allocated. }
var
  n, lwork : integer;
  work : array of double;
  workquery : array[0..0] of double;
begin
  assert(A.Cols = A.Rows, s+'Matrix A must be square');
  result := CopyObj(A);
  setlength(ipiv, A.rows);
  n := A.rows;
  accel_dgetrf_(@n, @n, result.DataPtr, @n, @ipiv[0], @info);
  assert(info = 0, s+'dgetrf_ failed (singular matrix?), info='+IntToStr(info));
  lwork := -1;
  accel_dgetri_(@n, result.DataPtr, @n, @ipiv[0], @workquery[0], @lwork, @info);
  lwork := Trunc(workquery[0]);
  if lwork < 1 then lwork := 1;
  setlength(work, lwork);
  accel_dgetri_(@n, result.DataPtr, @n, @ipiv[0], @work[0], @lwork, @info);
  assert(info = 0, s+'dgetri_ failed (singular matrix?), info='+IntToStr(info));
end;
  {$ELSE}
{ PUREPASCAL: PurePascalLU factorises a CopyObj scratch buffer (same
  non-mutating convention), then the inverse is obtained by solving
  A*X=I via PurePascalLUSolve against an identity right-hand side - a
  standard, if less efficient than LAPACKE_dgetri's dedicated algorithm,
  way to invert from an existing LU factorisation. }
var
  identity : TVMobj;
  k : Integer;
begin
  assert(A.Cols = A.Rows, s+'Matrix A must be square');
  result := CopyObj(A);
  setlength(ipiv, A.rows);
  info := PurePascalLU(result.DataPtr, A.rows, ipiv);
  assert(info = 0, s+'matrix is singular, first zero pivot at row='+IntToStr(info));
  identity := TVMobj.Create(A.rows, A.rows);
  for k := 0 to A.rows-1 do identity[k,k] := 1;
  PurePascalLUSolve(result.DataPtr, A.rows, ipiv, identity.DataPtr, A.rows);
  result := identity;
end;
  {$ENDIF}
{$ELSE}
begin
  assert(A.Cols = A.Rows, s+'Matrix A must be square');
  result := CopyObj(A);
  setlength(ipiv, A.rows);
  info := lapacke_dgetrf(CBlasRowMajor, A.rows, A.cols, result.DataPtr, A.cols, @ipiv[0]);
  assert(info = 0, s+'LAPACKE_dgetrf failed (singular matrix?), info='+IntToStr(info));
  info := lapacke_dgetri(CBlasRowMajor, A.rows, result.DataPtr, A.cols, @ipiv[0]);
  assert(info = 0, s+'LAPACKE_dgetri failed (singular matrix?), info='+IntToStr(info));
end;
{$ENDIF}

function Find(const A: TVMobj; Op: TVMCompareOp; Value: Double): TVMobjI;
var
  i, j : integer;
  matched : Boolean;
begin
  result := TVMobjI.Create(A.Rows, A.Cols);
  for i := 0 to A.Rows-1 do
    for j := 0 to A.Cols-1 do begin
      case Op of
        cmpEQ: matched := A[i,j] = Value;
        cmpLT: matched := A[i,j] < Value;
        cmpLE: matched := A[i,j] <= Value;
        cmpGT: matched := A[i,j] > Value;
        cmpGE: matched := A[i,j] >= Value;
      else
        matched := False;
      end;
      if matched then result[i,j] := 1 else result[i,j] := 0;
    end;
end;

function Kron(const A, B: TVMobj): TVMobj;
var
  i, j, k, rowdest, coldest : integer;
{$IFDEF PUREPASCAL_BLAS}
var
  l : integer;
begin
  result := TVMobj.Create(A.Rows*B.Rows, A.Cols*B.Cols);
  for i := 0 to A.Rows-1 do
    for j := 0 to A.Cols-1 do
      for k := 0 to B.Rows-1 do begin
        rowdest := i*B.Rows + k;
        coldest := j*B.Cols;
        for l := 0 to B.Cols-1 do
          result.fdata[calcoffset(rowdest,coldest+l,result.Cols)] := A[i,j]*B.fdata[calcoffset(k,l,B.Cols)];
      end;
end;
{$ELSE}
begin
  result := TVMobj.Create(A.Rows*B.Rows, A.Cols*B.Cols);
  for i := 0 to A.Rows-1 do
    for j := 0 to A.Cols-1 do
      for k := 0 to B.Rows-1 do begin
        rowdest := i*B.Rows + k;
        coldest := j*B.Cols;
        cblas_daxpy(B.Cols, A[i,j], @B.FData[k*B.Cols], 1, @result.FData[rowdest*result.Cols + coldest], 1);
      end;
end;
{$ENDIF}

function Diag(const A: TVMobj): TVMobj;
const
  s : String = 'Function Diag : ';
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
begin
  assert(A.Cols = 1, s+'A must be a column vector (n,1)');
  result := TVMobj.Create(A.Rows, A.Rows);
  for i := 0 to A.Rows-1 do
    result.fdata[calcoffset(i,i,A.Rows)] := A.fdata[i];
end;
{$ELSE}
begin
  assert(A.Cols = 1, s+'A must be a column vector (n,1)');
  result := TVMobj.Create(A.Rows, A.Rows);
  cblas_dcopy(A.Rows, A.DataPtr, 1, result.DataPtr, A.Rows+1);
end;
{$ENDIF}

function Norm(const A: TVMobj): Double;
const
  s : String = 'Function Norm : ';
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
  sumsq : Double;
begin
  assert((A.Rows=1) or (A.Cols=1), s+'A must be a vector (Rows=1 or Cols=1)');
  sumsq := 0;
  for i := 0 to A.Rows*A.Cols-1 do
    sumsq := sumsq + A.fdata[i]*A.fdata[i];
  result := Sqrt(sumsq);
end;
{$ELSE}
begin
  assert((A.Rows=1) or (A.Cols=1), s+'A must be a vector (Rows=1 or Cols=1)');
  result := cblas_dnrm2(A.Rows*A.Cols, A.DataPtr, 1);
end;
{$ENDIF}

function Trace(const A: TVMobj): Double;
const
  s : String = 'Function Trace : ';
var
  i : integer;
begin
  assert(A.Rows = A.Cols, s+'Matrix A must be square');
  result := 0;
  for i := 0 to A.Rows-1 do
    result := result + A[i,i];
end;

function Det(const A: TVMobj): Double;
const
  s : String = 'Function Det : ';
var
  ipiv : array of integer;
  info, i, sign : integer;
  scratch : TVMobj;
{$IFDEF PUREPASCAL}
  {$IFDEF HAVE_ACCELERATE}
var
  n : integer;
  {$ENDIF}
{$ENDIF}
begin
  assert(A.Cols = A.Rows, s+'Matrix A must be square');
  scratch := CopyObj(A);
  setlength(ipiv, A.rows);
{$IFDEF PUREPASCAL}
  {$IFDEF HAVE_ACCELERATE}
  { Accelerate has no LAPACKE_dgetrf (row-major C wrapper), only the
    classic Fortran dgetrf_ (column-major) - see cblas.pas. Determinant
    is invariant under transposition (det(A)=det(A^T)), and reinterpreting
    A's row-major buffer as column-major represents exactly A^T, so
    calling dgetrf_ directly on it - no transposing needed - factors A^T,
    and the existing sign/diagonal-product logic below already computes
    det(A^T) = det(A) unchanged. Confirmed against known values before
    wiring this in. }
  n := A.rows;
  accel_dgetrf_(@n, @n, scratch.DataPtr, @n, @ipiv[0], @info);
  {$ELSE}
  info := PurePascalLU(scratch.DataPtr, A.rows, ipiv);
  {$ENDIF}
{$ELSE}
  info := lapacke_dgetrf(CBlasRowMajor, A.rows, A.cols, scratch.DataPtr, A.cols, @ipiv[0]);
  assert(info >= 0, s+'LAPACKE_dgetrf reported an illegal argument, info='+IntToStr(info));
{$ENDIF}
  sign := 1;
  for i := 0 to A.rows-1 do
    if ipiv[i] <> i+1 then sign := -sign;
  result := sign;
  for i := 0 to A.rows-1 do
    result := result * scratch[i,i];
end;

function FlipUD(const A: TVMobj): TVMobj;
var
  i : integer;
begin
  result := TVMobj.Create(A.Rows, A.Cols);
{$IFDEF PUREPASCAL_BLAS}
  for i := 0 to A.Rows-1 do
    Move(A.FData[i*A.Cols], result.FData[(A.Rows-1-i)*A.Cols], A.Cols*SizeOf(Double));
{$ELSE}
  for i := 0 to A.Rows-1 do
    cblas_dcopy(A.Cols, @A.FData[i*A.Cols], 1, @result.FData[(A.Rows-1-i)*A.Cols], 1);
{$ENDIF}
end;

function FlipLR(const A: TVMobj): TVMobj;
var
  i : integer;
{$IFDEF PUREPASCAL}
  {$IFDEF HAVE_ACCELERATE}
{ vDSP_vrvrsD reverses in place (a single array, no separate src/dst
  pointers the way ippsFlip_64f has) - so each row is copied into result
  first, then reversed there directly. }
begin
  result := TVMobj.Create(A.Rows, A.Cols);
  for i := 0 to A.Rows-1 do begin
    Move(A.FData[i*A.Cols], result.FData[i*A.Cols], A.Cols*SizeOf(Double));
    accel_vDSP_vrvrsD(@result.FData[i*A.Cols], 1, A.Cols);
  end;
end;
  {$ELSE}
var
  j : integer;
begin
  result := TVMobj.Create(A.Rows, A.Cols);
  for i := 0 to A.Rows-1 do
    for j := 0 to A.Cols-1 do
      result.FData[i*A.Cols+j] := A.FData[i*A.Cols + (A.Cols-1-j)];
end;
  {$ENDIF}
{$ELSE}
begin
  result := TVMobj.Create(A.Rows, A.Cols);
  for i := 0 to A.Rows-1 do
    ippsFlip_64f(@A.FData[i*A.Cols], @result.FData[i*A.Cols], A.Cols);
end;
{$ENDIF}

function MergeUD(const A, B: TVMobj): TVMobj;
const
  s : String = 'Function MergeUD : ';
begin
  assert(A.Cols = B.Cols, s+'A and B must have the same number of columns');
  result := TVMobj.Create(A.Rows+B.Rows, A.Cols);
{$IFDEF PUREPASCAL_BLAS}
  Move(A.FData[0], result.FData[0], A.Rows*A.Cols*SizeOf(Double));
  Move(B.FData[0], result.FData[A.Rows*A.Cols], B.Rows*B.Cols*SizeOf(Double));
{$ELSE}
  cblas_dcopy(A.Rows*A.Cols, A.DataPtr, 1, result.DataPtr, 1);
  cblas_dcopy(B.Rows*B.Cols, B.DataPtr, 1, @result.FData[A.Rows*A.Cols], 1);
{$ENDIF}
end;

function MergeLR(const A, B: TVMobj): TVMobj;
const
  s : String = 'Function MergeLR : ';
var
  i : integer;
begin
  assert(A.Rows = B.Rows, s+'A and B must have the same number of rows');
  result := TVMobj.Create(A.Rows, A.Cols+B.Cols);
  for i := 0 to A.Rows-1 do begin
{$IFDEF PUREPASCAL_BLAS}
    Move(A.FData[i*A.Cols], result.FData[i*result.Cols], A.Cols*SizeOf(Double));
    Move(B.FData[i*B.Cols], result.FData[i*result.Cols + A.Cols], B.Cols*SizeOf(Double));
{$ELSE}
    cblas_dcopy(A.Cols, @A.FData[i*A.Cols], 1, @result.FData[i*result.Cols], 1);
    cblas_dcopy(B.Cols, @B.FData[i*B.Cols], 1, @result.FData[i*result.Cols + A.Cols], 1);
{$ENDIF}
  end;
end;

function Reshape(const A: TVMobj; NewRows, NewCols: TDim): TVMobj;
const
  s : String = 'Function Reshape : ';
begin
  assert(NewRows*NewCols = A.Rows*A.Cols, s+'NewRows*NewCols must equal A.Rows*A.Cols');
  result := TVMobj.Create(NewRows, NewCols);
{$IFDEF PUREPASCAL_BLAS}
  Move(A.FData[0], result.FData[0], A.Rows*A.Cols*SizeOf(Double));
{$ELSE}
  cblas_dcopy(A.Rows*A.Cols, A.DataPtr, 1, result.DataPtr, 1);
{$ENDIF}
end;

function Repmat(const A: TVMobj; RowReps, ColReps: Integer): TVMobj;
const
  s : String = 'Function Repmat : ';
var
  i, j, r, destRow : integer;
begin
  assert((RowReps > 0) and (ColReps > 0), s+'RowReps and ColReps must be > 0');
  result := TVMobj.Create(A.Rows*RowReps, A.Cols*ColReps);
  for i := 0 to RowReps-1 do
    for r := 0 to A.Rows-1 do begin
      destRow := i*A.Rows + r;
      for j := 0 to ColReps-1 do
{$IFDEF PUREPASCAL_BLAS}
        Move(A.FData[r*A.Cols], result.FData[destRow*result.Cols + j*A.Cols], A.Cols*SizeOf(Double));
{$ELSE}
        cblas_dcopy(A.Cols, @A.FData[r*A.Cols], 1, @result.FData[destRow*result.Cols + j*A.Cols], 1);
{$ENDIF}
    end;
end;

function AddScalar(const A: TVMobj; K: Double): TVMobj;
{$IFDEF PUREPASCAL}
  {$IFNDEF HAVE_ACCELERATE}
var
  i : Integer;
  {$ENDIF}
{$ENDIF}
begin
  result := CopyObj(A);
{$IFDEF PUREPASCAL}
  {$IFDEF HAVE_ACCELERATE}
  accel_vDSP_vsaddD(A.DataPtr, 1, @K, result.DataPtr, 1, A.Rows*A.Cols);
  {$ELSE}
  for i := 0 to A.Rows*A.Cols-1 do
    result.fdata[i] := result.fdata[i] + K;
  {$ENDIF}
{$ELSE}
  ippsAddC_64f_I(K, result.DataPtr, A.Rows*A.Cols);
{$ENDIF}
end;

function SubMatrix(const A: TVMobj; R0, C0, RCount, CCount: TDim): TVMobj;
const
  s : String = 'Function SubMatrix : ';
var
  i : Integer;
{ A sub-rectangle's rows aren't contiguous in either buffer (source
  stride A.Cols, dest stride CCount) - a genuinely strided copy, unlike
  CopyObj's whole-buffer case above - but the strided copy itself only
  ever needed a per-row cblas_dcopy loop (the same "no block primitive ->
  loop of per-row BLAS calls" idiom Kron/FlipUD/MergeLR/Repmat already
  use), not LAPACKE_dlacpy's dedicated routine, so this is gated on
  PUREPASCAL_BLAS rather than PUREPASCAL too. }
begin
  assert((R0+RCount <= A.Rows) and (C0+CCount <= A.Cols), s+'submatrix (R0,C0,RCount,CCount) extends beyond A''s bounds');
  result := TVMobj.Create(RCount, CCount);
{$IFDEF PUREPASCAL_BLAS}
  for i := 0 to RCount-1 do
    Move(A.FData[(R0+i)*A.Cols+C0], result.FData[i*CCount], CCount*SizeOf(Double));
{$ELSE}
  for i := 0 to RCount-1 do
    cblas_dcopy(CCount, @A.FData[(R0+i)*A.Cols+C0], 1, @result.FData[i*CCount], 1);
{$ENDIF}
end;

class operator TVMobj.+(const A, B: TVMobj): TVMobj;
const
  s : String = 'Operator + (TVMobj) : ';
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
{$ENDIF}
begin
  assert((A.Rows=B.Rows) and (A.Cols=B.Cols), s+'matrix dimensions must match');
  result := CopyObj(B);
{$IFDEF PUREPASCAL_BLAS}
  for i := 0 to A.Rows*A.Cols-1 do
    result.fdata[i] := result.fdata[i] + A.fdata[i];
{$ELSE}
  cblas_daxpy(A.Rows*A.Cols, 1, A.DataPtr, 1, result.DataPtr, 1);
{$ENDIF}
end;

class operator TVMobj.-(const A, B: TVMobj): TVMobj;
const
  s : String = 'Operator - (TVMobj) : ';
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
{$ENDIF}
begin
  assert((A.Rows=B.Rows) and (A.Cols=B.Cols), s+'matrix dimensions must match');
  result := CopyObj(A);
{$IFDEF PUREPASCAL_BLAS}
  for i := 0 to A.Rows*A.Cols-1 do
    result.fdata[i] := result.fdata[i] - B.fdata[i];
{$ELSE}
  cblas_daxpy(A.Rows*A.Cols, -1, B.DataPtr, 1, result.DataPtr, 1);
{$ENDIF}
end;

class operator TVMobj.-(const A: TVMobj): TVMobj;
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
{$ENDIF}
begin
  result := CopyObj(A);
{$IFDEF PUREPASCAL_BLAS}
  for i := 0 to A.Rows*A.Cols-1 do
    result.fdata[i] := -result.fdata[i];
{$ELSE}
  cblas_dscal(A.Rows*A.Cols, -1, result.DataPtr, 1);
{$ENDIF}
end;

class operator TVMobj.*(const A, B: TVMobj): TVMobj;
begin
  result := MulObj(A, B);
end;

class operator TVMobj.*(const A: TVMobj; const k: Double): TVMobj;
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
{$ENDIF}
begin
  result := CopyObj(A);
{$IFDEF PUREPASCAL_BLAS}
  for i := 0 to A.Rows*A.Cols-1 do
    result.fdata[i] := result.fdata[i] * k;
{$ELSE}
  cblas_dscal(A.Rows*A.Cols, k, result.DataPtr, 1);
{$ENDIF}
end;

class operator TVMobj.*(const k: Double; const A: TVMobj): TVMobj;
begin
  result := A * k;
end;

class operator TVMobj./(const A: TVMobj; const k: Double): TVMobj;
const
  s : String = 'Operator / (TVMobj) : ';
{$IFDEF PUREPASCAL}
  {$IFNDEF HAVE_ACCELERATE}
var
  i : Integer;
  {$ENDIF}
{$ENDIF}
begin
  assert(k<>0, s+'division by zero');
  result := CopyObj(A);
{$IFDEF PUREPASCAL}
  {$IFDEF HAVE_ACCELERATE}
  accel_vDSP_vsdivD(A.DataPtr, 1, @k, result.DataPtr, 1, A.Rows*A.Cols);
  {$ELSE}
  for i := 0 to A.Rows*A.Cols-1 do
    result.fdata[i] := result.fdata[i] / k;
  {$ENDIF}
{$ELSE}
  ippsDivC_64f_I(k, result.DataPtr, A.Rows*A.Cols);
{$ENDIF}
end;

class operator TVMobj.=(const A, B: TVMobj): Boolean;
begin
  Result := (A.Rows = B.Rows) and (A.Cols = B.Cols) and
            CompareMem(A.DataPtr, B.DataPtr, A.Rows*A.Cols*SizeOf(Double));
end;

function Sin(const A: TVMobj): TVMobj;
{$IFDEF PUREPASCAL}
  {$IFDEF HAVE_ACCELERATE}
var
  n : integer;
begin
  result := TVMobj.Create(A.Rows, A.Cols);
  n := A.Rows*A.Cols;
  accel_vvsin(result.DataPtr, A.DataPtr, @n);
end;
  {$ELSE}
var
  i : Integer;
begin
  result := TVMobj.Create(A.Rows, A.Cols);
  for i := 0 to A.Rows*A.Cols-1 do result.fdata[i] := System.Sin(A.fdata[i]);
end;
  {$ENDIF}
{$ELSE}
begin
  result := TVMobj.Create(A.Rows, A.Cols);
  vdSin(A.Rows*A.Cols, A.DataPtr, result.DataPtr);
end;
{$ENDIF}

function Cos(const A: TVMobj): TVMobj;
{$IFDEF PUREPASCAL}
  {$IFDEF HAVE_ACCELERATE}
var
  n : integer;
begin
  result := TVMobj.Create(A.Rows, A.Cols);
  n := A.Rows*A.Cols;
  accel_vvcos(result.DataPtr, A.DataPtr, @n);
end;
  {$ELSE}
var
  i : Integer;
begin
  result := TVMobj.Create(A.Rows, A.Cols);
  for i := 0 to A.Rows*A.Cols-1 do result.fdata[i] := System.Cos(A.fdata[i]);
end;
  {$ENDIF}
{$ELSE}
begin
  result := TVMobj.Create(A.Rows, A.Cols);
  vdCos(A.Rows*A.Cols, A.DataPtr, result.DataPtr);
end;
{$ENDIF}

function Tan(const A: TVMobj): TVMobj;
{$IFDEF PUREPASCAL}
  {$IFDEF HAVE_ACCELERATE}
var
  n : integer;
begin
  result := TVMobj.Create(A.Rows, A.Cols);
  n := A.Rows*A.Cols;
  accel_vvtan(result.DataPtr, A.DataPtr, @n);
end;
  {$ELSE}
var
  i : Integer;
begin
  result := TVMobj.Create(A.Rows, A.Cols);
  for i := 0 to A.Rows*A.Cols-1 do result.fdata[i] := Math.Tan(A.fdata[i]);
end;
  {$ENDIF}
{$ELSE}
begin
  result := TVMobj.Create(A.Rows, A.Cols);
  vdTan(A.Rows*A.Cols, A.DataPtr, result.DataPtr);
end;
{$ENDIF}

function Sinh(const A: TVMobj): TVMobj;
{$IFDEF PUREPASCAL}
  {$IFDEF HAVE_ACCELERATE}
var
  n : integer;
begin
  result := TVMobj.Create(A.Rows, A.Cols);
  n := A.Rows*A.Cols;
  accel_vvsinh(result.DataPtr, A.DataPtr, @n);
end;
  {$ELSE}
var
  i : Integer;
begin
  result := TVMobj.Create(A.Rows, A.Cols);
  for i := 0 to A.Rows*A.Cols-1 do result.fdata[i] := Math.Sinh(A.fdata[i]);
end;
  {$ENDIF}
{$ELSE}
begin
  result := TVMobj.Create(A.Rows, A.Cols);
  vdSinh(A.Rows*A.Cols, A.DataPtr, result.DataPtr);
end;
{$ENDIF}

function Sqr(const A: TVMobj): TVMobj;
{$IFDEF PUREPASCAL}
  {$IFDEF HAVE_ACCELERATE}
begin
  result := TVMobj.Create(A.Rows, A.Cols);
  accel_vDSP_vsqD(A.DataPtr, 1, result.DataPtr, 1, A.Rows*A.Cols);
end;
  {$ELSE}
var
  i : Integer;
begin
  result := TVMobj.Create(A.Rows, A.Cols);
  for i := 0 to A.Rows*A.Cols-1 do result.fdata[i] := System.Sqr(A.fdata[i]);
end;
  {$ENDIF}
{$ELSE}
begin
  result := TVMobj.Create(A.Rows, A.Cols);
  vdSqr(A.Rows*A.Cols, A.DataPtr, result.DataPtr);
end;
{$ENDIF}

function Sqrt(const A: TVMobj): TVMobj;
{$IFDEF PUREPASCAL}
  {$IFDEF HAVE_ACCELERATE}
var
  n : integer;
begin
  result := TVMobj.Create(A.Rows, A.Cols);
  n := A.Rows*A.Cols;
  accel_vvsqrt(result.DataPtr, A.DataPtr, @n);
end;
  {$ELSE}
var
  i : Integer;
begin
  result := TVMobj.Create(A.Rows, A.Cols);
  for i := 0 to A.Rows*A.Cols-1 do result.fdata[i] := System.Sqrt(A.fdata[i]);
end;
  {$ENDIF}
{$ELSE}
begin
  result := TVMobj.Create(A.Rows, A.Cols);
  vdSqrt(A.Rows*A.Cols, A.DataPtr, result.DataPtr);
end;
{$ENDIF}

function Exp(const A: TVMobj): TVMobj;
{$IFDEF PUREPASCAL}
  {$IFDEF HAVE_ACCELERATE}
var
  n : integer;
begin
  result := TVMobj.Create(A.Rows, A.Cols);
  n := A.Rows*A.Cols;
  accel_vvexp(result.DataPtr, A.DataPtr, @n);
end;
  {$ELSE}
var
  i : Integer;
begin
  result := TVMobj.Create(A.Rows, A.Cols);
  for i := 0 to A.Rows*A.Cols-1 do result.fdata[i] := System.Exp(A.fdata[i]);
end;
  {$ENDIF}
{$ELSE}
begin
  result := TVMobj.Create(A.Rows, A.Cols);
  vdExp(A.Rows*A.Cols, A.DataPtr, result.DataPtr);
end;
{$ENDIF}

function Ln(const A: TVMobj): TVMobj;
{$IFDEF PUREPASCAL}
  {$IFDEF HAVE_ACCELERATE}
var
  n : integer;
begin
  result := TVMobj.Create(A.Rows, A.Cols);
  n := A.Rows*A.Cols;
  accel_vvlog(result.DataPtr, A.DataPtr, @n);
end;
  {$ELSE}
var
  i : Integer;
begin
  result := TVMobj.Create(A.Rows, A.Cols);
  for i := 0 to A.Rows*A.Cols-1 do result.fdata[i] := System.Ln(A.fdata[i]);
end;
  {$ENDIF}
{$ELSE}
begin
  result := TVMobj.Create(A.Rows, A.Cols);
  vdLn(A.Rows*A.Cols, A.DataPtr, result.DataPtr);
end;
{$ENDIF}

function mulObj(const A, B: TVMObj): TVMObj;
const
  s: string ='Routine mulObj : ';
{$IFDEF PUREPASCAL}
  {$IFDEF HAVE_ACCELERATE}
begin
  assert((a.rows=b.rows)and(a.cols=b.cols),s+'Dimensions of A and B must be the same');
  result := TVMobj.Create(A.Rows, A.Cols);
  accel_vDSP_vmulD(A.DataPtr, 1, B.DataPtr, 1, result.DataPtr, 1, A.Rows*A.Cols);
end;
  {$ELSE}
var
  i : Integer;
begin
  assert((a.rows=b.rows)and(a.cols=b.cols),s+'Dimensions of A and B must be the same');
  result := CopyObj(A);
  for i := 0 to A.rows*A.cols-1 do
    result.fdata[i] := result.fdata[i] * B.fdata[i];
end;
  {$ENDIF}
{$ELSE}
begin
  assert((a.rows=b.rows)and(a.cols=b.cols),s+'Dimensions of A and B must be the same');
  result := CopyObj(A);
  vdMul(A.rows*A.cols,A.Dataptr,B.DataPtr,Result.DataPtr);

end;
{$ENDIF}

{$IFNDEF HAVE_FFTW}
// Direct O(N^2) trigonometric-sum evaluation of each of the 8 FFTW r2r
// kinds, as the fallback when FFTW isn't loaded - matching FFTW's own
// unnormalized formulas exactly (see "1D Real-even/odd DFTs (cosine/sine
// transforms)" in the FFTW manual), not a ported fast transform: DCT/DST
// have no simple radix-2-style fast algorithm as short as a direct FFT's,
// and this is a fallback path where O(N^2) simplicity/correctness matters
// more than speed - same rationale as newVMComplex.pas's PPDirectDFT.
// Verified against the library-backed path's own exact scale-factor
// contracts (e.g. DCT1(DCT1(x)) = x*2*(N-1)) via newVMTests.pas's existing
// round-trip tests, run with PUREPASCAL/HAVE_FFTW both forced off.
function PPDSgnPow(V: Double; K: Integer): Double; inline;
begin
  if Odd(K) then result := -V else result := V;
end;

procedure PPr2rTransform(N: Integer; InData, OutData: PDouble; kind: TFFTW_r2r_kind);
var
  j, k : Integer;
  acc : Double;
begin
  case kind of
    FFTW_REDFT00: //DCT-I: logical size 2*(N-1)
      for k := 0 to N-1 do begin
        acc := InData[0] + PPDSgnPow(InData[N-1], k);
        for j := 1 to N-2 do
          acc := acc + 2*InData[j]*cos(Pi*j*k/(N-1));
        OutData[k] := acc;
      end;
    FFTW_REDFT10: //DCT-II
      for k := 0 to N-1 do begin
        acc := 0;
        for j := 0 to N-1 do
          acc := acc + InData[j]*cos(Pi*(j+0.5)*k/N);
        OutData[k] := 2*acc;
      end;
    FFTW_REDFT01: //DCT-III
      for k := 0 to N-1 do begin
        acc := InData[0];
        for j := 1 to N-1 do
          acc := acc + 2*InData[j]*cos(Pi*j*(k+0.5)/N);
        OutData[k] := acc;
      end;
    FFTW_REDFT11: //DCT-IV
      for k := 0 to N-1 do begin
        acc := 0;
        for j := 0 to N-1 do
          acc := acc + InData[j]*cos(Pi*(j+0.5)*(k+0.5)/N);
        OutData[k] := 2*acc;
      end;
    FFTW_RODFT00: //DST-I: logical size 2*(N+1)
      for k := 0 to N-1 do begin
        acc := 0;
        for j := 0 to N-1 do
          acc := acc + InData[j]*sin(Pi*(j+1)*(k+1)/(N+1));
        OutData[k] := 2*acc;
      end;
    FFTW_RODFT10: //DST-II
      for k := 0 to N-1 do begin
        acc := 0;
        for j := 0 to N-1 do
          acc := acc + InData[j]*sin(Pi*(j+0.5)*(k+1)/N);
        OutData[k] := 2*acc;
      end;
    FFTW_RODFT01: //DST-III
      for k := 0 to N-1 do begin
        acc := PPDSgnPow(InData[N-1], k);
        for j := 0 to N-2 do
          acc := acc + 2*InData[j]*sin(Pi*(j+1)*(k+0.5)/N);
        OutData[k] := acc;
      end;
    FFTW_RODFT11: //DST-IV
      for k := 0 to N-1 do begin
        acc := 0;
        for j := 0 to N-1 do
          acc := acc + InData[j]*sin(Pi*(j+0.5)*(k+0.5)/N);
        OutData[k] := 2*acc;
      end;
  end;
end;
{$ENDIF}

function r2rTransform(const A: TVMobj; kind: TFFTW_r2r_kind): TVMobj;
const
  s : String = 'Routine r2rTransform : ';
var
  n : integer;
{$IFDEF HAVE_FFTW}
  plan : fftw_plan;
{$ENDIF}
begin
  assert((A.Rows=1) or (A.Cols=1), s+'A must be a vector (Rows=1 or Cols=1)');
  n := A.Rows*A.Cols;
  result := TVMobj.Create(A.Rows, A.Cols);
{$IFDEF HAVE_FFTW}
  assert(Assigned(fftw_plan_r2r_1d), s+'FFTW3 (double) library not loaded');
  plan := fftw_plan_r2r_1d(n, A.DataPtr, result.DataPtr, kind, FFTW_ESTIMATE or FFTW_PRESERVE_INPUT);
  assert(plan<>nil, s+'fftw_plan_r2r_1d failed');
  fftw_execute_r2r(plan, A.DataPtr, result.DataPtr);
  fftw_destroy_plan(plan);
{$ELSE}
  PPr2rTransform(n, A.DataPtr, result.DataPtr, kind);
{$ENDIF}
end;

function DCT1(const A: TVMobj): TVMobj;
begin
  result := r2rTransform(A, FFTW_REDFT00);
end;

function DCT2(const A: TVMobj): TVMobj;
begin
  result := r2rTransform(A, FFTW_REDFT10);
end;

function DCT3(const A: TVMobj): TVMobj;
begin
  result := r2rTransform(A, FFTW_REDFT01);
end;

function DCT4(const A: TVMobj): TVMobj;
begin
  result := r2rTransform(A, FFTW_REDFT11);
end;

function DST1(const A: TVMobj): TVMobj;
begin
  result := r2rTransform(A, FFTW_RODFT00);
end;

function DST2(const A: TVMobj): TVMobj;
begin
  result := r2rTransform(A, FFTW_RODFT10);
end;

function DST3(const A: TVMobj): TVMobj;
begin
  result := r2rTransform(A, FFTW_RODFT01);
end;

function DST4(const A: TVMobj): TVMobj;
begin
  result := r2rTransform(A, FFTW_RODFT11);
end;

end.
