unit newVMSingle;

{*******************************************************************************

     Vector / Matrix objects leveraging intel mkl libraries (SINGLE PRECISION)

     Derived from newVM.pas (double precision original by Dr H. Dent,
     howard@hgrd.co.uk, 29 July 2026). Adapted for 32-bit float data using
     the MKL "S" (single-precision real) BLAS/LAPACK/VSL routines.

     Inspired by Dew MtxVec Library for fpc but does not distinguish
     between matrix and vector objects. Vectors are column dimension (*,1)
     or row dimension (1,*).

     NOTE: function names below (cblas_sgemm, lapacke_slaset, lapacke_sgesv,
     LAPACKE_slacpy, vsRngGaussian) are the standard MKL single-precision
     ("s") analogues of the "d" routines used in newVM.pas. Verify these
     are declared with matching names/signatures in your cblas / OneAPI
     Pascal bindings before compiling - if your bindings use different
     casing or parameter conventions, adjust the calls accordingly.

     OPERATOR OVERLOADS (algebraic expressions on TVMobjS) - the single-
     precision analogue of the ones added to newVM.pas: '+'/'-' element-
     wise via cblas_saxpy, unary '-' via cblas_sscal, '*' between two
     TVMobjS is ELEMENT-WISE multiplication (delegates to MulObjS, MKL
     VML's vsMul) - NOT matrix multiplication; use MatMultS explicitly for
     a real matrix product (same distinction as newVM.pas's '*' - see its
     header comment), and '*'/'/' against a Single scalar scale via
     cblas_sscal / IPP's ippsDivC_32f_I.

*******************************************************************************}

{$mode Delphi}{$H+}
{$Align 8}

{$I newVMConfig.inc}
// newVMConfig.inc (generated by ./newvmconfigure - see newVM.pas's own
// header comment for the full rationale) defines HAVE_MKL/HAVE_IPP/
// HAVE_OPENBLAS/HAVE_FFTW and, derived from those, PUREPASCAL - set
// whenever any of OpenBLAS/MKL/IPP is missing on the machine that ran the
// configure tool. When PUREPASCAL is set, every routine below that would
// otherwise call into cblas/OneAPI instead uses a plain-Pascal
// implementation of its own, individually guarded - the single-precision
// analogue of newVM.pas's own PUREPASCAL bodies (see that unit for the
// algorithms: LU decomposition with partial pivoting backs
// LinearSolveS/InvertS/DetS; everything else is a direct loop). FFTW-
// backed DCT/DST (r2rTransformS) have no such fallback, same as newVM.pas.
// (NOTE: '//' line comments throughout this block deliberately, not a
// '{ ... }' block - see newVM.pas's own copy of this note for why.)

{$IFDEF UNIX}
  {$IFDEF HAVE_MKL}
{$Linklib 'mkl_rt.so'}
{$Linklib 'pthread'}
{$Linklib 'm'}
{$Linklib 'dl'}
//mkl_rt.so dlopen's libmkl_core.so (and friends) at runtime, which
//expects libm/pthread/dl to already be loaded into the process's
//global symbol table - without this you get errors like:
//  symbol lookup error: .../libmkl_core.so: undefined symbol: log10
//Unix/ELF dynamic-linker quirk only - not needed for mkl_rt.dll on Windows.
  {$ENDIF}
{$ENDIF}

interface

uses
  Classes, SysUtils, cblas, math, TestRegistry, OneAPI, Types, fftw3, newVMI;

Const
  MaxDimS = 65536;    //maximum dimensions of any array

Type
  TDimS = 0..MaxDimS-1;
  TDataSizeS = 1..MaxDimS*MaxDimS;
  TVectorS = Array of Single;   //maximum dimensions of any array


type

  { TVMobjS }

  TVMobjS = record
    private
      fData : TVectorS;  //Holds data for object
      frows, fcols : TDimS;
      fIpiv : array of Integer;  //cached LU pivot indices from LinearSolveS, valid iff fLUFactored
      fLUFactored : Boolean;     //True once LinearSolveS has LU-factorised this object in place (see LinearSolveS)
      function getelement(r,c: TDimS): Single;
      procedure setelement(r,c: TDimS; AValue: Single);
    public
      constructor create(r,c :TDimS);Overload;
      Constructor create(r,c: TDimS; const Values : TVectorS); overload;
      function writeMatrix: TStringList;
      property Element[r,c:TDimS]:Single read getelement write setelement; default;
      procedure fillRandom;
      procedure Id;
      procedure linspace(Start, increment: Single);
      function Transpose: TVMObjS;
      function DataPtr: PSingle;                  //raw buffer, for MKL interop from other units
      property Rows: TDimS read frows;             //read-only dimension accessors
      property Cols: TDimS read fcols;
      property LU: Boolean read fLUFactored;  //True once LinearSolveS has cached an LU factorisation of this object

      { Operator overloads - see OPERATOR OVERLOADS note in the header above.
        Mode Delphi only supports operator overloading as "class operator"
        members of the record. }
      class operator +(const A, B: TVMobjS): TVMobjS;
      class operator -(const A, B: TVMobjS): TVMobjS;
      class operator -(const A: TVMobjS): TVMobjS;
      class operator *(const A, B: TVMobjS): TVMobjS;
      class operator *(const A: TVMobjS; const k: Single): TVMobjS;
      class operator *(const k: Single; const A: TVMobjS): TVMobjS;
      class operator /(const A: TVMobjS; const k: Single): TVMobjS;
      class operator =(const A, B: TVMobjS): Boolean;
  end;

function calcoffsetS(r,c,cols :TDimS):integer;inline;
function MatMultS( const A, B: TVMObjS): TVMobjS;
function LinearSolveS(var A, B: TVMObjS):integer;
function CopyObjS(Const A : TVMObjS):TVMobjS;
function InvertS(const A: TVMobjS): TVMobjS;  //matrix inverse, via LAPACKE_sgetrf+sgetri; leaves A untouched
{ Find - see newVM.pas's Find for the full description. Marked "overload"
  since newVM.pas declares the TVMobj analogue of the same name. }
function Find(const A: TVMobjS; Op: TVMCompareOp; Value: Single): TVMobjI; overload;
function KronS(const A, B: TVMobjS): TVMobjS;  //Kronecker product - see Kron in newVM.pas
function DiagS(const A: TVMobjS): TVMobjS;  //column vector (n,1) -> (n,n) diagonal matrix - see Diag in newVM.pas
function NormS(const A: TVMobjS): Single;  //Euclidean norm - see Norm in newVM.pas
function TraceS(const A: TVMobjS): Single;  //sum of A's leading-diagonal elements - see Trace in newVM.pas
function DetS(const A: TVMobjS): Single;  //determinant, via LAPACKE_sgetrf - see Det in newVM.pas
function FlipUDS(const A: TVMobjS): TVMobjS;  //reverses row order - see FlipUD in newVM.pas
function FlipLRS(const A: TVMobjS): TVMobjS;  //reverses each row's element order, via ippsFlip_32f - see FlipLR in newVM.pas
function MergeUDS(const A, B: TVMobjS): TVMobjS;  //stacks A above B - see MergeUD in newVM.pas
function MergeLRS(const A, B: TVMobjS): TVMobjS;  //places A left of B - see MergeLR in newVM.pas
function ReshapeS(const A: TVMobjS; NewRows, NewCols: TDimS): TVMobjS;  //reinterprets A's elements with new dims - see Reshape in newVM.pas
function RepmatS(const A: TVMobjS; RowReps, ColReps: Integer): TVMobjS;  //tiles A RowReps x ColReps - see Repmat in newVM.pas
function AddScalarS(const A: TVMobjS; K: Single): TVMobjS;  //adds K to every element, via ippsAddC_32f_I - see AddScalar in newVM.pas
function SubMatrixS(const A: TVMobjS; R0, C0, RCount, CCount: TDimS): TVMobjS;  //extracts a submatrix, via LAPACKE_slacpy - see SubMatrix in newVM.pas

{ Elementwise transcendental/algebraic functions, via MKL VML (vs* routines
  in OneAPI.pas). Each returns a new TVMobjS of the same dimensions as A,
  with the function applied to every element. Marked "overload" since
  Sin/Cos/Sqr/Sqrt/Exp/Ln also exist in System/Math for plain numeric
  types - without "overload" the TVMobjS versions here would hide those
  entirely within this unit, breaking any plain Sqrt(x: Single) call. }
function Sin(const A: TVMobjS): TVMobjS; overload;
function Cos(const A: TVMobjS): TVMobjS; overload;
function Tan(const A: TVMobjS): TVMobjS; overload;
function Sinh(const A: TVMobjS): TVMobjS; overload;
function Sqr(const A: TVMobjS): TVMobjS; overload;
function Sqrt(const A: TVMobjS): TVMobjS; overload;
function Exp(const A: TVMobjS): TVMobjS; overload;
function Ln(const A: TVMobjS): TVMobjS; overload;
function MulObjS(const A, B: TVMObjS): TVMObjS;

{ Real-to-real DCT/DST types I-IV, via FFTW3 (fftw3.pas) r2r transforms on
  the single-precision library - see the matching DCT1..DST4 comment in
  newVM.pas for the shape/mutation/normalization rules, which apply here
  identically. Marked "overload" because newVM.pas declares the TVMobj
  (double) analogues of these same names. }
function DCT1(const A: TVMobjS): TVMobjS; overload;  //FFTW_REDFT00
function DCT2(const A: TVMobjS): TVMobjS; overload;  //FFTW_REDFT10
function DCT3(const A: TVMobjS): TVMobjS; overload;  //FFTW_REDFT01 (inverse of DCT2, up to scale)
function DCT4(const A: TVMobjS): TVMobjS; overload;  //FFTW_REDFT11 (self-inverse, up to scale)
function DST1(const A: TVMobjS): TVMobjS; overload;  //FFTW_RODFT00
function DST2(const A: TVMobjS): TVMobjS; overload;  //FFTW_RODFT10
function DST3(const A: TVMobjS): TVMobjS; overload;  //FFTW_RODFT01 (inverse of DST2, up to scale)
function DST4(const A: TVMobjS): TVMobjS; overload;  //FFTW_RODFT11 (self-inverse, up to scale)

implementation

function calcoffsetS(r, c, cols: TDimS): integer;
begin
  result := r*cols+c;
end;

{$IFDEF PUREPASCAL}
{ PurePascalLUS/PurePascalLUSolveS - Single-precision analogues of
  newVM.pas's PurePascalLU/PurePascalLUSolve; see that unit for the full
  rationale (matching LAPACKE_sgetrf's storage/ipiv convention). }
function PurePascalLUS(Data: PSingle; N: Integer; var ipiv: array of Integer): Integer;
var
  i, j, k, p: Integer;
  maxval, absval, tmp: Single;
begin
  result := 0;
  for k := 0 to N-1 do begin
    p := k;
    maxval := Abs(Data[k*N+k]);
    for i := k+1 to N-1 do begin
      absval := Abs(Data[i*N+k]);
      if absval > maxval then begin
        maxval := absval;
        p := i;
      end;
    end;
    ipiv[k] := p+1;
    if p <> k then
      for j := 0 to N-1 do begin
        tmp := Data[k*N+j];
        Data[k*N+j] := Data[p*N+j];
        Data[p*N+j] := tmp;
      end;
    if Data[k*N+k] = 0 then begin
      if result = 0 then result := k+1;
      Continue;
    end;
    for i := k+1 to N-1 do begin
      Data[i*N+k] := Data[i*N+k] / Data[k*N+k];
      for j := k+1 to N-1 do
        Data[i*N+j] := Data[i*N+j] - Data[i*N+k]*Data[k*N+j];
    end;
  end;
end;

procedure PurePascalLUSolveS(LU: PSingle; N: Integer; const ipiv: array of Integer; B: PSingle; nrhs: Integer);
var
  i, j, r, p: Integer;
  sum, tmp: Single;
begin
  for i := 0 to N-1 do begin
    p := ipiv[i]-1;
    if p <> i then
      for j := 0 to nrhs-1 do begin
        tmp := B[i*nrhs+j];
        B[i*nrhs+j] := B[p*nrhs+j];
        B[p*nrhs+j] := tmp;
      end;
  end;
  for r := 0 to nrhs-1 do
    for i := 1 to N-1 do begin
      sum := 0;
      for j := 0 to i-1 do
        sum := sum + LU[i*N+j]*B[j*nrhs+r];
      B[i*nrhs+r] := B[i*nrhs+r] - sum;
    end;
  for r := 0 to nrhs-1 do
    for i := N-1 downto 0 do begin
      sum := 0;
      for j := i+1 to N-1 do
        sum := sum + LU[i*N+j]*B[j*nrhs+r];
      B[i*nrhs+r] := (B[i*nrhs+r] - sum) / LU[i*N+i];
    end;
end;
{$ENDIF}

{ TVMobjS }

function TVMobjS.getelement(r,c: TDimS): Single;
var
   Ix : Integer;
begin
   assert((r<rows) and (c<cols),'Dimensions don''t match in getelement');
   Ix := calcoffsetS(r,c,cols);
   assert(Ix<= high(fdata),'Index out of range in get element');
   result := fdata[Ix];
end;

procedure TVMobjS.setelement(r,c:TDimS; AValue: Single);
var
 Ix : Integer;
begin
   assert((r<rows) and (c<cols),'Dimensions don''t match in setelement');
   Ix := calcoffsetS(r,c,cols);
   assert(Ix <= high(fdata),'Index out of range in set element');
   fdata[Ix] := Avalue;
end;

constructor TVMobjS.create(r,c :TDimS);
var
  i,N : integer;
begin
  assert((r>0) and (c>0),'rows and columns must be > 0');
  frows := r;
  fcols := c;
  N := r*c;
  setLength(fData,N);
  for i := low(fdata) to high(fdata) do fdata[i] := 0;
  fLUFactored := False;
end;

constructor TVMobjS.create(r,c : TDimS; const Values: TVectorS);
begin
  assert((r>0) and (c>0),'rows and columns must be > 0');
  assert( (r*c) = high(values)+1,'Incompatible dimensions ');
  frows := r;
  fcols := c;
  fdata := copy(Values,0,high(values)+1);
  fLUFactored := False;
end;

function TVMobjS.writeMatrix: TStringList;
const
  fieldwidth = 10;
var
   i,j,k,l: integer;
   s,t : String;
begin
  result:= TStringList.create;
  for i:=0 to rows-1 do begin // row by row
    s := '    ['+chr(9);//+chr(9);
    for j:=0 to cols-1 do begin
      t :=floatToStrf(FData[i*cols+j],fffixed,10,3);
      s := s + t;
      l := length(t);    // pad t to get constant length
     if l < fieldwidth then
      for k := 1 to fieldwidth-l do s := s +' ';
    end;
    s := s {+chr(9)}+']';
    result.add(s);
  end;
end;

procedure TVMobjS.fillRandom;
//
// Single-precision Gaussian RNG. vsRngGaussian is the MKL VSL
// single-precision counterpart to vdRngGaussian used in newVM.pas.
//
{$IFDEF PUREPASCAL}
{ PUREPASCAL: see newVM.pas's fillRandom for the fixed-seed Box-Muller
  rationale - identical here, just Single-typed. }
var
  i, n : Integer;
  u1, u2 : Single;
begin
  RandSeed := 777;
  n := high(fdata)+1;
  i := 0;
  while i < n do begin
    repeat
      u1 := Random;
    until u1 > 0;
    u2 := Random;
    fdata[i] := Sqrt(-2*Ln(u1))*Cos(2*Pi*u2);
    Inc(i);
    if i < n then begin
      fdata[i] := Sqrt(-2*Ln(u1))*Sin(2*Pi*u2);
      Inc(i);
    end;
  end;
end;
{$ELSE}
const
  vslConst = 8388608;
  VSL_RNG_METHOD_GAUSSIAN_ICDF = 2;
var
  vsSTream : pointer;
begin
  vslNewStream(@vsStream,vslConst,777);
  vsRngGaussian(VSL_RNG_METHOD_GAUSSIAN_ICDF,vsStream,high(fdata)+1,@Fdata[0],0,1);
  vsldeleteStream(@vsStream);
end;
{$ENDIF}

procedure TVMobjS.Id;
const
  s : string = 'Routine Id :';
{$IFNDEF HAVE_LAPACKE}
var
  i, j : TDimS;
begin
  assert(cols=rows,s +'Matrix A must be square');
  for i := 0 to rows-1 do
    for j := 0 to cols-1 do
      if i = j then fdata[calcoffsetS(i,j,cols)] := 1
      else fdata[calcoffsetS(i,j,cols)] := 0;
end;
{$ELSE}
begin
  //Check dimensions of matrices are compatible. A must be square
  assert(cols=rows,s +'Matrix A must be square');
  lapacke_slaset(CBlasRowMajor,'A',rows,cols,0,1,@Fdata[0],rows);
end;
{$ENDIF}

function TVMobjS.DataPtr: PSingle;
begin
  result := @fdata[0];
end;

procedure TVMobjS.linspace(Start, increment: Single);
const
  s : String ='routine linspace';
{$IFDEF PUREPASCAL}
  {$IFDEF HAVE_ACCELERATE}
begin
  assert(fdata <>nil,s+  ': MVObj Not Initialized');
  accel_vDSP_vramp(@Start, @increment, @FData[0], 1, high(fdata)+1);
end;
  {$ELSE}
var
  i : Integer;
begin
  assert(fdata <>nil,s+  ': MVObj Not Initialized');
  for i := 0 to high(fdata) do
    fdata[i] := start + i*increment;
end;
  {$ENDIF}
{$ELSE}
begin
  assert(fdata <>nil,s+  ': MVObj Not Initialized');
  ippsVectorSlope_32f(@FData[0],high(fdata)+1,start,increment);
end;
{$ENDIF}

function TVMobjS.Transpose:TVMObjS;
var
  temp : TDimS;
{$IFDEF PUREPASCAL}
var
  i, j : TDimS;
begin
  result := TVMObjS.Create(cols, rows);
  for i := 0 to rows-1 do
    for j := 0 to cols-1 do
      result.fdata[calcoffsetS(j,i,result.fcols)] := fdata[calcoffsetS(i,j,cols)];
end;
{$ELSE}
begin
  result := copyobjS(self);
  MKL_Simatcopy('R','T',rows,cols,1,result.DataPtr,cols,rows);
//swap row and column numbers
  temp := self.rows;
  result.frows := self.cols;
  result.fcols := temp;
end;
{$ENDIF}

function MatMultS(const A, B: TVMObjS): TVMobjS;
const
  s : String = 'Routine MatMultS :';
var
  m,n,k : integer;
  C : TVMObjS;
{$IFDEF PUREPASCAL_BLAS}
var
  ii, jj, kk : integer;
  sum : Single;
begin
  m := A.Rows;
  n := B.Cols;
  k := A.Cols;
  assert(A.cols = B.rows,s+'columns of first matrix must equal rows of second');
  c := TVMObjS.Create(m,n);
  for ii := 0 to m-1 do
    for jj := 0 to n-1 do begin
      sum := 0;
      for kk := 0 to k-1 do
        sum := sum + A.fdata[calcoffsetS(ii,kk,k)]*B.fdata[calcoffsetS(kk,jj,n)];
      C.fdata[calcoffsetS(ii,jj,n)] := sum;
    end;
  result := C;
end;
{$ELSE}
begin
  m := A.Rows;
  n := B.Cols;
  k := A.Cols;
  //Check for compatibility of matrices
  assert(A.cols = B.rows,s+'columns of first matrix must equal rows of second');
  c := TVMObjS.Create(m,n);
  cblas_sgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans,
              m,n,k, { m, n, k }
              1,     { alpha   }
                @A.FData[0], k,
                @B.Fdata[0], n,
              1, {beta}
                @C.Fdata[0],n
             );
    result := C;
end;
{$ENDIF}

function LinearSolveS(var A, B: TVMObjS):integer;
const
  s : String = 'Function LinearSolveS : ';
{ Direct linear solve for matrix A and Vectors B. On the first call for a
  given A, this LU-factorises A in place and solves for B via the combined
  LAPACKE_sgesv, caching the pivot indices on A and setting A.LU := True.
  A subsequent call against the same (already-factorised) A skips
  re-factorisation and reuses the cached LU factors/pivots via the cheaper
  LAPACKE_sgetrs (solve only) - much less work when the same A is solved
  against several different B's in turn. On return, A holds its LU-factored
  form (not the original matrix) and the solution is in B. Returns info
  from the underlying LAPACKE call. }
{$IFNDEF HAVE_LAPACKE}
  {$IFDEF HAVE_ACCELERATE}
{ See newVM.pas's LinearSolve for the full trans='T'/transpose-copy
  rationale - identical here, just Single/sgetrf_/sgetrs_-typed. }
var
  n, nrhs : integer;
  trans : char;
  bcol : array of single;
  r, c : integer;
begin
  assert(A.Cols = A.Rows,s+'Matrix A must be square');
  assert(A.Rows = B.Rows, s+'Matrix A and B have incompatible dimensions');
  n := A.rows;
  nrhs := B.cols;
  result := 0;
  if not A.LU then begin
    setlength(A.fIpiv,A.rows);
    accel_sgetrf_(@n, @n, A.DataPtr, @n, @A.fIpiv[0], @result);
    if result = 0 then A.fLUFactored := True;
  end;
  if result = 0 then begin
    setlength(bcol, n*nrhs);
    for r := 0 to n-1 do
      for c := 0 to nrhs-1 do
        bcol[c*n+r] := B.FData[r*nrhs+c];
    trans := 'T';
    accel_sgetrs_(@trans, @n, @nrhs, A.DataPtr, @n, @A.fIpiv[0], @bcol[0], @n, @result);
    if result = 0 then
      for r := 0 to n-1 do
        for c := 0 to nrhs-1 do
          B.FData[r*nrhs+c] := bcol[c*n+r];
  end;
end;
  {$ELSE}
begin
  assert(A.Cols = A.Rows,s+'Matrix A must be square');
  assert(A.Rows = B.Rows, s+'Matrix A and B have incompatible dimensions');
  if not A.LU then begin
    setlength(A.fIpiv,A.rows);
    PurePascalLUS(A.DataPtr, A.rows, A.fIpiv);
    A.fLUFactored := True;
  end;
  PurePascalLUSolveS(A.DataPtr, A.rows, A.fIpiv, B.DataPtr, B.cols);
  result := 0;
end;
  {$ENDIF}
{$ELSE}
begin
  assert(A.Cols = A.Rows,s+'Matrix A must be square');
  assert(A.Rows = B.Rows, s+'Matrix A and B have incompatible dimensions');
  if A.LU then
    result := lapacke_sgetrs(CBlasRowMajor,'N',A.rows,B.cols,@A.Fdata[0],A.cols,@A.fIpiv[0],@B.FData[0],B.cols)
  else begin
    setlength(A.fIpiv,A.rows);
    result := lapacke_sgesv(CBlasRowMajor,A.rows,B.cols,@A.Fdata[0],A.cols,@A.fIpiv[0],@B.FData[0],B.cols);
    if result = 0 then A.fLUFactored := True;
  end;
end;
{$ENDIF}

function CopyObjS(const A: TVMObjS): TVMobjS;
begin
  result := TVMObjS.Create(A.rows,A.cols);
{ See newVM.pas's CopyObj - a whole-buffer copy needs no strides, so a
  flat cblas_scopy suffices; gated on PUREPASCAL_BLAS rather than
  PUREPASCAL since it never genuinely needed real LAPACK. }
{$IFDEF PUREPASCAL_BLAS}
  Move(A.fdata[0], result.fdata[0], A.rows*A.cols*SizeOf(Single));
{$ELSE}
  cblas_scopy(A.rows*A.cols, A.DataPtr, 1, result.DataPtr, 1);
{$ENDIF}
end;

function InvertS(const A: TVMobjS): TVMobjS;
const
  s : String = 'Function InvertS : ';
var
  ipiv : array of integer;
  info : integer;
{ Matrix inverse via LAPACKE_sgetrf (LU factorisation) followed by
  LAPACKE_sgetri (inverse from the LU factors), on a CopyObjS scratch
  buffer - both LAPACKE calls overwrite their input matrix in place,
  so A itself is left untouched. }
{$IFNDEF HAVE_LAPACKE}
  {$IFDEF HAVE_ACCELERATE}
{ See newVM.pas's Invert for the transpose-symmetry rationale
  ((A^T)^-1 = (A^-1)^T) - identical here, just Single/sgetrf_/sgetri_
  -typed. }
var
  n, lwork : integer;
  work : array of single;
  workquery : array[0..0] of single;
begin
  assert(A.Cols = A.Rows, s+'Matrix A must be square');
  result := CopyObjS(A);
  setlength(ipiv, A.rows);
  n := A.rows;
  accel_sgetrf_(@n, @n, result.DataPtr, @n, @ipiv[0], @info);
  assert(info = 0, s+'sgetrf_ failed (singular matrix?), info='+IntToStr(info));
  lwork := -1;
  accel_sgetri_(@n, result.DataPtr, @n, @ipiv[0], @workquery[0], @lwork, @info);
  lwork := Trunc(workquery[0]);
  if lwork < 1 then lwork := 1;
  setlength(work, lwork);
  accel_sgetri_(@n, result.DataPtr, @n, @ipiv[0], @work[0], @lwork, @info);
  assert(info = 0, s+'sgetri_ failed (singular matrix?), info='+IntToStr(info));
end;
  {$ELSE}
var
  identity : TVMobjS;
  kk : Integer;
begin
  assert(A.Cols = A.Rows, s+'Matrix A must be square');
  result := CopyObjS(A);
  setlength(ipiv, A.rows);
  info := PurePascalLUS(result.DataPtr, A.rows, ipiv);
  assert(info = 0, s+'matrix is singular, first zero pivot at row='+IntToStr(info));
  identity := TVMobjS.Create(A.rows, A.rows);
  for kk := 0 to A.rows-1 do identity[kk,kk] := 1;
  PurePascalLUSolveS(result.DataPtr, A.rows, ipiv, identity.DataPtr, A.rows);
  result := identity;
end;
  {$ENDIF}
{$ELSE}
begin
  assert(A.Cols = A.Rows, s+'Matrix A must be square');
  result := CopyObjS(A);
  setlength(ipiv, A.rows);
  info := lapacke_sgetrf(CBlasRowMajor, A.rows, A.cols, result.DataPtr, A.cols, @ipiv[0]);
  assert(info = 0, s+'LAPACKE_sgetrf failed (singular matrix?), info='+IntToStr(info));
  info := lapacke_sgetri(CBlasRowMajor, A.rows, result.DataPtr, A.cols, @ipiv[0]);
  assert(info = 0, s+'LAPACKE_sgetri failed (singular matrix?), info='+IntToStr(info));
end;
{$ENDIF}

function Find(const A: TVMobjS; Op: TVMCompareOp; Value: Single): TVMobjI;
var
  i, j : integer;
  matched : Boolean;
begin
  result := TVMobjI.Create(A.Rows, A.Cols);
  for i := 0 to A.Rows-1 do
    for j := 0 to A.Cols-1 do begin
      case Op of
        cmpEQ: matched := A[i,j] = Value;
        cmpLT: matched := A[i,j] < Value;
        cmpLE: matched := A[i,j] <= Value;
        cmpGT: matched := A[i,j] > Value;
        cmpGE: matched := A[i,j] >= Value;
      else
        matched := False;
      end;
      if matched then result[i,j] := 1 else result[i,j] := 0;
    end;
end;

function KronS(const A, B: TVMobjS): TVMobjS;
var
  i, j, k, rowdest, coldest : integer;
{$IFDEF PUREPASCAL_BLAS}
var
  l : integer;
begin
  result := TVMobjS.Create(A.Rows*B.Rows, A.Cols*B.Cols);
  for i := 0 to A.Rows-1 do
    for j := 0 to A.Cols-1 do
      for k := 0 to B.Rows-1 do begin
        rowdest := i*B.Rows + k;
        coldest := j*B.Cols;
        for l := 0 to B.Cols-1 do
          result.fdata[calcoffsetS(rowdest,coldest+l,result.Cols)] := A[i,j]*B.fdata[calcoffsetS(k,l,B.Cols)];
      end;
end;
{$ELSE}
begin
  result := TVMobjS.Create(A.Rows*B.Rows, A.Cols*B.Cols);
  for i := 0 to A.Rows-1 do
    for j := 0 to A.Cols-1 do
      for k := 0 to B.Rows-1 do begin
        rowdest := i*B.Rows + k;
        coldest := j*B.Cols;
        cblas_saxpy(B.Cols, A[i,j], @B.FData[k*B.Cols], 1, @result.FData[rowdest*result.Cols + coldest], 1);
      end;
end;
{$ENDIF}

function DiagS(const A: TVMobjS): TVMobjS;
const
  s : String = 'Function DiagS : ';
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
begin
  assert(A.Cols = 1, s+'A must be a column vector (n,1)');
  result := TVMobjS.Create(A.Rows, A.Rows);
  for i := 0 to A.Rows-1 do
    result.fdata[calcoffsetS(i,i,A.Rows)] := A.fdata[i];
end;
{$ELSE}
begin
  assert(A.Cols = 1, s+'A must be a column vector (n,1)');
  result := TVMobjS.Create(A.Rows, A.Rows);
  cblas_scopy(A.Rows, A.DataPtr, 1, result.DataPtr, A.Rows+1);
end;
{$ENDIF}

function NormS(const A: TVMobjS): Single;
const
  s : String = 'Function NormS : ';
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
  sumsq : Single;
begin
  assert((A.Rows=1) or (A.Cols=1), s+'A must be a vector (Rows=1 or Cols=1)');
  sumsq := 0;
  for i := 0 to A.Rows*A.Cols-1 do
    sumsq := sumsq + A.fdata[i]*A.fdata[i];
  result := Sqrt(sumsq);
end;
{$ELSE}
begin
  assert((A.Rows=1) or (A.Cols=1), s+'A must be a vector (Rows=1 or Cols=1)');
  result := cblas_snrm2(A.Rows*A.Cols, A.DataPtr, 1);
end;
{$ENDIF}

function TraceS(const A: TVMobjS): Single;
const
  s : String = 'Function TraceS : ';
var
  i : integer;
begin
  assert(A.Rows = A.Cols, s+'Matrix A must be square');
  result := 0;
  for i := 0 to A.Rows-1 do
    result := result + A[i,i];
end;

function DetS(const A: TVMobjS): Single;
const
  s : String = 'Function DetS : ';
var
  ipiv : array of integer;
  info, i, sign : integer;
  scratch : TVMobjS;
{$IFNDEF HAVE_LAPACKE}
  {$IFDEF HAVE_ACCELERATE}
var
  n : integer;
  {$ENDIF}
{$ENDIF}
begin
  assert(A.Cols = A.Rows, s+'Matrix A must be square');
  scratch := CopyObjS(A);
  setlength(ipiv, A.rows);
{$IFNDEF HAVE_LAPACKE}
  {$IFDEF HAVE_ACCELERATE}
  { See newVM.pas's Det for the transpose-invariance rationale (det(A)=
    det(A^T)) - identical here, just Single/sgetrf_-typed. }
  n := A.rows;
  accel_sgetrf_(@n, @n, scratch.DataPtr, @n, @ipiv[0], @info);
  {$ELSE}
  info := PurePascalLUS(scratch.DataPtr, A.rows, ipiv);
  {$ENDIF}
{$ELSE}
  info := lapacke_sgetrf(CBlasRowMajor, A.rows, A.cols, scratch.DataPtr, A.cols, @ipiv[0]);
  assert(info >= 0, s+'LAPACKE_sgetrf reported an illegal argument, info='+IntToStr(info));
{$ENDIF}
  sign := 1;
  for i := 0 to A.rows-1 do
    if ipiv[i] <> i+1 then sign := -sign;
  result := sign;
  for i := 0 to A.rows-1 do
    result := result * scratch[i,i];
end;

function FlipUDS(const A: TVMobjS): TVMobjS;
var
  i : integer;
begin
  result := TVMobjS.Create(A.Rows, A.Cols);
{$IFDEF PUREPASCAL_BLAS}
  for i := 0 to A.Rows-1 do
    Move(A.FData[i*A.Cols], result.FData[(A.Rows-1-i)*A.Cols], A.Cols*SizeOf(Single));
{$ELSE}
  for i := 0 to A.Rows-1 do
    cblas_scopy(A.Cols, @A.FData[i*A.Cols], 1, @result.FData[(A.Rows-1-i)*A.Cols], 1);
{$ENDIF}
end;

function FlipLRS(const A: TVMobjS): TVMobjS;
var
  i : integer;
{$IFDEF PUREPASCAL}
  {$IFDEF HAVE_ACCELERATE}
{ See newVM.pas's FlipLR - vDSP_vrvrs reverses in place, so each row is
  copied into result first, then reversed there directly. }
begin
  result := TVMobjS.Create(A.Rows, A.Cols);
  for i := 0 to A.Rows-1 do begin
    Move(A.FData[i*A.Cols], result.FData[i*A.Cols], A.Cols*SizeOf(Single));
    accel_vDSP_vrvrs(@result.FData[i*A.Cols], 1, A.Cols);
  end;
end;
  {$ELSE}
var
  j : integer;
begin
  result := TVMobjS.Create(A.Rows, A.Cols);
  for i := 0 to A.Rows-1 do
    for j := 0 to A.Cols-1 do
      result.FData[i*A.Cols+j] := A.FData[i*A.Cols + (A.Cols-1-j)];
end;
  {$ENDIF}
{$ELSE}
begin
  result := TVMobjS.Create(A.Rows, A.Cols);
  for i := 0 to A.Rows-1 do
    ippsFlip_32f(@A.FData[i*A.Cols], @result.FData[i*A.Cols], A.Cols);
end;
{$ENDIF}

function MergeUDS(const A, B: TVMobjS): TVMobjS;
const
  s : String = 'Function MergeUDS : ';
begin
  assert(A.Cols = B.Cols, s+'A and B must have the same number of columns');
  result := TVMobjS.Create(A.Rows+B.Rows, A.Cols);
{$IFDEF PUREPASCAL_BLAS}
  Move(A.FData[0], result.FData[0], A.Rows*A.Cols*SizeOf(Single));
  Move(B.FData[0], result.FData[A.Rows*A.Cols], B.Rows*B.Cols*SizeOf(Single));
{$ELSE}
  cblas_scopy(A.Rows*A.Cols, A.DataPtr, 1, result.DataPtr, 1);
  cblas_scopy(B.Rows*B.Cols, B.DataPtr, 1, @result.FData[A.Rows*A.Cols], 1);
{$ENDIF}
end;

function MergeLRS(const A, B: TVMobjS): TVMobjS;
const
  s : String = 'Function MergeLRS : ';
var
  i : integer;
begin
  assert(A.Rows = B.Rows, s+'A and B must have the same number of rows');
  result := TVMobjS.Create(A.Rows, A.Cols+B.Cols);
  for i := 0 to A.Rows-1 do begin
{$IFDEF PUREPASCAL_BLAS}
    Move(A.FData[i*A.Cols], result.FData[i*result.Cols], A.Cols*SizeOf(Single));
    Move(B.FData[i*B.Cols], result.FData[i*result.Cols + A.Cols], B.Cols*SizeOf(Single));
{$ELSE}
    cblas_scopy(A.Cols, @A.FData[i*A.Cols], 1, @result.FData[i*result.Cols], 1);
    cblas_scopy(B.Cols, @B.FData[i*B.Cols], 1, @result.FData[i*result.Cols + A.Cols], 1);
{$ENDIF}
  end;
end;

function ReshapeS(const A: TVMobjS; NewRows, NewCols: TDimS): TVMobjS;
const
  s : String = 'Function ReshapeS : ';
begin
  assert(NewRows*NewCols = A.Rows*A.Cols, s+'NewRows*NewCols must equal A.Rows*A.Cols');
  result := TVMobjS.Create(NewRows, NewCols);
{$IFDEF PUREPASCAL_BLAS}
  Move(A.FData[0], result.FData[0], A.Rows*A.Cols*SizeOf(Single));
{$ELSE}
  cblas_scopy(A.Rows*A.Cols, A.DataPtr, 1, result.DataPtr, 1);
{$ENDIF}
end;

function RepmatS(const A: TVMobjS; RowReps, ColReps: Integer): TVMobjS;
const
  s : String = 'Function RepmatS : ';
var
  i, j, r, destRow : integer;
begin
  assert((RowReps > 0) and (ColReps > 0), s+'RowReps and ColReps must be > 0');
  result := TVMobjS.Create(A.Rows*RowReps, A.Cols*ColReps);
  for i := 0 to RowReps-1 do
    for r := 0 to A.Rows-1 do begin
      destRow := i*A.Rows + r;
      for j := 0 to ColReps-1 do
{$IFDEF PUREPASCAL_BLAS}
        Move(A.FData[r*A.Cols], result.FData[destRow*result.Cols + j*A.Cols], A.Cols*SizeOf(Single));
{$ELSE}
        cblas_scopy(A.Cols, @A.FData[r*A.Cols], 1, @result.FData[destRow*result.Cols + j*A.Cols], 1);
{$ENDIF}
    end;
end;

function AddScalarS(const A: TVMobjS; K: Single): TVMobjS;
{$IFDEF PUREPASCAL}
  {$IFNDEF HAVE_ACCELERATE}
var
  i : Integer;
  {$ENDIF}
{$ENDIF}
begin
  result := CopyObjS(A);
{$IFDEF PUREPASCAL}
  {$IFDEF HAVE_ACCELERATE}
  accel_vDSP_vsadd(A.DataPtr, 1, @K, result.DataPtr, 1, A.Rows*A.Cols);
  {$ELSE}
  for i := 0 to A.Rows*A.Cols-1 do
    result.fdata[i] := result.fdata[i] + K;
  {$ENDIF}
{$ELSE}
  ippsAddC_32f_I(K, result.DataPtr, A.Rows*A.Cols);
{$ENDIF}
end;

function SubMatrixS(const A: TVMobjS; R0, C0, RCount, CCount: TDimS): TVMobjS;
const
  s : String = 'Function SubMatrixS : ';
var
  i : Integer;
{ See newVM.pas's SubMatrix - a strided sub-rectangle copy only ever
  needed a per-row cblas_scopy loop, not LAPACKE_slacpy specifically, so
  this is gated on PUREPASCAL_BLAS too. }
begin
  assert((R0+RCount <= A.Rows) and (C0+CCount <= A.Cols), s+'submatrix (R0,C0,RCount,CCount) extends beyond A''s bounds');
  result := TVMobjS.Create(RCount, CCount);
{$IFDEF PUREPASCAL_BLAS}
  for i := 0 to RCount-1 do
    Move(A.FData[(R0+i)*A.Cols+C0], result.FData[i*CCount], CCount*SizeOf(Single));
{$ELSE}
  for i := 0 to RCount-1 do
    cblas_scopy(CCount, @A.FData[(R0+i)*A.Cols+C0], 1, @result.FData[i*CCount], 1);
{$ENDIF}
end;

class operator TVMobjS.+(const A, B: TVMobjS): TVMobjS;
const
  s : String = 'Operator + (TVMobjS) : ';
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
{$ENDIF}
begin
  assert((A.Rows=B.Rows) and (A.Cols=B.Cols), s+'matrix dimensions must match');
  result := CopyObjS(B);
{$IFDEF PUREPASCAL_BLAS}
  for i := 0 to A.Rows*A.Cols-1 do
    result.fdata[i] := result.fdata[i] + A.fdata[i];
{$ELSE}
  cblas_saxpy(A.Rows*A.Cols, 1, A.DataPtr, 1, result.DataPtr, 1);
{$ENDIF}
end;

class operator TVMobjS.-(const A, B: TVMobjS): TVMobjS;
const
  s : String = 'Operator - (TVMobjS) : ';
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
{$ENDIF}
begin
  assert((A.Rows=B.Rows) and (A.Cols=B.Cols), s+'matrix dimensions must match');
  result := CopyObjS(A);
{$IFDEF PUREPASCAL_BLAS}
  for i := 0 to A.Rows*A.Cols-1 do
    result.fdata[i] := result.fdata[i] - B.fdata[i];
{$ELSE}
  cblas_saxpy(A.Rows*A.Cols, -1, B.DataPtr, 1, result.DataPtr, 1);
{$ENDIF}
end;

class operator TVMobjS.-(const A: TVMobjS): TVMobjS;
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
{$ENDIF}
begin
  result := CopyObjS(A);
{$IFDEF PUREPASCAL_BLAS}
  for i := 0 to A.Rows*A.Cols-1 do
    result.fdata[i] := -result.fdata[i];
{$ELSE}
  cblas_sscal(A.Rows*A.Cols, -1, result.DataPtr, 1);
{$ENDIF}
end;

class operator TVMobjS.*(const A, B: TVMobjS): TVMobjS;
begin
  result := MulObjS(A, B);
end;

class operator TVMobjS.*(const A: TVMobjS; const k: Single): TVMobjS;
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
{$ENDIF}
begin
  result := CopyObjS(A);
{$IFDEF PUREPASCAL_BLAS}
  for i := 0 to A.Rows*A.Cols-1 do
    result.fdata[i] := result.fdata[i] * k;
{$ELSE}
  cblas_sscal(A.Rows*A.Cols, k, result.DataPtr, 1);
{$ENDIF}
end;

class operator TVMobjS.*(const k: Single; const A: TVMobjS): TVMobjS;
begin
  result := A * k;
end;

class operator TVMobjS./(const A: TVMobjS; const k: Single): TVMobjS;
const
  s : String = 'Operator / (TVMobjS) : ';
{$IFDEF PUREPASCAL}
  {$IFNDEF HAVE_ACCELERATE}
var
  i : Integer;
  {$ENDIF}
{$ENDIF}
begin
  assert(k<>0, s+'division by zero');
  result := CopyObjS(A);
{$IFDEF PUREPASCAL}
  {$IFDEF HAVE_ACCELERATE}
  accel_vDSP_vsdiv(A.DataPtr, 1, @k, result.DataPtr, 1, A.Rows*A.Cols);
  {$ELSE}
  for i := 0 to A.Rows*A.Cols-1 do
    result.fdata[i] := result.fdata[i] / k;
  {$ENDIF}
{$ELSE}
  ippsDivC_32f_I(k, result.DataPtr, A.Rows*A.Cols);
{$ENDIF}
end;

class operator TVMobjS.=(const A, B: TVMobjS): Boolean;
begin
  Result := (A.Rows = B.Rows) and (A.Cols = B.Cols) and
            CompareMem(A.DataPtr, B.DataPtr, A.Rows*A.Cols*SizeOf(Single));
end;

function Sin(const A: TVMobjS): TVMobjS;
{$IFDEF PUREPASCAL}
  {$IFDEF HAVE_ACCELERATE}
var
  n : integer;
begin
  result := TVMobjS.Create(A.Rows, A.Cols);
  n := A.Rows*A.Cols;
  accel_vvsinf(result.DataPtr, A.DataPtr, @n);
end;
  {$ELSE}
var
  i : Integer;
begin
  result := TVMobjS.Create(A.Rows, A.Cols);
  for i := 0 to A.Rows*A.Cols-1 do result.fdata[i] := System.Sin(A.fdata[i]);
end;
  {$ENDIF}
{$ELSE}
begin
  result := TVMobjS.Create(A.Rows, A.Cols);
  vsSin(A.Rows*A.Cols, A.DataPtr, result.DataPtr);
end;
{$ENDIF}

function Cos(const A: TVMobjS): TVMobjS;
{$IFDEF PUREPASCAL}
  {$IFDEF HAVE_ACCELERATE}
var
  n : integer;
begin
  result := TVMobjS.Create(A.Rows, A.Cols);
  n := A.Rows*A.Cols;
  accel_vvcosf(result.DataPtr, A.DataPtr, @n);
end;
  {$ELSE}
var
  i : Integer;
begin
  result := TVMobjS.Create(A.Rows, A.Cols);
  for i := 0 to A.Rows*A.Cols-1 do result.fdata[i] := System.Cos(A.fdata[i]);
end;
  {$ENDIF}
{$ELSE}
begin
  result := TVMobjS.Create(A.Rows, A.Cols);
  vsCos(A.Rows*A.Cols, A.DataPtr, result.DataPtr);
end;
{$ENDIF}

function Tan(const A: TVMobjS): TVMobjS;
{$IFDEF PUREPASCAL}
  {$IFDEF HAVE_ACCELERATE}
var
  n : integer;
begin
  result := TVMobjS.Create(A.Rows, A.Cols);
  n := A.Rows*A.Cols;
  accel_vvtanf(result.DataPtr, A.DataPtr, @n);
end;
  {$ELSE}
var
  i : Integer;
begin
  result := TVMobjS.Create(A.Rows, A.Cols);
  for i := 0 to A.Rows*A.Cols-1 do result.fdata[i] := Math.Tan(A.fdata[i]);
end;
  {$ENDIF}
{$ELSE}
begin
  result := TVMobjS.Create(A.Rows, A.Cols);
  vsTan(A.Rows*A.Cols, A.DataPtr, result.DataPtr);
end;
{$ENDIF}

function Sinh(const A: TVMobjS): TVMobjS;
{$IFDEF PUREPASCAL}
  {$IFDEF HAVE_ACCELERATE}
var
  n : integer;
begin
  result := TVMobjS.Create(A.Rows, A.Cols);
  n := A.Rows*A.Cols;
  accel_vvsinhf(result.DataPtr, A.DataPtr, @n);
end;
  {$ELSE}
var
  i : Integer;
begin
  result := TVMobjS.Create(A.Rows, A.Cols);
  for i := 0 to A.Rows*A.Cols-1 do result.fdata[i] := Math.Sinh(A.fdata[i]);
end;
  {$ENDIF}
{$ELSE}
begin
  result := TVMobjS.Create(A.Rows, A.Cols);
  vsSinh(A.Rows*A.Cols, A.DataPtr, result.DataPtr);
end;
{$ENDIF}

function Sqr(const A: TVMobjS): TVMobjS;
{$IFDEF PUREPASCAL}
  {$IFDEF HAVE_ACCELERATE}
begin
  result := TVMobjS.Create(A.Rows, A.Cols);
  accel_vDSP_vsq(A.DataPtr, 1, result.DataPtr, 1, A.Rows*A.Cols);
end;
  {$ELSE}
var
  i : Integer;
begin
  result := TVMobjS.Create(A.Rows, A.Cols);
  for i := 0 to A.Rows*A.Cols-1 do result.fdata[i] := System.Sqr(A.fdata[i]);
end;
  {$ENDIF}
{$ELSE}
begin
  result := TVMobjS.Create(A.Rows, A.Cols);
  vsSqr(A.Rows*A.Cols, A.DataPtr, result.DataPtr);
end;
{$ENDIF}

function Sqrt(const A: TVMobjS): TVMobjS;
{$IFDEF PUREPASCAL}
  {$IFDEF HAVE_ACCELERATE}
{ Apple's vvsqrtf (unlike every other vForce/vDSP entry point used in this
  unit - vvsinf/vvcosf/vvtanf/vvsinhf/vvexpf/vvlogf/vDSP_vsq/vDSP_vmul all
  confirmed fine at N as low as 1) crashes with an access violation for
  N<4 on this machine - reproduced in total isolation outside this
  codebase (a standalone program calling vvsqrtf directly via the exact
  same procedural-variable/cdecl mechanism, independent of newVM/cblas,
  still crashed at N=1..3 and only succeeded at N>=4). vForce's own
  header markets itself as being "for large arrays", so small-N may
  simply be outside what Apple validated. Since correctness can't depend
  on undocumented behaviour, N<4 falls back to the plain-Pascal loop -
  negligible cost given how small N has to be to hit it. }
var
  n : integer;
  i : Integer;
begin
  result := TVMobjS.Create(A.Rows, A.Cols);
  n := A.Rows*A.Cols;
  if n >= 4 then
    accel_vvsqrtf(result.DataPtr, A.DataPtr, @n)
  else
    for i := 0 to n-1 do result.fdata[i] := System.Sqrt(A.fdata[i]);
end;
  {$ELSE}
var
  i : Integer;
begin
  result := TVMobjS.Create(A.Rows, A.Cols);
  for i := 0 to A.Rows*A.Cols-1 do result.fdata[i] := System.Sqrt(A.fdata[i]);
end;
  {$ENDIF}
{$ELSE}
begin
  result := TVMobjS.Create(A.Rows, A.Cols);
  vsSqrt(A.Rows*A.Cols, A.DataPtr, result.DataPtr);
end;
{$ENDIF}

function Exp(const A: TVMobjS): TVMobjS;
{$IFDEF PUREPASCAL}
  {$IFDEF HAVE_ACCELERATE}
var
  n : integer;
begin
  result := TVMobjS.Create(A.Rows, A.Cols);
  n := A.Rows*A.Cols;
  accel_vvexpf(result.DataPtr, A.DataPtr, @n);
end;
  {$ELSE}
var
  i : Integer;
begin
  result := TVMobjS.Create(A.Rows, A.Cols);
  for i := 0 to A.Rows*A.Cols-1 do result.fdata[i] := System.Exp(A.fdata[i]);
end;
  {$ENDIF}
{$ELSE}
begin
  result := TVMobjS.Create(A.Rows, A.Cols);
  vsExp(A.Rows*A.Cols, A.DataPtr, result.DataPtr);
end;
{$ENDIF}

function Ln(const A: TVMobjS): TVMobjS;
{$IFDEF PUREPASCAL}
  {$IFDEF HAVE_ACCELERATE}
var
  n : integer;
begin
  result := TVMobjS.Create(A.Rows, A.Cols);
  n := A.Rows*A.Cols;
  accel_vvlogf(result.DataPtr, A.DataPtr, @n);
end;
  {$ELSE}
var
  i : Integer;
begin
  result := TVMobjS.Create(A.Rows, A.Cols);
  for i := 0 to A.Rows*A.Cols-1 do result.fdata[i] := System.Ln(A.fdata[i]);
end;
  {$ENDIF}
{$ELSE}
begin
  result := TVMobjS.Create(A.Rows, A.Cols);
  vsLn(A.Rows*A.Cols, A.DataPtr, result.DataPtr);
end;
{$ENDIF}

function MulObjS(const A, B: TVMObjS): TVMObjS;
const
  s: string ='Routine MulObjS : ';
{$IFDEF PUREPASCAL}
  {$IFDEF HAVE_ACCELERATE}
begin
  assert((a.rows=b.rows)and(a.cols=b.cols),s+'Dimensions of A and B must be the same');
  result := TVMobjS.Create(A.Rows, A.Cols);
  accel_vDSP_vmul(A.DataPtr, 1, B.DataPtr, 1, result.DataPtr, 1, A.Rows*A.Cols);
end;
  {$ELSE}
var
  i : Integer;
begin
  assert((a.rows=b.rows)and(a.cols=b.cols),s+'Dimensions of A and B must be the same');
  result := CopyObjS(A);
  for i := 0 to A.rows*A.cols-1 do
    result.fdata[i] := result.fdata[i] * B.fdata[i];
end;
  {$ENDIF}
{$ELSE}
begin
  assert((a.rows=b.rows)and(a.cols=b.cols),s+'Dimensions of A and B must be the same');
  result := CopyObjS(A);
  vsMul(A.rows*A.cols,A.Dataptr,B.DataPtr,Result.DataPtr);
end;
{$ENDIF}

{$IFNDEF HAVE_FFTW}
// Direct O(N^2) trigonometric-sum evaluation - single-precision counterpart
// to newVM.pas's own PPr2rTransform; see that unit's header comment for the
// full rationale and the exact FFTW-matching formulas per kind.
function PPDSgnPowS(V: Single; K: Integer): Single; inline;
begin
  if Odd(K) then result := -V else result := V;
end;

procedure PPr2rTransformS(N: Integer; InData, OutData: PSingle; kind: TFFTW_r2r_kind);
var
  j, k : Integer;
  acc : Single;
begin
  case kind of
    FFTW_REDFT00: //DCT-I: logical size 2*(N-1)
      for k := 0 to N-1 do begin
        acc := InData[0] + PPDSgnPowS(InData[N-1], k);
        for j := 1 to N-2 do
          acc := acc + 2*InData[j]*cos(Pi*j*k/(N-1));
        OutData[k] := acc;
      end;
    FFTW_REDFT10: //DCT-II
      for k := 0 to N-1 do begin
        acc := 0;
        for j := 0 to N-1 do
          acc := acc + InData[j]*cos(Pi*(j+0.5)*k/N);
        OutData[k] := 2*acc;
      end;
    FFTW_REDFT01: //DCT-III
      for k := 0 to N-1 do begin
        acc := InData[0];
        for j := 1 to N-1 do
          acc := acc + 2*InData[j]*cos(Pi*j*(k+0.5)/N);
        OutData[k] := acc;
      end;
    FFTW_REDFT11: //DCT-IV
      for k := 0 to N-1 do begin
        acc := 0;
        for j := 0 to N-1 do
          acc := acc + InData[j]*cos(Pi*(j+0.5)*(k+0.5)/N);
        OutData[k] := 2*acc;
      end;
    FFTW_RODFT00: //DST-I: logical size 2*(N+1)
      for k := 0 to N-1 do begin
        acc := 0;
        for j := 0 to N-1 do
          acc := acc + InData[j]*sin(Pi*(j+1)*(k+1)/(N+1));
        OutData[k] := 2*acc;
      end;
    FFTW_RODFT10: //DST-II
      for k := 0 to N-1 do begin
        acc := 0;
        for j := 0 to N-1 do
          acc := acc + InData[j]*sin(Pi*(j+0.5)*(k+1)/N);
        OutData[k] := 2*acc;
      end;
    FFTW_RODFT01: //DST-III
      for k := 0 to N-1 do begin
        acc := PPDSgnPowS(InData[N-1], k);
        for j := 0 to N-2 do
          acc := acc + 2*InData[j]*sin(Pi*(j+1)*(k+0.5)/N);
        OutData[k] := acc;
      end;
    FFTW_RODFT11: //DST-IV
      for k := 0 to N-1 do begin
        acc := 0;
        for j := 0 to N-1 do
          acc := acc + InData[j]*sin(Pi*(j+0.5)*(k+0.5)/N);
        OutData[k] := 2*acc;
      end;
  end;
end;
{$ENDIF}

function r2rTransformS(const A: TVMobjS; kind: TFFTW_r2r_kind): TVMobjS;
const
  s : String = 'Routine r2rTransformS : ';
var
  n : integer;
{$IFDEF HAVE_FFTW}
  plan : fftw_plan;
{$ENDIF}
begin
  assert((A.Rows=1) or (A.Cols=1), s+'A must be a vector (Rows=1 or Cols=1)');
  n := A.Rows*A.Cols;
  result := TVMobjS.Create(A.Rows, A.Cols);
{$IFDEF HAVE_FFTW}
  assert(Assigned(fftwf_plan_r2r_1d), s+'FFTW3 (single) library not loaded');
  plan := fftwf_plan_r2r_1d(n, A.DataPtr, result.DataPtr, kind, FFTW_ESTIMATE or FFTW_PRESERVE_INPUT);
  assert(plan<>nil, s+'fftwf_plan_r2r_1d failed');
  fftwf_execute_r2r(plan, A.DataPtr, result.DataPtr);
  fftwf_destroy_plan(plan);
{$ELSE}
  PPr2rTransformS(n, A.DataPtr, result.DataPtr, kind);
{$ENDIF}
end;

function DCT1(const A: TVMobjS): TVMobjS;
begin
  result := r2rTransformS(A, FFTW_REDFT00);
end;

function DCT2(const A: TVMobjS): TVMobjS;
begin
  result := r2rTransformS(A, FFTW_REDFT10);
end;

function DCT3(const A: TVMobjS): TVMobjS;
begin
  result := r2rTransformS(A, FFTW_REDFT01);
end;

function DCT4(const A: TVMobjS): TVMobjS;
begin
  result := r2rTransformS(A, FFTW_REDFT11);
end;

function DST1(const A: TVMobjS): TVMobjS;
begin
  result := r2rTransformS(A, FFTW_RODFT00);
end;

function DST2(const A: TVMobjS): TVMobjS;
begin
  result := r2rTransformS(A, FFTW_RODFT10);
end;

function DST3(const A: TVMobjS): TVMobjS;
begin
  result := r2rTransformS(A, FFTW_RODFT01);
end;

function DST4(const A: TVMobjS): TVMobjS;
begin
  result := r2rTransformS(A, FFTW_RODFT11);
end;

end.
