unit newVMComplex;

{*******************************************************************************

     Vector / Matrix objects leveraging intel mkl libraries (COMPLEX DOUBLE)

     Derived from newVM.pas (double precision original by Dr H. Dent,
     howard@hgrd.co.uk, 29 July 2026). Adapted for double-precision complex
     data using the MKL "Z" (double-precision complex) BLAS/LAPACK routines
     (the complex analogue of MKL_Complex16 / C's double _Complex).

     Inspired by Dew MtxVec Library for fpc but does not distinguish
     between matrix and vector objects. Vectors are column dimension (*,1)
     or row dimension (1,*).

     IMPORTANT ASSUMPTIONS - please verify against your actual bindings:

     1) TComplex16 below is a plain {re,im: Double} record chosen to match
        the memory layout of MKL_Complex16 (two contiguous IEEE-754
        doubles). If your OneAPI/cblas unit already declares MKL_Complex16
        (commonly with fields named "real"/"imag" rather than "re"/"im"),
        prefer that existing type instead of TComplex16 so the ABI matches
        exactly what the linked mkl_rt.so expects, and rename fields
        throughout this file accordingly.

     2) cblas_zgemm expects alpha/beta as pointers to a complex scalar
        (matching the CBLAS C convention `const void *alpha`), so alpha
        and beta are passed as @alpha/@beta here - unlike the real gemm
        routines which take alpha/beta by value.

     3) lapacke_zlaset takes its alpha/beta (off-diagonal/diagonal fill
        values) by value as complex scalars, matching the LAPACKE C
        signature - passed directly (not by pointer) here.

     4) MKL's VSL does not provide a complex Gaussian generator. fillRandom
        instead reinterprets the complex data buffer as a double array of
        twice the length (valid because TComplex16 is exactly two
        contiguous doubles) and calls vdRngGaussian once, filling both the
        real and imaginary parts with independent N(0,1) samples.

     Confirm function names/casing (cblas_zgemm, lapacke_zlaset,
     lapacke_zgesv, LAPACKE_zlacpy) match your cblas / OneAPI bindings.

     OPERATOR OVERLOADS (algebraic expressions on TVMobjZ):
       - '+' and '-' are element-wise, via cblas_zaxpy (alpha passed by
         pointer, per the CBLAS complex convention).
       - unary '-' negates via cblas_zdscal - MKL's "scale a complex
         vector by a real scalar" routine, used here with -1.
       - '*' between two same-type TVMobjZ is ELEMENT-WISE multiplication,
         delegating to MulObjZ (MKL VML's vzMul) - NOT matrix
         multiplication; use MatMultZ (cblas_zgemm) explicitly for a real
         matrix product.
       - '*' and '/' accept either a TComplex16 scalar (cblas_zscal) or a
         plain Double scalar (cblas_zdscal); division computes the scalar
         reciprocal in Pascal first, since there is no BLAS "divide by
         scalar" primitive.
       - mixed-type '+' and '-' against a real TVMobj promote the real
         operand to complex via RealToComplex, then delegate to the
         TVMobjZ operators above - so e.g.  Z := R + I;  (real matrix plus
         a complex identity) works without an explicit cast. Mixed-type
         '*' does NOT follow that pattern: TVMobjZ*TVMobj and
         TVMobj*TVMobjZ both call MatMultZ (real matrix multiplication)
         directly, not MulObjZ - so same-type Z*Z is element-wise but
         mixed-type Z*R/R*Z is a genuine matrix product (this is
         deliberately exercised by newVMTests.pas's
         TestEigDecomposeSatisfiesEigenEquation, via "Av := A * vcol"
         for the real eigenvector matrix A and complex eigenvector
         vcol). Know which one you're calling at each site - the two
         forms are not interchangeable despite looking identical.

*******************************************************************************}

{$mode Delphi}{$H+}
{$Align 8}

{$I newVMConfig.inc}
// newVMConfig.inc (generated by ./newvmconfigure - see newVM.pas's own
// header comment for the full rationale) defines HAVE_MKL/HAVE_IPP/
// HAVE_OPENBLAS/HAVE_FFTW and, derived from those, PUREPASCAL - set
// whenever any of OpenBLAS/MKL/IPP is missing on the machine that ran the
// configure tool. When PUREPASCAL is set, every routine below that would
// otherwise call into cblas/OneAPI instead uses a plain-Pascal
// implementation of its own, individually guarded - the complex-double
// analogue of newVM.pas's own PUREPASCAL bodies (see that unit for the
// real-valued algorithms this mirrors: LU decomposition with partial
// pivoting backs LinearSolveZ/InvertZ/DetZ, here using complex arithmetic
// throughout and |z|^2 in place of Abs() for pivot comparison; everything
// else is a direct loop). EigDecompose (LAPACKE_dgeev) and the FFTW-backed
// FFT_R2C/FFT_C2R/FFT/IFFT have no such fallback - out of scope, same as
// newVM.pas's own DCT/DST; they already assert clearly when the library
// they need isn't loaded.
// (NOTE: '//' line comments throughout this block deliberately, not a
// '{ ... }' block - see newVM.pas's own copy of this note for why.)

{$IFDEF UNIX}
  {$IFDEF HAVE_MKL}
{$Linklib 'mkl_rt.so'}
{$Linklib 'pthread'}
{$Linklib 'm'}
{$Linklib 'dl'}
//mkl_rt.so dlopen's libmkl_core.so (and friends) at runtime, which
//expects libm/pthread/dl to already be loaded into the process's
//global symbol table - without this you get errors like:
//  symbol lookup error: .../libmkl_core.so: undefined symbol: log10
//Unix/ELF dynamic-linker quirk only - not needed for mkl_rt.dll on Windows.
  {$ENDIF}
{$ENDIF}

interface

uses
  Classes, SysUtils, cblas, math, TestRegistry, OneAPI, Types, newVM, fftw3;

Const
  // See newVM.pas's own MaxDim comment - an arbitrary development-time
  // value, not a real limit, raised in step with it across every
  // parallel real/complex x double/single unit.
  MaxDimZ = 2097152;    //maximum dimensions of any array

Type
  TDimZ = 0..MaxDimZ-1;
  TDataSizeZ = 1..MaxDimZ*MaxDimZ;

  //Double precision complex scalar - layout matches MKL_Complex16
  //(two contiguous doubles). Rename to match your bindings if they
  //already declare an equivalent type - see header notes above.
  {TComplex16 = record
    re, im : Double;
  end; }

  TVectorZ = Array of TComplex16;   //maximum dimensions of any array


type

  { TVMobjZ }

  TVMobjZ = record
    private
      fData : TVectorZ;  //Holds data for object
      frows, fcols : TDimZ;
      fIpiv : array of Integer;  //cached LU pivot indices from LinearSolveZ, valid iff fLUFactored
      fLUFactored : Boolean;     //True once LinearSolveZ has LU-factorised this object in place (see LinearSolveZ)
      function getelement(r,c: TDimZ): TComplex16;
      procedure setelement(r,c: TDimZ; AValue: TComplex16);
    public
      constructor create(r,c :TDimZ);Overload;
      Constructor create(r,c: TDimZ; const Values : TVectorZ); overload;
      function writeMatrix: TStringList;
      property Element[r,c:TDimZ]:TComplex16 read getelement write setelement; default;
      procedure fillRandom;
      procedure Id;
      procedure linspace(Start, increment: TComplex16);
      function Transpose: TVMObjZ;
      property Rows: TDimZ read frows;              //read-only dimension accessors
      property Cols: TDimZ read fcols;
      property LU: Boolean read fLUFactored;  //True once LinearSolveZ has cached an LU factorisation of this object

      { Operator overloads - see OPERATOR OVERLOADS note in the header above.
        Mode Delphi only supports operator overloading as "class operator"
        members of the record. The mixed real/complex forms are declared
        here (rather than on TVMobj in newVM.pas) because TVMobjZ is the
        common operand in all of them, and only this unit sees both types. }
      class operator +(const A, B: TVMobjZ): TVMobjZ;
      class operator -(const A, B: TVMobjZ): TVMobjZ;
      class operator -(const A: TVMobjZ): TVMobjZ;
      class operator *(const A, B: TVMobjZ): TVMobjZ;
      class operator *(const A: TVMobjZ; const k: TComplex16): TVMobjZ;
      class operator *(const k: TComplex16; const A: TVMobjZ): TVMobjZ;
      class operator *(const A: TVMobjZ; const k: Double): TVMobjZ;
      class operator *(const k: Double; const A: TVMobjZ): TVMobjZ;
      class operator /(const A: TVMobjZ; const k: TComplex16): TVMobjZ;
      class operator /(const A: TVMobjZ; const k: Double): TVMobjZ;
      class operator +(const A: TVMobjZ; const B: TVMobj): TVMobjZ;
      class operator +(const A: TVMobj; const B: TVMobjZ): TVMobjZ;
      class operator -(const A: TVMobjZ; const B: TVMobj): TVMobjZ;
      class operator -(const A: TVMobj; const B: TVMobjZ): TVMobjZ;
      class operator *(const A: TVMobjZ; const B: TVMobj): TVMobjZ;
      class operator *(const A: TVMobj; const B: TVMobjZ): TVMobjZ;
      class operator =(const A, B: TVMobjZ): Boolean;
  end;

function calcoffsetZ(r,c,cols :TDimZ):integer;inline;
function MatMultZ( const A, B: TVMObjZ): TVMobjZ;
function LinearSolveZ(var A, B: TVMObjZ):integer;
function CopyObjZ(Const A : TVMObjZ):TVMobjZ;
function InvertZ(const A: TVMobjZ): TVMobjZ;  //matrix inverse, via LAPACKE_zgetrf+zgetri; leaves A untouched
function KronZ(const A, B: TVMobjZ): TVMobjZ;  //Kronecker product - see Kron in newVM.pas
function DiagZ(const A: TVMobjZ): TVMobjZ;  //column vector (n,1) -> (n,n) diagonal matrix - see Diag in newVM.pas
function NormZ(const A: TVMobjZ): Double;  //Euclidean norm (real-valued), via cblas_dznrm2 - see Norm in newVM.pas
function TraceZ(const A: TVMobjZ): TComplex16;  //sum of A's leading-diagonal elements - see Trace in newVM.pas
function DetZ(const A: TVMobjZ): TComplex16;  //determinant, via LAPACKE_zgetrf - see Det in newVM.pas
function FlipUDZ(const A: TVMobjZ): TVMobjZ;  //reverses row order - see FlipUD in newVM.pas
function FlipLRZ(const A: TVMobjZ): TVMobjZ;  //reverses each row's element order, via ippsFlip_64fc - see FlipLR in newVM.pas
function MergeUDZ(const A, B: TVMobjZ): TVMobjZ;  //stacks A above B - see MergeUD in newVM.pas
function MergeLRZ(const A, B: TVMobjZ): TVMobjZ;  //places A left of B - see MergeLR in newVM.pas
function ReshapeZ(const A: TVMobjZ; NewRows, NewCols: TDimZ): TVMobjZ;  //reinterprets A's elements with new dims - see Reshape in newVM.pas
function RepmatZ(const A: TVMobjZ; RowReps, ColReps: Integer): TVMobjZ;  //tiles A RowReps x ColReps - see Repmat in newVM.pas
{ AddScalarZ - adds K to every element, via ippsAddC_64fc_I - see AddScalar
  in newVM.pas. Two overloads, same convention as the '*'/'/' operators:
  a native TComplex16 constant, or a plain Double treated as a real scalar
  (added to every element's real part only, imaginary parts untouched -
  i.e. K is promoted to Cplx(K,0), not added to both parts). }
function AddScalarZ(const A: TVMobjZ; K: TComplex16): TVMobjZ; overload;
function AddScalarZ(const A: TVMobjZ; K: Double): TVMobjZ; overload;
function SubMatrixZ(const A: TVMobjZ; R0, C0, RCount, CCount: TDimZ): TVMobjZ;  //extracts a submatrix, via LAPACKE_zlacpy - see SubMatrix in newVM.pas
function Cplx(re,im : Double): TComplex16;inline;
function RealToComplex(const A : TVMobj): TVMobjZ;    //promotes a real double TVMobj to a complex TVMobjZ, im = 0
function GetRealPart(const A : TVMobjZ): TVMobj;      //extracts the real component of A into a real double TVMobj
function GetImagPart(const A : TVMobjZ): TVMobj;      //extracts the imaginary component of A into a real double TVMobj
procedure SplitComplex(const A : TVMobjZ; out RealPart, ImagPart: TVMobj); //convenience: both parts in one call
procedure EigDecompose(const A : TVMobj; out EigenValues, EigenVectors: TVMobjZ); //eigenvalues/(right) eigenvectors of a real square matrix, via LAPACKE_dgeev

{ Elementwise transcendental/algebraic functions, via MKL VML (vz* routines
  in OneAPI.pas - complex-valued, principal-branch results). Each returns a
  new TVMobjZ of the same dimensions as A, with the function applied to
  every element. Marked "overload" since Sin/Cos/Sqr/Sqrt/Exp/Ln also exist
  in System/Math for plain numeric types - without "overload" the TVMobjZ
  versions here would hide those entirely within this unit. }
function Sin(const A: TVMobjZ): TVMobjZ; overload;
function Cos(const A: TVMobjZ): TVMobjZ; overload;
function Tan(const A: TVMobjZ): TVMobjZ; overload;
function Sinh(const A: TVMobjZ): TVMobjZ; overload;
function Sqr(const A: TVMobjZ): TVMobjZ; overload;
function Sqrt(const A: TVMobjZ): TVMobjZ; overload;
function Exp(const A: TVMobjZ): TVMobjZ; overload;
function Ln(const A: TVMobjZ): TVMobjZ; overload;
function MulObjZ(const A, B: TVMObjZ): TVMobjZ;

{ Real<->complex and complex<->complex 1D FFTs, via FFTW3 (fftw3.pas) on
  the double-precision library. All vector-only (Rows=1 or Cols=1, result
  keeps A's orientation); input is never mutated (FFTW_PRESERVE_INPUT).
  FFT_R2C's result is FFTW's packed half-spectrum, length N div 2 + 1 (the
  upper half is redundant for real input by conjugate symmetry); FFT_C2R
  needs the target real length N explicitly, since N div 2 + 1 alone
  doesn't determine whether N was even or odd. Unlike raw FFTW (which is
  unnormalized), FFT_C2R and IFFT here divide by N, so
  FFT_C2R(FFT_R2C(x), N) = x and IFFT(FFT(x)) = x. Marked "overload" since
  newVMComplexSingle.pas declares the TVMobjS/TVMobjC analogues of these
  same names. }
function FFT_R2C(const A: TVMobj): TVMobjZ; overload;         //real -> packed half-spectrum
function FFT_C2R(const A: TVMobjZ; N: Integer): TVMobj; overload; //packed half-spectrum -> real, normalized
function FFT(const A: TVMobjZ): TVMobjZ; overload;             //complex -> complex, forward
function IFFT(const A: TVMobjZ): TVMobjZ; overload;            //complex -> complex, inverse, normalized

{ PowerSpectrum(A): one-call Hamming-windowed LINEAR power spectrum - see
  the implementation's own header comment for the full rationale (built
  for repeated use on fixed-size ADC-derived buffers). Real input (A:
  TVMobj) returns half A's length (A.Rows*A.Cols div 2, integer
  division); complex input (A: TVMobjZ) returns the same length as A,
  since a general complex signal has no redundant conjugate-symmetric
  half to drop the way real input does. Both always return a real TVMobj
  (a power spectrum is never itself complex-valued) of LINEAR power
  (re^2+im^2) - not dB; take 10*Log10(P+eps) at the call site for a dB
  scale, the eps guarding against an exact-zero bin same as any log-power
  display needs to. Marked "overload" for the same reason as FFT_R2C
  above: newVMComplexSingle.pas declares the TVMobjS/TVMobjC analogues of
  these same two names. }
function PowerSpectrum(const A: TVMobj): TVMobj; overload;   //real signal -> half-length linear power spectrum
function PowerSpectrum(const A: TVMobjZ): TVMobj; overload;  //complex signal -> full-length linear power spectrum

implementation

function Cplx(re,im: Double): TComplex16;
begin
  result.re := re;
  result.im := im;
end;

function calcoffsetZ(r, c, cols: TDimZ): integer;
begin
  result := r*cols+c;
end;

{$IFDEF PUREPASCAL}
{ Complex-arithmetic helpers used only by the PUREPASCAL routines below -
  TComplex16 has no operator overloads of its own (only TVMobjZ does, and
  only for whole matrices/vectors, not two loose scalars - same rationale
  DetZ's own hand-written "result := Cplx(re*d.re - im*d.im, ...)" already
  documents in the library-backed build). Self-contained (CDivZ doesn't
  call the later ReciprocalZ) since these are needed by
  PurePascalLUZ/PurePascalLUSolveZ, which - like their newVM.pas
  counterparts - have to come before LinearSolveZ/InvertZ/DetZ, well
  before ReciprocalZ's own position further down this file. }
function CAddZ(const a, b: TComplex16): TComplex16;
begin
  result.re := a.re + b.re;
  result.im := a.im + b.im;
end;

function CSubZ(const a, b: TComplex16): TComplex16;
begin
  result.re := a.re - b.re;
  result.im := a.im - b.im;
end;

function CMulZ(const a, b: TComplex16): TComplex16;
begin
  result.re := a.re*b.re - a.im*b.im;
  result.im := a.re*b.im + a.im*b.re;
end;

function CDivZ(const a, b: TComplex16): TComplex16;
var
  d : Double;
begin
  d := b.re*b.re + b.im*b.im;
  result.re := (a.re*b.re + a.im*b.im) / d;
  result.im := (a.im*b.re - a.re*b.im) / d;
end;

function CAbsSqZ(const a: TComplex16): Double;
begin
  result := a.re*a.re + a.im*a.im;
end;

function CExpZ(const a: TComplex16): TComplex16;
var
  ea : Double;
begin
  ea := Exp(a.re);
  result.re := ea*Cos(a.im);
  result.im := ea*Sin(a.im);
end;

function CLnZ(const a: TComplex16): TComplex16;
begin
  result.re := Ln(Sqrt(CAbsSqZ(a)));
  result.im := ArcTan2(a.im, a.re);
end;

function CSinZ(const a: TComplex16): TComplex16;
begin
  result.re := Sin(a.re)*Cosh(a.im);
  result.im := Cos(a.re)*Sinh(a.im);
end;

function CCosZ(const a: TComplex16): TComplex16;
begin
  result.re := Cos(a.re)*Cosh(a.im);
  result.im := -Sin(a.re)*Sinh(a.im);
end;

function CSinhZ(const a: TComplex16): TComplex16;
begin
  result.re := Sinh(a.re)*Cos(a.im);
  result.im := Cosh(a.re)*Sin(a.im);
end;

{ Principal square root: standard "r=|z|, re=sqrt((r+a.re)/2),
  im=sign(a.im)*sqrt((r-a.re)/2)" formula. }
function CSqrtZ(const a: TComplex16): TComplex16;
var
  r : Double;
begin
  r := Sqrt(CAbsSqZ(a));
  result.re := Sqrt((r+a.re)/2);
  if a.im >= 0 then
    result.im := Sqrt((r-a.re)/2)
  else
    result.im := -Sqrt((r-a.re)/2);
end;

{ PurePascalLUZ/PurePascalLUSolveZ - complex analogues of newVM.pas's
  PurePascalLU/PurePascalLUSolve; same LAPACKE_zgetrf-matching storage/
  ipiv convention, just with complex arithmetic throughout and |z|^2
  (CAbsSqZ, monotonic in |z| so comparison order is unaffected) standing
  in for Abs() when choosing the pivot row. }
function PurePascalLUZ(Data: PComplex16; N: Integer; var ipiv: array of Integer): Integer;
var
  i, j, k, p: Integer;
  maxval, absval: Double;
  tmp, factor: TComplex16;
begin
  result := 0;
  for k := 0 to N-1 do begin
    p := k;
    maxval := CAbsSqZ(Data[k*N+k]);
    for i := k+1 to N-1 do begin
      absval := CAbsSqZ(Data[i*N+k]);
      if absval > maxval then begin
        maxval := absval;
        p := i;
      end;
    end;
    ipiv[k] := p+1;
    if p <> k then
      for j := 0 to N-1 do begin
        tmp := Data[k*N+j];
        Data[k*N+j] := Data[p*N+j];
        Data[p*N+j] := tmp;
      end;
    if (Data[k*N+k].re = 0) and (Data[k*N+k].im = 0) then begin
      if result = 0 then result := k+1;
      Continue;
    end;
    for i := k+1 to N-1 do begin
      factor := CDivZ(Data[i*N+k], Data[k*N+k]);
      Data[i*N+k] := factor;
      for j := k+1 to N-1 do
        Data[i*N+j] := CSubZ(Data[i*N+j], CMulZ(factor, Data[k*N+j]));
    end;
  end;
end;

procedure PurePascalLUSolveZ(LU: PComplex16; N: Integer; const ipiv: array of Integer; B: PComplex16; nrhs: Integer);
var
  i, j, r, p: Integer;
  sum, tmp: TComplex16;
begin
  for i := 0 to N-1 do begin
    p := ipiv[i]-1;
    if p <> i then
      for j := 0 to nrhs-1 do begin
        tmp := B[i*nrhs+j];
        B[i*nrhs+j] := B[p*nrhs+j];
        B[p*nrhs+j] := tmp;
      end;
  end;
  for r := 0 to nrhs-1 do
    for i := 1 to N-1 do begin
      sum := Cplx(0,0);
      for j := 0 to i-1 do
        sum := CAddZ(sum, CMulZ(LU[i*N+j], B[j*nrhs+r]));
      B[i*nrhs+r] := CSubZ(B[i*nrhs+r], sum);
    end;
  for r := 0 to nrhs-1 do
    for i := N-1 downto 0 do begin
      sum := Cplx(0,0);
      for j := i+1 to N-1 do
        sum := CAddZ(sum, CMulZ(LU[i*N+j], B[j*nrhs+r]));
      B[i*nrhs+r] := CDivZ(CSubZ(B[i*nrhs+r], sum), LU[i*N+i]);
    end;
end;
{$ENDIF}

{ TVMobjZ }

function TVMobjZ.getelement(r,c: TDimZ): TComplex16;
var
   Ix : Integer;
begin
   assert((r<rows) and (c<cols),'Dimensions don''t match in getelement');
   Ix := calcoffsetZ(r,c,cols);
   assert(Ix<= high(fdata),'Index out of range in get element');
   result := fdata[Ix];
end;

procedure TVMobjZ.setelement(r,c:TDimZ; AValue: TComplex16);
var
 Ix : Integer;
begin
   assert((r<rows) and (c<cols),'Dimensions don''t match in setelement');
   Ix := calcoffsetZ(r,c,cols);
   assert(Ix <= high(fdata),'Index out of range in set element');
   fdata[Ix] := Avalue;
end;

constructor TVMobjZ.create(r,c :TDimZ);
var
  i,N : integer;
begin
  assert((r>0) and (c>0),'rows and columns must be > 0');
  frows := r;
  fcols := c;
  N := r*c;
  setLength(fData,N);
  for i := low(fdata) to high(fdata) do fdata[i] := Cplx(0,0);
  fLUFactored := False;
end;

constructor TVMobjZ.create(r,c : TDimZ; const Values: TVectorZ);
begin
  assert((r>0) and (c>0),'rows and columns must be > 0');
  assert( (r*c) = high(values)+1,'Incompatible dimensions ');
  frows := r;
  fcols := c;
  fdata := copy(Values,0,high(values)+1);
  fLUFactored := False;
end;

function TVMobjZ.writeMatrix: TStringList;
const
  fieldwidth = 22;
var
   i,j,k,l: integer;
   s,t : String;
   v : TComplex16;
begin
  result:= TStringList.create;
  for i:=0 to rows-1 do begin // row by row
    s := '    ['+chr(9);
    for j:=0 to cols-1 do begin
      v := FData[i*cols+j];
      t := floatToStrf(v.re,fffixed,10,3);
      if v.im >= 0 then
        t := t + '+' + floatToStrf(v.im,fffixed,10,3) + 'i'
      else
        t := t + '-' + floatToStrf(abs(v.im),fffixed,10,3) + 'i';
      s := s + t;
      l := length(t);    // pad t to get constant length
     if l < fieldwidth then
      for k := 1 to fieldwidth-l do s := s +' ';
    end;
    s := s+']';
    result.add(s);
  end;
end;

procedure TVMobjZ.fillRandom;
//
// MKL's VSL RNG functions only generate real-valued distributions -
// there is no complex Gaussian generator. Because TComplex16 is laid
// out as two contiguous doubles (re, im), we reinterpret the complex
// buffer as a plain double array of twice the length and fill it with
// vdRngGaussian in a single call - this fills both the real and
// imaginary parts with independent N(0,1) samples.
//
{$IFDEF PUREPASCAL}
{ PUREPASCAL: see newVM.pas's fillRandom for the fixed-seed Box-Muller
  rationale (reseeding RandSeed to 777 every call, so two same-sized calls
  are bit-identical, matching the tested contract) - identical here, just
  writing straight into re/im pairs instead of a flat double array. }
var
  i : Integer;
  u1, u2 : Double;
begin
  RandSeed := 777;
  for i := 0 to high(fdata) do begin
    repeat
      u1 := Random;
    until u1 > 0;
    u2 := Random;
    fdata[i].re := Sqrt(-2*Ln(u1))*Cos(2*Pi*u2);
    fdata[i].im := Sqrt(-2*Ln(u1))*Sin(2*Pi*u2);
  end;
end;
{$ELSE}
const
  vslConst = 8388608;
  VSL_RNG_METHOD_GAUSSIAN_ICDF = 2;
var
  vsSTream : pointer;
  n : integer;
begin
  n := (high(fdata)+1)*2; //2 doubles per complex element
  vslNewStream(@vsStream,vslConst,777);
  vdRngGaussian(VSL_RNG_METHOD_GAUSSIAN_ICDF,vsStream,n,PDouble(@Fdata[0]),0,1);
  vsldeleteStream(@vsStream);
end;
{$ENDIF}

procedure TVMobjZ.Id;
const
  s : string = 'Routine Id :';
{$IFNDEF HAVE_LAPACKE}
var
  i, j : TDimZ;
begin
  assert(cols=rows,s +'Matrix A must be square');
  for i := 0 to rows-1 do
    for j := 0 to cols-1 do
      if i = j then fdata[calcoffsetZ(i,j,cols)] := Cplx(1,0)
      else fdata[calcoffsetZ(i,j,cols)] := Cplx(0,0);
end;
{$ELSE}
var
  zero, one : TComplex16;
begin
  //Check dimensions of matrices are compatible. A must be square
  assert(cols=rows,s +'Matrix A must be square');
  zero := Cplx(0,0);
  one  := Cplx(1,0);
  lapacke_zlaset(CBlasRowMajor,'A',rows,cols,zero,one,@Fdata[0],rows);
end;
{$ENDIF}

procedure TVMobjZ.linspace(Start, increment: TComplex16);
const
  s : String ='routine linspace';
var
  i : integer;
begin
  assert(fdata <>nil,s+  ': MVObj Not Initialized');
  //IPP has no complex VectorSlope (ippsVectorSlope_64fc isn't exported by
  //libipps - only the real forms are), so build the arithmetic sequence
  //directly: FData[i] = Start + i*increment.
  for i := 0 to high(fdata) do
    FData[i] := Cplx(start.re + i*increment.re, start.im + i*increment.im);
end;

function TVMobjZ.Transpose:TVMObjZ;
var
  temp : TDimZ;
{$IFDEF PUREPASCAL}
var
  i, j : TDimZ;
begin
  result := TVMObjZ.Create(cols, rows);
  for i := 0 to rows-1 do
    for j := 0 to cols-1 do
      result.fdata[calcoffsetZ(j,i,result.fcols)] := fdata[calcoffsetZ(i,j,cols)];
end;
{$ELSE}
begin
  result := copyobjZ(self);
  MKL_Zimatcopy('R','T',rows,cols,Cplx(1,0),@result.FData[0],cols,rows);
//swap row and column numbers
  temp := self.rows;
  result.frows := self.cols;
  result.fcols := temp;
end;
{$ENDIF}

function MatMultZ(const A, B: TVMObjZ): TVMobjZ;
const
  s : String = 'Routine MatMultZ :';
var
  m,n,k : integer;
  C : TVMObjZ;
  alpha, beta : TComplex16;
{$IFDEF PUREPASCAL_BLAS}
var
  ii, jj, kk : integer;
  sum : TComplex16;
begin
  m := A.Rows;
  n := B.Cols;
  k := A.Cols;
  assert(A.cols = B.rows,s+'columns of first matrix must equal rows of second');
  c := TVMObjZ.Create(m,n);
  for ii := 0 to m-1 do
    for jj := 0 to n-1 do begin
      sum := Cplx(0,0);
      for kk := 0 to k-1 do
        sum := CAddZ(sum, CMulZ(A.fdata[calcoffsetZ(ii,kk,k)], B.fdata[calcoffsetZ(kk,jj,n)]));
      C.fdata[calcoffsetZ(ii,jj,n)] := sum;
    end;
  result := C;
end;
{$ELSE}
begin
  m := A.Rows;
  n := B.Cols;
  k := A.Cols;
  //Check for compatibility of matrices
  assert(A.cols = B.rows,s+'columns of first matrix must equal rows of second');
  c := TVMObjZ.Create(m,n);
  alpha := Cplx(1,0);
  beta  := Cplx(1,0);
  cblas_zgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans,
              m,n,k, { m, n, k }
              @alpha,  { alpha - by pointer, per CBLAS complex convention }
                @A.FData[0], k,
                @B.Fdata[0], n,
              @beta, {beta}
                @C.Fdata[0],n
             );
    result := C;
end;
{$ENDIF}

function LinearSolveZ(var A, B: TVMObjZ):integer;
const
  s : String = 'Function LinearSolveZ : ';
{ Direct linear solve for matrix A and Vectors B. On the first call for a
  given A, this LU-factorises A in place and solves for B via the combined
  LAPACKE_zgesv, caching the pivot indices on A and setting A.LU := True.
  A subsequent call against the same (already-factorised) A skips
  re-factorisation and reuses the cached LU factors/pivots via the cheaper
  LAPACKE_zgetrs (solve only) - much less work when the same A is solved
  against several different B's in turn. On return, A holds its LU-factored
  form (not the original matrix) and the solution is in B. Returns info
  from the underlying LAPACKE call.

  Deliberately has NO HAVE_ACCELERATE branch, unlike InvertZ/DetZ below -
  see cblas.pas's comment next to accel_zgetrf_/accel_zgetri_ for why:
  Accelerate's zgetrs_ (the solve step this would need) crashes with an
  access violation whenever the factored matrix has an exactly-zero-
  imaginary-part pivot, confirmed via a standalone reproduction outside
  this codebase. This stays on PurePascalLUZ/PurePascalLUSolveZ
  unconditionally until that's resolved. }
{$IFNDEF HAVE_LAPACKE}
begin
  assert(A.Cols = A.Rows,s+'Matrix A must be square');
  assert(A.Rows = B.Rows, s+'Matrix A and B have incompatible dimensions');
  if not A.LU then begin
    setlength(A.fIpiv,A.rows);
    PurePascalLUZ(@A.FData[0], A.rows, A.fIpiv);
    A.fLUFactored := True;
  end;
  PurePascalLUSolveZ(@A.FData[0], A.rows, A.fIpiv, @B.FData[0], B.cols);
  result := 0;
end;
{$ELSE}
begin
  assert(A.Cols = A.Rows,s+'Matrix A must be square');
  assert(A.Rows = B.Rows, s+'Matrix A and B have incompatible dimensions');
  if A.LU then
    result := lapacke_zgetrs(CBlasRowMajor,'N',A.rows,B.cols,@A.Fdata[0],A.cols,@A.fIpiv[0],@B.FData[0],B.cols)
  else begin
    setlength(A.fIpiv,A.rows);
    result := lapacke_zgesv(CBlasRowMajor,A.rows,B.cols,@A.Fdata[0],A.cols,@A.fIpiv[0],@B.FData[0],B.cols);
    if result = 0 then A.fLUFactored := True;
  end;
end;
{$ENDIF}

function CopyObjZ(const A: TVMObjZ): TVMobjZ;
begin
  result := TVMObjZ.Create(A.rows,A.cols);
{ See newVM.pas's CopyObj - a whole-buffer copy needs no strides, so a
  flat cblas_zcopy suffices; gated on PUREPASCAL_BLAS rather than
  PUREPASCAL since it never genuinely needed real LAPACK. }
{$IFDEF PUREPASCAL_BLAS}
  Move(A.fdata[0], result.fdata[0], A.rows*A.cols*SizeOf(TComplex16));
{$ELSE}
  cblas_zcopy(A.rows*A.cols, @A.FData[0], 1, @result.FData[0], 1);
{$ENDIF}
end;

function InvertZ(const A: TVMobjZ): TVMobjZ;
const
  s : String = 'Function InvertZ : ';
var
  ipiv : array of integer;
  info : integer;
{ Matrix inverse via LAPACKE_zgetrf (LU factorisation) followed by
  LAPACKE_zgetri (inverse from the LU factors), on a CopyObjZ scratch
  buffer - both LAPACKE calls overwrite their input matrix in place,
  so A itself is left untouched. }
{$IFNDEF HAVE_LAPACKE}
  {$IFDEF HAVE_ACCELERATE}
{ Accelerate-backed: raw Fortran zgetrf_/zgetri_ (see cblas.pas) - no
  LAPACKE row-major wrapper available. Matrix inversion is transpose-
  symmetric ((A^T)^-1 = (A^-1)^T - REGULAR transpose, not conjugate
  transpose, since this is purely a memory-layout reinterpretation with
  no complex arithmetic of its own involved) exactly as newVM.pas's
  Invert relies on, so reinterpreting A's row-major buffer as
  column-major and running the column-major factor+invert directly on it
  - no transposing needed - leaves the buffer holding, when read back as
  row-major, exactly inv(A). Confirmed against known values (including a
  deliberately non-Hermitian matrix, to rule out any conjugate-transpose
  mixup) before wiring this in - unlike LinearSolveZ, zgetrf_/zgetri_
  were verified with no crash even at exactly-zero-imaginary-part
  entries, so this one's safe. }
var
  n, lwork : integer;
  work : array of TComplex16;
  workquery : array[0..0] of TComplex16;
begin
  assert(A.Cols = A.Rows, s+'Matrix A must be square');
  result := CopyObjZ(A);
  setlength(ipiv, A.rows);
  n := A.rows;
  accel_zgetrf_(@n, @n, @result.FData[0], @n, @ipiv[0], @info);
  assert(info = 0, s+'zgetrf_ failed (singular matrix?), info='+IntToStr(info));
  lwork := -1;
  accel_zgetri_(@n, @result.FData[0], @n, @ipiv[0], @workquery[0], @lwork, @info);
  lwork := Trunc(workquery[0].re);
  if lwork < 1 then lwork := 1;
  setlength(work, lwork);
  accel_zgetri_(@n, @result.FData[0], @n, @ipiv[0], @work[0], @lwork, @info);
  assert(info = 0, s+'zgetri_ failed (singular matrix?), info='+IntToStr(info));
end;
  {$ELSE}
var
  identity : TVMobjZ;
  kk : Integer;
begin
  assert(A.Cols = A.Rows, s+'Matrix A must be square');
  result := CopyObjZ(A);
  setlength(ipiv, A.rows);
  info := PurePascalLUZ(@result.FData[0], A.rows, ipiv);
  assert(info = 0, s+'matrix is singular, first zero pivot at row='+IntToStr(info));
  identity := TVMobjZ.Create(A.rows, A.rows);
  for kk := 0 to A.rows-1 do identity[kk,kk] := Cplx(1,0);
  PurePascalLUSolveZ(@result.FData[0], A.rows, ipiv, @identity.FData[0], A.rows);
  result := identity;
end;
  {$ENDIF}
{$ELSE}
begin
  assert(A.Cols = A.Rows, s+'Matrix A must be square');
  result := CopyObjZ(A);
  setlength(ipiv, A.rows);
  info := lapacke_zgetrf(CBlasRowMajor, A.rows, A.cols, @result.Fdata[0], A.cols, @ipiv[0]);
  assert(info = 0, s+'LAPACKE_zgetrf failed (singular matrix?), info='+IntToStr(info));
  info := lapacke_zgetri(CBlasRowMajor, A.rows, @result.Fdata[0], A.cols, @ipiv[0]);
  assert(info = 0, s+'LAPACKE_zgetri failed (singular matrix?), info='+IntToStr(info));
end;
{$ENDIF}

function KronZ(const A, B: TVMobjZ): TVMobjZ;
var
  i, j, k, rowdest, coldest : integer;
  aval : TComplex16;
{$IFDEF PUREPASCAL_BLAS}
var
  l : integer;
begin
  result := TVMobjZ.Create(A.Rows*B.Rows, A.Cols*B.Cols);
  for i := 0 to A.Rows-1 do
    for j := 0 to A.Cols-1 do begin
      aval := A[i,j];
      for k := 0 to B.Rows-1 do begin
        rowdest := i*B.Rows + k;
        coldest := j*B.Cols;
        for l := 0 to B.Cols-1 do
          result.fdata[calcoffsetZ(rowdest,coldest+l,result.Cols)] := CMulZ(aval, B.fdata[calcoffsetZ(k,l,B.Cols)]);
      end;
    end;
end;
{$ELSE}
begin
  result := TVMobjZ.Create(A.Rows*B.Rows, A.Cols*B.Cols);
  for i := 0 to A.Rows-1 do
    for j := 0 to A.Cols-1 do begin
      aval := A[i,j];
      for k := 0 to B.Rows-1 do begin
        rowdest := i*B.Rows + k;
        coldest := j*B.Cols;
        cblas_zaxpy(B.Cols, @aval, @B.FData[k*B.Cols], 1, @result.FData[rowdest*result.Cols + coldest], 1);
      end;
    end;
end;
{$ENDIF}

function DiagZ(const A: TVMobjZ): TVMobjZ;
const
  s : String = 'Function DiagZ : ';
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
begin
  assert(A.Cols = 1, s+'A must be a column vector (n,1)');
  result := TVMobjZ.Create(A.Rows, A.Rows);
  for i := 0 to A.Rows-1 do
    result.fdata[calcoffsetZ(i,i,A.Rows)] := A.fdata[i];
end;
{$ELSE}
begin
  assert(A.Cols = 1, s+'A must be a column vector (n,1)');
  result := TVMobjZ.Create(A.Rows, A.Rows);
  cblas_zcopy(A.Rows, @A.FData[0], 1, @result.FData[0], A.Rows+1);
end;
{$ENDIF}

function NormZ(const A: TVMobjZ): Double;
const
  s : String = 'Function NormZ : ';
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
  sumsq : Double;
begin
  assert((A.Rows=1) or (A.Cols=1), s+'A must be a vector (Rows=1 or Cols=1)');
  sumsq := 0;
  for i := 0 to A.Rows*A.Cols-1 do
    sumsq := sumsq + CAbsSqZ(A.fdata[i]);
  result := Sqrt(sumsq);
end;
{$ELSE}
begin
  assert((A.Rows=1) or (A.Cols=1), s+'A must be a vector (Rows=1 or Cols=1)');
  result := cblas_dznrm2(A.Rows*A.Cols, @A.FData[0], 1);
end;
{$ENDIF}

function TraceZ(const A: TVMobjZ): TComplex16;
const
  s : String = 'Function TraceZ : ';
var
  i : integer;
begin
  assert(A.Rows = A.Cols, s+'Matrix A must be square');
  result.re := 0;
  result.im := 0;
  for i := 0 to A.Rows-1 do begin
    result.re := result.re + A[i,i].re;
    result.im := result.im + A[i,i].im;
  end;
end;

function DetZ(const A: TVMobjZ): TComplex16;
const
  s : String = 'Function DetZ : ';
var
  ipiv : array of integer;
  info, i, sign : integer;
  scratch : TVMobjZ;
  d : TComplex16;
{$IFNDEF HAVE_LAPACKE}
  {$IFDEF HAVE_ACCELERATE}
var
  n : integer;
  {$ENDIF}
{$ENDIF}
begin
  assert(A.Cols = A.Rows, s+'Matrix A must be square');
  scratch := CopyObjZ(A);
  setlength(ipiv, A.rows);
{$IFNDEF HAVE_LAPACKE}
  {$IFDEF HAVE_ACCELERATE}
  { See newVM.pas's Det / InvertZ above for the transpose-invariance
    rationale (det(A)=det(A^T), regular transpose) - identical here,
    just complex/zgetrf_-typed. }
  n := A.rows;
  accel_zgetrf_(@n, @n, @scratch.FData[0], @n, @ipiv[0], @info);
  {$ELSE}
  info := PurePascalLUZ(@scratch.FData[0], A.rows, ipiv);
  {$ENDIF}
{$ELSE}
  info := lapacke_zgetrf(CBlasRowMajor, A.rows, A.cols, @scratch.Fdata[0], A.cols, @ipiv[0]);
  assert(info >= 0, s+'LAPACKE_zgetrf reported an illegal argument, info='+IntToStr(info));
{$ENDIF}
  sign := 1;
  for i := 0 to A.rows-1 do
    if ipiv[i] <> i+1 then sign := -sign;
  result := Cplx(sign, 0);
  for i := 0 to A.rows-1 do begin
    d := scratch[i,i];
    result := Cplx(result.re*d.re - result.im*d.im, result.re*d.im + result.im*d.re);
  end;
end;

function FlipUDZ(const A: TVMobjZ): TVMobjZ;
var
  i : integer;
begin
  result := TVMobjZ.Create(A.Rows, A.Cols);
{$IFDEF PUREPASCAL_BLAS}
  for i := 0 to A.Rows-1 do
    Move(A.FData[i*A.Cols], result.FData[(A.Rows-1-i)*A.Cols], A.Cols*SizeOf(TComplex16));
{$ELSE}
  for i := 0 to A.Rows-1 do
    cblas_zcopy(A.Cols, @A.FData[i*A.Cols], 1, @result.FData[(A.Rows-1-i)*A.Cols], 1);
{$ENDIF}
end;

function FlipLRZ(const A: TVMobjZ): TVMobjZ;
var
  i : integer;
{$IFDEF PUREPASCAL}
var
  j : integer;
begin
  result := TVMobjZ.Create(A.Rows, A.Cols);
  for i := 0 to A.Rows-1 do
    for j := 0 to A.Cols-1 do
      result.FData[i*A.Cols+j] := A.FData[i*A.Cols + (A.Cols-1-j)];
end;
{$ELSE}
begin
  result := TVMobjZ.Create(A.Rows, A.Cols);
  for i := 0 to A.Rows-1 do
    ippsFlip_64fc(@A.FData[i*A.Cols], @result.FData[i*A.Cols], A.Cols);
end;
{$ENDIF}

function MergeUDZ(const A, B: TVMobjZ): TVMobjZ;
const
  s : String = 'Function MergeUDZ : ';
begin
  assert(A.Cols = B.Cols, s+'A and B must have the same number of columns');
  result := TVMobjZ.Create(A.Rows+B.Rows, A.Cols);
{$IFDEF PUREPASCAL_BLAS}
  Move(A.FData[0], result.FData[0], A.Rows*A.Cols*SizeOf(TComplex16));
  Move(B.FData[0], result.FData[A.Rows*A.Cols], B.Rows*B.Cols*SizeOf(TComplex16));
{$ELSE}
  cblas_zcopy(A.Rows*A.Cols, @A.FData[0], 1, @result.FData[0], 1);
  cblas_zcopy(B.Rows*B.Cols, @B.FData[0], 1, @result.FData[A.Rows*A.Cols], 1);
{$ENDIF}
end;

function MergeLRZ(const A, B: TVMobjZ): TVMobjZ;
const
  s : String = 'Function MergeLRZ : ';
var
  i : integer;
begin
  assert(A.Rows = B.Rows, s+'A and B must have the same number of rows');
  result := TVMobjZ.Create(A.Rows, A.Cols+B.Cols);
  for i := 0 to A.Rows-1 do begin
{$IFDEF PUREPASCAL_BLAS}
    Move(A.FData[i*A.Cols], result.FData[i*result.Cols], A.Cols*SizeOf(TComplex16));
    Move(B.FData[i*B.Cols], result.FData[i*result.Cols + A.Cols], B.Cols*SizeOf(TComplex16));
{$ELSE}
    cblas_zcopy(A.Cols, @A.FData[i*A.Cols], 1, @result.FData[i*result.Cols], 1);
    cblas_zcopy(B.Cols, @B.FData[i*B.Cols], 1, @result.FData[i*result.Cols + A.Cols], 1);
{$ENDIF}
  end;
end;

function ReshapeZ(const A: TVMobjZ; NewRows, NewCols: TDimZ): TVMobjZ;
const
  s : String = 'Function ReshapeZ : ';
begin
  assert(NewRows*NewCols = A.Rows*A.Cols, s+'NewRows*NewCols must equal A.Rows*A.Cols');
  result := TVMobjZ.Create(NewRows, NewCols);
{$IFDEF PUREPASCAL_BLAS}
  Move(A.FData[0], result.FData[0], A.Rows*A.Cols*SizeOf(TComplex16));
{$ELSE}
  cblas_zcopy(A.Rows*A.Cols, @A.FData[0], 1, @result.FData[0], 1);
{$ENDIF}
end;

function RepmatZ(const A: TVMobjZ; RowReps, ColReps: Integer): TVMobjZ;
const
  s : String = 'Function RepmatZ : ';
var
  i, j, r, destRow : integer;
begin
  assert((RowReps > 0) and (ColReps > 0), s+'RowReps and ColReps must be > 0');
  result := TVMobjZ.Create(A.Rows*RowReps, A.Cols*ColReps);
  for i := 0 to RowReps-1 do
    for r := 0 to A.Rows-1 do begin
      destRow := i*A.Rows + r;
      for j := 0 to ColReps-1 do
{$IFDEF PUREPASCAL_BLAS}
        Move(A.FData[r*A.Cols], result.FData[destRow*result.Cols + j*A.Cols], A.Cols*SizeOf(TComplex16));
{$ELSE}
        cblas_zcopy(A.Cols, @A.FData[r*A.Cols], 1, @result.FData[destRow*result.Cols + j*A.Cols], 1);
{$ENDIF}
    end;
end;

function AddScalarZ(const A: TVMobjZ; K: TComplex16): TVMobjZ;
{$IFDEF PUREPASCAL}
var
  i : Integer;
begin
  result := CopyObjZ(A);
  for i := 0 to A.Rows*A.Cols-1 do
    result.fdata[i] := CAddZ(result.fdata[i], K);
end;
{$ELSE}
begin
  result := CopyObjZ(A);
  ippsAddC_64fc_I(K, @result.FData[0], A.Rows*A.Cols);
end;
{$ENDIF}

function AddScalarZ(const A: TVMobjZ; K: Double): TVMobjZ;
begin
  result := AddScalarZ(A, Cplx(K, 0));
end;

function SubMatrixZ(const A: TVMobjZ; R0, C0, RCount, CCount: TDimZ): TVMobjZ;
const
  s : String = 'Function SubMatrixZ : ';
var
  i : Integer;
{ See newVM.pas's SubMatrix - a strided sub-rectangle copy only ever
  needed a per-row cblas_zcopy loop, not LAPACKE_zlacpy specifically, so
  this is gated on PUREPASCAL_BLAS too. }
begin
  assert((R0+RCount <= A.Rows) and (C0+CCount <= A.Cols), s+'submatrix (R0,C0,RCount,CCount) extends beyond A''s bounds');
  result := TVMobjZ.Create(RCount, CCount);
{$IFDEF PUREPASCAL_BLAS}
  for i := 0 to RCount-1 do
    Move(A.FData[(R0+i)*A.Cols+C0], result.FData[i*CCount], CCount*SizeOf(TComplex16));
{$ELSE}
  for i := 0 to RCount-1 do
    cblas_zcopy(CCount, @A.FData[(R0+i)*A.Cols+C0], 1, @result.FData[i*CCount], 1);
{$ENDIF}
end;

function RealToComplex(const A: TVMobj): TVMobjZ;
const
  s : String = 'Routine RealToComplex : ';
var
  n : integer;
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
begin
  n := A.Rows * A.Cols;
  result := TVMObjZ.Create(A.Rows, A.Cols);  //zero-fills both re and im
  for i := 0 to n-1 do
    result.fdata[i].re := A.DataPtr[i];
end;
{$ELSE}
begin
  //A is a real double TVMobj (from newVM.pas); result is the same
  //dimensions as a complex TVMobjZ with imaginary parts all zero.
  n := A.Rows * A.Cols;
  result := TVMObjZ.Create(A.Rows, A.Cols);  //zero-fills both re and im
  //TComplex16 = {re,im: Double} packed as two contiguous doubles per
  //element, so result.FData viewed as a flat double array has real
  //parts at even offsets (0,2,4,...) and imaginary parts at odd offsets.
  //cblas_dcopy with a destination stride of 2 writes only into the real
  //slots; the imaginary slots are left at the zero the constructor set.
  //A.DataPtr (public accessor added to TVMobj) supplies the source
  //buffer without needing friend access to newVM's private fields.
  cblas_dcopy(n, A.DataPtr, 1, PDouble(@result.FData[0]), 2);
end;
{$ENDIF}

function GetRealPart(const A: TVMobjZ): TVMobj;
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
begin
  result := TVMobj.Create(A.rows, A.cols);
  for i := 0 to A.rows*A.cols-1 do
    result.DataPtr[i] := A.fdata[i].re;
end;
{$ELSE}
begin
  //A.FData, viewed as a flat double array, has real parts at even
  //offsets (0,2,4,...). cblas_dcopy with a source stride of 2, starting
  //at offset 0, pulls out every real component into a contiguous,
  //ordinary TVMobj buffer (destination stride 1) - no per-element loop.
  result := TVMobj.Create(A.rows, A.cols);
  cblas_dcopy(A.rows*A.cols, PDouble(@A.FData[0]), 2, result.DataPtr, 1);
end;
{$ENDIF}

function GetImagPart(const A: TVMobjZ): TVMobj;
var
  pIm : PDouble;
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
begin
  result := TVMobj.Create(A.rows, A.cols);
  for i := 0 to A.rows*A.cols-1 do
    result.DataPtr[i] := A.fdata[i].im;
end;
{$ELSE}
begin
  //Same trick as GetRealPart, but starting one double further in, so
  //the stride-2 walk lands on the imaginary slots (offsets 1,3,5,...)
  //instead of the real ones.
  result := TVMobj.Create(A.rows, A.cols);
  pIm := PDouble(@A.FData[0]);
  inc(pIm);                              //step over the first real slot
  cblas_dcopy(A.rows*A.cols, pIm, 2, result.DataPtr, 1);
end;
{$ENDIF}

procedure SplitComplex(const A: TVMobjZ; out RealPart, ImagPart: TVMobj);
begin
  //Convenience wrapper: two independent MKL dcopy calls, one per part.
  RealPart := GetRealPart(A);
  ImagPart := GetImagPart(A);
end;

{$IFDEF PUREPASCAL}
{ ============================================================================
  PurePascal general eigenvalue decomposition - ported from LMath
  (LMath/ULineAlgebra/ubalance.pas, uelmhes.pas, ueltran.pas, uhqr2.pas,
  ubalbak.pas), itself a translation of the classic EISPACK Balance/Elmhes/Eltran/Hqr2/Balbak
  pipeline - the same algorithm family LAPACK's dgeev descends from, and the
  library-backed path above already uses.

  Ported as close to line-for-line as practical, INCLUDING LMath's own
  goto-based control flow in PPHqr2 ("a crude translation, many gotos kept"
  per that unit's own comment) - restructuring a 400-line QR-iteration
  routine into structured control flow would risk introducing a subtle bug
  for no real benefit, so it's kept exactly that shape here. Runs on local
  1-based-usable scratch arrays (index 0 unused - TPPMatrix/TPPVector/
  TPPIntVector below), matching LMath's own Lb=1 convention, rather than
  newVM's usual 0-based indexing; only PurePascalEigHqr2 itself converts
  between this and the 0-based row-major Double buffers EigDecompose works
  with, at the very start and very end.

  Five stages, run in sequence exactly as LMath's own EigenVect does:
    1. PPBalance - isolates/scales eigenvalues to improve numerical accuracy
    2. PPElmHes  - reduces to upper Hessenberg form via elementary similarity transforms
    3. PPEltran  - accumulates the transformations from step 2 into Z
    4. PPHqr2    - QR algorithm: eigenvalues AND eigenvectors of the Hessenberg matrix
    5. PPBalBak  - back-transforms the eigenvectors through the balancing from step 1

  PPHqr2 returns 0 on success, or -j (matching EISPACK's own convention) if
  the 30*N-iteration convergence limit was hit while seeking the j-th
  eigenvalue - PurePascalEigHqr2 propagates this up unchanged, and
  EigDecompose's PUREPASCAL branch asserts on it exactly like the
  LAPACKE_dgeev branch asserts on a non-zero info.

  LMath's Hqr2 documents its eigenvectors as unnormalised; LAPACKE_dgeev's
  are unit-Euclidean-norm (see EigDecompose's own header comment above), so
  PurePascalEigHqr2 normalises each eigenvector (real column, or the two
  columns of a complex-conjugate pair together) to unit norm before
  returning - done here, on the packed real/imaginary column-pair form,
  rather than after EigDecompose's own unpacking loop below, so that
  unpacking loop stays identical and correct for both branches.
  ============================================================================ }

type
  TPPVector    = array of Double;
  TPPIntVector = array of Integer;
  TPPMatrix    = array of TPPVector;
  TPPComplex   = array of TComplex16;   //1-based-usable, .re/.im per LMath's Lambda[I].X/.Y

function PPDSgn(A, B: Double): Double; inline;
begin
  if B < 0 then result := -Abs(A) else result := Abs(A);
end;

function PPMinI(A, B: Integer): Integer; inline;
begin
  if A <= B then result := A else result := B;
end;

function PPMaxD(A, B: Double): Double; inline;
begin
  if A >= B then result := A else result := B;
end;

// Ported from LMath's ubalance.pas (EISPACK Balanc) - balances A in place
// and isolates eigenvalues whenever possible; see that unit's own header
// comment for the full I_low/I_igh/Scale contract.
procedure PPBalance(A: TPPMatrix; Lb, Ub: Integer; out I_low, I_igh: Integer; Scale: TPPVector);
const
  RADIX = 2;
var
  I, J, M           : Integer;
  C, F, G, R, S, B2 : Double;
  Flag, Found, Conv : Boolean;

  procedure Exchange;
  var
    I : Integer;
  begin
    Scale[M] := J;
    if J = M then Exit;
    for I := Lb to I_igh do begin
      F := A[I,J]; A[I,J] := A[I,M]; A[I,M] := F;
    end;
    for I := I_low to Ub do begin
      F := A[J,I]; A[J,I] := A[M,I]; A[M,I] := F;
    end;
  end;

begin
  B2 := RADIX * RADIX;
  I_low := Lb;
  I_igh := Ub;

  repeat
    J := I_igh;
    repeat
      I := Lb;
      repeat
        Flag := (I <> J) and (A[J,I] <> 0.0);
        I := I + 1;
      until Flag or (I > I_igh);
      Found := not Flag;
      if Found then begin
        M := I_igh;
        Exchange;
        I_igh := I_igh - 1;
      end;
      J := J - 1;
    until Found or (J < Lb);
  until (not Found) or (I_igh < Lb);

  if I_igh < Lb then I_igh := Lb;
  if I_igh = Lb then Exit;

  repeat
    J := I_low;
    repeat
      I := I_low;
      repeat
        Flag := (I <> J) and (A[I,J] <> 0.0);
        I := I + 1;
      until Flag or (I > I_igh);
      Found := not Flag;
      if Found then begin
        M := I_low;
        Exchange;
        I_low := I_low + 1;
      end;
      J := J + 1;
    until Found or (J > I_igh);
  until (not Found);

  for I := I_low to I_igh do Scale[I] := 1.0;

  repeat
    Conv := True;
    for I := I_low to I_igh do begin
      C := 0.0; R := 0.0;
      for J := I_low to I_igh do
        if J <> I then begin
          C := C + Abs(A[J,I]);
          R := R + Abs(A[I,J]);
        end;
      if (C <> 0.0) and (R <> 0.0) then begin
        G := R / RADIX;
        F := 1.0;
        S := C + R;
        while C < G do begin F := F * RADIX; C := C * B2; end;
        G := R * RADIX;
        while C >= G do begin F := F / RADIX; C := C / B2; end;
        if (C + R) / F < 0.95 * S then begin
          G := 1.0 / F;
          Scale[I] := Scale[I] * F;
          Conv := False;
          for J := I_low to Ub do A[I,J] := A[I,J] * G;
          for J := Lb to I_igh do A[J,I] := A[J,I] * F;
        end;
      end;
    end;
  until Conv;
end;

// Ported from LMath's uelmhes.pas (EISPACK Elmhes) - reduces A[I_low..I_igh]
// to upper Hessenberg form by stabilised elementary similarity transforms.
procedure PPElmHes(A: TPPMatrix; Lb, Ub, I_low, I_igh: Integer; I_int: TPPIntVector);
var
  I, J, M, La, Kp1, Mm1, Mp1 : Integer;
  X, Y                       : Double;
begin
  La := I_igh - 1;
  Kp1 := I_low + 1;
  if La < Kp1 then Exit;

  for M := Kp1 to La do begin
    Mm1 := M - 1;
    X := 0.0;
    I := M;
    for J := M to I_igh do
      if Abs(A[J,Mm1]) > Abs(X) then begin
        X := A[J,Mm1];
        I := J;
      end;
    I_int[M] := I;
    if I <> M then begin
      for J := Mm1 to Ub do begin
        Y := A[I,J]; A[I,J] := A[M,J]; A[M,J] := Y;
      end;
      for J := Lb to I_igh do begin
        Y := A[J,I]; A[J,I] := A[J,M]; A[J,M] := Y;
      end;
    end;
    if X <> 0.0 then begin
      Mp1 := M + 1;
      for I := Mp1 to I_igh do begin
        Y := A[I,Mm1];
        if Y <> 0.0 then begin
          Y := Y / X;
          A[I,Mm1] := Y;
          for J := M to Ub do A[I,J] := A[I,J] - Y * A[M,J];
          for J := Lb to I_igh do A[J,M] := A[J,M] + Y * A[J,I];
        end;
      end;
    end;
  end;
end;

// Ported from LMath's ueltran.pas (EISPACK Eltran) - accumulates the
// similarity transforms PPElmHes used, into Z (initialised to identity).
procedure PPEltran(A: TPPMatrix; Lb, Ub, I_low, I_igh: Integer; I_int: TPPIntVector; Z: TPPMatrix);
var
  I, J, Mp, Mp1 : Integer;
begin
  for I := Lb to Ub do
    for J := Lb to Ub do
      if I = J then Z[I,J] := 1.0 else Z[I,J] := 0.0;

  if I_igh < I_low then Exit;

  for Mp := I_igh - 1 downto I_low + 1 do begin
    Mp1 := Mp + 1;
    for I := Mp1 to I_igh do Z[I,Mp] := A[I,Mp - 1];
    I := I_int[Mp];
    if I <> Mp then begin
      for J := Mp to I_igh do begin
        Z[Mp,J] := Z[I,J];
        Z[I,J] := 0.0;
      end;
      Z[I,Mp] := 1.0;
    end;
  end;
end;

// Ported from LMath's uhqr2.pas (EISPACK Hqr2) - eigenvalues AND
// (unnormalised) eigenvectors of the upper Hessenberg matrix H, via the QR
// algorithm; Z must hold the identity-seeded PPEltran output on entry, and
// holds the eigenvectors (packed real/imaginary column-pair form - see
// PurePascalEigHqr2's own header comment) on return. Returns 0 on success,
// or -j if 30*N iterations were exhausted seeking the j-th eigenvalue.
function PPHqr2(H: TPPMatrix; Lb, Ub, I_low, I_igh: Integer; Lambda: TPPComplex; Z: TPPMatrix): Integer;

  procedure Cdiv(Ar, Ai, Br, Bi : Double; var Cr, Ci : Double);
  var
    S, Ars, Ais, Brs, Bis : Double;
  begin
    S := Abs(Br) + Abs(Bi);
    Ars := Ar / S;
    Ais := Ai / S;
    Brs := Br / S;
    Bis := Bi / S;
    S := Sqr(Brs) + Sqr(Bis);
    Cr := (Ars * Brs + Ais * Bis) / S;
    Ci := (Ais * Brs - Ars * Bis) / S;
  end;

var
  I, J, K, L, M, N, En, Na, Itn, Its, Mp2, Enm2                : Integer;
  P, Q, R, S, T, W, X, Y, Ra, Sa, Vi, Vr, Zz, Norm, Tst1, Tst2 : Double;
  NotLas                                                       : Boolean;

label
  60, 70, 100, 130, 150, 170, 225, 260, 270, 280, 320, 330, 340,
  600, 630, 635, 640, 680, 700, 710, 770, 780, 790, 795, 800;

begin
  result := 0;

  K := Lb;
  Norm := 0.0;
  for I := Lb to Ub do begin
    for J := K to Ub do Norm := Norm + Abs(H[I,J]);
    K := I;
    if (I < I_low) or (I > I_igh) then begin
      Lambda[I].re := H[I,I];
      Lambda[I].im := 0.0;
    end;
  end;

  N := Ub - Lb + 1;
  Itn := 30 * N;
  En := I_igh;
  T := 0.0;

60:
  if En < I_low then goto 340;
  Its := 0;
  Na := En - 1;
  Enm2 := Na - 1;

70:
  for L := En downto I_low do begin
    if L = I_low then goto 100;
    S := Abs(H[L - 1,L - 1]) + Abs(H[L,L]);
    if S = 0.0 then S := Norm;
    Tst1 := S;
    Tst2 := Tst1 + Abs(H[L,L - 1]);
    if Tst2 = Tst1 then goto 100;
  end;

100:
  X := H[En,En];
  if L = En then goto 270;
  Y := H[Na,Na];
  W := H[En,Na] * H[Na,En];
  if L = Na then goto 280;

  if Itn = 0 then begin
    result := -En;
    Exit;
  end;

  if (Its <> 10) and (Its <> 20) then goto 130;

  T := T + X;
  for I := I_low to En do H[I,I] := H[I,I] - X;
  S := Abs(H[En,Na]) + Abs(H[Na,Enm2]);
  X := 0.75 * S;
  Y := X;
  W := - 0.4375 * S * S;

130:
  Its := Its + 1;
  Itn := Itn - 1;

  for M := Enm2 downto L do begin
    Zz := H[M,M];
    R := X - Zz;
    S := Y - Zz;
    P := (R * S - W) / H[M + 1,M] + H[M,M + 1];
    Q := H[M + 1,M + 1] - Zz - R - S;
    R := H[M + 2,M + 1];
    S := Abs(P) + Abs(Q) + Abs(R);
    P := P / S;
    Q := Q / S;
    R := R / S;
    if M = L then goto 150;
    Tst1 := Abs(P) * (Abs(H[M - 1,M - 1]) + Abs(Zz) + Abs(H[M + 1,M + 1]));
    Tst2 := Tst1 + Abs(H[M,M - 1]) * (Abs(Q) + Abs(R));
    if Tst2 = Tst1 then goto 150;
  end;

150:
  Mp2 := M + 2;
  for I := Mp2 to En do begin
    H[I,I - 2] := 0.0;
    if I <> Mp2 then H[I,I - 3] := 0.0;
  end;

  for K := M to Na do begin
    NotLas := (K <> Na);
    if (K = M) then goto 170;
    P := H[K,K - 1];
    Q := H[K + 1,K - 1];
    R := 0.0;
    if NotLas then R := H[K + 2,K - 1];
    X := Abs(P) + Abs(Q) + Abs(R);
    if X = 0.0 then goto 260;
    P := P / X;
    Q := Q / X;
    R := R / X;
170:S := PPDSgn(Sqrt(P * P + Q * Q + R * R), P);
    if K <> M then
      H[K,K - 1] := - S * X
    else if L <> M then
      H[K,K - 1] := - H[K,K - 1];
    P := P + S;
    X := P / S;
    Y := Q / S;
    Zz := R / S;
    Q := Q / P;
    R := R / P;
    if NotLas then goto 225;

    for J := K to Ub do begin
      P := H[K,J] + Q * H[K + 1,J];
      H[K,J] := H[K,J] - P * X;
      H[K + 1,J] := H[K + 1,J] - P * Y;
    end;

    J := PPMinI(En, K + 3);

    for I := Lb to J do begin
      P := X * H[I,K] + Y * H[I,K + 1];
      H[I,K] := H[I,K] - P;
      H[I,K + 1] := H[I,K + 1] - P * Q;
    end;

    for I := I_low to I_igh do begin
      P := X * Z[I,K] + Y * Z[I,K + 1];
      Z[I,K] := Z[I,K] - P;
      Z[I,K + 1] := Z[I,K + 1] - P * Q;
    end;
    goto 260;

225:
    for J := K to Ub do begin
      P := H[K,J] + Q * H[K + 1,J] + R * H[K + 2,J];
      H[K,J] := H[K,J] - P * X;
      H[K + 1,J] := H[K + 1,J] - P * Y;
      H[K + 2,J] := H[K + 2,J] - P * Zz;
    end;

    J := PPMinI(En, K + 3);

    for I := Lb to J do begin
      P := X * H[I,K] + Y * H[I,K + 1] + Zz * H[I,K + 2];
      H[I,K] := H[I,K] - P;
      H[I,K + 1] := H[I,K + 1] - P * Q;
      H[I,K + 2] := H[I,K + 2] - P * R;
    end;

    for I := I_low to I_igh do begin
      P := X * Z[I,K] + Y * Z[I,K + 1] + Zz * Z[I,K + 2];
      Z[I,K] := Z[I,K] - P;
      Z[I,K + 1] := Z[I,K + 1] - P * Q;
      Z[I,K + 2] := Z[I,K + 2] - P * R;
    end;

260: end;

  goto 70;

270:
  H[En,En] := X + T;
  Lambda[En].re := H[En,En];
  Lambda[En].im := 0.0;
  En := Na;
  goto 60;

280:
  P := 0.5 * (Y - X);
  Q := P * P + W;
  Zz := Sqrt(Abs(Q));
  H[En,En] := X + T;
  X := H[En,En];
  H[Na,Na] := Y + T;
  if Q < 0.0 then goto 320;

  Zz := P + PPDSgn(Zz, P);
  Lambda[Na].re := X + Zz;
  Lambda[En].re := Lambda[Na].re;
  if Zz <> 0.0 then Lambda[En].re := X - W / Zz;
  Lambda[Na].im := 0.0;
  Lambda[En].im := 0.0;
  X := H[En,Na];
  S := Abs(X) + Abs(Zz);
  P := X / S;
  Q := Zz / S;
  R := Sqrt(P * P + Q * Q);
  P := P / R;
  Q := Q / R;

  for J := Na to Ub do begin
    Zz := H[Na,J];
    H[Na,J] := Q * Zz + P * H[En,J];
    H[En,J] := Q * H[En,J] - P * Zz;
  end;

  for I := Lb to En do begin
    Zz := H[I,Na];
    H[I,Na] := Q * Zz + P * H[I,En];
    H[I,En] := Q * H[I,En] - P * Zz;
  end;

  for I := I_low to I_igh do begin
    Zz := Z[I,Na];
    Z[I,Na] := Q * Zz + P * Z[I,En];
    Z[I,En] := Q * Z[I,En] - P * Zz;
  end;

  goto 330;

320:
  Lambda[Na].re := X + P;
  Lambda[En].re := Lambda[Na].re;
  Lambda[Na].im := Zz;
  Lambda[En].im := - Zz;

330:
  En := Enm2;
  goto 60;

340:
  if Norm = 0.0 then Exit;

  for En := Ub downto Lb do begin
    P := Lambda[En].re;
    Q := Lambda[En].im;
    Na := En - 1;
    if Q < 0.0 then
      goto 710
    else if Q = 0.0 then
      goto 600
    else
      goto 800;

600:
    M := En;
    H[En,En] := 1.0;
    if Na < Lb then goto 800;

    for I := Na downto Lb do begin
      W := H[I,I] - P;
      R := 0.0;
      for J := M to En do R := R + H[I,J] * H[J,En];
      if Lambda[I].im >= 0.0 then goto 630;
      Zz := W;
      S := R;
      goto 700;
630:  M := I;
      if Lambda[I].im <> 0.0 then goto 640;
      T := W;
      if T <> 0.0 then goto 635;
      Tst1 := Norm;
      T := Tst1;
      repeat
        T := 0.01 * T;
        Tst2 := Norm + T;
      until Tst2 <= Tst1;
635:  H[I,En] := - R / T;
      goto 680;

640:
      X := H[I,I + 1];
      Y := H[I + 1,I];
      Q := Sqr(Lambda[I].re - P) + Sqr(Lambda[I].im);
      T := (X * S - Zz * R) / Q;
      H[I,En] := T;
      if Abs(X) > Abs(Zz) then
        H[I + 1,En] := (- R - W * T) / X
      else
        H[I + 1,En] := (- S - Y * T) / Zz;

680:
      T := Abs(H[I,En]);
      if T = 0.0 then goto 700;
      Tst1 := T;
      Tst2 := Tst1 + 1.0 / Tst1;
      if Tst2 > Tst1 then goto 700;
      for J := I to En do H[J,En] := H[J,En] / T;
700: end;
    goto 800;

710:
    M := Na;
    if Abs(H[En,Na]) > Abs(H[Na,En]) then begin
      H[Na,Na] := Q / H[En,Na];
      H[Na,En] := - (H[En,En] - P) / H[En,Na];
    end else
      Cdiv(0.0, - H[Na,En], H[Na,Na] - P, Q, H[Na,Na], H[Na,En]);

    H[En,Na] := 0.0;
    H[En,En] := 1.0;
    Enm2 := Na - 1;
    if Enm2 < Lb then goto 800;

    for I := Enm2 downto Lb do begin
      W := H[I,I] - P;
      Ra := 0.0;
      Sa := 0.0;
      for J := M to En do begin
        Ra := Ra + H[I,J] * H[J,Na];
        Sa := Sa + H[I,J] * H[J,En];
      end;
      if Lambda[I].im >= 0.0 then goto 770;
      Zz := W;
      R := Ra;
      S := Sa;
      goto 795;
770:  M := I;
      if Lambda[I].im <> 0.0 then goto 780;
      Cdiv(- Ra, - Sa, W, Q, H[I,Na], H[I,En]);
      goto 790;

780:
      X := H[I,I + 1];
      Y := H[I + 1,I];
      Vr := Sqr(Lambda[I].re - P) + Sqr(Lambda[I].im) - Sqr(Q);
      Vi := (Lambda[I].re - P) * 2.0 * Q;
      if (Vr = 0.0) and (Vi = 0.0) then begin
        Tst1 := Norm * (Abs(W) + Abs(Q) + Abs(X) + Abs(Y) + Abs(Zz));
        Vr := Tst1;
        repeat
          Vr := 0.01 * Vr;
          Tst2 := Tst1 + Vr;
        until Tst2 <= Tst1;
      end;
      Cdiv(X * R - Zz * Ra + Q * Sa, X * S - Zz * Sa - Q * Ra, Vr, Vi, H[I,Na], H[I,En]);
      if Abs(X) > Abs(Zz) + Abs(Q) then begin
        H[I + 1,Na] := (- Ra - W * H[I,Na] + Q * H[I,En]) / X;
        H[I + 1,En] := (- Sa - W * H[I,En] - Q * H[I,Na]) / X;
      end else
        Cdiv(- R - Y * H[I,Na], - S - Y * H[I,En], Zz, Q, H[I + 1,Na], H[I + 1,En]);

790:
      T := PPMaxD(Abs(H[I,Na]), Abs(H[I,En]));
      if T = 0.0 then goto 795;
      Tst1 := T;
      Tst2 := Tst1 + 1.0 / Tst1;
      if Tst2 > Tst1 then goto 795;
      for J := I to En do begin
        H[J,Na] := H[J,Na] / T;
        H[J,En] := H[J,En] / T;
      end;

795: end;
800: end;

  for I := Lb to Ub do
    if (I < I_low) or (I > I_igh) then
      for J := I to Ub do Z[I,J] := H[I,J];

  for J := Ub downto I_low do begin
    M := PPMinI(J, I_igh);
    for I := I_low to I_igh do begin
      Zz := 0.0;
      for K := I_low to M do Zz := Zz + Z[I,K] * H[K,J];
      Z[I,J] := Zz;
    end;
  end;

  result := 0;
end;

// Ported from LMath's ubalbak.pas (EISPACK Balbak) - back-transforms the
// eigenvectors in Z through the balancing PPBalance performed.
procedure PPBalBak(Z: TPPMatrix; Lb, Ub, I_low, I_igh: Integer; Scale: TPPVector; M: Integer);
var
  I, J, K : Integer;
  S       : Double;
begin
  if M < Lb then Exit;

  if I_igh <> I_low then
    for I := I_low to I_igh do begin
      S := Scale[I];
      for J := Lb to M do Z[I,J] := Z[I,J] * S;
    end;

  for I := (I_low - 1) downto Lb do begin
    K := Round(Scale[I]);
    if K <> I then
      for J := Lb to M do begin
        S := Z[I,J]; Z[I,J] := Z[K,J]; Z[K,J] := S;
      end;
  end;

  for I := (I_igh + 1) to Ub do begin
    K := Round(Scale[I]);
    if K <> I then
      for J := Lb to M do begin
        S := Z[I,J]; Z[I,J] := Z[K,J]; Z[K,J] := S;
      end;
  end;
end;

// Converts between EigDecompose's 0-based row-major Double buffers and the
// 1-based scratch arrays PPBalance..PPBalBak expect, runs the five stages
// in sequence, normalises the (LMath-documented-unnormalised) eigenvectors
// to unit Euclidean norm to match LAPACKE_dgeev's own contract, and returns
// PPHqr2's error code unchanged (0 = success).
function PurePascalEigHqr2(N: Integer; AData: PDouble; var Wr, Wi: TVector; var V: TVector): Integer;
var
  H, Z    : TPPMatrix;
  Scale   : TPPVector;
  I_int   : TPPIntVector;
  Lambda  : TPPComplex;
  I_low, I_igh, I, J, ErrCode : Integer;
  NormSq, Nrm : Double;
begin
  SetLength(H, N+1, N+1);
  SetLength(Z, N+1, N+1);
  SetLength(Scale, N+1);
  SetLength(I_int, N+1);
  SetLength(Lambda, N+1);

  for I := 0 to N-1 do
    for J := 0 to N-1 do
      H[I+1,J+1] := AData[I*N+J];

  PPBalance(H, 1, N, I_low, I_igh, Scale);
  PPElmHes(H, 1, N, I_low, I_igh, I_int);
  PPEltran(H, 1, N, I_low, I_igh, I_int, Z);
  ErrCode := PPHqr2(H, 1, N, I_low, I_igh, Lambda, Z);

  if ErrCode <> 0 then begin
    result := ErrCode;
    Exit;
  end;

  PPBalBak(Z, 1, N, I_low, I_igh, Scale, N);

  for I := 0 to N-1 do begin
    Wr[I] := Lambda[I+1].re;
    Wi[I] := Lambda[I+1].im;
  end;
  for I := 0 to N-1 do
    for J := 0 to N-1 do
      V[I*N+J] := Z[I+1,J+1];

  //--- normalise each eigenvector (real column, or a conjugate pair's two
  //    columns together) to unit Euclidean norm, matching LAPACKE_dgeev ---
  J := 0;
  while J <= N-1 do begin
    if Wi[J] = 0 then begin
      NormSq := 0;
      for I := 0 to N-1 do NormSq := NormSq + Sqr(V[I*N+J]);
      Nrm := Sqrt(NormSq);
      if Nrm > 0 then
        for I := 0 to N-1 do V[I*N+J] := V[I*N+J] / Nrm;
      inc(J);
    end else begin
      NormSq := 0;
      for I := 0 to N-1 do NormSq := NormSq + Sqr(V[I*N+J]) + Sqr(V[I*N+J+1]);
      Nrm := Sqrt(NormSq);
      if Nrm > 0 then
        for I := 0 to N-1 do begin
          V[I*N+J]   := V[I*N+J]   / Nrm;
          V[I*N+J+1] := V[I*N+J+1] / Nrm;
        end;
      inc(J,2);
    end;
  end;

  result := 0;
end;
{$ENDIF}

procedure EigDecompose(const A: TVMobj; out EigenValues, EigenVectors: TVMobjZ);
const
  s : String = 'Routine EigDecompose : ';
//
// General real nonsymmetric eigenvalue problem, via LAPACKE_dgeev.
// Even for a real A, eigenvalues/eigenvectors can be complex, occurring
// in conjugate pairs - hence the complex TVMobjZ outputs.
//
// EigenValues  : n x 1 TVMobjZ, one eigenvalue per row.
// EigenVectors : n x n TVMobjZ, right eigenvectors as columns (matching
//                the ordering of EigenValues), each normalised to unit
//                Euclidean norm by LAPACK.
//
// LAPACKE_dgeev returns eigenvectors in packed real form: if eigenvalue
// j is real, column j of the raw output IS the eigenvector; if
// eigenvalues j and j+1 are a complex-conjugate pair, column j holds
// the real part and column j+1 holds the imaginary part of both
// v(j) = col(j) + i*col(j+1) and v(j+1) = col(j) - i*col(j+1). This
// routine unpacks that convention into genuinely complex columns.
//
var
  n, i, j, info : integer;
  Acopy : TVMobj;
  wr, wi, vr : TVector;   //TVector = array of Double, exported by newVM
begin
  assert(A.Rows = A.Cols, s+'Matrix A must be square');
  n := A.Rows;

  //LAPACKE_dgeev overwrites its input matrix in place, so run it on a
  //scratch copy and leave the caller's A untouched.
  Acopy := CopyObj(A);

  SetLength(wr, n);
  SetLength(wi, n);
  SetLength(vr, n*n);

{$IFNDEF HAVE_LAPACKE}
  //PurePascalEigHqr2 - see its own header comment above - fills wr/wi/vr in
  //exactly the same packed real/imaginary-column-pair convention LAPACKE_dgeev
  //uses below, so the unpacking loops after this IFDEF are unchanged either way.
  info := PurePascalEigHqr2(n, Acopy.DataPtr, wr, wi, vr);
  assert(info = 0, s+'PurePascal QR iteration failed to converge, info='+IntToStr(info));
{$ELSE}
  //jobvl = 'N' : left eigenvectors not requested (vl unused -> nil, ldvl=n is a harmless placeholder)
  //jobvr = 'V' : right eigenvectors requested, returned in packed real form in vr
  info := LAPACKE_dgeev(CBlasRowMajor, 'N', 'V', n,
                          Acopy.DataPtr, n,
                          @wr[0], @wi[0],
                          nil, n,
                          @vr[0], n);
  assert(info = 0, s+'LAPACKE_dgeev failed, info='+IntToStr(info));
{$ENDIF}

  //--- eigenvalues: one complex value per row, straight from wr/wi ---
  EigenValues := TVMobjZ.Create(n,1);
  for i := 0 to n-1 do
    EigenValues.FData[i] := Cplx(wr[i], wi[i]);

  //--- eigenvectors: unpack LAPACK's real/imaginary column pairing ---
  EigenVectors := TVMobjZ.Create(n,n);
  j := 0;
  while j <= n-1 do begin
    if wi[j] = 0 then begin
      //real eigenvalue -> column j of vr IS the eigenvector, im = 0
      for i := 0 to n-1 do
        EigenVectors.FData[i*n+j] := Cplx(vr[i*n+j], 0);
      inc(j);
    end else begin
      //complex-conjugate pair sharing columns j (real part) and j+1 (imag part)
      for i := 0 to n-1 do begin
        EigenVectors.FData[i*n+j]   := Cplx(vr[i*n+j],  vr[i*n+j+1]);
        EigenVectors.FData[i*n+j+1] := Cplx(vr[i*n+j], -vr[i*n+j+1]);
      end;
      inc(j,2);
    end;
  end;
end;

function ReciprocalZ(const k: TComplex16): TComplex16;
const
  s : String = 'Operator / (TVMobjZ) : ';
var
  d : Double;
begin
  d := k.re*k.re + k.im*k.im;
  assert(d<>0, s+'division by zero complex scalar');
  result.re :=  k.re/d;
  result.im := -k.im/d;
end;

class operator TVMobjZ.+(const A, B: TVMobjZ): TVMobjZ;
const
  s : String = 'Operator + (TVMobjZ) : ';
var
  one : TComplex16;
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
begin
  assert((A.rows=B.rows) and (A.cols=B.cols), s+'matrix dimensions must match');
  result := CopyObjZ(B);
  for i := 0 to A.rows*A.cols-1 do
    result.fdata[i] := CAddZ(result.fdata[i], A.fdata[i]);
end;
{$ELSE}
begin
  assert((A.rows=B.rows) and (A.cols=B.cols), s+'matrix dimensions must match');
  one := Cplx(1,0);
  result := CopyObjZ(B);
  cblas_zaxpy(A.rows*A.cols, @one, @A.FData[0], 1, @result.FData[0], 1);
end;
{$ENDIF}

class operator TVMobjZ.-(const A, B: TVMobjZ): TVMobjZ;
const
  s : String = 'Operator - (TVMobjZ) : ';
var
  negOne : TComplex16;
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
begin
  assert((A.rows=B.rows) and (A.cols=B.cols), s+'matrix dimensions must match');
  result := CopyObjZ(A);
  for i := 0 to A.rows*A.cols-1 do
    result.fdata[i] := CSubZ(result.fdata[i], B.fdata[i]);
end;
{$ELSE}
begin
  assert((A.rows=B.rows) and (A.cols=B.cols), s+'matrix dimensions must match');
  negOne := Cplx(-1,0);
  result := CopyObjZ(A);
  cblas_zaxpy(A.rows*A.cols, @negOne, @B.FData[0], 1, @result.FData[0], 1);
end;
{$ENDIF}

class operator TVMobjZ.-(const A: TVMobjZ): TVMobjZ;
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
begin
  result := CopyObjZ(A);
  for i := 0 to A.rows*A.cols-1 do
    result.fdata[i] := Cplx(-result.fdata[i].re, -result.fdata[i].im);
end;
{$ELSE}
begin
  result := CopyObjZ(A);
  cblas_zdscal(A.rows*A.cols, -1, @result.FData[0], 1);
end;
{$ENDIF}

class operator TVMobjZ.*(const A, B: TVMobjZ): TVMobjZ;
begin
  result := MulObjZ(A, B);
end;

class operator TVMobjZ.*(const A: TVMobjZ; const k: TComplex16): TVMobjZ;
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
begin
  result := CopyObjZ(A);
  for i := 0 to A.rows*A.cols-1 do
    result.fdata[i] := CMulZ(result.fdata[i], k);
end;
{$ELSE}
begin
  result := CopyObjZ(A);
  cblas_zscal(A.rows*A.cols, @k, @result.FData[0], 1);
end;
{$ENDIF}

class operator TVMobjZ.*(const k: TComplex16; const A: TVMobjZ): TVMobjZ;
begin
  result := A * k;
end;

class operator TVMobjZ.*(const A: TVMobjZ; const k: Double): TVMobjZ;
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
begin
  result := CopyObjZ(A);
  for i := 0 to A.rows*A.cols-1 do
    result.fdata[i] := Cplx(result.fdata[i].re*k, result.fdata[i].im*k);
end;
{$ELSE}
begin
  result := CopyObjZ(A);
  cblas_zdscal(A.rows*A.cols, k, @result.FData[0], 1);
end;
{$ENDIF}

class operator TVMobjZ.*(const k: Double; const A: TVMobjZ): TVMobjZ;
begin
  result := A * k;
end;

class operator TVMobjZ./(const A: TVMobjZ; const k: TComplex16): TVMobjZ;
var
  r : TComplex16;
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
begin
  result := CopyObjZ(A);
  for i := 0 to A.rows*A.cols-1 do
    result.fdata[i] := CDivZ(result.fdata[i], k);
end;
{$ELSE}
begin
  r := ReciprocalZ(k);
  result := CopyObjZ(A);
  cblas_zscal(A.rows*A.cols, @r, @result.FData[0], 1);
end;
{$ENDIF}

class operator TVMobjZ./(const A: TVMobjZ; const k: Double): TVMobjZ;
const
  s : String = 'Operator / (TVMobjZ) : ';
{$IFDEF PUREPASCAL_BLAS}
var
  i : Integer;
begin
  assert(k<>0, s+'division by zero');
  result := CopyObjZ(A);
  for i := 0 to A.rows*A.cols-1 do
    result.fdata[i] := Cplx(result.fdata[i].re/k, result.fdata[i].im/k);
end;
{$ELSE}
begin
  assert(k<>0, s+'division by zero');
  result := CopyObjZ(A);
  cblas_zdscal(A.rows*A.cols, 1/k, @result.FData[0], 1);
end;
{$ENDIF}

class operator TVMobjZ.+(const A: TVMobjZ; const B: TVMobj): TVMobjZ;
begin
  result := A + RealToComplex(B);
end;

class operator TVMobjZ.+(const A: TVMobj; const B: TVMobjZ): TVMobjZ;
begin
  result := RealToComplex(A) + B;
end;

class operator TVMobjZ.-(const A: TVMobjZ; const B: TVMobj): TVMobjZ;
begin
  result := A - RealToComplex(B);
end;

class operator TVMobjZ.-(const A: TVMobj; const B: TVMobjZ): TVMobjZ;
begin
  result := RealToComplex(A) - B;
end;

class operator TVMobjZ.*(const A: TVMobjZ; const B: TVMobj): TVMobjZ;
begin
  result := MatMultZ(A, RealToComplex(B));
end;

class operator TVMobjZ.*(const A: TVMobj; const B: TVMobjZ): TVMobjZ;
begin
  result := MatMultZ(RealToComplex(A), B);
end;

class operator TVMobjZ.=(const A, B: TVMobjZ): Boolean;
begin
  Result := (A.rows = B.rows) and (A.cols = B.cols) and
            CompareMem(@A.FData[0], @B.FData[0], A.rows*A.cols*SizeOf(TComplex16));
end;

function Sin(const A: TVMobjZ): TVMobjZ;
{$IFDEF PUREPASCAL}
var
  i : Integer;
begin
  result := TVMobjZ.Create(A.rows, A.cols);
  for i := 0 to A.rows*A.cols-1 do result.fdata[i] := CSinZ(A.fdata[i]);
end;
{$ELSE}
begin
  result := TVMobjZ.Create(A.rows, A.cols);
  vzSin(A.rows*A.cols, @A.FData[0], @result.FData[0]);
end;
{$ENDIF}

function Cos(const A: TVMobjZ): TVMobjZ;
{$IFDEF PUREPASCAL}
var
  i : Integer;
begin
  result := TVMobjZ.Create(A.rows, A.cols);
  for i := 0 to A.rows*A.cols-1 do result.fdata[i] := CCosZ(A.fdata[i]);
end;
{$ELSE}
begin
  result := TVMobjZ.Create(A.rows, A.cols);
  vzCos(A.rows*A.cols, @A.FData[0], @result.FData[0]);
end;
{$ENDIF}

function Tan(const A: TVMobjZ): TVMobjZ;
{$IFDEF PUREPASCAL}
var
  i : Integer;
begin
  result := TVMobjZ.Create(A.rows, A.cols);
  for i := 0 to A.rows*A.cols-1 do result.fdata[i] := CDivZ(CSinZ(A.fdata[i]), CCosZ(A.fdata[i]));
end;
{$ELSE}
begin
  result := TVMobjZ.Create(A.rows, A.cols);
  vzTan(A.rows*A.cols, @A.FData[0], @result.FData[0]);
end;
{$ENDIF}

function Sinh(const A: TVMobjZ): TVMobjZ;
{$IFDEF PUREPASCAL}
var
  i : Integer;
begin
  result := TVMobjZ.Create(A.rows, A.cols);
  for i := 0 to A.rows*A.cols-1 do result.fdata[i] := CSinhZ(A.fdata[i]);
end;
{$ELSE}
begin
  result := TVMobjZ.Create(A.rows, A.cols);
  vzSinh(A.rows*A.cols, @A.FData[0], @result.FData[0]);
end;
{$ENDIF}

function Sqr(const A: TVMobjZ): TVMobjZ;
{$IFDEF PUREPASCAL}
var
  i : Integer;
begin
  //No MKL VM here either way - square elementwise via a complex self-multiply.
  result := TVMobjZ.Create(A.rows, A.cols);
  for i := 0 to A.rows*A.cols-1 do result.fdata[i] := CMulZ(A.fdata[i], A.fdata[i]);
end;
{$ELSE}
begin
  //MKL VM has no vzSqr (complex Sqr isn't part of the VM function set,
  //unlike real vdSqr) - so square elementwise via vzMul(A, A) instead.
  result := TVMobjZ.Create(A.rows, A.cols);
  vzMul(A.rows*A.cols, @A.FData[0], @A.FData[0], @result.FData[0]);
end;
{$ENDIF}

function Sqrt(const A: TVMobjZ): TVMobjZ;
{$IFDEF PUREPASCAL}
var
  i : Integer;
begin
  result := TVMobjZ.Create(A.rows, A.cols);
  for i := 0 to A.rows*A.cols-1 do result.fdata[i] := CSqrtZ(A.fdata[i]);
end;
{$ELSE}
begin
  result := TVMobjZ.Create(A.rows, A.cols);
  vzSqrt(A.rows*A.cols, @A.FData[0], @result.FData[0]);
end;
{$ENDIF}

function Exp(const A: TVMobjZ): TVMobjZ;
{$IFDEF PUREPASCAL}
var
  i : Integer;
begin
  result := TVMobjZ.Create(A.rows, A.cols);
  for i := 0 to A.rows*A.cols-1 do result.fdata[i] := CExpZ(A.fdata[i]);
end;
{$ELSE}
begin
  result := TVMobjZ.Create(A.rows, A.cols);
  vzExp(A.rows*A.cols, @A.FData[0], @result.FData[0]);
end;
{$ENDIF}

function Ln(const A: TVMobjZ): TVMobjZ;
{$IFDEF PUREPASCAL}
var
  i : Integer;
begin
  result := TVMobjZ.Create(A.rows, A.cols);
  for i := 0 to A.rows*A.cols-1 do result.fdata[i] := CLnZ(A.fdata[i]);
end;
{$ELSE}
begin
  result := TVMobjZ.Create(A.rows, A.cols);
  vzLn(A.rows*A.cols, @A.FData[0], @result.FData[0]);
end;
{$ENDIF}

function MulObjZ(const A, B: TVMObjZ): TVMobjZ;
const
  s: string ='Routine MulObjZ : ';
{$IFDEF PUREPASCAL}
var
  i : Integer;
begin
  assert((a.rows=b.rows)and(a.cols=b.cols),s+'Dimensions of A and B must be the same');
  result := CopyObjZ(A);
  for i := 0 to A.rows*A.cols-1 do
    result.fdata[i] := CMulZ(result.fdata[i], B.fdata[i]);
end;
{$ELSE}
begin
  assert((a.rows=b.rows)and(a.cols=b.cols),s+'Dimensions of A and B must be the same');
  result := CopyObjZ(A);
  vzMul(A.rows*A.cols, @A.FData[0], @B.FData[0], @result.FData[0]);
end;
{$ENDIF}

{$IFNDEF HAVE_FFTW}
// Direct O(N^2) DFT - the FFT_R2C/FFT_C2R/FFT/IFFT fallback when FFTW isn't
// loaded. Deliberately NOT a ported radix-2 fast FFT (e.g. LMath's own
// ufft.pas, which only handles power-of-two lengths): a direct summation is
// simpler, always correct, and - unlike a radix-2-only fast path - works
// for ANY N, matching FFTW's own generality, which matters here since
// FFT_R2C/FFT_C2R/FFT/IFFT accept arbitrary vector lengths, not just powers
// of two. O(N^2) is an acceptable trade for a fallback path where
// correctness/simplicity matter more than speed - same rationale as every
// other PUREPASCAL body in this codebase (e.g. MatMult's own plain triple
// loop, hundreds of times slower than cblas_dgemm).
procedure PPDirectDFT(N: Integer; InData, OutData: PComplex16; Forward: Boolean);
var
  k, m : Integer;
  sgn, angle, c, sn, accre, accim : Double;
begin
  if Forward then sgn := -1 else sgn := 1;
  for k := 0 to N-1 do begin
    accre := 0; accim := 0;
    for m := 0 to N-1 do begin
      angle := sgn * 2 * Pi * k * m / N;
      c := cos(angle); sn := sin(angle);
      accre := accre + InData[m].re*c - InData[m].im*sn;
      accim := accim + InData[m].re*sn + InData[m].im*c;
    end;
    OutData[k].re := accre;
    OutData[k].im := accim;
  end;
end;
{$ENDIF}

function FFT_R2C(const A: TVMobj): TVMobjZ;
const
  s : String = 'Routine FFT_R2C : ';
var
  n, nc : integer;
{$IFDEF HAVE_FFTW}
  plan : fftw_plan;
{$ELSE}
  k, m : Integer;
  angle, c, sn, accre, accim : Double;
{$ENDIF}
begin
  assert((A.Rows=1) or (A.Cols=1), s+'A must be a vector (Rows=1 or Cols=1)');
  n := A.Rows*A.Cols;
  nc := n div 2 + 1;
  if A.Cols = 1 then result := TVMobjZ.Create(nc, 1) else result := TVMobjZ.Create(1, nc);
{$IFDEF HAVE_FFTW}
  assert(Assigned(fftw_plan_dft_r2c_1d), s+'FFTW3 (double) library not loaded');
  plan := fftw_plan_dft_r2c_1d(n, A.DataPtr, PComplex16(@result.FData[0]), FFTW_ESTIMATE or FFTW_PRESERVE_INPUT);
  assert(plan<>nil, s+'fftw_plan_dft_r2c_1d failed');
  fftw_execute_dft_r2c(plan, A.DataPtr, PComplex16(@result.FData[0]));
  fftw_destroy_plan(plan);
{$ELSE}
  //Only the nc needed half-spectrum bins are computed directly (A's imaginary
  //part is implicitly 0 - a real vector treated as complex).
  for k := 0 to nc-1 do begin
    accre := 0; accim := 0;
    for m := 0 to n-1 do begin
      angle := -2 * Pi * k * m / n;
      c := cos(angle); sn := sin(angle);
      accre := accre + A.DataPtr[m]*c;
      accim := accim + A.DataPtr[m]*sn;
    end;
    result.FData[k] := Cplx(accre, accim);
  end;
{$ENDIF}
end;

function FFT_C2R(const A: TVMobjZ; N: Integer): TVMobj;
const
  s : String = 'Routine FFT_C2R : ';
var
  nc : integer;
{$IFDEF HAVE_FFTW}
  Nd : Double;
{$ENDIF}
{$IFDEF HAVE_FFTW}
  plan : fftw_plan;
{$ELSE}
  full, outc : array of TComplex16;
  k : Integer;
{$ENDIF}
begin
  assert((A.Rows=1) or (A.Cols=1), s+'A must be a vector (Rows=1 or Cols=1)');
  assert(N>0, s+'N must be > 0');
  nc := A.Rows*A.Cols;
  assert(nc = (N div 2 + 1), s+'A''s length must be N div 2 + 1');
  if A.Cols = 1 then result := TVMobj.Create(N, 1) else result := TVMobj.Create(1, N);
{$IFDEF HAVE_FFTW}
  assert(Assigned(fftw_plan_dft_c2r_1d), s+'FFTW3 (double) library not loaded');
  plan := fftw_plan_dft_c2r_1d(N, PComplex16(@A.FData[0]), result.DataPtr, FFTW_ESTIMATE or FFTW_PRESERVE_INPUT);
  assert(plan<>nil, s+'fftw_plan_dft_c2r_1d failed');
  fftw_execute_dft_c2r(plan, PComplex16(@A.FData[0]), result.DataPtr);
  fftw_destroy_plan(plan);
  assert(Assigned(cblas_dscal), s+'OpenBLAS not available on this machine - FFT_C2R normalization has no PUREPASCAL fallback');
  //Divide via an explicit Double intermediate (Nd), not "1.0/N" directly -
  //this FPC/AArch64 target silently computes a literal-over-Integer division
  //like "1.0/N" at reduced (~single) precision, even though "1.0/Nd" with Nd
  //already Double is fully precise; confirmed empirically (not just here -
  //IFFT below had the identical latent bug in "1.0/n", previously masked by
  //its round-trip test's looser DblSolveTol tolerance).
  Nd := N;
  cblas_dscal(N, 1.0/Nd, result.DataPtr, 1);   //normalize, matching FFT_C2R(FFT_R2C(x), N) = x
{$ELSE}
  //Expand the half-spectrum to the full N-point spectrum via conjugate
  //symmetry (X[N-k] = conj(X[k]), the defining property of a real-valued
  //time-domain signal - the same assumption FFTW's own C2R transform
  //makes), inverse-DFT it, and keep only the real part (the imaginary part
  //is ~0 for a genuine real-signal half-spectrum, by construction).
  SetLength(full, N);
  SetLength(outc, N);
  for k := 0 to nc-1 do full[k] := A.FData[k];
  for k := nc to N-1 do full[k] := Cplx(A.FData[N-k].re, -A.FData[N-k].im);
  PPDirectDFT(N, @full[0], @outc[0], False);
  for k := 0 to N-1 do result.DataPtr[k] := outc[k].re / N;
{$ENDIF}
end;

function FFT(const A: TVMobjZ): TVMobjZ;
const
  s : String = 'Routine FFT : ';
var
  n : integer;
{$IFDEF HAVE_FFTW}
  plan : fftw_plan;
{$ENDIF}
begin
  assert((A.Rows=1) or (A.Cols=1), s+'A must be a vector (Rows=1 or Cols=1)');
  n := A.Rows*A.Cols;
  result := TVMobjZ.Create(A.Rows, A.Cols);
{$IFDEF HAVE_FFTW}
  assert(Assigned(fftw_plan_dft_1d), s+'FFTW3 (double) library not loaded');
  plan := fftw_plan_dft_1d(n, PComplex16(@A.FData[0]), PComplex16(@result.FData[0]), FFTW_FORWARD, FFTW_ESTIMATE or FFTW_PRESERVE_INPUT);
  assert(plan<>nil, s+'fftw_plan_dft_1d failed');
  fftw_execute_dft(plan, PComplex16(@A.FData[0]), PComplex16(@result.FData[0]));
  fftw_destroy_plan(plan);
{$ELSE}
  PPDirectDFT(n, PComplex16(@A.FData[0]), PComplex16(@result.FData[0]), True);
{$ENDIF}
end;

function IFFT(const A: TVMobjZ): TVMobjZ;
const
  s : String = 'Routine IFFT : ';
var
  n, i : integer;
{$IFDEF HAVE_FFTW}
  plan : fftw_plan;
  Nd : Double;
{$ENDIF}
begin
  assert((A.Rows=1) or (A.Cols=1), s+'A must be a vector (Rows=1 or Cols=1)');
  n := A.Rows*A.Cols;
  result := TVMobjZ.Create(A.Rows, A.Cols);
{$IFDEF HAVE_FFTW}
  assert(Assigned(fftw_plan_dft_1d), s+'FFTW3 (double) library not loaded');
  plan := fftw_plan_dft_1d(n, PComplex16(@A.FData[0]), PComplex16(@result.FData[0]), FFTW_BACKWARD, FFTW_ESTIMATE or FFTW_PRESERVE_INPUT);
  assert(plan<>nil, s+'fftw_plan_dft_1d failed');
  fftw_execute_dft(plan, PComplex16(@A.FData[0]), PComplex16(@result.FData[0]));
  fftw_destroy_plan(plan);
  assert(Assigned(cblas_zdscal), s+'OpenBLAS not available on this machine - IFFT normalization has no PUREPASCAL fallback');
  Nd := n;  //see FFT_C2R's own comment above: avoid "1.0/n" (Integer) directly
  cblas_zdscal(n, 1.0/Nd, @result.FData[0], 1);  //normalize, matching IFFT(FFT(x)) = x
{$ELSE}
  PPDirectDFT(n, PComplex16(@A.FData[0]), PComplex16(@result.FData[0]), False);
  for i := 0 to n-1 do begin
    result.FData[i].re := result.FData[i].re / n;
    result.FData[i].im := result.FData[i].im / n;
  end;
{$ENDIF}
end;

// One-call linear power spectrum of a real signal: Hamming-windows A,
// FFT_R2C's it, and returns |X[k]|^2 for k=0..(N div 2)-1 - literally
// half A's length (integer division, so an odd N drops one more bin than
// FFT_R2C's own N div 2 + 1 would leave - deliberate, to land exactly on
// "half the length" rather than "half the length, plus one"). A itself
// is never mutated (matches FFT_R2C/the rest of this unit's convention).
// The Hamming window is recomputed each call rather than cached, since
// there's nowhere to cache it against (this routine is stateless and A's
// length could differ call to call, e.g. across different ADC captures)
// - that recomputation is O(N), negligible next to the O(N log N) FFT
// itself.
//
// Internally normalises A to a row vector via Reshape (a pure
// reinterpretation for any true vector, row- or column-shaped, since
// row-major storage means the flat element order is identical either
// way - see Reshape's own header comment in newVM.pas) so the windowing/
// FFT/power-extraction logic below doesn't need to branch on A's
// orientation, then reshapes the result back to match A's own
// orientation at the end - the same orientation-preserving convention
// FFT_R2C itself follows.
function PowerSpectrum(const A: TVMobj): TVMobj;
const
  s : String = 'Routine PowerSpectrum : ';
var
  N, HalfN, i : Integer;
  RowA, W, Windowed, RowResult : TVMobj;
  Spectrum : TVMobjZ;
  bin : TComplex16;
begin
  assert((A.Rows=1) or (A.Cols=1), s+'A must be a vector (Rows=1 or Cols=1)');
  N := A.Rows*A.Cols;
  HalfN := N div 2;
  assert(HalfN > 0, s+'A must have at least 2 elements');

  RowA := Reshape(A, 1, N);

  W := TVMobj.Create(1, N);
  for i := 0 to N-1 do
    W[0,i] := 0.54 - 0.46*cos(2*Pi*i/(N-1));

  Windowed := RowA * W;
  Spectrum := FFT_R2C(Windowed);

  RowResult := TVMobj.Create(1, HalfN);
  for i := 0 to HalfN-1 do begin
    bin := Spectrum[0,i];
    RowResult[0,i] := bin.re*bin.re + bin.im*bin.im;
  end;

  if A.Cols = 1 then result := Reshape(RowResult, HalfN, 1) else result := RowResult;
end;

// One-call linear power spectrum of a complex signal - see the real-input
// overload's own comment for the shared rationale (repeated-use design,
// row-vector normalisation trick). Differs in three ways a real signal
// doesn't need: the Hamming window is applied by hand, one complex
// element at a time (each element's re/im scaled by the same real window
// value) rather than via the '*' operator - TVMobjZ's own same-type '*'
// is elementwise, matching what windowing needs, but that would first
// need the real window promoted to complex (RealToComplex) purely to
// satisfy the type checker, an extra full-length allocation for no
// benefit; FFT (complex-to-complex) is used instead of FFT_R2C, since a
// general complex signal isn't Hermitian-symmetric the way real input
// is, so there's no packed half-spectrum form to compute in the first
// place; and the result keeps ALL N bins (the full length of A), not
// half, since there is no redundant conjugate-symmetric upper half to
// drop.
function PowerSpectrum(const A: TVMobjZ): TVMobj;
const
  s : String = 'Routine PowerSpectrum : ';
var
  N, i : Integer;
  RowA, Windowed, Spectrum : TVMobjZ;
  W, RowResult : TVMobj;
  bin : TComplex16;
begin
  assert((A.Rows=1) or (A.Cols=1), s+'A must be a vector (Rows=1 or Cols=1)');
  N := A.Rows*A.Cols;
  assert(N > 0, s+'A must have at least 1 element');

  RowA := ReshapeZ(A, 1, N);

  W := TVMobj.Create(1, N);
  for i := 0 to N-1 do
    W[0,i] := 0.54 - 0.46*cos(2*Pi*i/(N-1));

  Windowed := TVMobjZ.Create(1, N);
  for i := 0 to N-1 do begin
    bin := RowA[0,i];
    Windowed[0,i] := Cplx(bin.re*W[0,i], bin.im*W[0,i]);
  end;

  Spectrum := FFT(Windowed);

  RowResult := TVMobj.Create(1, N);
  for i := 0 to N-1 do begin
    bin := Spectrum[0,i];
    RowResult[0,i] := bin.re*bin.re + bin.im*bin.im;
  end;

  if A.Cols = 1 then result := Reshape(RowResult, N, 1) else result := RowResult;
end;

end.
