unit uFMReceiver;

{*******************************************************************************

     TFMBroadcastReceiver - onward CPU-side signal processing of a
     TSDRRFSource's IQ stream (see uSDRRFSource.pas): a complete
     broadcast-FM receive chain built entirely from uDSPBlocks.pas's
     modular pieces, producing audible 48kHz stereo audio via
     uWaveOutPlayer.pas. A non-visual, installable Lazarus component
     (TComponent, same shape as TSDRRFSource itself) with a Source
     property pointing at a sibling TSDRRFSource - the standard
     "consumer points at a sibling component" link this project already
     uses for TSDRSpectrumAnalyser.Source (uVMPlotSDRSpectrum.pas).

     THE CHAIN (per epoch, EpochDurationMs worth of IQ at a time):
       1. Source.TryReadEpoch -> wideband IQ, at the RF source's own
          SampleRateHz (Fs_in - e.g. 2Msps on an SDRplay RSP1A).
       2. TComplexMixer, tuned to -(TunedFrequencyHz - Source.
          CenterFreqHz): shifts the selected station from wherever it
          sits within the wideband capture down to baseband (0Hz) - this
          is the "local quadrature oscillator + mixer" pair the design
          asked for, and is what lets TunedFrequencyHz move freely across
          the whole captured bandwidth without ever retuning the RF
          front end itself.
       3. TRationalResamplerC, Fs_in -> BasebandRateHz (200,000 - see
          below): a "rational re-sampler" cuts the wideband capture rate
          down to exactly the broadcast-FM channel rate, its own
          anti-alias filter (cutoff BasebandRateHz/2 = 100kHz) doubling
          as the channel-selectivity filter. BasebandRateHz = 200,000 is
          not arbitrary: a complex baseband signal's occupied bandwidth
          equals its sample rate (Nyquist on both sides), so sampling the
          selected channel at exactly 200kHz IS what gives it exactly the
          200kHz bandwidth broadcast FM standards call for - the sample
          rate and the bandwidth spec are the same number by
          construction, not two separate things kept in sync by hand.
       4. TFMDemodulator, at BasebandRateHz, PeakDeviationHz=75000 (the
          broadcast-FM standard's own peak deviation almost everywhere
          this hardware is likely used) -> the real FM multiplex signal
          (mono L+R, 19kHz pilot, 23-53kHz L-R subcarrier).
       5. TFMStereoDecoder, at BasebandRateHz, 75us de-emphasis (US
          broadcast-FM standard; most of the rest of the world uses 50us
          - see that class's own constructor comment) -> independent L/R
          audio, still at BasebandRateHz.
       6. Two TRationalResamplerS instances (BasebandRateHz -> 48,000),
          one per channel - the SAME reusable resampler class stage 3
          used, just real instead of complex, reused rather than a
          separate "final resample" concept: a rational resampler is a
          rational resampler regardless of where in the chain it sits.
       7. Volume-scaled, soft-limited, and queued to a TWaveOutPlayer for
          audible, real-time playback.

     Deliberately NOT reconfigured on every TunedFrequencyHz change: only
     the mixer's own oscillator frequency updates live (SetTunedFrequencyHz
     just touches FMixer.FrequencyHz, when the chain already exists) -
     rebuilding the resamplers/demodulator/stereo decoder on every retune
     would reset their internal filter delay lines and produce an audible
     glitch, and none of their own configuration (which only depends on
     Source.SampleRateHz/BasebandRateHz/AudioRateHz, none of which change
     when simply retuning within the same capture) actually needs to
     change for a retune anyway.

     WHY THIS RUNS ON ITS OWN THREAD (FDSPThread), NOT A TTIMER: the
     first working version ran the whole chain (TryReadEpoch through
     QueueStereo) from an ordinary TTimer tick, on the GUI thread - same
     thread TSDRSpectrumAnalyser's own GPU/OpenCL processing runs on.
     Moving IQ ACQUISITION to a background thread (see uSDRRFSource.pas's
     own FPollThread) fixed data loss, but real-hardware testing still
     showed audible clicks/pops in the live app even though a WAV file
     generated by a single-threaded standalone harness (no spectrum
     analyser, no GUI contention) sounded clean end to end with the exact
     same chain and Source. The difference was exactly the GUI-thread
     contention itself: even with correct, lossless IQ data always
     available, running the DEMOD CHAIN and QueueStereo from a GUI timer
     still meant a slow spectrum tick could delay this component's own
     tick long enough to underrun TWaveOutPlayer's buffer - acquisition
     being lossless doesn't help if the audio never gets PRODUCED and
     QUEUED in time. FDSPThread runs the entire chain independently of
     GUI-thread scheduling, the same rationale as uSDRRFSource.pas's own
     FPollThread, so a slow spectrum tick can no longer stall audio at
     all. FSource.TryReadEpoch is already thread-safe for this (see that
     unit's own FStreamLock); TWaveOutPlayer's Win32 waveOut calls are
     safe to make from any single thread as long as nothing else calls
     into the same TWaveOutPlayer instance concurrently, which nothing
     else here does.

*******************************************************************************}

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils,
  newVM, newVMSingle, newVMComplexSingle,
  uSDRRFSource, uDSPBlocks, uWaveOutPlayer;

const
  DefaultBasebandRateHz = 200000;    // = broadcast FM's own 200kHz channel bandwidth - see this unit's header comment
  DefaultAudioRateHz = 48000;
  DefaultPeakDeviationHz = 75000;
  DefaultDeEmphasisTauSeconds = 75e-6;   // US broadcast-FM standard; most of the rest of the world uses 50e-6
  DefaultEpochDurationMs = 20;

type
  TFMBroadcastReceiver = class;

  // Plain tight loop, mirroring uSDRRFSource.pas's own FPollThread - see
  // this unit's own header comment ("WHY THIS RUNS ON ITS OWN THREAD")
  // for why the whole chain has to run off the GUI thread, not just IQ
  // acquisition.
  { TFMDSPThread }
  TFMDSPThread = class(TThread)
  private
    FOwner: TFMBroadcastReceiver;
  protected
    procedure Execute; override;
  public
    constructor Create(AOwner: TFMBroadcastReceiver);
  end;

  { TFMBroadcastReceiver }
  TFMBroadcastReceiver = class(TComponent)
  private
    FSource: TSDRRFSource;
    FSourceCursor: TSDRStreamCursor;
    FTunedFrequencyHz: Double;
    FVolume: Single;
    FEpochDurationMs: Integer;

    FMixer: TComplexMixer;
    FResamplerToBaseband: TRationalResamplerC;
    FDemod: TFMDemodulator;
    FStereoDecoder: TFMStereoDecoder;
    FResamplerL, FResamplerR: TRationalResamplerS;
    FPlayer: TWaveOutPlayer;
    FDSPThread: TFMDSPThread;
    FChainBuilt: Boolean;

    procedure SetSource(AValue: TSDRRFSource);
    procedure SetTunedFrequencyHz(AValue: Double);
    function GetActive: Boolean;
    procedure SetActive(AValue: Boolean);
    procedure BuildChain;
    procedure TeardownChain;
    // Called only from FDSPThread. Returns True iff an epoch was
    // actually processed (so the thread's own loop knows whether to
    // yield briefly or keep going).
    function ProcessOnce: Boolean;
  protected
    procedure Notification(AComponent: TComponent; Operation: TOperation); override;
  public
    constructor Create(AOwner: TComponent); override;
    destructor Destroy; override;
  published
    property Source: TSDRRFSource read FSource write SetSource;
    // Absolute RF frequency to listen to, in Hz - independent of
    // Source's own CenterFreqHz, as long as it falls within the
    // currently-captured bandwidth (CenterFreqHz +- SampleRateHz/2) -
    // see this unit's own header comment for how the mixer makes that
    // work. May be changed live while Active.
    property TunedFrequencyHz: Double read FTunedFrequencyHz write SetTunedFrequencyHz;
    property Volume: Single read FVolume write FVolume;
    property EpochDurationMs: Integer read FEpochDurationMs write FEpochDurationMs
      default DefaultEpochDurationMs;
    property Active: Boolean read GetActive write SetActive default False;
  end;

procedure Register;

implementation

constructor TFMBroadcastReceiver.Create(AOwner: TComponent);
begin
  inherited Create(AOwner);
  FVolume := 1.0;
  FEpochDurationMs := DefaultEpochDurationMs;
  FPlayer := TWaveOutPlayer.Create;
end;

destructor TFMBroadcastReceiver.Destroy;
begin
  SetActive(False);   // stops and waits for FDSPThread before tearing anything down
  FPlayer.Free;
  inherited Destroy;
end;

{ TFMDSPThread }

constructor TFMDSPThread.Create(AOwner: TFMBroadcastReceiver);
begin
  inherited Create(False);
  FOwner := AOwner;
  FreeOnTerminate := False;
end;

procedure TFMDSPThread.Execute;
begin
  while not Terminated do
    if not FOwner.ProcessOnce then Sleep(1);
end;

procedure TFMBroadcastReceiver.Notification(AComponent: TComponent; Operation: TOperation);
begin
  inherited Notification(AComponent, Operation);
  if (Operation = opRemove) and (AComponent = FSource) then FSource := nil;
end;

procedure TFMBroadcastReceiver.SetSource(AValue: TSDRRFSource);
begin
  if FSource = AValue then Exit;
  if Assigned(FSource) then FSource.RemoveFreeNotification(Self);
  FSource := AValue;
  if Assigned(FSource) then begin
    FSource.FreeNotification(Self);
    // See uSDRRFSource.pas's own header comment: every independent
    // consumer of the shared stream needs its own cursor - this used to
    // be a single-consumer destructive read, which silently corrupted
    // both this component's own stream and TSDRSpectrumAnalyser's the
    // moment both were active on the same Source at once.
    FSourceCursor := FSource.NewStreamCursor;
  end;
end;

procedure TFMBroadcastReceiver.SetTunedFrequencyHz(AValue: Double);
begin
  FTunedFrequencyHz := AValue;
  // See this unit's own header comment for the sign: the mixer must
  // shift the station DOWN to baseband, i.e. by minus its offset from
  // the RF source's own centre frequency. FMixer.FrequencyHz is a plain
  // Double field read every FDSPThread iteration - deliberately not
  // synchronised with this (GUI-thread) setter: a torn/stale read here
  // has no worse an effect than a one-epoch-late retune, and this
  // property is written far more often (a user dragging a frequency
  // control) than the cost of adding real synchronisation would justify.
  if FChainBuilt and Assigned(FSource) then
    FMixer.FrequencyHz := -(FTunedFrequencyHz - FSource.CenterFreqHz);
end;

function TFMBroadcastReceiver.GetActive: Boolean;
begin
  Result := Assigned(FDSPThread);
end;

procedure TFMBroadcastReceiver.SetActive(AValue: Boolean);
begin
  if AValue = Assigned(FDSPThread) then Exit;
  if AValue then begin
    if not (Assigned(FSource) and FSource.IsOpen) then Exit;   // nothing to receive from yet
    BuildChain;
    FDSPThread := TFMDSPThread.Create(Self);
  end else begin
    FDSPThread.Terminate;
    FDSPThread.WaitFor;
    FreeAndNil(FDSPThread);
    TeardownChain;
  end;
end;

procedure TFMBroadcastReceiver.BuildChain;
const
  s = 'TFMBroadcastReceiver.BuildChain : ';
var
  FsIn: Double;
  MaxAudioSamples: Integer;
begin
  TeardownChain;
  assert(Assigned(FSource) and FSource.IsOpen, s + 'Source must be connected');
  FsIn := FSource.SampleRateHz;

  // TransitionBW arguments were loosened twice now after real-time
  // testing against actual hardware showed the tighter, longer filters
  // couldn't keep up with the wideband capture rate - TFIRFilterS/
  // TRationalResamplerC/S are all direct-form (O(N*NumTaps)), and
  // NumTaps roughly halves for each doubling of TransitionBW (see
  // ChooseNumTaps's own comment). 50kHz here is the single biggest lever
  // available: this filter runs at FsIn (e.g. 2MHz), an order of
  // magnitude higher than every other filter in the chain (which run at
  // BasebandRateHz, 200kHz), so for the SAME TransitionBW-in-Hz it costs
  // ~10x as many taps - it needs a proportionally wider transition to
  // stay cheap. This does NOT touch BasebandRateHz itself (still exactly
  // 200,000 - the actual 200kHz channel-bandwidth spec, unchanged); it
  // only loosens how sharply the antialiasing filter rolls off at that
  // boundary, trading a little out-of-channel rejection for real-time
  // headroom.
  FMixer := TComplexMixer.Create(FsIn, -(FTunedFrequencyHz - FSource.CenterFreqHz));
  FResamplerToBaseband := TRationalResamplerC.Create(FsIn, DefaultBasebandRateHz, 50000);
  FDemod := TFMDemodulator.Create(DefaultBasebandRateHz, DefaultPeakDeviationHz);
  FStereoDecoder := TFMStereoDecoder.Create(DefaultBasebandRateHz, DefaultDeEmphasisTauSeconds);
  FResamplerL := TRationalResamplerS.Create(DefaultBasebandRateHz, DefaultAudioRateHz, 8000);
  FResamplerR := TRationalResamplerS.Create(DefaultBasebandRateHz, DefaultAudioRateHz, 8000);

  // Generous headroom over the nominal per-epoch audio sample count,
  // since TRationalResamplerS's output length can vary by a sample or
  // two either way depending on exact phase alignment.
  MaxAudioSamples := Round(DefaultAudioRateHz * FEpochDurationMs / 1000 * 2) + 64;
  FPlayer.Open(DefaultAudioRateHz, MaxAudioSamples);

  // A fresh cursor for this streaming session - StartStreaming resets
  // the source's own stream position, so a cursor left over from a
  // previous session (or from before Source was ever streaming) would
  // otherwise read as "hopelessly behind" and just skip-forward once,
  // rather than starting caught up cleanly.
  FSourceCursor := FSource.NewStreamCursor;

  FChainBuilt := True;
end;

procedure TFMBroadcastReceiver.TeardownChain;
begin
  if not FChainBuilt then Exit;
  FPlayer.Close;
  FreeAndNil(FMixer);
  FreeAndNil(FResamplerToBaseband);
  FreeAndNil(FDemod);
  FreeAndNil(FStereoDecoder);
  FreeAndNil(FResamplerL);
  FreeAndNil(FResamplerR);
  FChainBuilt := False;
end;

function TFMBroadcastReceiver.ProcessOnce: Boolean;
var
  N: Integer;
  IQ, Baseband: TVMobjC;
  Multiplex: TVMobjS;
  StereoL, StereoR, AudioL, AudioR: TVMobjS;
begin
  Result := False;
  if not (FChainBuilt and Assigned(FSource)) then Exit;

  N := Round(FSource.SampleRateHz * FEpochDurationMs / 1000);
  if not FSource.TryReadEpoch(N, FSourceCursor, IQ) then Exit;

  Baseband := FResamplerToBaseband.Process(FMixer.Process(IQ));
  Multiplex := FDemod.Process(Baseband);
  FStereoDecoder.Process(Multiplex, StereoL, StereoR);
  AudioL := FResamplerL.Process(StereoL);
  AudioR := FResamplerR.Process(StereoR);

  if FVolume <> 1.0 then begin
    AudioL := AudioL * FVolume;
    AudioR := AudioR * FVolume;
  end;

  FPlayer.QueueStereo(AudioL, AudioR);
  Result := True;
end;

procedure Register;
begin
  RegisterComponents('SDR', [TFMBroadcastReceiver]);
end;

end.
