unit CXS.FEMLAP.TestFace_Q4V2;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

{$mode delphi}{$H+}

interface

uses
  fpcunit, testregistry, CXS.FEMLAP.Face_Q4V2, CXS.FEMLAP.Node,
  CXS.FEMLAP.Exceptions, SysUtils, newVM, CXS.FEMLAP.Edge_B2V1,
  CXS.FEMLAP.Element_Face;

type
  // Test methods for class TFace_Q4V2

  TestTFace_Q4V2 = class(TTestCase)
  strict private
    Ftol : Double;
    FFace_Q4V2: TFace_Q4V2;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestCalcGeoProperties;
    procedure TestCalc;
  end;

implementation

procedure TestTFace_Q4V2.SetUp;
begin
  FFace_Q4V2 := TFace_Q4V2.Create;

  Ftol := 1E-10;

  FFace_Q4V2.CoordX[0] := 0;
  FFace_Q4V2.CoordY[0] := 0;
  FFace_Q4V2.CoordZ[0] := 0;

  FFace_Q4V2.CoordX[1] := 2;
  FFace_Q4V2.CoordY[1] := 0;
  FFace_Q4V2.CoordZ[1] := 0;

  FFace_Q4V2.CoordX[2] := 2;
  FFace_Q4V2.CoordY[2] := 1;
  FFace_Q4V2.CoordZ[2] := 0;

  FFace_Q4V2.CoordX[3] := 0;
  FFace_Q4V2.CoordY[3] := 1;
  FFace_Q4V2.CoordZ[3] := 0;

  FFace_Q4V2.CalcGeoProperties;

end;

procedure TestTFace_Q4V2.TearDown;
begin
  FFace_Q4V2.Free;
  FFace_Q4V2 := nil;
end;

procedure TestTFace_Q4V2.TestCalcGeoProperties;
begin
  FFace_Q4V2.CalcGeoProperties;
  // TODO: Validate method results
end;

procedure TestTFace_Q4V2.TestCalc;
begin
  FFace_Q4V2.ReCalcD;
  FFace_Q4V2.Calc;

  // Stiffness matrix
  CheckTrue(Abs(Det(FFace_Q4V2.K) - 0.0) < Ftol, Format('Det(FFace_Q4V2.K): %e <> %e', [Det(FFace_Q4V2.K), 0.0]));

end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTFace_Q4V2);
end.
