unit CXS.FEMLAP.TestEdge_B2V1;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

{$mode delphi}{$H+}

interface

uses
  fpcunit, testregistry, CXS.FEMLAP.Element, CXS.FEMLAP.Edge_B2V1, SysUtils, newVM, CXS.FEMLAP.Node;

type
  // Test methods for class TEdge_B2V1

  TestTEdge_B2V1 = class(TTestCase)
  strict private
    Ftol : Double;
    FEdge_B2V1: TEdge_B2V1;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestCalcGeoProperties;
    procedure TestCalc;
    procedure TestSetSourceOnNode;
    procedure TestSetSourceOnEdge;
  end;

implementation

procedure TestTEdge_B2V1.SetUp;
begin
  FEdge_B2V1 := TEdge_B2V1.Create;
  Ftol := 1E-10;

  FEdge_B2V1.CoordX[0] := 0;
  FEdge_B2V1.CoordY[0] := 0;
  FEdge_B2V1.CoordZ[0] := 0;

  FEdge_B2V1.CoordX[1] := 1;
  FEdge_B2V1.CoordY[1] := 1;
  FEdge_B2V1.CoordZ[1] := 1;

  FEdge_B2V1.CalcGeoProperties;

end;

procedure TestTEdge_B2V1.TearDown;
begin
  FEdge_B2V1.Free;
  FEdge_B2V1 := nil;
end;

procedure TestTEdge_B2V1.TestCalcGeoProperties;
begin

  CheckTrue(Abs(FEdge_B2V1.Length - sqrt(3)) < Ftol, Format('FEdge_B2V1.Length: %f <> %f', [FEdge_B2V1.Length, sqrt(3)]));

end;

procedure TestTEdge_B2V1.TestCalc;
var

  i, j : Integer;

  s : Integer;
  p : Double;

begin

  FEdge_B2V1.Transient := True;
  FEdge_B2V1.TimeInterval := 0.1;

  FEdge_B2V1.Calc;

  // Stiffness matrix
  for i := 0 to 1 do
  begin
    for j := 0 to 1 do
    begin

      if (i = j) then s := 1 else s := -1;

      CheckTrue(Abs(FEdge_B2V1.K[i,j] - 1 / sqrt(3) * s) < Ftol, Format('FEdge_B2V1.K[%d,%d]: %f <> %f', [i, j, FEdge_B2V1.K[i,j], 1 / sqr(3) * s]));

    end;
  end;

  // Mass matrix
  for i := 0 to 1 do
  begin
    for j := 0 to 1 do
    begin

      if (i = j) then p := 1/3 else p := 1/6;

      CheckTrue(Abs(FEdge_B2V1.M[i,j] - p * FEdge_B2V1.Length / FEdge_B2V1.TimeInterval) < Ftol, Format('FEdge_B2V1.M[%d,%d]: %f <> %f', [i, j, FEdge_B2V1.M[i,j], p * FEdge_B2V1.Length / FEdge_B2V1.TimeInterval]));

    end;
  end;

end;

procedure TestTEdge_B2V1.TestSetSourceOnNode;
var
  vn: Double;
  NIndex: Integer;
begin

  vn := 1;
  NIndex := 0;

  // FEdge_B2V1.b.SetZero in the original - b is now a read-only TVMobj
  // property backed by a value-type record, so it can't be mutated
  // through the property the way MtxVec's reference-type TVec allowed.
  // Unnecessary anyway: b (Fb) is already zero-filled fresh from
  // TEdge_B2V1.Create (called in SetUp above) and nothing has written to
  // it since, so it's already in the state this line was trying to force.

  FEdge_B2V1.SetSourceOnNode(NIndex, vn);

  CheckTrue(Abs(FEdge_B2V1.b[0,0] - vn) < Ftol, Format('FEdge_B2V1.b[0]: %f <> %f', [FEdge_B2V1.b[0,0], vn]));

end;

procedure TestTEdge_B2V1.TestSetSourceOnEdge;
var

  i : Integer;

  ve: Double;

begin

  ve := 1;

  // See TestSetSourceOnNode's comment above - b is already zero here too.

  FEdge_B2V1.SetSourceOnEdge(ve);

  for i := 0 to 1 do
  begin

    CheckTrue(Abs(FEdge_B2V1.b[i,0] - ve * 0.5) < Ftol, Format('FEdge_B2V1.b[i]: %f <> %f', [FEdge_B2V1.b[i,0], ve * 0.5]));

  end;

end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTEdge_B2V1);
end.
