unit CXS.FEMLAP.TestBrick_W6V1;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

{$mode delphi}{$H+}

interface

uses
  fpcunit, testregistry, CXS.FEMLAP.Element, CXS.FEMLAP.Node, CXS.FEMLAP.Edge_B2V1, CXS.FEMLAP.Brick_W6V1, CXS.FEMLAP.Face_Q4V1, SysUtils,
  newVM;

type
  // Test methods for class TBrick_W6V1

  TestTBrick_W6V1 = class(TTestCase)
  strict private
    Ftol : Double;
    FBrick_W6V1: TBrick_W6V1;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestCalcGeoProperties;
    procedure TestCalc;
    procedure TestSetSourceOnNode;
    procedure TestSetSourceOnEdge;
    procedure TestSetSourceOnFace;
    procedure TestSetSourceOnBrick;
  end;

implementation

procedure TestTBrick_W6V1.SetUp;
begin
  FBrick_W6V1 := TBrick_W6V1.Create;
  Ftol := 1E-10;

  FBrick_W6V1.CoordX[0] := 0;
  FBrick_W6V1.CoordY[0] := 0;
  FBrick_W6V1.CoordZ[0] := -0.5;

  FBrick_W6V1.CoordX[1] := 1;
  FBrick_W6V1.CoordY[1] := 0;
  FBrick_W6V1.CoordZ[1] := -0.5;

  FBrick_W6V1.CoordX[2] := 0;
  FBrick_W6V1.CoordY[2] := 1;
  FBrick_W6V1.CoordZ[2] := -0.5;

  FBrick_W6V1.CoordX[3] := 0;
  FBrick_W6V1.CoordY[3] := 0;
  FBrick_W6V1.CoordZ[3] := 0.5;

  FBrick_W6V1.CoordX[4] := 1;
  FBrick_W6V1.CoordY[4] := 0;
  FBrick_W6V1.CoordZ[4] := 0.5;

  FBrick_W6V1.CoordX[5] := 0;
  FBrick_W6V1.CoordY[5] := 1;
  FBrick_W6V1.CoordZ[5] := 0.5;

  FBrick_W6V1.CalcGeoProperties;

end;

procedure TestTBrick_W6V1.TearDown;
begin
  FBrick_W6V1.Free;
  FBrick_W6V1 := nil;
end;

procedure TestTBrick_W6V1.TestCalcGeoProperties;
begin

  CheckTrue(Abs(FBrick_W6V1.Volume - 0.5) < Ftol, Format('FBrick_W6V1.Volume: %f <> %f', [FBrick_W6V1.Volume, 0.5]));

end;

procedure TestTBrick_W6V1.TestCalc;
begin

  FBrick_W6V1.Transient := True;
  FBrick_W6V1.TimeInterval := 0.1;

  FBrick_W6V1.Calc;

  // Stiffness matrix
  CheckTrue(Abs(Det(FBrick_W6V1.K) - 0.0) < Ftol, Format('Det(FBrick_W6V1.K): %e <> %e', [Det(FBrick_W6V1.K), 0.0]));

  // Mass matrix
  CheckTrue(Abs(Det(FBrick_W6V1.M) - 1.31433579825720E-009) < Ftol, Format('Det(FBrick_W6V1.M): %e <> %e', [Det(FBrick_W6V1.K), 1.31433579825720E-009]));

end;

procedure TestTBrick_W6V1.TestSetSourceOnNode;
var
  vn: Double;
  NIndex: Integer;
begin

  vn := 1;
  NIndex := 0;

  FBrick_W6V1.SetSourceOnNode(NIndex, vn);

  CheckTrue(Abs(FBrick_W6V1.b[0,0] - vn) < Ftol, Format('FBrick_W6V1.b[0]: %f <> %f', [FBrick_W6V1.b[0,0], vn]));

end;

procedure TestTBrick_W6V1.TestSetSourceOnEdge;
var
  i : Integer;

  ve: Double;
  EIndex: Integer;
begin

  ve := 1;
  EIndex := 0;

  FBrick_W6V1.SetSourceOnEdge(EIndex, ve);

  for i := 0 to 1 do
  begin

    CheckTrue(Abs(FBrick_W6V1.b[i,0] - ve * 0.5) < Ftol, Format('FBrick_W6V1.b[i]: %f <> %f', [FBrick_W6V1.b[i,0], ve * 0.5]));

  end;

end;

procedure TestTBrick_W6V1.TestSetSourceOnFace;
var
  i : Integer;

  vf: Double;
  FIndex: Integer;
begin

  vf := 1;
  FIndex := 0;

  FBrick_W6V1.SetSourceOnFace(FIndex, vf);

  for i := 0 to 2 do
  begin

    CheckTrue(Abs(FBrick_W6V1.b[i,0] - vf * 0.5 / 3) < Ftol, Format('FBrick_W6V1.b[i]: %f <> %f', [FBrick_W6V1.b[i,0], vf * 0.5 / 3]));

  end;

end;

procedure TestTBrick_W6V1.TestSetSourceOnBrick;
var
  i : Integer;

  vb: Double;
begin

  vb := 1;

  FBrick_W6V1.SetSourceOnBrick(vb);

  for i := 0 to 5 do
  begin

    CheckTrue(Abs(FBrick_W6V1.b[i,0] - vb * 0.5 / 6) < Ftol, Format('FBrick_W6V1.b[i]: %f <> %f', [FBrick_W6V1.b[i,0], vb * 0.5 / 6]));

  end;

end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTBrick_W6V1);
end.
