unit CXS.FEMLAP.TestFace_T3V2;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

{$mode delphi}{$H+}

interface

uses
  fpcunit, testregistry, CXS.FEMLAP.Node, CXS.FEMLAP.Exceptions, SysUtils, newVM,
  CXS.FEMLAP.Face_T3V2, CXS.FEMLAP.Edge_B2V1, CXS.FEMLAP.Element_Face;

type
  // Test methods for class TFace_T3V2

  TestTFace_T3V2 = class(TTestCase)
  strict private
    Ftol : Double;
    FFace_T3V2: TFace_T3V2;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestCalcGeoProperties;
    procedure TestCalc;
  end;

implementation

procedure TestTFace_T3V2.SetUp;
begin
  FFace_T3V2 := TFace_T3V2.Create;

  Ftol := 1E-10;

  FFace_T3V2.CoordX[0] := 0;
  FFace_T3V2.CoordY[0] := 0;
  FFace_T3V2.CoordZ[0] := 0;

  FFace_T3V2.CoordX[1] := 1;
  FFace_T3V2.CoordY[1] := 0;
  FFace_T3V2.CoordZ[1] := 0;

  FFace_T3V2.CoordX[2] := 0;
  FFace_T3V2.CoordY[2] := 1;
  FFace_T3V2.CoordZ[2] := 0;

  FFace_T3V2.CalcGeoProperties;

end;

procedure TestTFace_T3V2.TearDown;
begin
  FFace_T3V2.Free;
  FFace_T3V2 := nil;
end;

procedure TestTFace_T3V2.TestCalcGeoProperties;
begin
  FFace_T3V2.CalcGeoProperties;

  CheckTrue(Abs(FFace_T3V2.Area - 0.5) < Ftol, Format('FFace_T3V2.Area: %f <> %f', [FFace_T3V2.Area, 0.5]));

end;

procedure TestTFace_T3V2.TestCalc;
begin


  FFace_T3V2.ReCalcD;
  FFace_T3V2.Calc;

  // Stiffness matrix
  CheckTrue(Abs(Det(FFace_T3V2.K) - 0.0) < Ftol, Format('Det(FFace_T3V1.K): %e <> %e', [Det(FFace_T3V2.K), 0.0]));

end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTFace_T3V2);
end.
