unit CXS.FEMLAP.TestFace_Q4V1;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

{$mode delphi}{$H+}

interface

uses
  fpcunit, testregistry, CXS.FEMLAP.Element, CXS.FEMLAP.Node, CXS.FEMLAP.Edge_B2V1, CXS.FEMLAP.Face_Q4V1, SysUtils, newVM;

type
  // Test methods for class TFace_Q4V1

  TestTFace_Q4V1 = class(TTestCase)
  strict private
    Ftol : Double;
    FFace_Q4V1: TFace_Q4V1;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestCalcGeoProperties;
    procedure TestCalc;
    procedure TestSetSourceOnNode;
    procedure TestSetSourceOnEdge;
    procedure TestSetSourceOnFace;
  end;

implementation

procedure TestTFace_Q4V1.SetUp;
begin
  FFace_Q4V1 := TFace_Q4V1.Create;
  Ftol := 1E-10;

  FFace_Q4V1.CoordX[0] := 0;
  FFace_Q4V1.CoordY[0] := 0;
  FFace_Q4V1.CoordZ[0] := 0;

  FFace_Q4V1.CoordX[1] := 1;
  FFace_Q4V1.CoordY[1] := 0;
  FFace_Q4V1.CoordZ[1] := 0;

  FFace_Q4V1.CoordX[2] := 1;
  FFace_Q4V1.CoordY[2] := 1;
  FFace_Q4V1.CoordZ[2] := 0;

  FFace_Q4V1.CoordX[3] := 0;
  FFace_Q4V1.CoordY[3] := 1;
  FFace_Q4V1.CoordZ[3] := 0;

  FFace_Q4V1.CalcGeoProperties;

end;

procedure TestTFace_Q4V1.TearDown;
begin
  FFace_Q4V1.Free;
  FFace_Q4V1 := nil;
end;

procedure TestTFace_Q4V1.TestCalcGeoProperties;
begin

  CheckTrue(Abs(FFace_Q4V1.Area - 1) < Ftol, Format('FFace_Q4V1.Area: %f <> %f', [FFace_Q4V1.Area, 1.0]));

end;

procedure TestTFace_Q4V1.TestCalc;
begin

  FFace_Q4V1.Transient := True;
  FFace_Q4V1.TimeInterval := 0.1;

  FFace_Q4V1.Calc;

  // Stiffness matrix
  CheckTrue(Abs(Det(FFace_Q4V1.K) - 0.0) < Ftol, Format('Det(FFace_Q4V1.K): %e <> %e', [Det(FFace_Q4V1.K), 0.0]));

  // Mass matrix
  CheckTrue(Abs(Det(FFace_Q4V1.M) - 4.82253086489077E-1) < Ftol, Format('Det(FFace_Q4V1.M): %e <> %e', [Det(FFace_Q4V1.M), 4.82253086489077E-1]));

end;

procedure TestTFace_Q4V1.TestSetSourceOnNode;
var
  vn: Double;
  NIndex: Integer;
begin

  vn := 1;
  NIndex := 0;

  // b already starts zero-filled - see TestEdge_B2V1.pas's
  // TestSetSourceOnNode comment for why.

  FFace_Q4V1.SetSourceOnNode(NIndex, vn);

  CheckTrue(Abs(FFace_Q4V1.b[0,0] - vn) < Ftol, Format('FFace_Q4V1.b[0]: %f <> %f', [FFace_Q4V1.b[0,0], vn]));

end;

procedure TestTFace_Q4V1.TestSetSourceOnEdge;
var
  i : Integer;

  ve: Double;
  EIndex: Integer;

begin

  ve := 1;
  EIndex := 0;

  FFace_Q4V1.SetSourceOnEdge(EIndex, ve);

  for i := 0 to 1 do
  begin

    CheckTrue(Abs(FFace_Q4V1.b[i,0] - ve * 0.5) < Ftol, Format('FFace_Q4V1.b[i]: %f <> %f', [FFace_Q4V1.b[i,0], ve * 0.5]));

  end;

end;

procedure TestTFace_Q4V1.TestSetSourceOnFace;
var

  i : Integer;

  vf: Double;

begin

  vf := 1;

  FFace_Q4V1.SetSourceOnFace(vf);

  for i := 0 to 3 do
  begin

    CheckTrue(Abs(FFace_Q4V1.b[i,0] - vf * 0.25) < Ftol, Format('FFace_Q4V1.b[i]: %f <> %f', [FFace_Q4V1.b[i,0], vf * 0.25]));

  end;

end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTFace_Q4V1);
end.
