#!/usr/bin/env python3
# ---------------------------------------------------------------------------
# Generates the two data include files for the CanterburyRain demo's
# location panel (uPlaces.pas includes both):
#
#   ukplaces.inc   every populated place in the UK and Ireland with a
#                  population over 50,000, alphabetical: name, country,
#                  latitude, longitude, population
#   ukoutline.inc  coastline/border rings of the United Kingdom, Ireland
#                  and the Isle of Man for the outline map
#
# Sources (download them first, into one directory):
#   GeoNames, CC-BY 4.0 - https://download.geonames.org/export/dump/
#     cities15000.zip (unzipped to cities15000.txt): all places over 15,000
#   Natural Earth, public domain - 1:50m admin-0 countries, GeoJSON:
#     https://raw.githubusercontent.com/nvkelso/natural-earth-vector/
#       master/geojson/ne_50m_admin_0_countries.geojson
#
# GeoNames feature code PPLX ("section of populated place" - Putney, Canary
# Wharf, South Dublin, a duplicate "Londonderry County Borough") is left
# out; London boroughs that GeoNames lists as places in their own right
# (PPLA3/PPLL - Croydon, Islington, ...) stay in. GeoNames' population
# figures are its own and mix definitions (city proper, borough, urban
# area), so the 50,000 threshold is only as good as they are.
#
# Usage: python3 make_location_data.py <download dir>
# ---------------------------------------------------------------------------
import sys, os, csv, json

src = sys.argv[1]
here = os.path.dirname(os.path.abspath(__file__))
MIN_POP = 50000
COUNTRY = {('GB', 'ENG'): 'England', ('GB', 'SCT'): 'Scotland', ('GB', 'WLS'): 'Wales',
           ('GB', 'NIR'): 'Northern Ireland'}

def pas(s):
    return "'" + s.replace("'", "''") + "'"

places = []
with open(os.path.join(src, 'cities15000.txt'), encoding='utf-8') as fh:
    for r in csv.reader(fh, delimiter='\t', quoting=csv.QUOTE_NONE):
        cc, adm1, fcode, pop = r[8], r[10], r[7], int(r[14])
        if cc not in ('GB', 'IE') or pop <= MIN_POP or fcode == 'PPLX':
            continue
        country = 'Ireland' if cc == 'IE' else COUNTRY.get((cc, adm1), 'United Kingdom')
        places.append((r[1], country, float(r[4]), float(r[5]), pop))
places.sort(key=lambda p: (p[0].lower(), p[1]))
names = [p[0] for p in places]
assert len(names) == len(set(names)), 'duplicate place names - the display names need qualifying'
assert 'Canterbury' in names, 'Canterbury (the default) is missing'

with open(os.path.join(here, 'ukplaces.inc'), 'w', encoding='utf-8') as fh:
    fh.write('// Generated by make_location_data.py from GeoNames cities15000 (CC-BY 4.0) - do not edit.\n')
    fh.write('// UK and Ireland places with population over %d, alphabetical.\n' % MIN_POP)
    fh.write('const\n  PlaceCount = %d;\n' % len(places))
    fh.write('  Places: array[0..PlaceCount - 1] of TPlace = (\n')
    rows = ['    (Name: %s; Country: %s; Lat: %.5f; Lon: %.5f; Population: %d)'
            % (pas(n), pas(c), la, lo, po) for n, c, la, lo, po in places]
    fh.write(',\n'.join(rows) + '\n  );\n')

g = json.load(open(os.path.join(src, 'ne_50m_admin_0_countries.geojson'), encoding='utf-8'))
rings = []
for f in g['features']:
    if f['properties'].get('ADM0_A3') not in ('GBR', 'IRL', 'IMN'):
        continue
    geom = f['geometry']
    polys = geom['coordinates'] if geom['type'] == 'MultiPolygon' else [geom['coordinates']]
    for poly in polys:
        for ring in poly:
            rings.append(ring[:-1] if ring[0] == ring[-1] else ring)
starts, lons, lats = [0], [], []
for ring in rings:
    for lo, la in ring:
        lons.append(lo)
        lats.append(la)
    starts.append(len(lons))

def arr(name, typ, vals, fmt):
    out = '  %s: array[0..%d] of %s = (\n' % (name, len(vals) - 1, typ)
    items = [fmt % v for v in vals]
    lines = [', '.join(items[i:i + 10]) for i in range(0, len(items), 10)]
    return out + '    ' + ',\n    '.join(lines) + '\n  );\n'

with open(os.path.join(here, 'ukoutline.inc'), 'w') as fh:
    fh.write('// Generated by make_location_data.py from Natural Earth 1:50m admin-0 countries\n')
    fh.write('// (public domain): United Kingdom, Ireland, Isle of Man - do not edit.\n')
    fh.write('// Ring r is points OutlineStart[r] .. OutlineStart[r+1]-1, lon/lat in degrees.\n')
    fh.write('const\n  OutlineRingCount = %d;\n  OutlinePointCount = %d;\n' % (len(rings), len(lons)))
    fh.write(arr('OutlineStart', 'Integer', starts, '%d'))
    fh.write(arr('OutlineLon', 'Single', lons, '%.4f'))
    fh.write(arr('OutlineLat', 'Single', lats, '%.4f'))

print('%d places, %d outline rings, %d points' % (len(places), len(rings), len(lons)))
