unit uCountyRain;

{*******************************************************************************

     County rainfall for the CanterburyRain demo's county map: the total
     over the last 12 months for each of the 218 UK counties and unitary
     authorities, and the 1991-2020 average for the same 12 calendar
     months.

     SOURCE - the Met Office, not a model: HadUK-Grid, the Met Office's
     gridded analysis of its UK station network (Crown copyright, Open
     Government Licence). The monthly 12 km rainfall grids are downloaded
     at run time from the Met Office Hadley Centre's provisional data pages
     (hadleyserver.metoffice.gov.uk/hadobs/hadukgrid, netCDF, ~190 kB a
     month; a month appears shortly after it ends), so the 12 months are
     the latest 12 published. Months older than four months are taken from
     the local cache once downloaded; newer ones are fetched again each
     run, since provisional data can be revised.

     Each county's value is the mean of the 12 km cells whose centres fall
     inside it (countydata.inc, generated by make_county_data.py from the
     ONS boundaries and the same grid); 48 small areas that contain no cell
     centre use the one cell nearest their ONS label point. The 1991-2020
     averages are the HadUK-Grid 12 km monthly averages over the same
     cells, compiled in - so the totals and the averages are like for like.

     NETCDF - the grids are netCDF-4 (HDF5), read through the netCDF C
     library (libnetcdf), loaded dynamically when first needed; without it
     GetCountyRain fails with a message saying so rather than the program
     failing to start. Ubuntu has it as libnetcdf19 (ParaView pulls it in).

*******************************************************************************}

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils, DateUtils, Math, dynlibs, fphttpclient, opensslsockets;

{$I countydata.inc}

type
  TCountyValues = array[0..CountyCount - 1] of Double;

  TCountyRainSummary = record
    FirstMonth, LastMonth: TDateTime;   // 1st of the first and last of the 12 months
    Total: TCountyValues;               // mm over the 12 months
    Normal: TCountyValues;              // 1991-2020 average for those 12 calendar months, mm
    UKTotal, UKNormal: Double;          // over all UK land cells
    CachedMonths: Integer;              // months taken from the cache this time
    Offline: Boolean;                   // nothing could be downloaded
    Note: string;                       // e.g. why the cache was used
  end;

// Downloads (or takes from the cache) the latest 12 published months and
// reduces them per county. ForceOffline uses the cache only.
function GetCountyRain(out S: TCountyRainSummary; out Err: string;
  ForceOffline: Boolean = False): Boolean;

// The county whose boundary contains (E, N), British National Grid, or -1.
function CountyAt(E, N: Double): Integer;

implementation

const
  BaseUrl = 'https://hadleyserver.metoffice.gov.uk/hadobs/hadukgrid/data/';
  RefetchMonths = 4;     // months this recent are re-downloaded every run
  NoData = 1e19;         // HadUK-Grid _FillValue is 1e20 (sea)

{ ---- netCDF, loaded on demand ------------------------------------------- }

type
  Tnc_open = function(path: PChar; mode: LongInt; ncidp: PLongInt): LongInt; cdecl;
  Tnc_close = function(ncid: LongInt): LongInt; cdecl;
  Tnc_inq_varid = function(ncid: LongInt; name: PChar; varidp: PLongInt): LongInt; cdecl;
  Tnc_inq_dimid = function(ncid: LongInt; name: PChar; dimidp: PLongInt): LongInt; cdecl;
  Tnc_inq_dimlen = function(ncid, dimid: LongInt; lenp: PPtrUInt): LongInt; cdecl;
  Tnc_get_var_double = function(ncid, varid: LongInt; ip: PDouble): LongInt; cdecl;

var
  NcLib: TLibHandle = NilHandle;
  nc_open: Tnc_open;
  nc_close: Tnc_close;
  nc_inq_varid: Tnc_inq_varid;
  nc_inq_dimid: Tnc_inq_dimid;
  nc_inq_dimlen: Tnc_inq_dimlen;
  nc_get_var_double: Tnc_get_var_double;

function LoadNetCDF(out Err: string): Boolean;
const
  Names: array[0..5] of string = (
    {$IFDEF WINDOWS}'netcdf.dll', 'libnetcdf.dll', '', '', '', ''
    {$ELSE}{$IFDEF DARWIN}'libnetcdf.dylib', 'libnetcdf.19.dylib', '/opt/homebrew/lib/libnetcdf.dylib',
    '/usr/local/lib/libnetcdf.dylib', '', ''
    {$ELSE}'libnetcdf.so.19', 'libnetcdf.so.22', 'libnetcdf.so.18', 'libnetcdf.so.15',
    'libnetcdf.so', ''{$ENDIF}{$ENDIF});
var
  n: string;
begin
  Err := '';
  if NcLib <> NilHandle then Exit(True);
  for n in Names do
    if n <> '' then begin
      NcLib := LoadLibrary(n);
      if NcLib <> NilHandle then Break;
    end;
  if NcLib = NilHandle then begin
    Err := 'the netCDF library (libnetcdf) is not installed - it is needed to read the '
      + 'Met Office files (Ubuntu: apt install libnetcdf19)';
    Exit(False);
  end;
  Pointer(nc_open) := GetProcAddress(NcLib, 'nc_open');
  Pointer(nc_close) := GetProcAddress(NcLib, 'nc_close');
  Pointer(nc_inq_varid) := GetProcAddress(NcLib, 'nc_inq_varid');
  Pointer(nc_inq_dimid) := GetProcAddress(NcLib, 'nc_inq_dimid');
  Pointer(nc_inq_dimlen) := GetProcAddress(NcLib, 'nc_inq_dimlen');
  Pointer(nc_get_var_double) := GetProcAddress(NcLib, 'nc_get_var_double');
  result := Assigned(nc_open) and Assigned(nc_close) and Assigned(nc_inq_varid)
    and Assigned(nc_inq_dimid) and Assigned(nc_inq_dimlen) and Assigned(nc_get_var_double);
  if not result then Err := 'the netCDF library lacks the expected functions';
end;

type
  TGrid = array of Double;

// The month's rainfall grid, GridNY x GridNX, row j (northing) major; sea
// cells keep the file's 1e20.
function ReadGrid(const FileName: string; out G: TGrid; out Err: string): Boolean;
var
  ncid, varid, dimid: LongInt;
  nx, ny: PtrUInt;
begin
  result := False;
  if not LoadNetCDF(Err) then Exit;
  if nc_open(PChar(FileName), 0, @ncid) <> 0 then begin
    Err := 'cannot open ' + ExtractFileName(FileName);
    Exit;
  end;
  try
    if (nc_inq_dimid(ncid, 'projection_x_coordinate', @dimid) <> 0)
       or (nc_inq_dimlen(ncid, dimid, @nx) <> 0)
       or (nc_inq_dimid(ncid, 'projection_y_coordinate', @dimid) <> 0)
       or (nc_inq_dimlen(ncid, dimid, @ny) <> 0)
       or (nx <> GridNX) or (ny <> GridNY) then begin
      Err := ExtractFileName(FileName) + ' is not on the expected 12 km grid';
      Exit;
    end;
    if nc_inq_varid(ncid, 'rainfall', @varid) <> 0 then begin
      Err := ExtractFileName(FileName) + ' has no rainfall variable';
      Exit;
    end;
    SetLength(G, GridNX * GridNY);
    if nc_get_var_double(ncid, varid, @G[0]) <> 0 then begin
      Err := 'cannot read the rainfall in ' + ExtractFileName(FileName);
      Exit;
    end;
    result := True;
  finally
    nc_close(ncid);
  end;
end;

{ ---- downloads and cache --------------------------------------------------- }

function CacheDir: string;
begin
  result := IncludeTrailingPathDelimiter(GetAppConfigDir(False)) + 'hadukgrid' + PathDelim;
end;

function MonthFile(M: TDateTime): string;
begin
  result := 'rainfall_hadukgrid_uk_12km_mon_' + FormatDateTime('yyyymm', M) + '.nc';
end;

// Downloads URL to FileName. 1 = done, 0 = not published (404), -1 = error.
function Fetch(const Url, FileName: string; out Err: string): Integer;
var
  Client: TFPHTTPClient;
  Mem: TMemoryStream;
begin
  result := -1;
  Err := '';
  Client := TFPHTTPClient.Create(nil);
  Mem := TMemoryStream.Create;
  try
    try
      Client.AllowRedirect := True;
      Client.IOTimeout := 30000;
      Client.AddHeader('User-Agent', 'newVM CanterburyRain demo');
      Client.HTTPMethod('GET', Url, Mem, [200, 404]);
      if Client.ResponseStatusCode = 404 then Exit(0);
      ForceDirectories(ExtractFilePath(FileName));
      Mem.SaveToFile(FileName);
      result := 1;
    except
      on E: Exception do Err := E.Message;
    end;
  finally
    Mem.Free;
    Client.Free;
  end;
end;

// Makes the month's file available locally. 1 = downloaded, 2 = from the
// cache, 0 = not published (and not cached), -1 = failed.
function EnsureMonth(M: TDateTime; ForceOffline: Boolean; out Path: string;
  out Err: string): Integer;
var
  r: Integer;
begin
  Err := '';
  Path := CacheDir + MonthFile(M);
  if FileExists(Path) and (ForceOffline
     or (M <= IncMonth(StartOfTheMonth(Date), -RefetchMonths))) then Exit(2);
  if ForceOffline then Exit(0);
  r := Fetch(BaseUrl + FormatDateTime('yyyy', M) + '/' + MonthFile(M), Path, Err);
  if r = 1 then Exit(1);
  if FileExists(Path) then Exit(2);        // keep using the earlier copy
  result := r;
end;

{ ---- per county ------------------------------------------------------------ }

function CountyAt(E, N: Double): Integer;
var
  c, r, k, a, b: Integer;
  inside: Boolean;
begin
  for c := 0 to CountyCount - 1 do begin
    inside := False;
    for r := CountyRingFirst[c] to CountyRingFirst[c + 1] - 1 do begin
      a := CountyRingStart[r];
      b := CountyRingStart[r + 1] - 1;
      for k := a to b do
        if (CountyPtN[k] > N) <> (CountyPtN[IfThen(k = b, a, k + 1)] > N) then
          if E < CountyPtE[k] + (N - CountyPtN[k])
               * (CountyPtE[IfThen(k = b, a, k + 1)] - CountyPtE[k])
               / (CountyPtN[IfThen(k = b, a, k + 1)] - CountyPtN[k]) then
            inside := not inside;
    end;
    if inside then Exit(c);
  end;
  result := -1;
end;

function GetCountyRain(out S: TCountyRainSummary; out Err: string;
  ForceOffline: Boolean = False): Boolean;
var
  Months: array[0..11] of TDateTime;
  Paths: array[0..11] of string;
  Latest, M: TDateTime;
  k, c, i, r, n, cm, CellCount: Integer;
  G: TGrid;
  sum: Double;
  MErr: string;
begin
  result := False;
  Err := '';
  S := Default(TCountyRainSummary);
  if not LoadNetCDF(Err) then Exit;

  // the latest published month: last month, else the one before, ...
  Latest := 0;
  for k := 1 to 3 do begin
    M := IncMonth(StartOfTheMonth(Date), -k);
    r := EnsureMonth(M, ForceOffline, Paths[11], MErr);
    if r > 0 then begin
      Latest := M;
      if r = 2 then Inc(S.CachedMonths);
      Break;
    end;
    if r < 0 then S.Note := MErr;
  end;
  if Latest = 0 then begin
    if S.Note <> '' then Err := 'could not download the Met Office rainfall grids (' + S.Note + ')'
    else Err := 'no Met Office rainfall grid found for the last three months';
    if ForceOffline then Err := 'offline, and no cached Met Office rainfall grids';
    Exit;
  end;
  for k := 0 to 11 do Months[k] := IncMonth(Latest, k - 11);
  for k := 0 to 10 do begin
    r := EnsureMonth(Months[k], ForceOffline, Paths[k], MErr);
    if r <= 0 then begin
      Err := 'Met Office rainfall grid for ' + FormatDateTime('mmmm yyyy', Months[k])
        + ' unavailable';
      if MErr <> '' then Err := Err + ' (' + MErr + ')';
      Exit;
    end;
    if r = 2 then Inc(S.CachedMonths);
  end;
  S.Offline := S.CachedMonths = 12;
  S.FirstMonth := Months[0];
  S.LastMonth := Months[11];

  for k := 0 to 11 do begin
    if not ReadGrid(Paths[k], G, Err) then Exit;
    cm := MonthOf(Months[k]);
    for c := 0 to CountyCount - 1 do begin
      sum := 0;
      n := 0;
      for i := CountyCellFirst[c] to CountyCellFirst[c + 1] - 1 do
        if G[CountyCells[i]] < NoData then begin
          sum := sum + G[CountyCells[i]];
          Inc(n);
        end;
      if n > 0 then S.Total[c] := S.Total[c] + sum / n
      else S.Total[c] := NaN;
      S.Normal[c] := S.Normal[c] + CountyNormal[c * 12 + cm - 1];
    end;
  end;

  // UK: cell-weighted over the counties made of whole cells (the small
  // single-cell areas reuse a neighbour's cell, so they are left out)
  CellCount := 0;
  for c := 0 to CountyCount - 1 do
    if not CountySingleCell[c] and not IsNan(S.Total[c]) then begin
      n := CountyCellFirst[c + 1] - CountyCellFirst[c];
      S.UKTotal := S.UKTotal + n * S.Total[c];
      S.UKNormal := S.UKNormal + n * S.Normal[c];
      Inc(CellCount, n);
    end;
  if CellCount > 0 then begin
    S.UKTotal := S.UKTotal / CellCount;
    S.UKNormal := S.UKNormal / CellCount;
  end;
  result := True;
end;

end.
